### ISSUE TITLE
org.nd4j.linalg.jcublas.blas.JcublasLevel1 syncronizes on CudaContext causing performance problem

### ISSUE THREAD

**Issue by valncrt** [deeplearning4j/nd4j#1006]
I'm using  nd4j 0.4-rc3.9 and dl4j 0.4-rc3.10-SNAPSHOT to build a ParagraphVector using using GPU's and the training time is significantly longer than if I were using CPU's.  It looks like synchonizing on the CudaContext is causing seven other threads to wait for the lock (the instance I'm using has 8 CPU's).  Below are the typical lock/wait stacks. 

"VectorCalculationsThread 4" #24 prio=5 os_prio=0 tid=0x00007f8a7aa6f000 nid=0x356 runnable [0x00007f8a9b4ef000]
   java.lang.Thread.State: RUNNABLE
	at org.nd4j.nativeblas.NativeOps.setBlasStream(Native Method)
	at org.nd4j.linalg.jcublas.blas.JcublasLevel1.saxpy(JcublasLevel1.java:410)
	- locked <0x00000006e1a8f5e8> (a org.nd4j.jita.allocator.pointers.cuda.cublasHandle_t)
	at org.nd4j.linalg.api.blas.impl.BaseLevel1.axpy(BaseLevel1.java:301)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.iterateSample(SkipGram.java:197)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.skipGram(SkipGram.java:154)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.learnSequence(SkipGram.java:129)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors.trainSequence(SequenceVectors.java:218)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:921)

"VectorCalculationsThread 3" #23 prio=5 os_prio=0 tid=0x00007f8a7aa32800 nid=0x355 waiting for monitor entry [0x00007f8a9b5f0000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.nd4j.linalg.jcublas.blas.JcublasLevel1.saxpy(JcublasLevel1.java:409)
	- waiting to lock <0x00000006e1a8f5e8> (a org.nd4j.jita.allocator.pointers.cuda.cublasHandle_t)
	at org.nd4j.linalg.api.blas.impl.BaseLevel1.axpy(BaseLevel1.java:301)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.iterateSample(SkipGram.java:197)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.skipGram(SkipGram.java:154)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.learnSequence(SkipGram.java:129)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors.trainSequence(SequenceVectors.java:218)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:921)

or

"VectorCalculationsThread 6" #26 prio=5 os_prio=0 tid=0x00007fea2281c800 nid=0x63e runnable [0x00007fea787b8000]
   java.lang.Thread.State: RUNNABLE
	at org.nd4j.nativeblas.Nd4jBlas.saxpy(Native Method)
	at org.nd4j.linalg.jcublas.blas.JcublasLevel1.saxpy(JcublasLevel1.java:413)
	- locked <0x00000006e1add778> (a org.nd4j.jita.allocator.pointers.cuda.cublasHandle_t)
	at org.nd4j.linalg.api.blas.impl.BaseLevel1.axpy(BaseLevel1.java:301)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.iterateSample(SkipGram.java:197)
	at org.deeplearning4j.models.embeddings.learning.impl.sequence.DBOW.dbow(DBOW.java:104)
	at org.deeplearning4j.models.embeddings.learning.impl.sequence.DBOW.learnSequence(DBOW.java:71)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors.trainSequence(SequenceVectors.java:225)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:921)

"VectorCalculationsThread 5" #25 prio=5 os_prio=0 tid=0x00007fea2281a800 nid=0x63d waiting for monitor entry [0x00007fea788b9000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.nd4j.linalg.jcublas.blas.JcublasLevel1.sdot(JcublasLevel1.java:52)
	- waiting to lock <0x00000006e1add778> (a org.nd4j.jita.allocator.pointers.cuda.cublasHandle_t)
	at org.nd4j.linalg.api.blas.impl.BaseLevel1.dot(BaseLevel1.java:33)
	at org.nd4j.linalg.factory.BaseBlasWrapper.dot(BaseBlasWrapper.java:188)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.iterateSample(SkipGram.java:181)
	at org.deeplearning4j.models.embeddings.learning.impl.sequence.DBOW.dbow(DBOW.java:104)
	at org.deeplearning4j.models.embeddings.learning.impl.sequence.DBOW.learnSequence(DBOW.java:71)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors.trainSequence(SequenceVectors.java:225)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:921)

**Comment by raver119** [comment]
Even without synchronization, subsequent kernel launches on CUDA device will be worse performance-wise, then full-blown separate CUDA implementation W2V. So, CUDA performance on W2V tasks in current architecture is suffering mosly from x86 parallelism model, then on those syncs.

To address that we've already discussed special CUDA implementation for W2V and it's derivatives.
Blockwise dot/axpy approach performance should be enough to outperform x86 approach.

**Comment by raver119** [comment]
Some numbers:

Average w2v model vector length hides somewhere between 100 and 300 elements.For SIMD-enabled cpu that's 25-75 cpu cycles for dot. 

And to do the same on CUDA you still need to launch kernel. Kernel will have  1 - 9 blocks (depending on approach, but 1 block is enough). So, in total you'll have 300 threads. And this means you just have no room to become competitive with cpu. Just too small task.

That's why it's slow right now. CUDA Word2Vec just requires a bit different parallelism model.
