### ISSUE TITLE
getRows(int... rows) on a column vector can cause ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by andrewclegg** [deeplearning4j/nd4j#1099]
The problem is here:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at org.nd4j.linalg.indexing.ShapeOffsetResolution.tryShortCircuit(ShapeOffsetResolution.java:118)
	at org.nd4j.linalg.indexing.ShapeOffsetResolution.exec(ShapeOffsetResolution.java:325)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.get(BaseNDArray.java:3671)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getRows(BaseNDArray.java:3654)
```

because by this point the integer row indexes have been wrapped into a single `SpecifiedIndex` object. So the `indexes` arg to `tryShortCircuit` has only one element -- meaning `indexes[1]` on line 118 barfs.

**Comment by eraly** [comment]
@andrewclegg I would like to rerun whatever code you used before I start looking at it. Can you please post a gist? :)

**Comment by andrewclegg** [comment]
I don't have the exact code but it's easy to reproduce:

```
val rowVector = Nd4j.create(Array(1.0, 2.0, 3.0))
val colVector = rowVector.transpose
colVector.getRows(0)

java.lang.ArrayIndexOutOfBoundsException: 1
	at org.nd4j.linalg.indexing.ShapeOffsetResolution.tryShortCircuit(ShapeOffsetResolution.java:118)
	at org.nd4j.linalg.indexing.ShapeOffsetResolution.exec(ShapeOffsetResolution.java:325)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.get(BaseNDArray.java:3689)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getRows(BaseNDArray.java:3672)
```

**Comment by eraly** [comment]
Fix in master. Closing. Thanks guys.
