### ISSUE TITLE
Balanced mini batches error

### ISSUE THREAD

**Issue by dinhthap** [deeplearning4j/nd4j#1117]
Unable to merge empty datasets

Here code:
public static void main(String[] args) throws Exception {
        ImageRecordReader reader = new ImageRecordReader(height,width,channels,new ParentPathLabelGenerator());
        reader.initialize(new FileSplit(new File("/home/dinhthap/Desktop/1.train")));
        DataSetIterator iterator = new RecordReaderDataSetIterator(reader,batchSize);
        DataNormalization scaler = new NormalizerStandardize();
        scaler.fit(iterator);
        iterator.reset();

        while (iterator.hasNext()){
            DataSet next = iterator.next();
            scaler.transform(next);

        }

        iterator.reset();

        BalanceMinibatches balanceMinibatches = BalanceMinibatches.builder()
                .dataSetIterator(iterator)
                .miniBatchSize(batchSize)
                .numLabels(new File("/home/dinhthap/Desktop/1.train").list().length)
                .rootDir(new File("minibatches")).rootSaveDir(new File("minibatchessave")).dataNormalization(scaler)
                .build();
        balanceMinibatches.balance();
        scaler.save(new File("mean.bin"),new File("std.bin"));

Exception in thread "main" java.lang.IllegalArgumentException: Unable to merge empty dataset
	at org.nd4j.linalg.dataset.DataSet.merge(DataSet.java:332)
	at com.fis.cnn.BalanceMinibatches.balance(BalanceMinibatches.java:93)
	at com.fis.cnn.Demo2.main(Demo2.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/pull/1131
