### ISSUE TITLE
putRow edge case bug

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1161]
See test case below.

```java
        INDArray a1 = Nd4j.create(1,3);
        INDArray a2 = Nd4j.create(2,3);

        //Works, though putting a column vector into a row (length is correct, however)
        a2.putRow(0, Nd4j.create(3,1));

        //Works, putting a row vector into a row
        a1.putRow(0, Nd4j.create(1,3));

        //FAILS, putting a column vector into a row (row vector). Throws exception below
        //This should be consistent with the first case, but isn't.
        //Either both should work, or both should fail
        a1.putRow(0, Nd4j.create(3,1));
```

Exception in thread "main" java.lang.IllegalStateException: Mis matched lengths
	at org.nd4j.linalg.util.LinAlgExceptions.assertSameLength(LinAlgExceptions.java:39)
	at org.nd4j.linalg.api.ops.BaseTransformOp.<init>(BaseTransformOp.java:48)
	at org.nd4j.linalg.api.ops.impl.transforms.Set.<init>(Set.java:25)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.assign(BaseNDArray.java:1103)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.put(BaseNDArray.java:1804)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.putRow(BaseNDArray.java:3250)

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/nd4j/pull/1162
