### ISSUE TITLE
java.lang.IllegalArgumentException: Unable to get linear index >= 1

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/nd4j#118]
Running deeplearning4j examples Convolutional Example hit the following error after Fine Tuning:

Exception in thread "main" java.lang.IllegalArgumentException: Unable to get linear index >= 1
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:3180)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.slice(BaseNDArray.java:2867)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.get(BaseNDArray.java:3608)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.get(BaseNDArray.java:3609)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.get(BaseNDArray.java:3570)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.get(BaseNDArray.java:3565)
	at org.nd4j.linalg.ops.transforms.Transforms.downSample(Transforms.java:130)
	at org.deeplearning4j.nn.layers.convolution.subsampling.SubsamplingLayer.activate(SubsamplingLayer.java:118)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.activationFromPrevLayer(MultiLayerNetwork.java:481)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForward(MultiLayerNetwork.java:501)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.finetune(MultiLayerNetwork.java:1073)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1129)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1156)
	at org.deeplearning4j.convolution.ConvolutionalExample.main(ConvolutionalExample.java:95)
-- org.jblas INFO Deleting /var/folders/_m/15fcv4yn3y9dh93shs2lgql80000gn/T/jblas7193021059297454202/libjblas.dylib
-- org.jblas INFO Deleting /var/folders/_m/15fcv4yn3y9dh93shs2lgql80000gn/T/jblas7193021059297454202/libjblas_arch_flavor.dylib
-- org.jblas INFO Deleting /var/folders/_m/15fcv4yn3y9dh93shs2lgql80000gn/T/jblas7193021059297454202

**Comment by agibsonccc** [comment]
This is fixed in gpudeps.
