### ISSUE TITLE
NormalizerStandardize error

### ISSUE THREAD

**Issue by akhodakivskiy** [deeplearning4j/nd4j#1197]
This error occurs in regression model with `fitLabels = true`

```
Exception in thread "main" java.lang.IllegalArgumentException: Illegal concatneation at array 1 and shape element 1
        at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.concat(JCublasNDArrayFactory.java:581)
        at org.nd4j.linalg.factory.Nd4j.concat(Nd4j.java:4795)
        at org.nd4j.linalg.factory.BaseNDArrayFactory.vstack(BaseNDArrayFactory.java:1201)
        at org.nd4j.linalg.factory.Nd4j.vstack(Nd4j.java:4683)
        at org.nd4j.linalg.dataset.api.preprocessor.NormalizerStandardize.getMean(NormalizerStandardize.java:231)
```

**Comment by akhodakivskiy** [comment]
@eraly FYI

**Comment by akhodakivskiy** [comment]
Not sure if it's a good idea to join these arrays - maybe it's better to expose `labelMean` and `labelStd` via dedicated getters?

**Comment by eraly** [comment]
@akhodakivskiy Can you post a gist of the code you are running?

**Comment by akhodakivskiy** [comment]
It's fairly straightforward:

```
NormalizerStandardize n = new NormalizerStandardize();

if (files.exist()) {
    n.load(f1, f2, f3, f4);
} else {
    n.fit(iterator);
    n.save(f1, f2, f3, f4);
}

n.getMean();
```

I think the issue is that you call Nd4j.vstack on 2 INDArrays with different number of columns (labels and features)

**Comment by eraly** [comment]
Yes, I put in a fix and so I am closing this issue. There might be another bug that has to do with an edgecase with std dev elsewhere. Thanks!
