### ISSUE TITLE
Read and Write to file problem

### ISSUE THREAD

**Issue by mbabadi** [deeplearning4j/nd4j#1246]
Here's a simple class I use for reading and writing NDArray to file:

```
package org.broadinstitute.hellbender.tools.coveragemodel.nd4jutils;

import org.apache.commons.io.input.ReaderInputStream;
import org.apache.commons.io.output.WriterOutputStream;
import org.broadinstitute.hellbender.exceptions.UserException;
import org.nd4j.linalg.api.buffer.DataBuffer;
import org.nd4j.linalg.api.buffer.util.DataTypeUtil;
import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.api.shape.Shape;
import org.nd4j.linalg.factory.Nd4j;

import javax.annotation.Nonnull;
import java.io.*;
import java.nio.charset.Charset;

import static org.nd4j.linalg.factory.Nd4j.createArrayFromShapeBuffer;

/**
 * @author Mehrtash Babadi &lt;mehrtash@broadinstitute.org&gt;
 */
public class Nd4jIOUtils {

    /**
     * Write NDArray to a writer.
     *
     * @param arr
     * @param writer
     * @param writerName
     */
    public static void writeNDArrayToWriter(@Nonnull final INDArray arr,
                                            @Nonnull final Writer writer,
                                            @Nonnull final String writerName) {
        try (final DataOutputStream dos = new DataOutputStream(new WriterOutputStream(writer))) {
            Nd4j.write(arr, dos);
        } catch (final IOException ex) {
            throw new UserException.CouldNotCreateOutputFile(writerName, "Could not write the NDArray", ex);
        }
    }

    /**
     * Write NDArray to a file.
     *
     * @param arr
     * @param outputFile
     */
    public static void writeNDArrayToFile(@Nonnull final INDArray arr,
                                          @Nonnull final File outputFile) {
        try (final FileWriter writer = new FileWriter(outputFile)) {
            writeNDArrayToWriter(arr, writer, outputFile.getAbsolutePath());
        } catch (final IOException ex) {
            throw new UserException.CouldNotCreateOutputFile(outputFile, "Could not write the NDArray");
        }
    }

    /**
     * Read NDArray from a reader.
     *
     * @param reader
     * @param readerName
     * @return
     */
    public static INDArray readNDArrayFromReader(@Nonnull final Reader reader, @Nonnull final String readerName) {
        try (final DataInputStream dis = new DataInputStream(new ReaderInputStream(reader))) {
            return Nd4j.read(dis);
        } catch (final IOException ex) {
            throw new UserException.CouldNotReadInputFile(readerName, "Could not read INDArray");
        }
    }

    /**
     * Read NDArray from a file.
     *
     * @param inputFile
     * @return
     */
    public static INDArray readNDArrayFromFile(@Nonnull final File inputFile) {
        try (final FileReader reader = new FileReader(inputFile)) {
            return readNDArrayFromReader(reader, inputFile.getAbsolutePath());
        } catch (final IOException ex) {
            throw new UserException.CouldNotReadInputFile(inputFile, "Could not read the input file");
        }
    }

}
```

The following test fails:

```
    @Test
    public void basicTest() {
        final INDArray arr = Nd4j.rand(1000, 10);
        final File outFile = createTempFile("Nd4j-IO-test", ".nd4j");
        Nd4jIOUtils.writeNDArrayToFile(arr, outFile);
        final INDArray arr2 = Nd4jIOUtils.readNDArrayFromFile(outFile); /* EOFException */
    }
```

with exception:

```
java.lang.RuntimeException: java.io.EOFException

	at org.nd4j.linalg.api.buffer.BaseDataBuffer.read(BaseDataBuffer.java:1297)
	at org.nd4j.linalg.factory.Nd4j.read(Nd4j.java:2223)
	at org.broadinstitute.hellbender.tools.coveragemodel.nd4jutils.Nd4jIOUtils.readNDArrayFromReader(Nd4jIOUtils.java:64)
	at org.broadinstitute.hellbender.tools.coveragemodel.nd4jutils.Nd4jIOUtils.readNDArrayFromFile(Nd4jIOUtils.java:78)
....
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at java.io.DataInputStream.readFloat(DataInputStream.java:446)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.read(BaseDataBuffer.java:1287)
```

I am using nd4j-0.5.0.

**Comment by mbabadi** [comment]
Huh... the issue is with the way I make input/output data streams...

**Comment by eraly** [comment]
@mbabadi Closing.
