### ISSUE TITLE
Sync lock in org.bytedeco.javacpp.Pointer.deallocator is significantly slowing down model building in 6.0

### ISSUE THREAD

**Issue by valncrt** [deeplearning4j/nd4j#1284]
After moving from 4.0 to 6.0 my model building time increased significantly from ~6 per epoch to ~25 with 6.0.  It looks like the problem
is a sync lock in org.bytedeco.javacpp.Pointer.deallocator (I'm using the latest version of javacpp). 

It'a 16 CPU box, locks in the threads look like below.  Stack from the locking thread along with a example of a blocked stack.
```
	- locked <0x000000038240f8c0> (a java.lang.Class for org.bytedeco.javacpp.Pointer$DeallocatorThread)
	- waiting to lock <0x000000038240f8c0> (a java.lang.Class for org.bytedeco.javacpp.Pointer$DeallocatorThread)
	- waiting to lock <0x000000038240f8c0> (a java.lang.Class for org.bytedeco.javacpp.Pointer$DeallocatorThread)
	- waiting to lock <0x000000038240f8c0> (a java.lang.Class for org.bytedeco.javacpp.Pointer$DeallocatorThread)
	- waiting to lock <0x000000038240f8c0> (a java.lang.Class for org.bytedeco.javacpp.Pointer$DeallocatorThread)
	- waiting to lock <0x000000038240f8c0> (a java.lang.Class for org.bytedeco.javacpp.Pointer$DeallocatorThread)
	- waiting to lock <0x000000038240f8c0> (a java.lang.Class for org.bytedeco.javacpp.Pointer$DeallocatorThread)
	- waiting to lock <0x000000038240f8c0> (a java.lang.Class for org.bytedeco.javacpp.Pointer$DeallocatorThread)
	- waiting to lock <0x000000038240f8c0> (a java.lang.Class for org.bytedeco.javacpp.Pointer$DeallocatorThread)
	- waiting to lock <0x000000038240f8c0> (a java.lang.Class for org.bytedeco.javacpp.Pointer$DeallocatorThread)
	- waiting to lock <0x000000038240f8c0> (a java.lang.Class for org.bytedeco.javacpp.Pointer$DeallocatorThread)
	- waiting to lock <0x000000038240f8c0> (a java.lang.Class for org.bytedeco.javacpp.Pointer$DeallocatorThread)
	- waiting to lock <0x000000038240f8c0> (a java.lang.Class for org.bytedeco.javacpp.Pointer$DeallocatorThread)
	- waiting to lock <0x000000038240f8c0> (a java.lang.Class for org.bytedeco.javacpp.Pointer$DeallocatorThread)
	- waiting to lock <0x000000038240f8c0> (a java.lang.Class for org.bytedeco.javacpp.Pointer$DeallocatorThread)


"VectorCalculationsThread 11" #33 prio=5 os_prio=0 tid=0x00007f8d8c846000 nid=0x879b waiting for monitor entry [0x00007f8cf1d49000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:522)
	- locked <0x000000038240f8c0> (a java.lang.Class for org.bytedeco.javacpp.Pointer$DeallocatorThread)
	at org.bytedeco.javacpp.Pointer.init(Pointer.java:121)
	at org.bytedeco.javacpp.FloatPointer.allocateArray(Native Method)
	at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:68)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:454)
	at org.nd4j.linalg.api.buffer.FloatBuffer.<init>(FloatBuffer.java:57)
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createFloat(DefaultDataBufferFactory.java:238)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1277)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1252)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:945)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3099)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:2967)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.iterateSample(SkipGram.java:186)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.skipGram(SkipGram.java:168)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.learnSequence(SkipGram.java:138)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors.trainSequence(SequenceVectors.java:238)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:953)

   Locked ownable synchronizers:
	- None

"VectorCalculationsThread 10" #32 prio=5 os_prio=0 tid=0x00007f8d8c847000 nid=0x879a waiting for monitor entry [0x00007f8cf1e4a000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:522)
	- waiting to lock <0x000000038240f8c0> (a java.lang.Class for org.bytedeco.javacpp.Pointer$DeallocatorThread)
	at org.bytedeco.javacpp.Pointer.init(Pointer.java:121)
	at org.bytedeco.javacpp.FloatPointer.allocateArray(Native Method)
	at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:68)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:454)
	at org.nd4j.linalg.api.buffer.FloatBuffer.<init>(FloatBuffer.java:57)
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createFloat(DefaultDataBufferFactory.java:238)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1277)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1252)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:945)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3099)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:2967)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.iterateSample(SkipGram.java:186)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.skipGram(SkipGram.java:168)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.learnSequence(SkipGram.java:138)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors.trainSequence(SequenceVectors.java:238)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:953)

   Locked ownable synchronizers:
	- None
```

**Comment by agibsonccc** [comment]
Could you give us training times between the 2 and jvisualvm screenshots please?

**Comment by saudet** [comment]
This can happen when allocating too many temporary objects. Would you have
some statistics we could look at for 0.4.0, 0.5.0, and 0.6.0?

**Comment by raver119** [comment]
Let me clarify this: is that 16 CORE cpu?

**Comment by valncrt** [comment]
It's a 16 core CPU (c4.4xlarge).
I think it was one of the recent syncronization changes to org.bytedeco.javacpp.Pointer.java (https://github.com/bytedeco/javacpp/commits/d666a119cf858e0df663e486c08973d19bcb670b/src/main/java/org/bytedeco/javacpp/Pointer.java) which leads to the problem.  Down grading to 1.23 (the sync stuff appears to be 1.24) seemed to resolve the problem.  The problem maybe in that code instead of DL4J.  The performance problem comes from the lock serialization, reducing parallelization rather than from a more 'traditional' performance problem.

**Comment by saudet** [comment]
There has always been a synchronized block in DeallocatorReference.add(), adding a second one just outside of that call by itself cannot make that much of a difference. There's something else going on here. Are you sure you're not running low on memory? If that's the case, you should increase it with -Xmx or by some other means.

**Comment by valncrt** [comment]
Below is a stack trace from the JVM after the model had been building for ~20 minutes.  RSS at the time was ~3.3, Xmx was set to 10G.  DL4J was 5.0 & javacpp was 1.24 (1.23 doesn't exhibit the behavior).
[jstack.txt](https://github.com/deeplearning4j/nd4j/files/482691/jstack.txt)

**Comment by valncrt** [comment]
One more thing, I'm using Java 9 when this Jstack was generated trying to workaround a native memory problem/leak I'm having ( side note, this is the solution I'm exploring http://www.evanjones.ca/java-bytebuffer-leak.html), but the blocking behavior also happens a Java 8 JVM too.

**Comment by saudet** [comment]
It's only going to block there if there isn't enough memory available in the first place, though. On the runs that you try with JavaCPP 1.2.3, are you not seeing memory usage increase over 20G? If so, then you simply have not given it enough memory. Going over the memory limit like that was a problem with previous versions of JavaCPP.

**Comment by raver119** [comment]
It's not an issue anymore, since word2vec/paravec was migrated to full-native codebase, so i'm closing this issue for now, and will open another one, with allocation performance investigation.
