### ISSUE TITLE
Loading Google WordVector Database causes `java.lang.RuntimeException: Can't allocate [HOST] memory: 3600000000`

### ISSUE THREAD

**Issue by Mocuto** [deeplearning4j/nd4j#1332]
Loading Google WordVector Database causes `java.lang.RuntimeException: Can't allocate [HOST] memory: 3600000000`

Code Sample:
```scala
import org.scalatest._

import com.tasky.model._

import java.io._

import org.deeplearning4j.models.embeddings.loader.WordVectorSerializer;

class TaskyDataIteratorSpec extends FlatSpec with Matchers {

  val WordVectorPath = "D:/code/GoogleNews-vectors-negative300.bin"
  val wv = WordVectorSerializer.loadGoogleModel(new File(WordVectorPath), true);

  val jsonFilename = "/data.json"

  "TaskyDataIterator" should "have correct number of examples" in {
    val tdi = new TaskyDataIterator(com.tasky.Tasky.getResourcePath(jsonFilename), wv, 1)
    val expected = 1
    val actual = tdi.numExamples
    actual should === (expected)
  }
}
```
Console Output:
```
[debug] Running TaskDef(TaskyDataIteratorSpec, org.scalatest.tools.Framework$$anon$1@127548a8, false, [SuiteSelector])
[debug] Running TaskDef(HelloSpec, org.scalatest.tools.Framework$$anon$1@127548a8, false, [SuiteSelector])
java.lang.RuntimeException: Can't allocate [HOST] memory: 3600000000; threadId: 46
        at org.nd4j.jita.memory.impl.CudaDirectProvider.malloc(CudaDirectProvider.java:58)
        at org.nd4j.jita.memory.impl.CudaCachingZeroProvider.malloc(CudaCachingZeroProvider.java:116)
        at org.nd4j.jita.memory.impl.CudaFullCachingProvider.malloc(CudaFullCachingProvider.java:76)
        at org.nd4j.jita.handler.impl.CudaZeroHandler.alloc(CudaZeroHandler.java:219)
        at org.nd4j.jita.handler.impl.CudaZeroHandler.alloc(CudaZeroHandler.java:240)
        at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:381)
        at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:338)
        at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<init>(BaseCudaDataBuffer.java:144)
        at org.nd4j.linalg.jcublas.buffer.CudaFloatDataBuffer.<init>(CudaFloatDataBuffer.java:59)
        at org.nd4j.linalg.jcublas.buffer.factory.CudaDataBufferFactory.createFloat(CudaDataBufferFactory.java:251)
        at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1277)
        at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1252)
        at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:249)
        at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:286)
        at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:563)
        at org.nd4j.linalg.jcublas.JCublasNDArray.<init>(JCublasNDArray.java:258)
        at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.create(JCublasNDArrayFactory.java:224)
        at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4369)
        at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4331)
        at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3584)
        at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readBinaryModel(WordVectorSerializer.java:22
5)
        at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.loadGoogleModel(WordVectorSerializer.java:12
4)
        at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.loadGoogleModel(WordVectorSerializer.java:10
4)
        at TaskyDataIteratorSpec.<init>(TaskyDataIteratorSpec.scala:12)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.lang.Class.newInstance(Unknown Source)
        at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:646)
        at sbt.TestRunner.runTest$1(TestFramework.scala:76)
        at sbt.TestRunner.run(TestFramework.scala:85)
        at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
        at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
        at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
        at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
        at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
        at sbt.TestFunction.apply(TestFramework.scala:207)
        at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
        at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
        at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
        at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[error] Could not run test TaskyDataIteratorSpec: java.lang.RuntimeException: Can't allocate [HOST] memory: 3600000000;
threadId: 46
[info] Run completed in 5 seconds, 202 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[debug] Passed tests:
[debug]         HelloSpec
[error] Error during tests:
[error]         TaskyDataIteratorSpec
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
```

**Comment by raver119** [comment]
Now, we have special way to load Word2Vec model in single/multi GPUenvironment for training neural nets with w2v model as vectors lookup source. It's already available at current master: https://github.com/deeplearning4j/deeplearning4j/blob/b4293e678080aea6e00604afb94a476a0faaebb3/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/embeddings/loader/WordVectorSerializer.java#L2192-L2192

On top of that, nlp getting overhaul right now, and we hope starting with next release it'll be also possible to train w2v/paravec/glove models on GPUs efficiently.
