### ISSUE TITLE
Number format exception while creating inferred vectors from our own para vectors

### ISSUE THREAD

**Issue by rahulahuja16** [deeplearning4j/nd4j#1352]
//Created Para vectors using

WordVectorSerializer.writeParagraphVectors(paragraphVectors, filePath);

//Code for creating inferred vector

ClassPathResource resource = new ClassPathResource(myPath);
	        TokenizerFactory t = new DefaultTokenizerFactory();
	        t.setTokenPreProcessor(new CommonPreprocessor());

	        // we load externally originated model
	        ParagraphVectors pv = WordVectorSerializer.readParagraphVectors(myPath);
	        pv.setTokenizerFactory(t);
	        pv.getConfiguration().setIterations(1);
	        

			
			
	        
			bw=new BufferedWriter(new FileWriter(inferrVectorFile));
			bw.write("Doc id \t Label \t Vector \n");

			
			for (CustomLabelledDocument customLabelledDocument : datalist) {
				
				INDArray inferredVector = pv.inferVector(customLabelledDocument.getContent());
				
				bw.write(customLabelledDocument.getDocid()+"\t"+customLabelledDocument.getLabel()+"\t"+inferredVector+"\n");
				//System.out.println("Content:"+customLabelledDocument.getContent());
				System.out.println("Inferred Vector :" + inferredVector);

			
			}
			bw.close();
      

//Error

Exception in thread "main" java.lang.NumberFormatException: For input string: "News)"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readWord2VecFromText(WordVectorSerializer.java:849)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readWord2Vec(WordVectorSerializer.java:785)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readParagraphVectors(WordVectorSerializer.java:699)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readParagraphVectors(WordVectorSerializer.java:686)
	at org.deeplearning4j.examples.nlp.paragraphvectors.ParagraphVectorsClassifierExample.createInferredVectors(ParagraphVectorsClassifierExample.java:146)
	at org.deeplearning4j.examples.nlp.paragraphvectors.ParagraphVectorsClassifierExample.main(ParagraphVectorsClassifierExample.java:127)

**Comment by raver119** [comment]
Please, show first 2 lines of your input file with saved model.

**Comment by rahulahuja16** [comment]
Method used for saving model...

 public static void writeParagraphVectors(ParagraphVectors vectors, OutputStream stream) throws IOException {
        ZipOutputStream zipfile = new ZipOutputStream(new CloseShieldOutputStream(stream));

        ZipEntry syn0 = new ZipEntry("syn0.txt");
        zipfile.putNextEntry(syn0);

**Comment by raver119** [comment]
Problem, surprisingly is your labels that contain spaces.

**Comment by raver119** [comment]
So yes, that's the roots of the issue. I'll add some form of encoding there, like base64, to make sure there'll be no issues like this in future.

**Comment by rahulahuja16** [comment]
Ohh yeah. You are right. I didn't notice this thing. It worked after removing labels with special chars. Thanks a lot.

**Comment by raver119** [comment]
Here's the test that reproduces issue: https://github.com/deeplearning4j/deeplearning4j/blob/3ed2fbba985ab02991df22962a55af61a71cd07d/deeplearning4j-nlp-parent/deeplearning4j-nlp-uima/src/test/java/org/deeplearning4j/models/WordVectorSerializerTest.java#L695-L695

Now i've added base64 encoding/decoding for labels during model save/restore, so this test passes.

Will be merged a bit later today.
