### ISSUE TITLE
nd4j-perf

### ISSUE THREAD

**Issue by chrisvnicholson** [deeplearning4j/nd4j#136]
========================= Benchmark: org.nd4j.linalg.benchmark.gemm.GemmBenchmarkPerformer ===========================
Exception in thread "main" java.lang.IllegalStateException: Given ndarray does not have data type double
	at org.nd4j.linalg.factory.DataTypeValidation.assertDouble(DataTypeValidation.java:43)
	at org.nd4j.linalg.factory.DataTypeValidation.assertDouble(DataTypeValidation.java:33)
	at org.nd4j.linalg.jblas.BlasWrapper.gemv(BlasWrapper.java:460)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmuli(BaseNDArray.java:2572)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmul(BaseNDArray.java:2384)
	at org.nd4j.linalg.benchmark.gemm.GemmOpRunner.runOp(GemmOpRunner.java:16)
	at org.nd4j.linalg.benchmark.api.BaseBenchmarkPerformer.run(BaseBenchmarkPerformer.java:49)
	at org.nd4j.linalg.benchmark.app.BenchmarkRunnerApp.doMain(BenchmarkRunnerApp.java:68)
	at org.nd4j.linalg.benchmark.app.BenchmarkRunnerApp.main(BenchmarkRunnerApp.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
-- org.jblas INFO Deleting /var/folders/dy/kzbsrq1d4k7bb19g2q_v8mtw0000gn/T/jblas7810277292055995577/libjblas.dylib
-- org.jblas INFO Deleting /var/folders/dy/kzbsrq1d4k7bb19g2q_v8mtw0000gn/T/jblas7810277292055995577/libjblas_arch_flavor.dylib
-- org.jblas INFO Deleting /var/folders/dy/kzbsrq1d4k7bb19g2q_v8mtw0000gn/T/jblas7810277292055995577

Process finished with exit code 1

**Comment by agibsonccc** [comment]
FIxed
