### ISSUE TITLE
Multi GPU issue with data types

### ISSUE THREAD

**Issue by rahulahuja16** [deeplearning4j/nd4j#1384]
//Error
```
o.n.n.NativeOps - Number of threads used for NativeOps: 32
o.n.n.Nd4jBlas - Number of threads used for BLAS: 12
o.d.e.m.MultiGpuLenetMnistExample - Load data....


o.d.e.m.MultiGpuLenetMnistExample - Build model....
o.d.e.m.MultiGpuLenetMnistExample - Train model....
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:5484 code=77(<unknown>) "cudaStreamSynchronize(*stream)" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4838 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4817 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
Exception in thread "main" CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
java.lang.NullPointerException
	at org.nd4j.jita.allocator.pointers.CudaPointer.<init>(CudaPointer.java:22)
	at org.nd4j.jita.allocator.pointers.cuda.cudaEvent_t.<init>(cudaEvent_t.java:26)
	at org.nd4j.jita.concurrency.EventsProvider.getEvent(EventsProvider.java:35)
	at org.nd4j.jita.flow.impl.SynchronousFlowController.registerAction(SynchronousFlowController.java:216)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.exec(CudaGridExecutioner.java:864)CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 

CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
	at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.pushToGrid(CudaGridExecutioner.java:242)
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
	at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.processAsGridOp(CudaGridExecutioner.java:304)CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 

CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
	at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.exec(CudaGridExecutioner.java:97)CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 

CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
	at org.nd4j.linalg.api.ndarray.BaseNDArray.divi(BaseNDArray.java:1418)CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 

CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
	at org.nd4j.linalg.api.ndarray.BaseNDArray.divi(BaseNDArray.java:3200)CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 

CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
	at org.deeplearning4j.parallelism.ParallelWrapper.fit(ParallelWrapper.java:152)CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 

CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
CUDA error at /projects/skymind/libnd4j/blas/cuda/NativeOps.cu:4979 code=77(<unknown>) "result" 
	at org.deeplearning4j.examples.multigpu.MultiGpuLenetMnistExample.main(MultiGpuLenetMnistExample.java:147)

```
//System Info

OS : Ubuntu 14.04
Glibc : 2.19
cuda : 7.5
driver version : 361.93.02

Also getting this error while using CUDA in para vectors

https://gist.github.com/rahulahuja16/f0880c03aa517d3caab174de0f8247ff

**Comment by rahulahuja16** [comment]
Similar propblem is with TYPE as DOUBLE

**Comment by raver119** [comment]
Right, bug confirmed. Working on fix now.

**Comment by raver119** [comment]
Issue is fixed.

Thanks for highlighting this one.
