### ISSUE TITLE
Get arbitrarily rows from Dataset or INDArray  

### ISSUE THREAD

**Issue by yylonly** [deeplearning4j/nd4j#1385]
```
DataSetIterator iteratortest = new RecordReaderDataSetIterator(recordReadertest,testsetsize,numInputs,numInputs,true);
	        
DataSet alldata = iteratortest.next();
int[] index = {1,2,3};
alldata.get(index);

```

or

```
INDArray featuresTest = alldata.getFeatureMatrix().get(new SpecifiedIndex(80,126,17,1,11,45,25,131,61,72,13,12,65,82,110), NDArrayIndex.all());

INDArray lablesTest = alldata.getLabels();
	       
INDArray ls = lablesTest.get(new SpecifiedIndex(80,126,17,1,11,45,25,131,61,72,13,12,65,82,110), NDArrayIndex.all());
```

will get error

```
Exception in thread "main" java.lang.UnsupportedOperationException: Illegal combination of indexes for vector
	at org.nd4j.linalg.indexing.ShapeOffsetResolution.tryShortCircuit(ShapeOffsetResolution.java:135)
	at org.nd4j.linalg.indexing.ShapeOffsetResolution.exec(ShapeOffsetResolution.java:325)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.get(BaseNDArray.java:3767)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getRows(BaseNDArray.java:3750)
	at org.nd4j.linalg.dataset.DataSet.get(DataSet.java:774)
	at net.mydreamy.mlpharmaceutics.oraldisintegratingtablet.PredictDisintegrationTimeSimilarity.main(PredictDisintegrationTimeSimilarity.java:52)
```

INDArray getRows() on labels will lead the same error, getRows on FeatureMatrix is okay.

Thanks!

Both my dj4j and nd4j version are 0.6.0

**Comment by eraly** [comment]
@yylonly There was an issue in 0.6.0 where you couldn't getRows on column vectors. 
https://github.com/deeplearning4j/nd4j/issues/1364

This was fixed in 0.7.0. Closing.
