### ISSUE TITLE
DL4J Unit Test Failures with CUDA

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1436]
2 issues (both are cuda specific - relevant tests are passing for native).
Using libnd4j/nd4j/dl4j master.

SPTree.testLargeTree stalls on CUDA - doesn't proceed even after >> 10 mins.

Multiple failures on CUDA for RNG:
```
java.lang.UnsupportedOperationException
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.exec(DefaultOpExecutioner.java:389)
	at org.nd4j.linalg.factory.Nd4j.randn(Nd4j.java:2894)
	at org.deeplearning4j.nn.weights.WeightInitUtil.initWeights(WeightInitUtil.java:90)
	at org.deeplearning4j.nn.params.ConvolutionParamInitializer.createWeightMatrix(ConvolutionParamInitializer.java:139)
```

**Comment by AlexDBlack** [comment]
Also, ND4J CUDA unit tests (via mvn clean test; all native tests are passing):

Failed tests:
  RandomTests.testStepOver1:244 expected:<0.0> but was:<NaN>
Tests in error:
  DoubleDataBufferTest.testSerialization:129 » Runtime java.lang.UnsupportedOper...

Tests run: 840, Failures: 1, Errors: 1, Skipped: 19

**Comment by saudet** [comment]
I'm seeing any errors related to RNG on Linux, so this is maybe specific to Windows

**Comment by raver119** [comment]
It looks like malformed env. Why would it use DefaultOpExecutioner?

**Comment by raver119** [comment]
Fixed
