### ISSUE TITLE
INDArray.eq(integer) throws exceptions

### ISSUE THREAD

**Issue by EdeMeijer** [deeplearning4j/nd4j#1473]
These are 2 bugs really.

To reproduce:
```java
Nd4j.ones(2, 2).eq(1);
```

On CUDA backend, you get this:
```
Exception in thread "main" java.lang.NullPointerException
	at org.nd4j.jita.allocator.impl.AtomicAllocator.getPointer(AtomicAllocator.java:263)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.intercept(CudaExecutioner.java:1376)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.invoke(CudaExecutioner.java:1470)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.pushToGrid(CudaGridExecutioner.java:239)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.processAsGridOp(CudaGridExecutioner.java:306)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.exec(CudaGridExecutioner.java:110)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.eqi(BaseNDArray.java:1291)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.eq(BaseNDArray.java:1285)
	at io.buybrain.sparktest.DumpEpochs.main(DumpEpochs.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
Something with op.y() being null, which goes wrong in CudaExecutioner here
```java
Pointer y = AtomicAllocator.getInstance().getPointer(op.y(), context);
```

On native backend, we get this:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
	at org.nd4j.linalg.cpu.nativecpu.CpuTADManager.getTADOnlyShapeInfo(CpuTADManager.java:49)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.invoke(NativeOpExecutioner.java:400)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:454)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:58)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.eqi(BaseNDArray.java:1291)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.eq(BaseNDArray.java:1285)
	at io.buybrain.sparktest.DumpEpochs.main(DumpEpochs.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

Which has to do with `ScalarEquals` overriding `getDimension` and just returning `new int[0]`.

**Comment by EdeMeijer** [comment]
You might want to check your other ops too, maybe

**Comment by raver119** [comment]
Yes, that's new int[0] shouldn't be ever going out.

**Comment by raver119** [comment]
Fixed
