### ISSUE TITLE
INDArray.put - row vector edge case bug

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1498]
The following code throws an exception, but shouldn't:

```
        INDArray arr = Nd4j.create(1,10);
        INDArray row = Nd4j.create(1,10);

//        arr.putRow(0, row);   //OK
        arr.put(new INDArrayIndex[]{NDArrayIndex.point(0), NDArrayIndex.all()}, row);   //Exception
```

```
Exception in thread "main" java.lang.IllegalStateException: Mis matched lengths: [1] != [10]
	at org.nd4j.linalg.util.LinAlgExceptions.assertSameLength(LinAlgExceptions.java:40)
	at org.nd4j.linalg.api.ops.BaseTransformOp.<init>(BaseTransformOp.java:48)
	at org.nd4j.linalg.api.ops.impl.transforms.Set.<init>(Set.java:25)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.assign(BaseNDArray.java:1125)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.put(BaseNDArray.java:1877)
```

**Comment by agibsonccc** [comment]
Added a test and found it to pass. Closing

**Comment by AlexDBlack** [comment]
The unit test is currently failing on master for me:
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/api/indexing/IndexingTestsC.java#L39

**Comment by agibsonccc** [comment]
This has been fixed: https://github.com/deeplearning4j/nd4j/blob/578d4246fbc2bad1da88df1507047bb3d288bb24/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/api/indexing/IndexingTestsC.java#L96-L96
