### ISSUE TITLE
Not work with cuda-8

### ISSUE THREAD

**Issue by evg299** [deeplearning4j/nd4j#1500]
I'm try run MultiGpuLenetMnistExample, and see stack trace below:

`Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:16)
	at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:9)
	at org.nd4j.jita.conf.Configuration.<init>(Configuration.java:151)
	at org.nd4j.jita.conf.CudaEnvironment.<init>(CudaEnvironment.java:24)
	at org.nd4j.jita.conf.CudaEnvironment.<clinit>(CudaEnvironment.java:18)
	at org.deeplearning4j.examples.multigpu.MultiGpuLenetMnistExample.main(MultiGpuLenetMnistExample.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
	at org.nd4j.nativeblas.NativeOps.<clinit>(NativeOps.java:39)
	... 11 more
Caused by: java.lang.UnsatisfiedLinkError: no jnind4j in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:804)
	at org.bytedeco.javacpp.Loader.load(Loader.java:613)
	at org.nd4j.nativeblas.NativeOps.<clinit>(NativeOps.java:37)
	... 11 more
Caused by: java.lang.UnsatisfiedLinkError: /home/evgeny/.javacpp/cache/nd4j-cuda-7.5-0.7.1-linux-x86_64.jar/org/nd4j/nativeblas/linux-x86_64/libjnind4j.so: libcublas.so.7.5: can not open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:784)
	... 13 more`

On cuda 7.5 works fine.

I suggest it happen because nativeblas search libcublas.so.7.5 but it already replaced libcublas.so.8.0

**Comment by raver119** [comment]
Use another artifact, we provide nd4j-cuda-7.5-platform AND nd4j-cuda-8.0-platform.

In your case you need later one.
