### ISSUE TITLE
Exception when using AllocationModel.CACHE_HOST

### ISSUE THREAD

**Issue by mjakobus** [deeplearning4j/nd4j#1501]
Hi,

when using the cuda 8.0 backend with AllocationModel.CACHE_HOST it is throwing an exception when trying to print the cache-statistics (host and device hit ratios) the first time.

**System informations:**
Deeplearning Version 0.7.1
System Windows 10 64bit
Nvidia Geforce GTX 1080

**Stacktrace:**
```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.nd4j.jita.memory.impl.CudaCachingZeroProvider.printCacheStats(CudaCachingZeroProvider.java:200)
	at org.nd4j.jita.memory.impl.CudaCachingZeroProvider.malloc(CudaCachingZeroProvider.java:88)
	at org.nd4j.jita.handler.impl.CudaZeroHandler.alloc(CudaZeroHandler.java:219)
	at org.nd4j.jita.handler.impl.CudaZeroHandler.alloc(CudaZeroHandler.java:240)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:386)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:343)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<init>(BaseCudaDataBuffer.java:144)
	at org.nd4j.linalg.jcublas.buffer.CudaFloatDataBuffer.<init>(CudaFloatDataBuffer.java:59)
	at org.nd4j.linalg.jcublas.buffer.factory.CudaDataBufferFactory.createFloat(CudaDataBufferFactory.java:251)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1304)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:266)
	at org.nd4j.linalg.jcublas.JCublasNDArray.<init>(JCublasNDArray.java:114)
	at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.createUninitialized(JCublasNDArrayFactory.java:229)
	at org.nd4j.linalg.factory.Nd4j.createUninitialized(Nd4j.java:4502)
	at org.nd4j.linalg.api.shape.Shape.toOffsetZeroCopyHelper(Shape.java:152)
	at org.nd4j.linalg.api.shape.Shape.toOffsetZeroCopy(Shape.java:108)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.dup(BaseNDArray.java:1502)
	at org.nd4j.linalg.jcublas.JCublasNDArray.dup(JCublasNDArray.java:407)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mul(BaseNDArray.java:2644)
	at org.nd4j.linalg.learning.AdaDelta.getGradient(AdaDelta.java:91)
	at org.deeplearning4j.nn.updater.LayerUpdater.update(LayerUpdater.java:85)
	at org.deeplearning4j.nn.updater.MultiLayerUpdater.update(MultiLayerUpdater.java:120)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.updateGradientAccordingToParams(BaseOptimizer.java:294)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:161)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:54)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:51)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1503)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1468)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1547)
	at com.simple.example.MainSimpleExampleExtern.training(MainSimpleExampleExtern.java:341)
	at com.simple.example.MainSimpleExampleExtern.main(MainSimpleExampleExtern.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by raver119** [comment]
Wow, yes. That should be removed.

Thanks for highlighting this one.
