### ISSUE TITLE
Exception when using setFirstMemory(AllocationStatus.DELAYED)

### ISSUE THREAD

**Issue by mjakobus** [deeplearning4j/nd4j#1503]
Hi,

by testing different memory options is stumbled upon another exception when using:
```
        CudaEnvironment.getInstance().getConfiguration()
                .setFirstMemory(AllocationStatus.DELAYED);
```

**Additional information:**
dl4j 0.7.1
backend: cuda 8.0
GTX 1080
Windows 10 64bit

**Stacktrace:**
```
Exception in thread "main" java.lang.IllegalStateException: Can't allocate memory on target [DELAYED]
	at org.nd4j.jita.handler.impl.CudaZeroHandler.alloc(CudaZeroHandler.java:325)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:386)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:343)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<init>(BaseCudaDataBuffer.java:144)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<init>(BaseCudaDataBuffer.java:229)
	at org.nd4j.linalg.jcublas.buffer.CudaFloatDataBuffer.<init>(CudaFloatDataBuffer.java:84)
	at org.nd4j.linalg.jcublas.buffer.factory.CudaDataBufferFactory.createFloat(CudaDataBufferFactory.java:311)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1346)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:1959)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:1954)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3186)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3013)
	at org.deeplearning4j.datasets.iterator.AbstractDataSetIterator.fillQueue(AbstractDataSetIterator.java:199)
	at org.deeplearning4j.datasets.iterator.AbstractDataSetIterator.<init>(AbstractDataSetIterator.java:43)
	at org.deeplearning4j.datasets.iterator.DoublesDataSetIterator.<init>(DoublesDataSetIterator.java:11)
	at com.simple.example.DoublesDataSetShuffleIterator.<init>(DoublesDataSetShuffleIterator.java:18)
	at com.simple.example.MainSimpleExampleExtern.training(MainSimpleExampleExtern.java:136)
	at com.simple.example.MainSimpleExampleExtern.main(MainSimpleExampleExtern.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by raver119** [comment]
Can you please share the code, which reproduces this?

DELAYED stuff originally was supposed for Spark, but later we've got better solution there, but it still shouldn't fail that way.

**Comment by mjakobus** [comment]
Just run the following example. Sorry, if it is looking quick and dirty (This discription is still too good for that), but it is my little class for testing around.

https://gist.github.com/mjakobus/eba09fd2f814ffc100b051bb22e88425

**Comment by raver119** [comment]
Thanks, will do

13 дек. 2016 г. 21:24 пользователь "mjakobus" <notifications@github.com>
написал:
