### ISSUE TITLE
Redeployment of a WAR that uses nd4j fails at runtime with a UnsatisfiedLinkError

### ISSUE THREAD

**Issue by wmeddie** [deeplearning4j/nd4j#1507]
"Then don't do that" is a satisfactory answer here. I'm still wondering if it's possible for nd4j to not fail if the same version of the library has already been loaded.

You can find the sources of the app here: https://gist.github.com/wmeddie/af727d199634f91646d36c32bea009fb

Deploying after a container restart works fine:

```
07:57:06,142 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 66) RESTEASY002225: Deploying javax.ws.rs.core.Application: class com.yumusoft.DeepApp
07:57:06,243 INFO  [org.hibernate.validator.internal.util.Version] (ServerService Thread Pool -- 66) HV000001: Hibernate Validator 5.2.4.Final
07:57:06,325 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 66) WFLYUT0021: Registered web context: /api
07:57:06,369 INFO  [org.jboss.as.server] (management-handler-thread - 2) WFLYSRV0010: Deployed "api.war" (runtime-name : "api.war")
[2016-12-15 07:57:06,434] Artifact dlweb2:war: Artifact is deployed successfully
[2016-12-15 07:57:06,435] Artifact dlweb2:war: Deploy took 28,126 milliseconds
08:00:52,883 INFO  [org.nd4j.nativeblas.NativeOps] (default task-3) Number of threads used for NativeOps: 4
Unable to guess runtime. Please set OMP_NUM_THREADS or equivalent manually.
08:00:53,045 INFO  [org.nd4j.nativeblas.Nd4jBlas] (default task-3) Number of threads used for BLAS: 4

```

But a redeploy fails with the following error.

```
07:54:13,088 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 70) RESTEASY002225: Deploying javax.ws.rs.core.Application: class com.yumusoft.DeepApp
07:54:13,135 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 70) WFLYUT0021: Registered web context: /api
07:54:13,150 INFO  [org.jboss.as.server] (management-handler-thread - 7) WFLYSRV0010: Deployed "api.war" (runtime-name : "api.war")
[2016-12-15 07:54:13,205] Artifact dlweb2:war: Artifact is deployed successfully
[2016-12-15 07:54:13,206] Artifact dlweb2:war: Deploy took 28,401 milliseconds
07:54:46,023 ERROR [io.undertow.request] (default task-5) UT005023: Exception handling request to /api/v1/tests/nd4j: org.jboss.resteasy.spi.UnhandledException: java.lang.ExceptionInInitializerError
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:77)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:220)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:175)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:418)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ExceptionInInitializerError
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:16)
	at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:9)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:38)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5444)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5352)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:186)
	at com.yumusoft.controllers.TestResource.nd4j(TestResource.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
	... 42 more
Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
	at org.nd4j.nativeblas.NativeOps.<clinit>(NativeOps.java:39)
	... 63 more
Caused by: java.lang.UnsatisfiedLinkError: no jnind4j in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1865)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:804)
	at org.bytedeco.javacpp.Loader.load(Loader.java:613)
	at org.nd4j.nativeblas.NativeOps.<clinit>(NativeOps.java:37)
	... 63 more
Caused by: java.lang.UnsatisfiedLinkError: Native Library /Users/eddie/.javacpp/cache/libjnind4j.dylib/libjnind4j.dylib already loaded in another classloader
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1903)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1822)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:784)
	... 65 more
```

**Comment by saudet** [comment]
> ```
> Caused by: java.lang.UnsatisfiedLinkError: Native Library /Users/eddie/.javacpp/cache/libjnind4j.dylib/libjnind4j.dylib already loaded in another classloader
> ```
> 

Yeah, you're going to need to figure out how you're supposed to deal with JNI in your container. Tomcat has stuff to say about this here, for example:
https://wiki.apache.org/tomcat/HowTo#I.27m_encountering_classloader_problems_when_using_JNI_under_Tomcat
Basically, make sure ND4J gets loaded only once, by the system classloader or whichever one the container dictates to use.

**Comment by saudet** [comment]
Should this be a documentation issue?

**Comment by agibsonccc** [comment]
Something like that. I updated the label. Is there *anything* we can do to make this easier on our side? Containers are  fairly common use case in java.

**Comment by saudet** [comment]
Document general workaround such as running only one DL4J  application per container and restarting the whole server instead of redeploying?

**Comment by agibsonccc** [comment]
Hmm 1 war model in all of an app server? That's not an acceptable solution. That beats the whole purpose of an app server.

**Comment by saudet** [comment]
There doesn't seem to be any standard concept of a "shared" or "common" class loader, either as part of Jave EE or a de facto one among various containers, apart from the system class loader, but putting stuff there is pretty much guaranteed going to cause conflicts...

**Comment by agibsonccc** [comment]
Wondering what we could do with specific app servers? https://docs.jboss.org/author/display/WFLY8/Class+Loading+in+WildFly

**Comment by saudet** [comment]
Yes, they pretty much all have ways to deal with this. We could document something for each of them.

**Comment by Atry** [comment]
Also nd4j prevent the `ClassLoader` from unloading if there is a static reference to any `INArray` in the `ClassLoader`.

**Comment by Atry** [comment]
The unloading problem is due to https://stackoverflow.com/questions/48416928/how-to-unload-a-classloader-that-contains-static-native-resources-in-java-9

[holger](https://meta.stackoverflow.com/users/2711488/holger) said
> 1) being closed by a Cleaner should not be the primary resource cleanup method, 2) the resource should not be shared by a static field. Both has been discouraged for more than twenty years now. External resources should be closed by an explicit action rather than hoping that the garbage collector will free them eventually.

I understand `ReferenceQueue` can be used as a safety net for INDArray's clean up. However, missing explicit method `close` in `INDArray` does not seem like a wise decision.

**Comment by agibsonccc** [comment]
What are the updates here? @saudet @wmeddie ?

**Comment by wmeddie** [comment]
@raver119 Is it possible to use nest workspaces in a way that they can clean up every single INDArray reference?

**Comment by raver119** [comment]
Something like global workspace for all INDArrays within session?

**Comment by wmeddie** [comment]
Yeah for cleanup purposes when restarting an app inside a container.

**Comment by saudet** [comment]
Ah, I found this for JBoss: https://developer.jboss.org/thread/35523?_sscc=t
Looks like we need to create an "MBean" around classes using JNI:

> You can use the mbean to load a class that wraps the
> native implementation. The mbean is loaded at server
> start, i.e. the code only happens once.
> The servlets can then reference that class, probably
> through some sort of static factory method?

I'll keep posting here information about various containers when I stumble on it, and one day we'll get a comprehensive guide...
