### ISSUE TITLE
error with nd4J in image pipeline example

### ISSUE THREAD

**Issue by jihensalma** [deeplearning4j/nd4j#1548]
Hello, 
Can you please help me with this error I get when I run the image pipeline example in deeplearning4j
I am using netbeans as an editor

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/nd4j/linalg/exception/ND4JIllegalStateException
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5236)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5183)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:167)
	at org.datavec.image.loader.NativeImageLoader.asMatrix(NativeImageLoader.java:258)
	at org.datavec.image.loader.NativeImageLoader.asMatrix(NativeImageLoader.java:209)
	at org.datavec.image.loader.NativeImageLoader.asMatrix(NativeImageLoader.java:194)
	at org.datavec.image.recordreader.BaseImageRecordReader.next(BaseImageRecordReader.java:204)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:152)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:333)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:46)
	at com.mycompany.mavenproject3.readdata.main(readdata.java:81)
Caused by: java.lang.ClassNotFoundException: org.nd4j.linalg.exception.ND4JIllegalStateException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more
```

**Comment by raver119** [comment]
You have version clash somewhere. If you'll show your pom.xml, i'll be glad to point you to your mistake.

But generally: You have to set equal versions for nd4j/dl4j/datavec. Right now latest version is 0.7.1, in a day or two it'll be 0.7.2

**Comment by jihenAM** [comment]
Thank you @raver119  for the helpful answer I set equal versions as you told me and it fixed the problem.

**Comment by jihensalma** [comment]
Thank you @raver119  for the helpful answer I set equal versions as you told me and it fixed the problem.
