### ISSUE TITLE
sub() ends in exception: java.lang.IllegalArgumentException: Array must be a vector

### ISSUE THREAD

**Issue by c0der1337** [deeplearning4j/nd4j#156]
Example code:
		   INDArray y = Nd4j.rand(3,4);
		   x = Nd4j.rand(3,4);
		   y.sub(x);

Exception in thread "main" java.lang.IllegalArgumentException: Array must be a vector
	at org.nd4j.linalg.util.LinAlgExceptions.assertVector(LinAlgExceptions.java:54)
	at org.nd4j.linalg.util.LinAlgExceptions.assertVector(LinAlgExceptions.java:44)
	at org.nd4j.linalg.factory.BaseBlasWrapper.axpy(BaseBlasWrapper.java:155)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subi(BaseNDArray.java:2695)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subi(BaseNDArray.java:2672)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.sub(BaseNDArray.java:2465)

**Comment by agibsonccc** [comment]
This is fixed now. This was due to requiring axpy.
