### ISSUE TITLE
MemcpyAsync failed: AllocationShape

### ISSUE THREAD

**Issue by webstorms** [deeplearning4j/nd4j#1560]
Error:
https://gist.github.com/webstorms/c7ff8d3f7cabe9f50613d6440e7d7218

[Files.zip](https://github.com/deeplearning4j/nd4j/files/679617/Files.zip)

(DataSet not included in zip but pom and all source code)

**Comment by raver119** [comment]
Please show full output log as well

**Comment by raver119** [comment]
Also, you have multiple files there, what exactly you've been executing?

**Comment by webstorms** [comment]
[pom.xml.zip](https://github.com/deeplearning4j/nd4j/files/679645/pom.xml.zip)

**Comment by webstorms** [comment]
Updated the output and pom

**Comment by webstorms** [comment]
It seems that DataTypeUtil.setDTypeForContext(DataBuffer.Type.HALF); is the problem because DataTypeUtil.setDTypeForContext(DataBuffer.Type.DOUBLE); seems to be working so far

**Comment by raver119** [comment]
Can you please do the following:
- Set back HALF data type
- Enable debugging mode, by adding this:

```
CudaEnvironment.getInstance().getConfiguration().enableDebug(true).setVerbose(true);
```
- And run your app once again.

You'll have much more output in your console, so you just post it here as link to https://gist.github.com

**Comment by webstorms** [comment]
I did what you suggested but get the following error: https://gist.github.com/webstorms/1ea0682f76f8ced5d40a4c2fcd3752a0
when adding the CudaEnvironment.getInstance().getConfiguration().enableDebug(true).setVerbose(true);
statement

**Comment by webstorms** [comment]
It seems like CudaEnvironment.getInstance(); is throwing all sorts of exceptions due to missing nd4j dependencies

**Comment by agibsonccc** [comment]
@webstorms that's going to happen by default :D not sure what you're expecting being that this is an nd4j backend complaining about nd4j backend related things :D

**Comment by webstorms** [comment]
I've run the latest provided example MultiGpuLenetMnistExample with
`java -cp dl4j-cuda-specific-examples/target/dl4j-cuda-specific-examples-0.7-SNAPSHOT-bin.jar org.deeplearning4j.examples.multigpu.MultiGpuLenetMnistExample`
But I get the same error:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.nd4j.jita.conf.Configuration.<init>(Configuration.java:150)
        at org.nd4j.jita.conf.CudaEnvironment.<init>(CudaEnvironment.java:24)
        at org.nd4j.jita.conf.CudaEnvironment.<clinit>(CudaEnvironment.java:18)
        at org.deeplearning4j.examples.multigpu.MultiGpuLenetMnistExample.main(MultiGpuLenetMnistExample.java:43)
Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
        at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:40)
        at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:16)
        ... 4 more
Caused by: java.lang.NullPointerException
        at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:23)
        ... 5 more
```

**Comment by webstorms** [comment]
Any suggestions as to what I should try to save you time?

**Comment by webstorms** [comment]
Turns out you need to call `Nd4j.create(1);` before any call to `CudaEnvironment.getInstance()`. Now to get back to the initial problem. I call 
`CudaEnvironment.getInstance().getConfiguration().enableDebug(true).setVerbose(true);` as you wanted @raver119

I get the following output now:
```
CUDA error at /projects/skymind/deploy/linux-x86_64/libnd4j/blas/cuda/NativeOps.cu:5192 code=77(<unknown>) "result"
CUDA error at /projects/skymind/deploy/linux-x86_64/libnd4j/blas/cuda/NativeOps.cu:5192 code=77(<unknown>) "result"
CUDA error at /projects/skymind/deploy/linux-x86_64/libnd4j/blas/cuda/NativeOps.cu:5192 code=77(<unknown>) "result"
CUDA error at /projects/skymind/deploy/linux-x86_64/libnd4j/blas/cuda/NativeOps.cu:5192 code=77(<unknown>) "result"
CUDA error at /projects/skymind/deploy/linux-x86_64/libnd4j/blas/cuda/NativeOps.cu:5192 code=77(<unknown>) "result"
CUDA error at /projects/skymind/deploy/linux-x86_64/libnd4j/blas/cuda/NativeOps.cu:5192 code=77(<unknown>) "result"
CUDA error at /projects/skymind/deploy/linux-x86_64/libnd4j/blas/cuda/NativeOps.cu:2020 code=77(<unknown>) "cudaStreamSynchronize(*stream)"
CUDA error at /projects/skymind/deploy/linux-x86_64/libnd4j/blas/cuda/NativeOps.cu:5044 code=77(<unknown>) "result"
CUDA error at /projects/skymind/deploy/linux-x86_64/libnd4j/blas/cuda/NativeOps.cu:5044 code=77(<unknown>) "result"
CUDA error at /projects/skymind/deploy/linux-x86_64/libnd4j/blas/cuda/NativeOps.cu:5192 code=77(<unknown>) "result"
CUDA error at /projects/skymind/deploy/linux-x86_64/libnd4j/blas/cuda/NativeOps.cu:5192 code=77(<unknown>) "result"
CUDA error at /projects/skymind/deploy/linux-x86_64/libnd4j/blas/cuda/NativeOps.cu:5192 code=77(<unknown>) "result"
CUDA error at /projects/skymind/deploy/linux-x86_64/libnd4j/blas/cuda/NativeOps.cu:5192 code=77(<unknown>) "result"
Exception in thread "main" java.lang.RuntimeException: Can't allocate [HOST] memory: 128; threadId: 1
        at org.nd4j.jita.memory.impl.CudaDirectProvider.malloc(CudaDirectProvider.java:58)
        at org.nd4j.jita.memory.impl.CudaCachingZeroProvider.malloc(CudaCachingZeroProvider.java:113)
        at org.nd4j.jita.memory.impl.CudaFullCachingProvider.malloc(CudaFullCachingProvider.java:89)
        at org.nd4j.jita.handler.impl.CudaZeroHandler.alloc(CudaZeroHandler.java:219)
        at org.nd4j.jita.handler.impl.CudaZeroHandler.alloc(CudaZeroHandler.java:240)
        at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:386)
        at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:343)
        at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<init>(BaseCudaDataBuffer.java:144)
        at org.nd4j.linalg.jcublas.buffer.CudaHalfDataBuffer.<init>(CudaHalfDataBuffer.java:59)
        at org.nd4j.linalg.jcublas.buffer.factory.CudaDataBufferFactory.createHalf(CudaDataBufferFactory.java:396)
        at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1311)
        at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1282)
        at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:253)
        at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:290)
        at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:567)
        at org.nd4j.linalg.jcublas.JCublasNDArray.<init>(JCublasNDArray.java:258)
        at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.create(JCublasNDArrayFactory.java:230)
        at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4646)
        at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3810)
        at org.nd4j.linalg.factory.Nd4j.zeros(Nd4j.java:5235)
        at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.buildZ(CudaGridExecutioner.java:571)
        at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.exec(CudaGridExecutioner.java:656)
        at org.nd4j.linalg.factory.Nd4j.argMax(Nd4j.java:683)
        at org.deeplearning4j.eval.Evaluation.eval(Evaluation.java:258)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.evaluate(MultiLayerNetwork.java:2423)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.evaluate(MultiLayerNetwork.java:2376)
        at edu.uct.research.CrossValidation.CrossValidation.getTop1Score(CrossValidation.java:146)
        at edu.uct.research.CrossValidation.CrossValidation.getEvaluationAcc(CrossValidation.java:78)
        at edu.uct.research.Model.Experiment$2.onEpochComplete(Experiment.java:86)
        at edu.uct.research.CrossValidation.CrossValidation.trainModel(CrossValidation.java:121)
        at edu.uct.research.CrossValidation.CrossValidation.fit(CrossValidation.java:97)
        at edu.uct.research.Model.Experiment.logEpochs(Experiment.java:105)
        at edu.uct.research.Project.Launcher.main(Launcher.java:27)
```

**Comment by raver119** [comment]
I need full output, not only the part you think as relevant.

**Comment by agibsonccc** [comment]
@raver119 we determined it was the order of the CudaEnvironment and nd4j.

**Comment by agibsonccc** [comment]
FWIW when alex and I worked with him yesterday - calling nd4j first was the fix. I get the curiosity though :D

**Comment by DuaneNielsen** [comment]
Just a pointer for others that might end up here.. I had a similar exception, and it turned out that I was simply putting too many rows into a single INDArray.  The error in my case meant "I'm out of memory", although it wasn't easy to figure that out.

**Comment by agibsonccc** [comment]
Could we maybe get this fixed? This kind of behavior shouldn't persist in to 0.8.

**Comment by TheBigLou13** [comment]
Had the same issue in the XOR-Example. If you run it with Cuda it crashes on calling **Nd4j.zeros(4, 2);** (first command). If you move the creation of the Dataset right in front of **net.fit(ds);** (the first usage) everything works fine again. Looks like some initialisation needs to take action before you can call any Nd4j function to not get a crash. Mentioned crash was:

`
Exception in thread "main" org.nd4j.linalg.exception.ND4JException: CUDA exception happened. Terminating. Last op: [null]
	at org.nd4j.jita.allocator.pointers.cuda.cudaStream_t.synchronize(cudaStream_t.java:24)
	at org.nd4j.jita.handler.impl.CudaZeroHandler.alloc(CudaZeroHandler.java:302)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:470)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:396)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<init>(BaseCudaDataBuffer.java:216)
	at org.nd4j.linalg.jcublas.buffer.CudaFloatDataBuffer.<init>(CudaFloatDataBuffer.java:60)
	at org.nd4j.linalg.jcublas.buffer.factory.CudaDataBufferFactory.createFloat(CudaDataBufferFactory.java:321)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1468)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1442)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:1578)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:1688)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.zeros(BaseNDArrayFactory.java:1235)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.zeros(BaseNDArrayFactory.java:803)
	at org.nd4j.linalg.factory.Nd4j.zeros(Nd4j.java:5265)
	at lou.ai.dl4jp.App.main(App.java:33)
CUDA error at D:/jenkins/workspace/dl4j/all-multiplatform_windows-x86_64/libnd4j/stream3/libnd4j/blas/cuda/NativeOps.cu:4885 code=2(cudaErrorMemoryAllocation) "result" 
`

Worth mentioning: I dont have a directory D:\jenkins. I have no idea why there is an hardcoded path causing issues in a stable cuda version. This feels pretty unstable. If you google that hole path you see that it seems to cause all kinds of issues.

**Comment by agibsonccc** [comment]
@TheBigLou13 the hardcoded path isn't relevant here fyi. In fact it's a straw man.
 That's just standard output from the crash. As for what you're running in to, could you give us something a bit more useful? Eg: What are you running in to? What does your code look like? If youc an give us something to run and what your version is we could take a look at this.

I have to be super skeptical here, the guy right above you corrected it with a  memory fix. You're supposedly not running that large of a problem so that shouldn't be the cause.

**Comment by TheBigLou13** [comment]
Even stranger: Again in the feedforward XOR-Example.

if you create the Dataset before **builder.seed(123)** it crashes. If you create it afterwards it works. Seems that setting the seed is the initialization needed to call any Nd4j method.

**Comment by TheBigLou13** [comment]
This is the mentioned XOR-Example: 
https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/feedforward/xor/XorExample.java

**Comment by TheBigLou13** [comment]
Okay - broke it down to something runnable:

**Crashes:**
NeuralNetConfiguration.Builder builder = new NeuralNetConfiguration.Builder();
INDArray input = Nd4j.zeros(4, 2);
System.exit(0);

**Works:**
NeuralNetConfiguration.Builder builder = new NeuralNetConfiguration.Builder();
builder.seed(123);
INDArray input = Nd4j.zeros(4, 2);
System.exit(0);

**Comment by agibsonccc** [comment]
Perfect! All we were missing thanks. This is with 0.9.1 right?

**Comment by TheBigLou13** [comment]
Correct - i just cloned the example repo and set everything up about 2 hours ago - even with a fresh 8.0 Cuda installation. So version-wise as fesh as it can be ;)

Incredible response time btw - as the ticket was created in 2016 i wasn't so sure if it's still alive ;)
Good job!
