### ISSUE TITLE
NoClassDefFoundError: org/nd4j/linalg/api/blas/Blas error in ImageClassification example

### ISSUE THREAD

**Issue by rezacsedu** [deeplearning4j/nd4j#1565]
Hi there,

I am trying to use the image classification application using CNN given at https://github.com/deeplearning4j/dl4j-examples/tree/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/convolution 
However, I#m getting the following error:
19:33:05.465 [main] INFO  c.e.I.AnimalsClassification - Load data....
19:33:05.499 [main] INFO  c.e.I.AnimalsClassification - Build model....
Exception in thread "main" java.lang.NoClassDefFoundError: org/nd4j/linalg/api/blas/Blas
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5413)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5352)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:186)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.seed(NeuralNetConfiguration.java:633)
	at com.example.ImageClassificationUsingCNN.AnimalsClassification.alexnetModel(AnimalsClassification.java:264)
	at com.example.ImageClassificationUsingCNN.AnimalsClassification.run(AnimalsClassification.java:135)
	at com.example.ImageClassificationUsingCNN.AnimalsClassification.main(AnimalsClassification.java:315)
Caused by: java.lang.ClassNotFoundException: org.nd4j.linalg.api.blas.Blas
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more

Any kind of help will be appreciated.

**Comment by raver119** [comment]
Open your pom.xml, and make sure all our dependencies -> nd4j/dl4j/datavec - all have the same version. Latest version is 0.7.2. It sounds like version clash issue.

**Comment by rezacsedu** [comment]
Hi,
You're right. It was a version conflict issue. Now it works after changing to version 0.7.2. 

Thanks a lot.
