### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopenblas in java.library.path

### ISSUE THREAD

**Issue by demongolem** [deeplearning4j/nd4j#1627]
I see #1564, however it does not help my case.

I am on Windows 10 with java 1.8.

I followed the guidelines of [this guide](http://electronsfree.blogspot.com/2016/10/how-to-setup-dl4j-project-with-eclipse.html) to quickly set up with Eclipse and without Maven.  I have all the jars included from robottag-master, not including the 6 with "cuda" in their name.

I downloaded OpenBLAS-v0.2.19-Win64-int32.zip for my blas, moved it to C:\OpenBLAS-v0.2.19-Win64-int32 and added that directory to my Windows Path Environment variable.

I am trying to run the example GravesLSTMCharModellingExample.java and get the following stack trace:

`Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopenblas in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:945)
	at org.bytedeco.javacpp.Loader.load(Loader.java:750)
	at org.bytedeco.javacpp.Loader.load(Loader.java:657)
	at org.bytedeco.javacpp.openblas.<clinit>(openblas.java:10)
	at org.nd4j.linalg.cpu.nativecpu.blas.CpuBlas.setMaxThreads(CpuBlas.java:87)
	at org.nd4j.nativeblas.Nd4jBlas.<init>(Nd4jBlas.java:36)
	at org.nd4j.linalg.cpu.nativecpu.blas.CpuBlas.<init>(CpuBlas.java:11)
	at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.createBlas(CpuNDArrayFactory.java:79)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.blas(BaseNDArrayFactory.java:71)
	at org.nd4j.linalg.cpu.nativecpu.blas.CpuLevel1.<init>(CpuLevel1.java:22)
	at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.createLevel1(CpuNDArrayFactory.java:84)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.level1(BaseNDArrayFactory.java:78)
	at org.nd4j.linalg.factory.BaseBlasWrapper.level1(BaseBlasWrapper.java:31)
	at org.deeplearning4j.nn.layers.recurrent.LSTMHelpers.activateHelper(LSTMHelpers.java:137)
	at org.deeplearning4j.nn.layers.recurrent.GravesLSTM.activateHelper(GravesLSTM.java:150)
	at org.deeplearning4j.nn.layers.recurrent.GravesLSTM.rnnActivateUsingStoredState(GravesLSTM.java:222)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.rnnActivateUsingStoredState(MultiLayerNetwork.java:2274)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:1810)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:151)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:54)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:51)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.doTruncatedBPTT(MultiLayerNetwork.java:1185)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1482)
	at GravesLSTMCharModellingExample.main(GravesLSTMCharModellingExample.java:202)
Caused by: java.lang.UnsatisfiedLinkError: no openblas in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:945)
	at org.bytedeco.javacpp.Loader.load(Loader.java:738)
	... 22 more
` 

I see that my java.library.path ends up being my Path directory since I do not explicitly set it.  I have slipped into the example `System.setProperty("org.bytedeco.javacpp.logger.debug", "true");` and can give the output of my run, if necessary.

None of the few cases I can google seem to resolve my situation, so this is the issue to address my setup.

**Comment by demongolem** [comment]
So if I do like `System.load("C:\\OpenBLAS-v0.2.19-Win64-int32\\bin\\libopenblas.dll");` in my own separate program, I see 

`Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\OpenBLAS-v0.2.19-Win64-int32\bin\libopenblas.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at MeaCulpa.main(MeaCulpa.java:10)`

So I guess the dll does not work for me out of the box?

**Comment by saudet** [comment]
It looks like you're trying to use an old version. Could you try again with 0.7.2?

**Comment by raver119** [comment]
You are trying to use DL4j without maven, right?

**Comment by demongolem** [comment]
Ok, will try again to make sure I have 0.7.2.  Yes that is right, the tutorial above I was following for those who did not want to use maven.

**Comment by demongolem** [comment]
I have given in and gone the git/mvn route.  I do

> $ git clone https://github.com/deeplearning4j/dl4j-examples.git
> $ cd dl4j-examples/
> $ mvn clean install

as the quickstart page urges me to do.  I then try to run the same example file from that git clone I did in the step above instead of the one I had initially been using.  (Still using Eclipse), I set 

> -Djava.library.path="C:\\OpenBLAS-v0.2.19-Win64-int32\\bin\\"

and I get the same 

> Loading library libopenblas
> Failed to load for libopenblas: java.lang.UnsatisfiedLinkError: C:\OpenBLAS-v0.2.19-Win64-int32\bin\libopenblas.dll: Can't find dependent libraries

that I get meaning that it sees the dll, but it cannot work with it.  I suppose then my problem lies with the blas installation on my Windows 10 machine since via 2 different methods of creating my repository I arrive at the same error message.

**Comment by demongolem** [comment]
I then try again with the same git/mvn code I retrieved as above except with intelliJ instead of Eclipse and it works for me.  I import as maven project then associate jdk8 with it and it does run.  This is not very satisfactory for me that I have to use the exact combination of tools to get it to work.  The others I talk with on creating NLP models use Eclipse as well, not too excited. Things seem a little to fragile for me at the moment.

**Comment by agibsonccc** [comment]
@demongolem you're in the minority my friend. We're in prod in tons of places; many of who use windows.   That being said; I have little tolerance for this kind of dialogue. Please keep it professional.
The "other tools" are usually going to be higher level I am assuming you are talking about UIMA and their associated tooling. If you want to go use them please do. You aren't paying for this software. Keep the entitlement down. if you want entitlement, engage in a proper commercial engagement with us.

We support intellij because it's what has worked for us. A lot of us are former eclipse people who have switched because eclipse just breaks randomly, everything from classpath resource resolution, out of memory, stale environment variables, it's just inconsistent.  If you want an eclipse based stack the ASF is ->

That being said if we're going to keep this productive, could you give us a full stack trace?

**Comment by saudet** [comment]
Let 's check what Dependency Walker tells us:
https://github.com/bytedeco/javacpp-presets/wiki/Debugging-UnsatisfiedLinkError-on-Windows
The <module> here is Nd4jCpu.

**Comment by agibsonccc** [comment]
Closing due to inactivity.

**Comment by biswadeb** [comment]
I am running DL4J on MS Windows 7 with Java 8. I simply followed the instructions as described in the Quick Start Guide using GIT, IntelliJ and maven. In my case the problem was resolved by removing the environment variables pointing to the Anaconda installation included in the PATH environment variables specified.

**Comment by saudet** [comment]
@biswadeb Which version of Anaconda are you using?

**Comment by biswadeb** [comment]
Hi Saudet,
I have Anaconda3 installed. I don't think that the problem is related to a specific version of Anaconda. During the execution of the example, I noticed that the MKPL, OpenBLAS and some other libraries were being retrieved from the Anaconda installation. When I removed the Anaconda PATH variables defined, the example worked fine.

I hope this helps.

Cheers,
Biswadeb.

**Comment by saudet** [comment]
@biswadeb I've installed the latest version of Anadonda3 here, and everything is fine. ND4J uses the MKL binaries that come with that version of Anaonda3 without any issue at all. If you could tell us the version of Anaconda3 your are using, it would be helpful. Thank you

**Comment by biswadeb** [comment]
Hi Saudet,
I am not using the latest version of Anaconda on my laptop. I have Anaconda version 4.1.0.
If you are not running into a problem with Anaconda then the problem I had must have been specific to my environment. Outside of this I do not have any further inputs.
Cheers,
Biswadeb.

**Comment by saudet** [comment]
I tried Anaconda3 4.2.0 and didn't have a problem. I'll try 4.1.0...

**Comment by priyankasadan** [comment]
Caused by: java.lang.UnsatisfiedLinkError: no opencv_imgproc320 in java.library.path
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.lang.System.loadLibrary(Unknown Source)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:976)
	at org.bytedeco.javacpp.Loader.load(Loader.java:765)

Please help me to solve this error

**Comment by AlexDBlack** [comment]
@priyankasadan you are unlikely to get help by posting on very old issues that are unrelated to your issue. I'd suggest opening a new ND4J issue, and more information, such as your maven pom.xml file (or equivalent).

**Comment by Fitap** [comment]
Hi, I have the same issue like @priyankasadan 

java.lang.UnsatisfiedLinkError: no listSerialsj in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at processing.app.Platform.<clinit>(Platform.java:157)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at processing.app.BaseNoGui.initPlatform(BaseNoGui.java:527)
        at processing.app.Base.<init>(Base.java:199)
        at processing.app.Base.main(Base.java:144)

eix libserialport
[I] dev-libs/libserialport
     Available versions:  ~0.1.0 0.1.1 **9999 {static-libs udev}
     Installed versions:  0.1.1(19:38:45 01/03/18)(-static-libs)
     Homepage:            http://sigrok.org/wiki/Libserialport
     Description:         Cross platform serial port access library

My best.

**Comment by raver119** [comment]
O_o

How  this `libserialport` relates to dl4j/nd4j?
