### ISSUE TITLE
NPE in NdArraySerializerTest

### ISSUE THREAD

**Issue by huitseeker** [deeplearning4j/nd4j#1633]
While investigating a follow-up to #1625 (see [here](https://github.com/huitseeker/nd4j/commit/93f240d407c3d769704fb54bb2c499537636b84b)) I noticed a test failure, with an NPE in `NdArrayDeserializer` at

            String field = node.get("array").asText();

triggered by `NdArraySerializerTest`.

With a bit more println for diagnostic ([here](https://github.com/huitseeker/nd4j/commit/f12e05c37ca0eb472570f09e1120f3052751c663)), it seems the array written in `NdArraySerializerTest` at

            String json = objectMapper.writeValueAsString(Nd4j.create(2,2));

since #1629 is an array that is not read back correctly in `readValue`. Is the base64 string written by the serializer conformant with the tree model assumed by this line in `NdArrayDeserializer` ?

           JsonNode node = jp.getCodec().readTree(jp);

Relevant test output (with the printlns):
```
Running org.nd4j.serde.jackson.NdArraySerializerTest

"array""AAdKQVZBQ1BQAAAACAADSU5UAAAAAgAAAAIAAAACAAAAAgAAAAEAAAAAAAAAAQAAAGMAB0pBVkFD\r\nUFAAAAAEAAVGTE9BVAAAAAAAAAAAAAAAAAAAAAA=\r\n"
NODE: "array"
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.019 sec <<< FAILURE! - in org.nd4j.serde.jackson.NdArraySerializerTest
testSerde(org.nd4j.serde.jackson.NdArraySerializerTest)  Time elapsed: 0.016 sec  <<< ERROR!
java.lang.NullPointerException
	at org.nd4j.shade.serde.jackson.shaded.NDArrayDeSerializer.deserialize(NDArrayDeSerializer.java:26)
	at org.nd4j.shade.serde.jackson.shaded.NDArrayDeSerializer.deserialize(NDArrayDeSerializer.java:19)
	at org.nd4j.shade.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3562)
	at org.nd4j.shade.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2578)
	at org.nd4j.serde.jackson.NdArraySerializerTest.testSerde(NdArraySerializerTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)

Running org.nd4j.serde.jackson.VectorSerializeTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.009 sec - in org.nd4j.serde.jackson.VectorSerializeTest

Results :

Tests in error: 
  NdArraySerializerTest.testSerde:33 » NullPointer

Tests run: 965, Failures: 0, Errors: 1, Skipped: 23
```

Full compilation output with  ` mvn -X -e -Dsurefire.useFile=false -DtrimStackTrace=false -Dmaven.javadoc.skip=true package`

is [here](https://gist.github.com/huitseeker/f50cf00b8e79b3a0d4c6f7469902b2cd)

**Comment by agibsonccc** [comment]
Should be fixed: https://github.com/deeplearning4j/nd4j/blob/8070249e1af069ab6d1efcc5afd0a8f8f5bc9389/nd4j-serde/nd4j-jackson/src/main/java/org/nd4j/shade/serde/jackson/ndarray/NDArraySerializer.java#L23-L23 will wait till merge on raver's PR (which should also be merged here soon)

**Comment by huitseeker** [comment]
I'm afraid not. [Here](https://github.com/huitseeker/nd4j/tree/jackson-investigation)'s a branch with the patch above, and with the [diagnostic commit](https://github.com/huitseeker/nd4j/commit/f12e05c37ca0eb472570f09e1120f3052751c663). Similar output (below), same error. Full gist [here](https://gist.github.com/huitseeker/76148a2bdcc2b7cb4d313627e1c036d3).

```
Running org.nd4j.serde.jackson.NdArraySerializerTest

"array""AAdKQVZBQ1BQAAAACAADSU5UAAAAAgAAAAIAAAACAAAAAgAAAAEAAAAAAAAAAQAAAGMAB0pBVkFD\r\nUFAAAAAEAAVGTE9BVAAAAAAAAAAAAAAAAAAAAAA=\r\n"
NODE: "array"
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.024 sec <<< FAILURE! - in org.nd4j.serde.jackson.NdArraySerializerTest
testSerde(org.nd4j.serde.jackson.NdArraySerializerTest)  Time elapsed: 0.019 sec  <<< ERROR!
java.lang.NullPointerException
	at org.nd4j.shade.serde.jackson.shaded.NDArrayDeSerializer.deserialize(NDArrayDeSerializer.java:26)
	at org.nd4j.shade.serde.jackson.shaded.NDArrayDeSerializer.deserialize(NDArrayDeSerializer.java:19)
	at org.nd4j.shade.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3562)
	at org.nd4j.shade.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2578)
	at org.nd4j.serde.jackson.NdArraySerializerTest.testSerde(NdArraySerializerTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)

Running org.nd4j.serde.jackson.VectorSerializeTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.009 sec - in org.nd4j.serde.jackson.VectorSerializeTest

Results :

Tests in error: 
  NdArraySerializerTest.testSerde:33 » NullPointer

Tests run: 965, Failures: 0, Errors: 1, Skipped: 23
```

**Comment by agibsonccc** [comment]
So this is what I'm seeing:

**Comment by huitseeker** [comment]
Yep, took me a while but I can confirm this one is fixed. Probably a missing `-U` in my `mvn` command-line that caused a pickup of an old `nd4j-serde` module somewhere in my cache.
