### ISSUE TITLE
Initializing a random array fails if length >= Integer.MAX_Value

### ISSUE THREAD

**Issue by amrast** [deeplearning4j/nd4j#1644]
Hey folks,

I work on a pretty large corpus and while learning from it, nd4j creates a large random array with a UniformDistribution. It fails in the following UniformDistribution class. I marked the line with the fix.

`package org.nd4j.linalg.api.ops.random.impl;

public class UniformDistribution extends BaseRandomOp {
   
    /**
     * This op fills Z with random values within from...to boundaries
     * @param z
     * @param from
     * @param to
     */
    public UniformDistribution(@NonNull INDArray z, double from, double to) {
        init(null, null, z, z.length());  // <-- this should be the error. It should call z.lengthLong() instead
        this.from = from;
        this.to = to;
        this.extraArgs = new Object[]{this.from, this.to};
    }

}
`

Stacktrace:
` Exception in thread "main" java.lang.IllegalArgumentException: Length is >= Integer.MAX_VALUE: lengthLong() must be called instead
        at org.nd4j.linalg.api.ndarray.BaseNDArray.length(BaseNDArray.java:4203)
        at org.nd4j.linalg.api.ops.random.impl.UniformDistribution.<init>(UniformDistribution.java:25)
        at org.nd4j.linalg.api.ops.random.impl.UniformDistribution.<init>(UniformDistribution.java:36)
        at org.nd4j.linalg.factory.Nd4j.rand(Nd4j.java:2843)
        at org.deeplearning4j.models.embeddings.inmemory.InMemoryLookupTable.resetWeights(InMemoryLookupTable.java:133)
        at org.deeplearning4j.models.sequencevectors.SequenceVectors.fit(SequenceVectors.java:188)
        at org.deeplearning4j.models.paragraphvectors.ParagraphVectors.fit(ParagraphVectors.java:450)
        at de.unisaarland.st.webtest.nlp.ParapgraphVectorBuilder$.makeParagraphVectors(ParapgraphVectorBuilder.scala:65)
        at de.unisaarland.st.webtest.nlp.ParapgraphVectorBuilder$.delayedEndpoint$de$unisaarland$st$webtest$nlp$ParapgraphVectorBuilder$1(ParapgraphVectorBuilder.scala:28)
        at de.unisaarland.st.webtest.nlp.ParapgraphVectorBuilder$delayedInit$body.apply(ParapgraphVectorBuilder.scala:12)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at de.unisaarland.st.webtest.nlp.ParapgraphVectorBuilder$.main(ParapgraphVectorBuilder.scala:12)
        at de.unisaarland.st.webtest.nlp.ParapgraphVectorBuilder.main(ParapgraphVectorBuilder.scala)`

I am working on the latest version 0.7.2.

**Comment by agibsonccc** [comment]
Do you have any code we can use to reproduce this? Perhaps a corpus or something we can run?

**Comment by raver119** [comment]
Nothing to reproduce there. Same issue with long indexing. We can fix it easily, but we cant make blas/cublas work with longs :(

**Comment by amrast** [comment]
Yeah, thought the same. 

The corpus file is from wikipedia-sentences.  
- 116 million sentences.
- 12GB uncompressed.

I checked out the source and try to apply the mentioned fix. Takes a while though to run it ;)

**Comment by agibsonccc** [comment]
Ahh didn't see lengthLong() in there.

**Comment by raver119** [comment]
Are you 100% sure you want each sentence to have own label? It looks like in YOUR case it doesn't have too much sense. So those 116 million labels is just wasted ram after all...

**Comment by raver119** [comment]
I mean - obviously, lengthLong() issue is a known one, but for YOUR task - you probably don't need that lengthLong() anyway, you need slightly different setup for d2v probably

**Comment by amrast** [comment]
You are right of course, I don't want a label for each sentence, I want to use Paragraph2Vec to get a notion of sentence similarity.

On the other hand, I didn't think that this code would actually fit the labels:

```
val iterator = new BasicLineIterator(f.jfile)
    val tokenizerFactory = new DefaultTokenizerFactory()
    tokenizerFactory.setTokenPreProcessor(new CommonPreprocessor())

    val paragraphVectors = new ParagraphVectors.Builder().learningRate(0.025)
      .minLearningRate(0.001)
      .minWordFrequency(20)
      .batchSize(1000)
      .epochs(20)
     .iterate(iterator)
.trainWordVectors(true).trainElementsRepresentation(true).trainSequencesRepresentation(true)
      .tokenizerFactory(tokenizerFactory)
      .build()

    paragraphVectors.fit()
    WordVectorSerializer.writeWord2VecModel(paragraphVectors, file.bufferedOutput())
`````

**Comment by raver119** [comment]
That code definitely fits the labels. And each sentence will have own label. That's why i'm speaking about 100m+ labels.

In your case you probably just want word2vec model built with CBOW and hierarchicSoftmax. Then you use it as .existingModel() in paravec, and just do inference. We support that option.

p.s. paravec should be saved using paravec saving routines in WordVectorSerializer.

**Comment by raver119** [comment]
I've updated random ops to be working on long arrays, but there's another problem was spotted. So i'll create new issue instead of this one
