### ISSUE TITLE
ND4J unit test failures

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1655]
When running ND4J unit tests on Windows, via "mvn clean test" in the /nd4j-backends/nd4j-backend-impls/nd4j-native and /nd4j-cuda directories, I'm still seeing the following failures:

ND4J native:
- RngTests.testRandomWithOrder:64 expected:<0.778587281703949> but was:<0.0>
- OperationProfilerTests.testBadTad4:195
- OperationProfilerTests.testBlasFF:253 » Arithmetic / by zero

ND4J CUDA:
- LoneTest.testArgMax:170
- OperationProfilerTests.testBadTad4:195
- OperationProfilerTests.testBlasFF:253 » Arithmetic / by zero

**Comment by saudet** [comment]
And CUDA seems to be crashing on Linux with AWS's GRID K520 GPU:
http://ec2-54-191-187-162.us-west-2.compute.amazonaws.com:8080/job/nd4j/lastFailedBuild/console

**Comment by agibsonccc** [comment]
Of note here is I don't see these failures in intellij (haven't ran mvn clean test yet)

**Comment by saudet** [comment]
CUDA doesn't crash anymore (Fedora 23 laptop as well as CI on AWS), but I still get some failed tests and errors for nd4j-native:
```
Failed tests: 
  OperationProfilerTests.testBadTad4:198
Tests in error: 
  OperationProfilerTests.testBlasFF:256 » Arithmetic / by zero
```
nd4j-cuda-8.0:
```
Failed tests: 
  LoneTest.testArgMax:173
  OperationProfilerTests.testBadTad4:198
Tests in error: 
  OperationProfilerTests.testBlasFF:256 » Arithmetic / by zero
```
nd4j-serde:
```
Tests in error: 
  deserializeRawJson_ArrayIsRankFive_ExpectCorrectDeserialization(org.nd4j.serde.gson.GsonDeserializationUtilsTest)
  deserializeRawJson_HaveCommaInsideNumbers_ExpectCorrectDeserialization(org.nd4j.serde.gson.GsonDeserializationUtilsTest): Could not initialize class org.nd4j.linalg.factory.Nd4j
  deserializeRawJson_ArrayHasOnlyOneRowWithColumns_ExpectCorrectDeserialization(org.nd4j.serde.gson.GsonDeserializationUtilsTest): Could not initialize class org.nd4j.linalg.factory.Nd4j
  deserializeRawJson_PassInInRank3Array_ExpectCorrectDeserialization(org.nd4j.serde.gson.GsonDeserializationUtilsTest): Could not initialize class org.nd4j.linalg.factory.Nd4j
```
And nd4j-parameter-server-node crashes the JVM in Agrona:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fb72542918a, pid=6421, tid=0x00007fb638cfb700
#
# JRE version: OpenJDK Runtime Environment (8.0_111-b16) (build 1.8.0_111-b16)
# Java VM: OpenJDK 64-Bit Server VM (25.111-b16 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# J 1284 C1 org.agrona.concurrent.UnsafeBuffer.putIntOrdered(II)V (31 bytes) @ 0x00007fb72542918a [0x00007fb7254290c0+0xca]
```

**Comment by agibsonccc** [comment]
Hmm is libnd4j being properly built and up to date? I ask because I'm not seeing the failures you are. I'm just running on my laptop though.

**Comment by AlexDBlack** [comment]
Running "mvn clean test" on latest libnd4j and nd4j (in backend directories) as per the original issue: I'm still seeing the same test failures.

**Comment by agibsonccc** [comment]
I wonder if this is os specific? I can't reproduce those failures.

**Comment by AlexDBlack** [comment]
I'm on Windows, and @saudet is reporting the same tests on Fedora, so maybe not?
Not sure what the delta is though. I'll try a fresh clone on libnd4j, on the off-chance that makes a difference.

**Comment by saudet** [comment]
Yes, Linux here. However, only this one is failing on the CI server (for example http://ec2-54-191-187-162.us-west-2.compute.amazonaws.com:8080/job/nd4j/281/consoleFull):
```
Failed tests: 
  LoneTest.testArgMax:173
```

**Comment by AlexDBlack** [comment]
No difference with a fresh clone/build.

**nd4j-native**
Fails in isolation:
mvn clean test -Dtest=*RngTests#testRandomWithOrder*

Passes in isolation:
mvn clean test -Dtest=*NormalizerTests#testPreProcessors*
mvn clean test -Dtest=*OperationProfilerTests#testBadTad4*

**Comment by AlexDBlack** [comment]
I'm seeing all backend tests ("mvn clean test") passing now. Will keep this issue open until the other issues (serde, parameter server) have been confirmed as fixed.

**Comment by agibsonccc** [comment]
I can't reproduce the gson errors. Might need help there. Tried with intellij *and* command line.

**Comment by saudet** [comment]
@agibsonccc Gson only fails if I build all of nd4j. Everything is OK when building only nd4j-serde, so it seems like something that gets built before (on some machines) is conflicting with tests for Gson for some reason.

**Comment by huitseeker** [comment]
As of 601bf2e816150650498bbeae175001ddaf5f8c86, I have the following failing:
```
deserializeRawJson_ArrayIsRankFive_ExpectCorrectDeserialization(org.nd4j.serde.gson.GsonDeserializationUtilsTest)  Time elapsed: 0.074 sec  <<< ERROR!
deserializeRawJson_HaveCommaInsideNumbers_ExpectCorrectDeserialization(org.nd4j.serde.gson.GsonDeserializationUtilsTest)  Time elapsed: 0 sec  <<< ERROR!
deserializeRawJson_ArrayHasOnlyOneRowWithColumns_ExpectCorrectDeserialization(org.nd4j.serde.gson.GsonDeserializationUtilsTest)  Time elapsed: 0 sec  <<< ERROR!
deserializeRawJson_PassInInRank3Array_ExpectCorrectDeserialization(org.nd4j.serde.gson.GsonDeserializationUtilsTest)  Time elapsed: 0.001 sec  <<< ERROR!
testPerformanceUnicast1(org.nd4j.parameterserver.distributed.VoidParameterServerStressTest)  Time elapsed: 630.519 sec  <<< ERROR!
testPerformanceUnicast3(org.nd4j.parameterserver.distributed.VoidParameterServerStressTest)  Time elapsed: 630.132 sec  <<< ERROR!
testPerformanceUnicast4(org.nd4j.parameterserver.distributed.VoidParameterServerStressTest)  Time elapsed: 630.132 sec  <<< ERROR!
getBatchedDotAggregation1(org.nd4j.parameterserver.distributed.messages.aggregations.VoidAggregationTest)  Time elapsed: 0 sec  <<< ERROR!
getScalarDotAggregation1(org.nd4j.parameterserver.distributed.messages.aggregations.VoidAggregationTest)  Time elapsed: 0 sec  <<< ERROR!
getAccumulatedResult1(org.nd4j.parameterserver.distributed.messages.aggregations.VoidAggregationTest)  Time elapsed: 0 sec  <<< ERROR!
testPin1(org.nd4j.parameterserver.distributed.logic.ClipboardTest)  Time elapsed: 0 sec  <<< ERROR!
testPin2(org.nd4j.parameterserver.distributed.logic.ClipboardTest)  Time elapsed: 0 sec  <<< ERROR!
testPin3(org.nd4j.parameterserver.distributed.logic.ClipboardTest)  Time elapsed: 0 sec  <<< ERROR!
org.nd4j.parameterserver.node.ParameterServerNodeTest  Time elapsed: 0.957 sec  <<< ERROR!
```

(run with `-Dmaven.test.failure.ignore`, `-Dmaven.test.error.ignore` so possibly cascading)

Full log : https://gist.github.com/bbeafca0699d2ad2472c860832f87e36

**Comment by agibsonccc** [comment]
The parameter server tests run fine for me.

**Comment by agibsonccc** [comment]
so the parameter server tests pass for me, could you try rerunning those? Raver fixed a shut down related bug which I'm guessing could be causing this? These pass in isolation.

**Comment by raver119** [comment]
I'm still not sure why clipboard etc tests are failing for @huitseeker , these were fixed 2 days ago by @agibsonccc and yesterday by me. Are you sure you've pulled latest nd4j & rebuilt it?

**Comment by huitseeker** [comment]
Was at libnd4j 1e50fefd496a6eb8df4338c411027887ce5a4645. I'll be launching another test run.

**Comment by saudet** [comment]
gson and parameter-server-node are currently failing on the CI server:
http://ec2-54-191-187-162.us-west-2.compute.amazonaws.com:8080/job/nd4j/286/testReport/
So, I guess they are just flaky...

**Comment by agibsonccc** [comment]
Pretty sure we are set here?

**Comment by huitseeker** [comment]
In isolation
```
huitseeker@FGbuild:/mnt/Dl4j$ for i in libnd4j nd4j; do pushd $i; echo $i; git rev-parse HEAD; popd; done
/mnt/Dl4j/libnd4j /mnt/Dl4j
libnd4j
1e50fefd496a6eb8df4338c411027887ce5a4645
/mnt/Dl4j
/mnt/Dl4j/nd4j /mnt/Dl4j
nd4j
758fa990d1ba76fa2f68726253444eb7a774a41e
/mnt/Dl4j
```

```
deserializeRawJson_ArrayIsRankFive_ExpectCorrectDeserialization(org.nd4j.serde.gson.GsonDeserializationUtilsTest)  Time elapsed: 0.072 sec  <<< ERROR!
deserializeRawJson_HaveCommaInsideNumbers_ExpectCorrectDeserialization(org.nd4j.serde.gson.GsonDeserializationUtilsTest)  Time elapsed: 0 sec  <<< ERROR!
deserializeRawJson_ArrayHasOnlyOneRowWithColumns_ExpectCorrectDeserialization(org.nd4j.serde.gson.GsonDeserializationUtilsTest)  Time elapsed: 0 sec  <<< ERROR!
deserializeRawJson_PassInInRank3Array_ExpectCorrectDeserialization(org.nd4j.serde.gson.GsonDeserializationUtilsTest)  Time elapsed: 0.001 sec  <<< ERROR!
testPerformanceUnicast1(org.nd4j.parameterserver.distributed.VoidParameterServerStressTest)  Time elapsed: 630.392 sec  <<< ERROR!
testPerformanceUnicast3(org.nd4j.parameterserver.distributed.VoidParameterServerStressTest)  Time elapsed: 630.119 sec  <<< ERROR!
testPerformanceUnicast4(org.nd4j.parameterserver.distributed.VoidParameterServerStressTest)  Time elapsed: 630.128 sec  <<< ERROR!
getBatchedDotAggregation1(org.nd4j.parameterserver.distributed.messages.aggregations.VoidAggregationTest)  Time elapsed: 0 sec  <<< ERROR!
getScalarDotAggregation1(org.nd4j.parameterserver.distributed.messages.aggregations.VoidAggregationTest)  Time elapsed: 0 sec  <<< ERROR!
getAccumulatedResult1(org.nd4j.parameterserver.distributed.messages.aggregations.VoidAggregationTest)  Time elapsed: 0 sec  <<< ERROR!
testPin1(org.nd4j.parameterserver.distributed.logic.ClipboardTest)  Time elapsed: 0 sec  <<< ERROR!
testPin2(org.nd4j.parameterserver.distributed.logic.ClipboardTest)  Time elapsed: 0 sec  <<< ERROR!
testPin3(org.nd4j.parameterserver.distributed.logic.ClipboardTest)  Time elapsed: 0 sec  <<< ERROR!
org.nd4j.parameterserver.node.ParameterServerNodeTest  Time elapsed: 0.807 sec  <<< ERROR!
deserializeRawJson_ArrayIsRankFive_ExpectCorrectDeserialization(org.nd4j.serde.gson.GsonDeserializationUtilsTest)  Time elapsed: 0.077 sec  <<< ERROR!
deserializeRawJson_HaveCommaInsideNumbers_ExpectCorrectDeserialization(org.nd4j.serde.gson.GsonDeserializationUtilsTest)  Time elapsed: 0 sec  <<< ERROR!
deserializeRawJson_ArrayHasOnlyOneRowWithColumns_ExpectCorrectDeserialization(org.nd4j.serde.gson.GsonDeserializationUtilsTest)  Time elapsed: 0.001 sec  <<< ERROR!
deserializeRawJson_PassInInRank3Array_ExpectCorrectDeserialization(org.nd4j.serde.gson.GsonDeserializationUtilsTest)  Time elapsed: 0 sec  <<< ERROR!
testPerformanceUnicast1(org.nd4j.parameterserver.distributed.VoidParameterServerStressTest)  Time elapsed: 630.382 sec  <<< ERROR!
testPerformanceUnicast3(org.nd4j.parameterserver.distributed.VoidParameterServerStressTest)  Time elapsed: 630.118 sec  <<< ERROR!
testPerformanceUnicast4(org.nd4j.parameterserver.distributed.VoidParameterServerStressTest)  Time elapsed: 630.11 sec  <<< ERROR!
getBatchedDotAggregation1(org.nd4j.parameterserver.distributed.messages.aggregations.VoidAggregationTest)  Time elapsed: 0 sec  <<< ERROR!
getScalarDotAggregation1(org.nd4j.parameterserver.distributed.messages.aggregations.VoidAggregationTest)  Time elapsed: 0 sec  <<< ERROR!
getAccumulatedResult1(org.nd4j.parameterserver.distributed.messages.aggregations.VoidAggregationTest)  Time elapsed: 0 sec  <<< ERROR!
testPin1(org.nd4j.parameterserver.distributed.logic.ClipboardTest)  Time elapsed: 0 sec  <<< ERROR!
testPin2(org.nd4j.parameterserver.distributed.logic.ClipboardTest)  Time elapsed: 0 sec  <<< ERROR!
testPin3(org.nd4j.parameterserver.distributed.logic.ClipboardTest)  Time elapsed: 0 sec  <<< ERROR!
org.nd4j.parameterserver.node.ParameterServerNodeTest  Time elapsed: 1.19 sec  <<< ERROR!
```

Full output https://gist.github.com/4a645a5deafedf4b09f691b37d899ce3

**Comment by raver119** [comment]
Amazing...

**Comment by raver119** [comment]
Can i have remote access to the box you're using?

**Comment by huitseeker** [comment]
@raver119 
build command is :
```
~/build-dl4j-stack.sh -c cuda -d --testnd4j --testdl4j --mvnopts "-Dmaven.test.error.ignore=true -Dmaven.test.failure.ignore=true"|tee ~/deeplearning4j.log
```

the script is of course that of https://github.com/deeplearning4j/deeplearning4j/pull/2932

**Comment by raver119** [comment]
Here's stack trace, after which jvm can't init Nd4j anymore:

https://gist.github.com/raver119/a9d6d33df31c97a629e7306f10b55e14

Steps to reproduce: just "mvn clean install" in root folder. It'll launch tests in the following order:
nd4j-tests -> nd4j->aeron -> BOOM -> nd4j-gson failed -> nd4j-param-server failed

**Comment by huitseeker** [comment]
Now at :

```
huitseeker@FGbuild:/mnt/DeepLearning4J$ for i in libnd4j nd4j; do pushd $i >/dev/null; echo  $(pwd; git rev-parse HEAD); popd >/dev/null; done
/mnt/DeepLearning4J/libnd4j 1e50fefd496a6eb8df4338c411027887ce5a4645
/mnt/DeepLearning4J/nd4j ec0340166f29f62c2899b3b1e4ace9cc9a8a01ba
```

I have :

```
testSerialization[0: backend(org.nd4j.linalg.cpu.nativecpu.CpuBackend)={1}](org.nd4j.linalg.Nd4jTestsC)  Time elapsed: 0.098 sec  <<< ERROR!
java.nio.file.AccessDeniedException: /tmp/dl4jtestserialization.bin
	at org.nd4j.linalg.Nd4jTestsC.testSerialization(Nd4jTestsC.java:115)
--
deserializeRawJson_ArrayIsRankFive_ExpectCorrectDeserialization(org.nd4j.serde.gson.GsonDeserializationUtilsTest)  Time elapsed: 0.082 sec  <<< ERROR!
java.lang.ExceptionInInitializerError: null
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
--
deserializeRawJson_HaveCommaInsideNumbers_ExpectCorrectDeserialization(org.nd4j.serde.gson.GsonDeserializationUtilsTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.nd4j.linalg.factory.Nd4j
	at org.nd4j.serde.gson.GsonDeserializationUtilsTest.deserializeRawJson_HaveCommaInsideNumbers_ExpectCorrectDeserialization(GsonDeserializationUtilsTest.java:55)
--
deserializeRawJson_ArrayHasOnlyOneRowWithColumns_ExpectCorrectDeserialization(org.nd4j.serde.gson.GsonDeserializationUtilsTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.nd4j.linalg.factory.Nd4j
	at org.nd4j.serde.gson.GsonDeserializationUtilsTest.deserializeRawJson_ArrayHasOnlyOneRowWithColumns_ExpectCorrectDeserialization(GsonDeserializationUtilsTest.java:23)
--
deserializeRawJson_PassInInRank3Array_ExpectCorrectDeserialization(org.nd4j.serde.gson.GsonDeserializationUtilsTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.nd4j.linalg.factory.Nd4j
	at org.nd4j.serde.gson.GsonDeserializationUtilsTest.buildExpectedArray(GsonDeserializationUtilsTest.java:63)
```

Full test output: https://gist.github.com/dd51e1e95bf8e9345d035d209e3c105f

**Comment by agibsonccc** [comment]
At this point, I am willing to do a release despite seeing this. Raver and I have never been able to reproduce bugs you are seeing and frankly I have to wonder if the test environment is suspect.

**Comment by huitseeker** [comment]
Not that I'd make a different call, but @raver119 has stated here that the issue is 100% reproducible : 
https://gitter.im/deeplearning4j/dev_channel?at=58b84a25e961e53c7f8d5f72

This test was run with the build script, downloading a fresh repo.

**Comment by huitseeker** [comment]
## Update at master = 5eb47c2e6398d32fd5884ece3e35dab92d111757

```
35 matches for "\(FAILURE\|ERROR\)" in buffer: nd4j.log
    892:[ERROR] Error fetching link: /mnt/Dl4j/nd4j/nd4j-shade/jackson/target/apidocs/package-list. Ignored it.
   2915:[ERROR] Error fetching link: /mnt/Dl4j/nd4j/nd4j-shade/jackson/target/apidocs/package-list. Ignored it.
   6151:Tests run: 6, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 0.173 sec <<< FAILURE! - in org.nd4j.linalg.shape.indexing.IndexingTests
   6152:testGet[0: backend(org.nd4j.linalg.cpu.nativecpu.CpuBackend)={1}](org.nd4j.linalg.shape.indexing.IndexingTests)  Time elapsed: 0.04 sec  <<< FAILURE!
  27337:[ERROR] There are test failures.
  30476:13:54:01,271 ERROR ~ io.aeron.exceptions.DriverTimeoutException: Driver has been inactive for over 10000ms
  30981:Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.224 sec <<< FAILURE! - in org.nd4j.serde.gson.GsonDeserializationUtilsTest
  30982:deserializeRawJson_ArrayIsRankFive_ExpectCorrectDeserialization(org.nd4j.serde.gson.GsonDeserializationUtilsTest)  Time elapsed: 0.098 sec  <<< ERROR!
  31012:deserializeRawJson_HaveCommaInsideNumbers_ExpectCorrectDeserialization(org.nd4j.serde.gson.GsonDeserializationUtilsTest)  Time elapsed: 0.001 sec  <<< ERROR!
  31016:deserializeRawJson_ArrayHasOnlyOneRowWithColumns_ExpectCorrectDeserialization(org.nd4j.serde.gson.GsonDeserializationUtilsTest)  Time elapsed: 0 sec  <<< ERROR!
  31020:deserializeRawJson_PassInInRank3Array_ExpectCorrectDeserialization(org.nd4j.serde.gson.GsonDeserializationUtilsTest)  Time elapsed: 0.001 sec  <<< ERROR!
  31036:[ERROR] There are test failures.
  31120:Tests run: 3, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 1.18 sec <<< FAILURE! - in org.nd4j.reflectionloader.JacksonReflectionLoaderTest
  31121:testLoad(org.nd4j.reflectionloader.JacksonReflectionLoaderTest)  Time elapsed: 0.314 sec  <<< ERROR!
  31126:testInstantiate(org.nd4j.reflectionloader.JacksonReflectionLoaderTest)  Time elapsed: 0.369 sec  <<< ERROR!
  31142:[ERROR] There are test failures.
  31164:[ERROR] Error fetching link: /mnt/Dl4j/nd4j/nd4j-shade/jackson/target/apidocs/package-list. Ignored it.
  36034:Tests run: 6, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 0.192 sec <<< FAILURE! - in org.nd4j.linalg.shape.indexing.IndexingTests
  36035:testGet[0: backend(org.nd4j.linalg.jcublas.JCublasBackend)={1}](org.nd4j.linalg.shape.indexing.IndexingTests)  Time elapsed: 0.042 sec  <<< FAILURE!
  57269:[ERROR] There are test failures.
  58679:Tests run: 7, Failures: 0, Errors: 3, Skipped: 4, Time elapsed: 1,891.075 sec <<< FAILURE! - in org.nd4j.parameterserver.distributed.VoidParameterServerStressTest
  58680:testPerformanceUnicast1(org.nd4j.parameterserver.distributed.VoidParameterServerStressTest)  Time elapsed: 630.516 sec  <<< ERROR!
  58707:testPerformanceUnicast3(org.nd4j.parameterserver.distributed.VoidParameterServerStressTest)  Time elapsed: 630.121 sec  <<< ERROR!
  58734:testPerformanceUnicast4(org.nd4j.parameterserver.distributed.VoidParameterServerStressTest)  Time elapsed: 630.112 sec  <<< ERROR!
  58766:Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0 sec <<< FAILURE! - in org.nd4j.parameterserver.distributed.messages.aggregations.VoidAggregationTest
  58767:getBatchedDotAggregation1(org.nd4j.parameterserver.distributed.messages.aggregations.VoidAggregationTest)  Time elapsed: 0 sec  <<< ERROR!
  58771:getScalarDotAggregation1(org.nd4j.parameterserver.distributed.messages.aggregations.VoidAggregationTest)  Time elapsed: 0 sec  <<< ERROR!
  58775:getAccumulatedResult1(org.nd4j.parameterserver.distributed.messages.aggregations.VoidAggregationTest)  Time elapsed: 0 sec  <<< ERROR!
  58784:Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0 sec <<< FAILURE! - in org.nd4j.parameterserver.distributed.logic.ClipboardTest
  58785:testPin1(org.nd4j.parameterserver.distributed.logic.ClipboardTest)  Time elapsed: 0 sec  <<< ERROR!
  58789:testPin2(org.nd4j.parameterserver.distributed.logic.ClipboardTest)  Time elapsed: 0 sec  <<< ERROR!
  58793:testPin3(org.nd4j.parameterserver.distributed.logic.ClipboardTest)  Time elapsed: 0 sec  <<< ERROR!
  58802:Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.804 sec <<< FAILURE! - in org.nd4j.parameterserver.node.ParameterServerNodeTest
  58803:org.nd4j.parameterserver.node.ParameterServerNodeTest  Time elapsed: 0.804 sec  <<< ERROR!
  58827:[ERROR] There are test failures.
```

## Analysis

A few things are not new: the parameter server test is still causing classpath issues referenced in #1645 — that can be see in the long runtimes (& timeouts) of `VoidParameterServerStressTest` and the subsequent 0s runtimes of `VoidAggregationTest` & `ClipboardTest`. 

What's interesting is the failure in `IndexingTests`:
```

Failed tests: 
  IndexingTests.testGet:80 expected:<[[32.00, 57.00, 82.00],
 [37.00, 62.00, 87.00],
 [42.00, 67.00, 92.00]]> but was:<[[17.00, 42.00, 67.00],
 [22.00, 47.00, 72.00],
 [27.00, 52.00, 77.00]]>

Tests run: 983, Failures: 1, Errors: 0, Skipped: 24
```
The Gson tests are having classloader issues, I'll chalk that up to parameter server messing with the class loader:

```
Tests in error: 
  GsonDeserializationUtilsTest.deserializeRawJson_ArrayIsRankFive_ExpectCorrectDeserialization:44->buildExpectedArray:63 » ExceptionInInitializer
  GsonDeserializationUtilsTest.deserializeRawJson_HaveCommaInsideNumbers_ExpectCorrectDeserialization:55 NoClassDefFound
  GsonDeserializationUtilsTest.deserializeRawJson_ArrayHasOnlyOneRowWithColumns_ExpectCorrectDeserialization:23 NoClassDefFound
  GsonDeserializationUtilsTest.deserializeRawJson_PassInInRank3Array_ExpectCorrectDeserialization:13->buildExpectedArray:63 NoClassDefFound
```

The parameter server tests with a long runtime end in :
```
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Giving up on message delivery...
```

## Reproducing

Download the base image (containing a dev env with Cuda & al, but nothing related to nd4j/dl4j):
```
 docker run -it --rm huitseeker/dl4j-centos7-dev-env /bin/bash
```

Then in the image:

```
cd /root # == $HOME
git clone https://github.com/deeplearning4j/libnd4j
git clone https://github.com/deeplearning4j/nd4j
cd libnd4j
./buildnativeoperations.sh
./buildnativeoperations.sh -c cuda -cc 61
cd ../nd4j
export LIBND4J_HOME=/root/libnd4j
mvn package -Dmaven.test.error.ignore=true -Dmaven.test.failure.ignore=true | tee ~/nd4j.log
```

Then after execution `docker cp mycontainer:/root/nd4j.log nd4j.log`, where mycontainer is the name of your container as spotted in `docker ps`.


Full log:
https://gist.github.com/5e947a8eb2ce6ae1458eddd055dc3c0d
