### ISSUE TITLE
Large matrix allocation failing.

### ISSUE THREAD

**Issue by turingsmart** [deeplearning4j/nd4j#166]
Using Nd4J  with cuda 7 and latest jcublas maven version.
I am getting this exception...
```
java.lang.IllegalArgumentException: initialCapacity: -294967296 (expectd: 0+)
	at io.netty.buffer.AbstractByteBufAllocator.validate(AbstractByteBufAllocator.java:196)
	at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:135)
	at io.netty.buffer.Unpooled.buffer(Unpooled.java:141)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:147)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<init>(BaseCudaDataBuffer.java:107)
	at org.nd4j.linalg.jcublas.buffer.CudaFloatDataBuffer.<init>(CudaFloatDataBuffer.java:48)
	at org.nd4j.linalg.jcublas.buffer.factory.CudaDataBufferFactory.createFloat(CudaDataBufferFactory.java:41)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:566)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:183)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:200)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:374)
	at org.nd4j.linalg.jcublas.JCublasNDArray.<init>(JCublasNDArray.java:231)
	at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.create(JCublasNDArrayFactory.java:176)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:193)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3109)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:2500)
```

Code :
VectorA dimensions : 1000 X 200
VectorB dimensions : 200  X 1000000
```java
public static synchronized long multiplyArrays(INDArray vectorA, INDArray vectorB) {
        INDArray mul = Nd4j.create(vectorA.rows(), vectorB.columns());
    }
```

**Comment by agibsonccc** [comment]
This translates to: When are you guys going to support IPC?

**Comment by turingsmart** [comment]
We have to load a matrix of 200 * 6 million in GPU.
First try : Create three matrices of 200 * 2 million each, sequentially, on a single thread. This succeeds.
Second try : Create two matrices of 200 * 3 million each, sequentially, on a single thread. This fails with the following exception, on trying to create the first matrix.
```
java.lang.IllegalArgumentException: initialCapacity: -1884136096 (expectd: 0+)
	at io.netty.buffer.AbstractByteBufAllocator.validate(AbstractByteBufAllocator.java:196)
	at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:135)
	at io.netty.buffer.Unpooled.buffer(Unpooled.java:141)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:147)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<init>(BaseCudaDataBuffer.java:107)
	at org.nd4j.linalg.jcublas.buffer.CudaFloatDataBuffer.<init>(CudaFloatDataBuffer.java:48)
	at org.nd4j.linalg.jcublas.buffer.factory.CudaDataBufferFactory.createFloat(CudaDataBufferFactory.java:41)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:566)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:217)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:385)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:433)
	at org.nd4j.linalg.jcublas.JCublasNDArray.<init>(JCublasNDArray.java:299)
	at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.create(JCublasNDArrayFactory.java:375)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3221)
```

**Comment by jknair** [comment]
@agibsonccc hey we have pinpointed the issue the Nd4j.create eventually calls ```DataBufferFactory.createFloat``` which uses ``int`` length that would restrict it to ```2.14 gb`` of matrix size and thats why we were getting an initialCapacity less than 0 exception.

**Comment by agibsonccc** [comment]
If you look netty underneath, you're going to find it only supports int. We have a few paths to extend it to long and the like though.

**Comment by jknair** [comment]
netty has something called CompositeByteBuf that can be used to make multiple buffers as a single merged buffer

**Comment by agibsonccc** [comment]
You're welcome to send a PR. There's a lot more logistics involved with the calculations though. Most blas implementations only take in int as a parameter. There's going to be more gymnastics than changing this to long.

**Comment by jknair** [comment]
sure let me see what I can come up with :)

**Comment by agibsonccc** [comment]
Possible solution here:
File file = ...;
FileChannel channel = new RandomAccessFile(file, "r").getChannel();

ByteBuffer buf = channel.map(MapMode.READ_ONLY, 0L, file.length());
buf.order(ByteOrder.LITTLE_ENDIAN);

We can wrap this with netty. It would only work for certain backends but it's worth a shot.

**Comment by agibsonccc** [comment]
This is handled with javacpp now. (long pointers and indexing)
