### ISSUE TITLE
`repeat` make me confused

### ISSUE THREAD

**Issue by izhangzhihao** [deeplearning4j/nd4j#1668]
Hi, there are two `repeat` in `BaseNDArray`,and when I call `test.repeat(1, 4)`,I mean repeat the second demention 4 times,and comes an error,

```
Error:(705, 21) ambiguous reference to overloaded definition,
both method repeat in trait INDArray of type (x$1: <repeated...>[Int])org.nd4j.linalg.api.ndarray.INDArray
and  method repeat in trait INDArray of type (x$1: Int, x$2: <repeated...>[Int])org.nd4j.linalg.api.ndarray.INDArray
match argument types (Int,Int)
                   .repeat(-1, Seq(upstreamShape(dimensions(1))): _*)
```

when I check the source code ,I see:
```java
    @Override
    public INDArray repeat(int dimension, int... repeats) {
        if (dimension < 0)
            dimension += rank();

        if (repeats.length < rank()) {
            if (dimension > 0)
                repeats = Ints.concat(ArrayUtil.nTimes(rank() - repeats.length, 1), repeats);
                //append rather than prepend for dimension == 0
            else
                repeats = Ints.concat(repeats, ArrayUtil.nTimes(rank() - repeats.length, 1));

        }

        int[] newShape = new int[rank()];

        for (int i = 0; i < newShape.length; i++)
            newShape[i] = size(i) * repeats[i];

        INDArray ret = create(newShape);

        //number of times to repeat each value
        int repeatDelta = ArrayUtil.prod(newShape) / length();
        for(int i = 0; i < tensorssAlongDimension(dimension); i++) {
            INDArray thisTensor = tensorAlongDimension(i,dimension);
            INDArray retTensor = ret.tensorAlongDimension(i,dimension);
            int retIdx = 0;
            for(int k = 0; k < thisTensor.length(); k++) {
                for(int j = 0; j < repeatDelta; j++) {
                    retTensor.putScalar(retIdx++,thisTensor.getDouble(k));
                }
            }
        }

        return ret;
    }

    @Override
    public INDArray repeat(int... repeats) {
        if(repeats.length == 1) {
            INDArray ret = create(1,length() * repeats[0]);
            int idx = 0;
            for(int i = 0; i < length(); i++) {
                for(int j = 0; j < repeats[0]; j++) {
                    ret.putScalar(idx++,getDouble(i));
                }
            }
            return ret;
        }

        throw new IllegalStateException("Illegal length");
    }
```

in the second `repeat` will throw an error when `repeats.length!=1`,so why use variable parameter？

**Comment by izhangzhihao** [comment]
And how can I convert 

```
[[1.00, 2.00, 3.00],
 [4.00, 5.00, 6.00],
 [7.00, 8.00, 9.00]]
```
to
```
      [1, 1, 2, 2, 3, 3],
       [1, 1, 2, 2, 3, 3],
       [4 4, 5, 5, 6, 6],
       [4 4, 5, 5, 6, 6],
       [7, 7, 8, 8, 9, 9],
       [7, 7, 8, 8, 9, 9]]
```

**Comment by izhangzhihao** [comment]
I'm try another one,but got a exception
```scala
val test = (1 to (2 * 2 * 4 * 8)).toNDArray.reshape(2, 2, 4, 8)
  println(
    test
      .repeat(2, Seq(2): _*)// I want to repeat the 3st dimentions 2 times
      .permute(0, 1, 3, 2)
      .repeat(3, Seq(2): _*)// I want to repeat the 4st dimentions 2 times
      .permute(0, 1, 3, 2)
  )
```

```
Exception in thread "main" java.lang.IllegalArgumentException: Invalid indices: cannot get [0,2] from a [1, 2] NDArray
	at org.nd4j.linalg.api.shape.Shape.getOffsetUnsafe(Shape.java:368)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.putScalar(BaseNDArray.java:1187)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.putScalar(BaseNDArray.java:1141)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.repeat(BaseNDArray.java:3376)
	at com.test.deeplearning.tutorial.test$.delayedEndpoint$com$test$deeplearning$tutorial$test$1(test.scala:18)
	at com.test.deeplearning.tutorial.test$delayedInit$body.apply(test.scala:8)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
```

**Comment by agibsonccc** [comment]
Thanks! We will look in to this.

**Comment by agibsonccc** [comment]
I got rid of the duplicate repeat overload here. https://github.com/deeplearning4j/nd4j/pull/1670
