### ISSUE TITLE
serialization to bytes fails

### ISSUE THREAD

**Issue by migel** [deeplearning4j/nd4j#167]
```scala
  var m = Nd4j.rand(3,3)                          //> m  : org.nd4j.linalg.api.ndarray.INDArray = [[0.7617881298065186, 1.11140048
                                                  //| 50387573, -0.22977286577224731]
                                                  //|  [-1.5332295894622803, 1.6605161428451538, 2.099828004837036]
                                                  //|   ,[0.06744436174631119, 0.46019449830055237, 0.3325360417366028]]
                                                  //| 
  m.data().asBytes()                              //> java.lang.NullPointerException
                                                  //| 	at org.nd4j.linalg.api.buffer.BaseDataBuffer.asBytes(BaseDataBuffer.java
                                                  //| :428)
                                                  //| 	at bytes$$anonfun$main$1.apply$mcV$sp(bytes.scala:6)
                                                  //| 	at org.scalaide.worksheet.runtime.library.WorksheetSupport$$anonfun$$exe
                                                  //| cute$1.apply$mcV$sp(WorksheetSupport.scala:76)
                                                  //| 	at org.scalaide.worksheet.runtime.library.WorksheetSupport$.redirected(W
                                                  //| orksheetSupport.scala:65)
                                                  //| 	at org.scalaide.worksheet.runtime.library.WorksheetSupport$.$execute(Wor
                                                  //| ksheetSupport.scala:75)
                                                  //| 	at bytes$.main(bytes.scala:3)
                                                  //| 	at bytes.main(bytes.scala)
```

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/pull/172
