### ISSUE TITLE
Selecting device in multi-gpu system

### ISSUE THREAD

**Issue by chamilka** [deeplearning4j/nd4j#1682]
I am using the example code : dl4j-examples/dl4j-cuda-specific-examples/src/main/java/org/deeplearning4j/examples/multigpu/MultiGpuLenetMnistExample.java

It is working fine in multi-gpu system and all gpus (I have 3) show the usage. 

But what I want is to run this in single gpu without interacting each other. So I change the code to specify gpu id at run time. 

` CudaEnvironment.getInstance().getConfiguration()
         .allowMultiGPU(false)
         .setMaximumDeviceCache(2L * 1024L * 1024L * 1024L)
         .allowCrossDeviceAccess(false)
         .useDevice(Integer.parseInt(args[0]));
`         
[MultiGpuLenetMnistExample_SingleGpu.txt](https://github.com/deeplearning4j/nd4j/files/819051/MultiGpuLenetMnistExample_SingleGpu.txt)

Now when I run the java program 1st time it works fine showing usage of a single Gpu. But when I re run it while my 1st Gpu is in use, I get the error **Can't create new cuBLAS handle!**

`Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<clinit>(BaseCudaDataBuffer.java:72)
        at org.nd4j.linalg.jcublas.buffer.factory.CudaDataBufferFactory.createHalf(CudaDataBufferFactory.java:396)
        at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1311)
        at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1282)
        at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:965)
        at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3254)
        at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3119)
        at MultiGpuLenetMnistExample.main(MultiGpuLenetMnistExample.java:43)
Caused by: java.lang.IllegalStateException: Can't create new cuBLAS handle! cuBLAS errorCode: [1]
        at org.nd4j.jita.allocator.context.impl.BasicContextPool.createNewCublasHandle(BasicContextPool.java:189)
        at org.nd4j.jita.allocator.context.impl.LimitedContextPool.fillPoolWithResources(LimitedContextPool.java:84)
        at org.nd4j.jita.allocator.context.impl.LimitedContextPool.<init>(LimitedContextPool.java:50)
        at org.nd4j.jita.handler.impl.CudaZeroHandler.<init>(CudaZeroHandler.java:127)
        at org.nd4j.jita.allocator.impl.AtomicAllocator.<init>(AtomicAllocator.java:120)
        at org.nd4j.jita.allocator.impl.AtomicAllocator.<clinit>(AtomicAllocator.java:70)
        ... 8 more
`

Gpu usage when I run 1st time is like this (original example shows utilization in all 3, but now only Gpu-0 exactly as I want it). It seems though I specify .useDevice(0) it create 3 processes and use only 1.

![gpu_0_usage](https://cloud.githubusercontent.com/assets/12293116/23583935/961003c2-0195-11e7-9fbf-90f8f87ded2a.PNG)

Is there any possible way to run this same program simultaneously in different Gpus?

**Comment by raver119** [comment]
Fix was applied to current master.

Besides of that, you always have an option doing the same from within your app, by just mapping any given thread to specific device, by using Nd4j.getAffinityManager() helper.

Or you can do the same by using CUDA env variables.

**Comment by chamilka** [comment]
Thank you for the fix. 
if I use Nd4j.getAffinityManager() will you be able to guide me to find a sample of this?. 
Is it Nd4j.getAffinityManager().attachThreadToDevice(threadId,deviceId). I tried this but still get the same problem.
Also is it possible for me to change CUDA env variables through Nd4j?

**Comment by raver119** [comment]
Please define "get the same problem". If there would be problem with attachThreadToDevice - you'd be unable to use multi-gpu setup at all.

**Comment by raver119** [comment]
and better do that in new issue.
