### ISSUE TITLE
Ubuntu: java.lang.UnsatisfiedLinkError: no jnind4jcpu in java.library.path

### ISSUE THREAD

**Issue by loretoparisi** [deeplearning4j/nd4j#1687]
I get this error on `Ubuntu 16.04` / Oracle JDF 1.8 `jdk-8u111-linux-x64`
As suggested in https://github.com/deeplearning4j/nd4j/issues/1118
I have modified the pom to use `nd4j-native-platform` instead of `nd4j-native`, so my pom file is

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.pippo</groupId>
    <artifactId>pippo</artifactId>
    <version>1.0-SNAPSHOT</version>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <properties>
        <nd4j.version>0.7.2</nd4j.version>
        <dl4j.version>0.7.2</dl4j.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-ui_2.10</artifactId>
            <version>${dl4j.version}</version>
        </dependency> 
		
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-native-platform</artifactId>
            <version>${nd4j.version}</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/com.opencsv/opencsv -->
        <dependency>
            <groupId>com.opencsv</groupId>
            <artifactId>opencsv</artifactId>
            <version>3.7</version>
        </dependency>
    </dependencies>


</project>
```

Stacktrace:

```
Error: Error creating class
java.lang.ExceptionInInitializerError
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:41)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5646)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5554)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:189)
	at org.deeplearning4j.models.embeddings.inmemory.InMemoryLookupTable$Builder.<init>(InMemoryLookupTable.java:580)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors$Builder.presetTables(SequenceVectors.java:801)
	at org.deeplearning4j.models.word2vec.Word2Vec$Builder.build(Word2Vec.java:476)
	at embedding.word2vec.WordLyrics2Vec.<init>(WordLyrics2Vec.java:49)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:40)
	at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:16)
	... 17 more
Caused by: java.lang.UnsatisfiedLinkError: no jnind4jcpu in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:945)
	at org.bytedeco.javacpp.Loader.load(Loader.java:750)
	at org.bytedeco.javacpp.Loader.load(Loader.java:657)
	at org.nd4j.nativeblas.Nd4jCpu.<clinit>(Nd4jCpu.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:712)
	at org.bytedeco.javacpp.Loader.load(Loader.java:657)
	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.<clinit>(Nd4jCpu.java:54)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:23)
	... 18 more
Caused by: java.lang.UnsatisfiedLinkError: no nd4jcpu in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:945)
	at org.bytedeco.javacpp.Loader.load(Loader.java:738)
	... 28 more

    at Error (native)
    at new Embedding (/musixmatch/node_modules/@mxmdev/musixmatch-intelligence-node-sdk/lib/embedding/index.js:86:35)
    at createInstanceWithArguments (/musixmatch/node_modules/@mxmdev/musixmatch-intelligence-node-sdk/lib/module/factory.js:90:26)
    at Promise (/musixmatch/node_modules/@mxmdev/musixmatch-intelligence-node-sdk/lib/module/factory.js:94:28)
    at ModuleFactory.load (/musixmatch/node_modules/@mxmdev/musixmatch-intelligence-node-sdk/lib/module/factory.js:93:16)
    at Util.promiseAll (/musixmatch/node_modules/@mxmdev/musixmatch-intelligence-node-sdk/lib/module/factory.js:124:33)
    at /musixmatch/node_modules/@mxmdev/musixmatch-intelligence-node-sdk/lib/util/util.js:83:23
    at /musixmatch/node_modules/@mxmdev/musixmatch-intelligence-node-sdk/lib/util/util.js:82:22
    at /musixmatch/node_modules/@mxmdev/musixmatch-intelligence-node-sdk/lib/util/util.js:85:14
    at Array.forEach (native)
 [Tue Mar 07 2017 10:50:09 GMT+0000 (UTC)] _initModules error:
Error: Error creating class
java.lang.ExceptionInInitializerError
```

**Comment by raver119** [comment]
What's the environment you have there? I see .js (??) files in trace?

**Comment by loretoparisi** [comment]
@raver119 Yes I'm using [node-java](https://github.com/joeferner/node-java), but this normally works with java libraries, and native libs via JNI (like C++ libraries). Has ND4J any kind of static library loading so that it could be only a path issue to be passed to the JVM?
My project is a jar with all resources within.

**Comment by raver119** [comment]
nd4j-native-platform contains platform-specific binaries, that are being loaded during Nd4j init.

**Comment by loretoparisi** [comment]
@raver119 my guess is this log `Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
`

Does it means that (1) the static `x86-64` lib was not build or (2) the library path was missing?

**Comment by raver119** [comment]
It meanse that "something went wrong", and what exactly went wrong is explained below: `Caused by: java.lang.UnsatisfiedLinkError: no nd4jcpu in java.library.path`

**Comment by loretoparisi** [comment]
@raver119 ok thanks, so what I assume it happens here is that the`jnind4jcpu` is not loaded/built during during Nd4j init. Is that correct?

**Comment by raver119** [comment]
it wasn't found. Something wrong with paths i guess.

**Comment by loretoparisi** [comment]
so where are these native libraries located on the system?
Thanks

**Comment by raver119** [comment]
No, you're not missing it. You have nd4j-native-platform as dependency, it contains binaries for all supported platforms, i've mentioned that above.

**Comment by loretoparisi** [comment]
Ok sorry, I'm now understanding better how it works.

My wonder is that why in my compiled jar I only see

```
jar tf dl4japp.jar | grep jnind4jcpu
org/nd4j/nativeblas/macosx-x86_64/libjnind4jcpu.dylib
```

**Comment by saudet** [comment]
Looks like a problem with your version of Maven. Please try again with Maven 3.3.9.

**Comment by raver119** [comment]
It should be impossible if you've used nd4j-native-platform and created proper uber jar.
That's the whole idea of nd4j-native-platform approach. It allows you to build jars on one platform, and use that jar on any other supported platform: windows, mac, linux, android etc

**Comment by loretoparisi** [comment]
@saudet it's IntelliJ embedded `maven 3.3.9`. @raver119 uhm so it's creating macosx binaries since the platform selected is macOS?

**Comment by raver119** [comment]
It's not "creating" anything. All binaries you have - were compiled by our team (by Sam) and published on maven central, within nd4j-native-platform jar.

So basically you should have ALL binaries within your jar file.

**Comment by loretoparisi** [comment]
@raver119 ok now I get it, what happens is that IntelliJ / maven is not getting the binaries. In fact I cannot see those binaries `nind4jcpu` for windows as well under `org/nd4j/nativeblas/`.

**Comment by raver119** [comment]
No. 

What happens is you hadn't provided uber jar. You've shared your pom.xml, and i don't see single line about maven shade plugin. So you're providing limited jar, that has only current dependencies.

And shame on me, i've just realized that.

**Comment by raver119** [comment]
P.s. please use maven shade plugin for uber jar generation.

**Comment by loretoparisi** [comment]
@raver119 ok thank you guys, now I have to figure out how to configure a shade plugin for the uber jar generation. We are taking as example https://github.com/treo/dl4j-0.4-examples/blob/master/datavec-examples/pom.xml#L56

**Comment by raver119** [comment]
https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/pom.xml#L140-L178

**Comment by loretoparisi** [comment]
@raver119 thanks a lot this definitively solved the problem. Now all binaries on all 3 platforms were generated!

**Comment by raver119** [comment]
Great :)
