### ISSUE TITLE
columns vector concat fails

### ISSUE THREAD

**Issue by migel** [deeplearning4j/nd4j#169]
```scala
  val input1 = Nd4j.zeros(2, 1)                   //> input1  : org.nd4j.linalg.api.ndarray.INDArray = [[0.0,
                                                  //|   0.0]]
                                                  //|  
  val input2 = Nd4j.ones(2, 1)                    //> input2  : org.nd4j.linalg.api.ndarray.INDArray = [[1.0,
                                                  //|   1.0]]
                                                  //|  
  val inputCat = Nd4j.concat(1, input1, input2)   //> java.lang.IllegalArgumentException: Index greater than possible number of ve
                                                  //| ctors along dimension 0
                                                  //| 	at org.nd4j.linalg.api.ndarray.BaseNDArray.vectorAlongDimension(BaseNDAr
                                                  //| ray.java:625)
                                                  //| 	at org.nd4j.linalg.api.ndarray.BaseNDArray.getColumn(BaseNDArray.java:36
                                                  //| 40)
                                                  //| 	at org.nd4j.linalg.api.ndarray.BaseNDArray.putColumn(BaseNDArray.java:32
                                                  //| 78)
                                                  //| 	at org.nd4j.linalg.factory.BaseNDArrayFactory.concat(BaseNDArrayFactory.
                                                  //| java:964)
                                                  //| 	at org.nd4j.linalg.factory.Nd4j.concat(Nd4j.java:2067)
                                                  //| 	at bytes$$anonfun$main$1.apply$mcV$sp(bytes.scala:14)
                                                  //| 	at org.scalaide.worksheet.runtime.library.WorksheetSupport$$anonfun$$exe
                                                  //| cute$1.apply$mcV$sp(WorksheetSupport.scala:76)
                                                  //| 	at org.scalaide.worksheet.runtime.library.WorksheetSupport$.redirected(W
                                                  //| orksheetSupport.scala:65)
                                                  //| 	at org.scalaide.worksheet.runtime.library.WorksheetSupport$.$execute(Wor
                                                  //| ksheetSupport.scala:75)
                                                  //| 	at bytes$.main(bytes.scala:3)
                                                  //| 	at bytes.main(bytes.scala)
```

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/pull/171
