### ISSUE TITLE
Stacked net should validate all layer configurations before runtime. Wrong config can produce cryptic exception (bcs) or ignored (wcs)

### ISSUE THREAD

**Issue by vlovsky** [deeplearning4j/nd4j#1706]
.layer(0, new RBM.Builder().nIn(inSz).nOut(1000).build())
            .layer(1, new RBM.Builder().nIn(1000).nOut(500).build())
            .layer(1, new RBM.Builder().nIn(500).nOut(1000).build()) //<- wrong index starting here
            .layer(2, new OutputLayer.Builder().nIn(1000).nOut(numRows*numColumns).build())

This config throws following exception at runtime:

Exception in thread "main" org.nd4j.linalg.exception.ND4JIllegalStateException: Cannot execute matrix multiplication: [10, 1000]x[500, 1000]: Column of left array 1000 != rows of right 500
	at org.nd4j.linalg.util.LinAlgExceptions.assertMultiplies(LinAlgExceptions.java:90)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmuli(BaseNDArray.java:2857)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmul(BaseNDArray.java:2723)
	at org.deeplearning4j.nn.layers.feedforward.rbm.RBM.preOutput(RBM.java:318)
	at org.deeplearning4j.nn.layers.feedforward.rbm.RBM.propUp(RBM.java:338)
	at org.deeplearning4j.nn.layers.feedforward.rbm.RBM.propUp(RBM.java:328)
	at org.deeplearning4j.nn.layers.feedforward.rbm.RBM.sampleHiddenGivenVisible(RBM.java:228)
	at org.deeplearning4j.nn.layers.feedforward.rbm.RBM.computeGradientAndScore(RBM.java:119)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:158)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:57)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:51)
	at org.deeplearning4j.nn.layers.BaseLayer.fit(BaseLayer.java:574)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.pretrain(MultiLayerNetwork.java:274)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1420)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1400)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1477)

Net configuration should be validated before runtime. E.g. all layers are present and there are no duplicates. Tested on a few net types. Some nets don't even hit any runtime problems and therefore can produce unintended results.

**Comment by raver119** [comment]
@AlexDBlack i think network validation was imporved since this issue was opened, and it's safe to close now?
