### ISSUE TITLE
RuntimeException: Can't allocate [HOST] memory: 32; threadId: 1

### ISSUE THREAD

**Issue by stealthman13** [deeplearning4j/nd4j#1717]
Running a LSTM model on a CentOS box with a GeForce GTX 1070 gpu. First run on 0.8 I got the following exception and stack trace:

> Everything loaded. Now normalizing
o.n.l.f.Nd4jBackend - Loaded [JCublasBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 32
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Linux]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [8]; Memory: [21.3GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [CUBLAS]
o.n.l.j.o.e.CudaExecutioner - Device name: [GeForce GTX 1070]; CC: [6.1]; Total/free memory: [8502181888]
CUDA error at /projects/skymind/deploy/linux-x86_64/libnd4j/blas/cuda/NativeOps.cu:4841 code=77(<unknown>) "result" 
Exception in thread "main" java.lang.RuntimeException: Can't allocate [HOST] memory: 32; threadId: 1
	at org.nd4j.jita.memory.impl.CudaDirectProvider.malloc(CudaDirectProvider.java:59)
	at org.nd4j.jita.memory.impl.CudaCachingZeroProvider.malloc(CudaCachingZeroProvider.java:114)
	at org.nd4j.jita.memory.impl.CudaFullCachingProvider.malloc(CudaFullCachingProvider.java:90)
	at org.nd4j.jita.handler.impl.CudaZeroHandler.alloc(CudaZeroHandler.java:227)
	at org.nd4j.jita.handler.impl.CudaZeroHandler.alloc(CudaZeroHandler.java:248)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:390)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:345)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<init>(BaseCudaDataBuffer.java:142)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<init>(BaseCudaDataBuffer.java:182)
	at org.nd4j.linalg.jcublas.buffer.CudaIntDataBuffer.<init>(CudaIntDataBuffer.java:52)
	at org.nd4j.jita.allocator.tad.BasicTADManager.getTADOnlyShapeInfo(BasicTADManager.java:48)
	at org.nd4j.jita.allocator.tad.DeviceTADManager.getTADOnlyShapeInfo(DeviceTADManager.java:73)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.naiveExec(CudaExecutioner.java:209)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.pushToGrid(CudaGridExecutioner.java:228)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.processAsGridOp(CudaGridExecutioner.java:336)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.exec(CudaGridExecutioner.java:641)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mean(BaseNDArray.java:3710)
	at org.nd4j.linalg.dataset.api.preprocessor.stats.DistributionStats$Builder.add(DistributionStats.java:105)
	at org.nd4j.linalg.dataset.api.preprocessor.stats.DistributionStats$Builder.addFeatures(DistributionStats.java:80)
	at org.nd4j.linalg.dataset.api.preprocessor.stats.DistributionStats$Builder.addFeatures(DistributionStats.java:71)
	at org.nd4j.linalg.dataset.api.preprocessor.AbstractDataSetNormalizer.fit(AbstractDataSetNormalizer.java:95)

**Comment by raver119** [comment]
Please show source code of your model as gist.

**Comment by stealthman13** [comment]
https://gist.github.com/stealthman13/f2e1ba5f85ce919443d5017f47985be5

**Comment by raver119** [comment]
Please comment out normalizer part, and run again. Literally - comment out everything that's about normalization.

**Comment by stealthman13** [comment]
Works as expected with normalization commented out.

**Comment by raver119** [comment]
Thanks man!

Now we know, it's normalizer.

**Comment by virl** [comment]
Slightly modified (just russian alphabet instead of english) GravesLSTMCharModellingExample on macOS Sierra 10.12.5 with EVGA GTX 960 2GB causes exactly same problem.

**Comment by virl** [comment]
And what is strange is that bug is not deterministic.

**Comment by raver119** [comment]
it's not a problem, its  2GB ram in your case. You just get OOM.
