### ISSUE TITLE
Compression issue on android

### ISSUE THREAD

**Issue by gdamaskinos** [deeplearning4j/nd4j#1751]
#### Issue Description

```java
double[][] data = new double[10][10];
System.out.println(data[2][2]);

Nd4j.getCompressor().setDefaultCompression("FLOAT16");
NDArray array = (NDArray) Nd4j.getCompressor().compress(Nd4j.create(data));
NDArray out = (NDArray) Nd4j.getCompressor().decompress(array);
System.out.println(out);


Caused by: java.lang.RuntimeException: Non-existent compression algorithm requested: [FLOAT16]
                                                                         at org.nd4j.linalg.compression.BasicNDArrayCompressor.compress(BasicNDArrayCompressor.java:174)
                                                                         at org.nd4j.linalg.compression.BasicNDArrayCompressor.compress(BasicNDArrayCompressor.java:150)
                                                                         at com.androidsrc.core_components.MainActivity.onCreate(MainActivity.java:67)
                                                                         at android.app.Activity.performCreate(Activity.java:6679)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                                         at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:154) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

[build.gradle](https://gist.github.com/gdamaskinos/9e5e5a983cd08082b3f9709870be5cc1)

**Comment by raver119** [comment]
And the same code works on pc.

**Comment by raver119** [comment]
Should be fixed now
