### ISSUE TITLE
Handling OutOfMemoryError error

### ISSUE THREAD

**Issue by loretoparisi** [deeplearning4j/nd4j#1768]
When running large dataset it can happen a OutOfMemory error.

These are the running threads:

```

Java Threads: ( => current thread )
  0x000000013705f000 JavaThread "ParallelTransformer thread 2" daemon [_thread_blocked, id=34059, stack(0x000070000a8f7000,0x000070000a9f7000)]
  0x0000000138229800 JavaThread "ParallelTransformer thread 1" daemon [_thread_blocked, id=35075, stack(0x000070000aafd000,0x000070000abfd000)]
  0x0000000138228800 JavaThread "ParallelTransformer thread 0" daemon [_thread_blocked, id=34563, stack(0x000070000a9fa000,0x000070000aafa000)]
  0x000000010510d800 JavaThread "Thread-18" [_thread_in_native, id=7939, stack(0x00007000073f0000,0x0000700007bf0000)]
  0x00000001060b1800 JavaThread "ParallelTransformer thread 3" daemon [_thread_blocked, id=31491, stack(0x000070000a45f000,0x000070000a55f000)]
  0x000000010504f800 JavaThread "ParallelTransformer thread 2" daemon [_thread_blocked, id=30979, stack(0x000070000a35c000,0x000070000a45c000)]
  0x0000000105094000 JavaThread "ParallelTransformer thread 1" daemon [_thread_blocked, id=30467, stack(0x000070000a259000,0x000070000a359000)]
  0x0000000137060800 JavaThread "ParallelTransformer thread 0" daemon [_thread_blocked, id=29955, stack(0x000070000a156000,0x000070000a256000)]
  0x0000000137075000 JavaThread "AsyncIterator Reader thread" daemon [_thread_blocked, id=29447, stack(0x000070000a053000,0x000070000a153000)]
  0x000000010331b800 JavaThread "Thread-11" [_thread_blocked, id=7683, stack(0x0000700006bed000,0x00007000073ed000)]
  0x000000010421e000 JavaThread "ParallelTransformer thread 3" daemon [_thread_blocked, id=28931, stack(0x0000700009f50000,0x000070000a050000)]
  0x000000010616d000 JavaThread "ParallelTransformer thread 2" daemon [_thread_blocked, id=28419, stack(0x0000700009e4d000,0x0000700009f4d000)]
  0x0000000105113800 JavaThread "ParallelTransformer thread 1" daemon [_thread_blocked, id=27907, stack(0x0000700009d4a000,0x0000700009e4a000)]
  0x0000000105112800 JavaThread "ParallelTransformer thread 0" daemon [_thread_blocked, id=27395, stack(0x0000700009c47000,0x0000700009d47000)]
  0x0000000105948000 JavaThread "AsyncIterator Reader thread" daemon [_thread_blocked, id=26887, stack(0x0000700009b44000,0x0000700009c44000)]
  0x000000010247b800 JavaThread "NativeRandomDeallocator thread 0" daemon [_thread_blocked, id=26371, stack(0x0000700009a41000,0x0000700009b41000)]
  0x00000001040cd800 JavaThread "JavaCPP Deallocator" daemon [_thread_blocked, id=17671, stack(0x0000700008f17000,0x0000700009017000)]
  0x0000000105008800 JavaThread "Timer-0" daemon [_thread_blocked, id=25603, stack(0x00007000097b5000,0x00007000098b5000)]
  0x00000001059c9000 JavaThread "Thread-1" [_thread_blocked, id=8195, stack(0x0000700007bf3000,0x00007000083f3000)]
  0x000000010599c800 JavaThread "Thread-0" [_thread_in_native, id=7427, stack(0x00007000063ea000,0x0000700006bea000)]
  0x00000001020be800 JavaThread "Service Thread" daemon [_thread_blocked, id=24323, stack(0x00007000095af000,0x00007000096af000)]
  0x000000010205a000 JavaThread "C1 CompilerThread3" daemon [_thread_blocked, id=23811, stack(0x00007000094ac000,0x00007000095ac000)]
  0x000000010308e800 JavaThread "C2 CompilerThread2" daemon [_thread_blocked, id=23299, stack(0x00007000093a9000,0x00007000094a9000)]
  0x000000010405c000 JavaThread "C2 CompilerThread1" daemon [_thread_blocked, id=22787, stack(0x00007000092a6000,0x00007000093a6000)]
  0x00000001058a9800 JavaThread "C2 CompilerThread0" daemon [_thread_blocked, id=22275, stack(0x00007000091a3000,0x00007000092a3000)]
  0x0000000103029000 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=21763, stack(0x00007000090a0000,0x00007000091a0000)]
  0x00000001058a1000 JavaThread "Finalizer" daemon [_thread_blocked, id=16899, stack(0x0000700008e14000,0x0000700008f14000)]
  0x000000010589e800 JavaThread "Reference Handler" daemon [_thread_blocked, id=16387, stack(0x0000700008d11000,0x0000700008e11000)]
  0x0000000105860800 JavaThread "main" [_thread_in_native, id=775, stack(0x00007fff5f400000,0x00007fff5fc00000)]
```

and the heap status:

```
Heap:
 PSYoungGen      total 227328K, used 113664K [0x00000007ab300000, 0x00000007c0000000, 0x00000007c0000000)
  eden space 113664K, 100% used [0x00000007ab300000,0x00000007b2200000,0x00000007b2200000)
  from space 113664K, 0% used [0x00000007b2200000,0x00000007b2200000,0x00000007b9100000)
  to   space 113664K, 0% used [0x00000007b9100000,0x00000007b9100000,0x00000007c0000000)
 ParOldGen       total 683008K, used 682620K [0x0000000781800000, 0x00000007ab300000, 0x00000007ab300000)
  object space 683008K, 99% used [0x0000000781800000,0x00000007ab29f088,0x00000007ab300000)
 Metaspace       used 27735K, capacity 27980K, committed 28672K, reserved 1075200K
  class space    used 2875K, capacity 2981K, committed 3072K, reserved 1048576K
```

My question is if within DL4J there is a way to avoid those error, assumed we read data in streaming, is there a way to check the memory and stop the process before fitting the whole available free memory?

The full heap stack trace is [here](https://gist.github.com/loretoparisi/fb693cae4936c28c3ffed51459030fd2).

**Comment by agibsonccc** [comment]
Could you post a gist of how you're getting work done? Most of dl4j is actually off heap.

**Comment by loretoparisi** [comment]
I have found the exception on the logs:

```
Exception in thread "VectorCalculationsThread 1" Exception in thread "VectorCalculationsThread 0" Exception in thread "VectorCalculationsThread 7" java.lang.OutOfMemoryError: Java heap space
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:853)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:916)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.learnSequence(SkipGram.java:176)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors.trainSequence(SequenceVectors.java:349)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:1165)
java.lang.OutOfMemoryError: Java heap space
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:867)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:916)
```

while the operation was

```
DEBUG [Thread-1] (VocabConstructor.java:197) - Trying source iterator: [0]
DEBUG [Thread-1] (VocabConstructor.java:198) - Target vocab size before building: [0]
DEBUG [Thread-1] (VocabConstructor.java:286) - Wating till all processes stop...
DEBUG [Thread-1] (VocabConstructor.java:296) - Vocab size before truncation: [69546],  NumWords: [5658961], sequences parsed: [150], counter: [5658812]
DEBUG [Thread-1] (VocabConstructor.java:303) - Vocab size after truncation: [69546],  NumWords: [5658961], sequences parsed: [150], counter: [5658812]
 INFO [Thread-1] (VocabConstructor.java:372) - Sequences checked: [150], Current vocabulary size: [69546]; Sequences/sec: [8,46];
 INFO [Thread-1] (WordVectorSerializer.java:2821) - Projected memory use for model: [106,12 MB]
 INFO [Thread-1] (InMemoryLookupTable.java:141) - Initializing syn1...
 INFO [Thread-1] (SequenceVectors.java:160) - Building learning algorithms:
 INFO [Thread-1] (SequenceVectors.java:168) -           building SequenceLearningAlgorithm: [PV-DBOW]
 INFO [Thread-1] (SequenceVectors.java:176) -           building ElementsLearningAlgorithm: [SkipGram]
 INFO [Thread-1] (SequenceVectors.java:273) - Starting learning process...
```

**Comment by agibsonccc** [comment]
If you look at the projected memory, it's telling you it needs at least 10GB. I would just add more heap space with -Xmx and call it a day. There's not much to really do here.

**Comment by loretoparisi** [comment]
@agibsonccc are you referring to JVM log

```
Metaspace       used 27735K, capacity 27980K, committed 28672K, reserved 1075200K
class space    used 2875K, capacity 2981K, committed 3072K, reserved 1048576K
```

reserved memory?

**Comment by loretoparisi** [comment]
@agibsonccc another question, more generic, can we say that about the model we can assume that having 3M words, 300 features we have about:

`3 million words * 300 features * 4bytes/feature = ~3.35GB`

Thanks.

**Comment by agibsonccc** [comment]
No we tell ou that:
 INFO [Thread-1] (WordVectorSerializer.java:2821) - Projected memory use for model: [106,12 MB]

You have to remember that at the very minimum this memory is being used twice: once for syn0 and once for syn1 (for training)
