### ISSUE TITLE
Random.getSeed() no such method error.

### ISSUE THREAD

**Issue by brettins** [deeplearning4j/nd4j#186]
`Exception in thread "main" java.lang.NoSuchMethodError: org.nd4j.linalg.api.rng.Random.getSeed()J
	at org.deeplearning4j.nn.weights.WeightInitUtil.initWeights(WeightInitUtil.java:78)
	at org.deeplearning4j.nn.weights.WeightInitUtil.initWeights(WeightInitUtil.java:123)
	at org.deeplearning4j.nn.params.DefaultParamInitializer.createWeightMatrix(DefaultParamInitializer.java:67)
	at org.deeplearning4j.nn.params.DefaultParamInitializer.init(DefaultParamInitializer.java:44)
	at org.deeplearning4j.nn.layers.factory.DefaultLayerFactory.getParams(DefaultLayerFactory.java:95)
	at org.deeplearning4j.nn.layers.factory.DefaultLayerFactory.create(DefaultLayerFactory.java:64)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:395)
	at org.deeplearning4j.App.main(App.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
-- org.jblas INFO Starting temp DLL cleanup task.`

Pom.xml looks like this:
https://gist.github.com/brettins/308c15fc638f3defefb6

**Comment by brettins** [comment]
Looks like ND4J compiler isn't finsihing in a normal way which may affect this:

https://gist.github.com/brettins/8484bdff34caedf74bb5

**Comment by agibsonccc** [comment]
This is related to mis matched versions.
