### ISSUE TITLE
 Out of [DEVICE] memory, host memory will be used instead: deviceId: [0], requested bytes: [102579200]

### ISSUE THREAD

**Issue by aliray** [deeplearning4j/nd4j#1874]
Hi I'm trying to run EncoderDecoderLSTM with gpu
here is my gpu code  
public static void main(String[] args) throws IOException {
        CudaEnvironment.getInstance().getConfiguration()
            .allowMultiGPU(true)
            .setMaximumDeviceCache(1L * 1024L * 1024L * 1024L)
            .allowCrossDeviceAccess(true);
        new EncoderDecoderLSTM().run(args);
    }
 but it tips error :

o.n.l.f.Nd4jBackend - Loaded [JCublasBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 32
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Windows 10]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [8]; Memory: [3.6GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [CUBLAS]
o.n.l.j.o.e.CudaExecutioner - Device name: [GeForce GTX 1060 6GB]; CC: [6.1]; Total/free memory: [6442450944]
Building the dictionary...
Dictionary is ready, size is 20035
Total dictionary size is 20035. Processing the dataset...
Done. Corpus size is 281312
Creating a new network...
Number of parameters: 57289283
Epoch 1
o.n.n.Nd4jBlas - Number of threads used for BLAS: 0
o.n.j.h.i.CudaZeroHandler - Out of [DEVICE] memory, host memory will be used instead: deviceId: [0], requested bytes: [102579200]

sometimes errors like below:

Exception in thread "main" Disconnected from the target VM, address: '127.0.0.1:56354', transport: 'socket'
java.lang.RuntimeException: Can't allocate [HOST] memory: 102579200; threadId: 1
	at org.nd4j.jita.memory.impl.CudaDirectProvider.malloc(CudaDirectProvider.java:59)
	at org.nd4j.jita.memory.impl.CudaCachingZeroProvider.malloc(CudaCachingZeroProvider.java:117)
	at org.nd4j.jita.memory.impl.CudaFullCachingProvider.malloc(CudaFullCachingProvider.java:90)
	at org.nd4j.jita.handler.impl.CudaZeroHandler.alloc(CudaZeroHandler.java:227)
	at org.nd4j.jita.handler.impl.CudaZeroHandler.alloc(CudaZeroHandler.java:248)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:390)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:345)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<init>(BaseCudaDataBuffer.java:142)
	at org.nd4j.linalg.jcublas.buffer.CudaFloatDataBuffer.<init>(CudaFloatDataBuffer.java:59)
	at org.nd4j.linalg.jcublas.buffer.factory.CudaDataBufferFactory.createFloat(CudaDataBufferFactory.java:241)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1301)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:265)
	at org.nd4j.linalg.jcublas.JCublasNDArray.<init>(JCublasNDArray.java:102)
	at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.createUninitialized(JCublasNDArrayFactory.java:231)
	at org.nd4j.linalg.factory.Nd4j.createUninitialized(Nd4j.java:4808)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.reshape(BaseNDArray.java:3625)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.reshape(BaseNDArray.java:3656)
	at org.deeplearning4j.util.TimeSeriesUtils.reshape3dTo2d(TimeSeriesUtils.java:102)
	at org.deeplearning4j.nn.layers.recurrent.RnnOutputLayer.getLabels2d(RnnOutputLayer.java:115)
	at org.deeplearning4j.nn.layers.BaseOutputLayer.getGradientsAndDelta(BaseOutputLayer.java:176)
	at org.deeplearning4j.nn.layers.BaseOutputLayer.backpropGradient(BaseOutputLayer.java:157)
	at org.deeplearning4j.nn.layers.recurrent.RnnOutputLayer.backpropGradient(RnnOutputLayer.java:63)
	at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.doBackward(LayerVertex.java:121)
	at org.deeplearning4j.nn.graph.ComputationGraph.calcBackpropGradients(ComputationGraph.java:1258)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1012)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:158)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:57)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:51)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:818)
	at org.deeplearning4j.examples.multigpu.rnn.decoder.EncoderDecoderLSTM.train(EncoderDecoderLSTM.java:224)
	at org.deeplearning4j.examples.multigpu.rnn.decoder.EncoderDecoderLSTM.run(EncoderDecoderLSTM.java:179)
	at org.deeplearning4j.examples.multigpu.rnn.decoder.EncoderDecoderLSTM.main(EncoderDecoderLSTM.java:148)

**Comment by agibsonccc** [comment]
Use workspaces if you're running out of ram: http://deeplearning4j.org/workspaces (this is not in the current release it's in snapshots) . Beyond that increase your heap space.

Keep in mind your gpu hardware also matters.

**Comment by aliray** [comment]
My computer memory is 8g, graphics model is gtx1060 6G, which is not enough to run this example? I tried to increase my heap space, but still prompted the same mistake

**Comment by aliray** [comment]
My current version is 0.8 so i can not use workspaces ， so you mean if i upd my version to 0.8.1 , it may solve this problem?

**Comment by agibsonccc** [comment]
Yes. Just use the snapshots repository: https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/pom.xml#L62

**Comment by aliray** [comment]
thanks buddy

**Comment by ableli** [comment]
@aliray my log output append below, have you sloved the problem?
Device name: [GeForce GTX 1060 3GB]; CC: [6.1]; Total/free memory: [3221225472]
Reflections took 3 ms to scan 2 urls, producing 2 keys and 2 values
Reflections took 258 ms to scan 13 urls, producing 392 keys and 1528 values
Start convert torrent to vec , tatal 303, pageNum 1
Number of threads used for BLAS: 0
Score at iteration 0 is 1.9467529296875
Start convert torrent to vec , tatal 303, pageNum 2
Score at iteration 1 is 1.9341827392578126
Start convert torrent to vec , tatal 303, pageNum 3
Score at iteration 2 is 1.908181396484375
Start convert torrent to vec , tatal 303, pageNum 4
Score at iteration 3 is 1.8864927978515624
Start convert torrent to vec , tatal 303, pageNum 5
Score at iteration 4 is 1.87310107421875
Start convert torrent to vec , tatal 303, pageNum 6
Score at iteration 5 is 1.8607081298828125
Start convert torrent to vec , tatal 303, pageNum 7
Out of [DEVICE] memory, host memory will be used instead: deviceId: [0], requested bytes: [202760000]
Out of [DEVICE] memory, host memory will be used instead: deviceId: [0], requested bytes: [40000000]

**Comment by agibsonccc** [comment]
@ableli just because you don't get help within 5 seconds on gitter doesn't mean you need to go commenting on old issues. This is a well known problem people have when they have more cpu ram than gpu ram. Either get a better gpu or decrease your memory usage.
