### ISSUE TITLE
ND4J : backend specification not present running tests

### ISSUE THREAD

**Issue by huitseeker** [deeplearning4j/nd4j#1894]
#### Issue Description
Running tests:
```
java.lang.NoClassDefFoundError: Could not initialize class org.nd4j.linalg.factory.Nd4j
    at org.nd4j.linalg.BaseNd4jTest.after(BaseNd4jTest.java:124)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
```
...
```
Caused by: java.lang.UnsatisfiedLinkError: no jnind4jcpu in java.library.path
```

The nd4j-tests pom includes a choice of backend, of course

Bisection shows e27e57441 is good, then 08d9198 and after fails /cc @raver119

**Comment by huitseeker** [comment]
Fixed at nd4j-0.9.1( 08c299897acb5be1d57485a8c92ff7469db030ea )

Full log : https://gist.github.com/4d0382d8666b00b1763387446eeb9e30
