### ISSUE TITLE
nd4j related FATAL EXCEPTION encountered while trying to run dl4j on Android

### ISSUE THREAD

**Issue by Yu-Hang** [deeplearning4j/nd4j#1922]
#### Issue Description

I was trying to run dl4j on Android. I followed the tutorial on [Here](https://deeplearning4j.org/android). The build was successful. However, there was a fatal exception when I ran the app. 

Please describe your issue, along with:
- expected behavior: app run through
- encountered behavior: fatal execption

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 0.7.2
* platform information (OS, etc): Android
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing

```
File NNfilePath = new File(Environment.getExternalStorageDirectory()+"/trained_model.zip");

        //load the trained weights to the CNN classifier
        try {
            MultiLayerNetwork model = ModelSerializer.restoreMultiLayerNetwork(NNfilePath);
        } catch (IOException e) {
            e.printStackTrace();
        }
```
```
`07-06 17:29:14.193 19488-19488/com.yuh5.nih.testall W/System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
07-06 17:29:14.193 19488-19488/com.yuh5.nih.testall W/System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
07-06 17:29:14.193 19488-19488/com.yuh5.nih.testall W/System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
07-06 17:29:14.263 19488-19498/com.yuh5.nih.testall I/art: Background partial concurrent mark sweep GC freed 18098(12MB) AllocSpace objects, 10(24MB) LOS objects, 54% free, 13MB/29MB, paused 6.799ms total 83.079ms
07-06 17:29:14.353 19488-19488/com.yuh5.nih.testall D/AndroidRuntime: Shutting down VM
07-06 17:29:14.353 19488-19488/com.yuh5.nih.testall E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.yuh5.nih.testall, PID: 19488
                                                                      java.lang.ExceptionInInitializerError
                                                                          at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:41)
                                                                          at java.lang.Class.newInstance(Native Method)
                                                                          at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5646)
                                                                          at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5554)
                                                                          at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:189)
                                                                          at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:216)
                                                                          at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:167)
                                                                          at com.yuh5.nih.testall.NeuralNetwork.<init>(NeuralNetwork.java:33)
                                                                          at com.yuh5.nih.testall.Cells.<init>(Cells.java:209)
                                                                          at com.yuh5.nih.testall.MainActivity.processImage(MainActivity.java:363)
                                                                          at com.yuh5.nih.testall.MainActivity$1.onClick(MainActivity.java:243)
                                                                          at android.view.View.performClick(View.java:5697)
                                                                          at android.widget.TextView.performClick(TextView.java:10815)
                                                                          at android.view.View$PerformClick.run(View.java:22526)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:158)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                       Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
                                                                          at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:40)
                                                                          at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:16)
                                                                          at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:41) 
                                                                          at java.lang.Class.newInstance(Native Method) 
                                                                          at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5646) 
                                                                          at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5554) 
                                                                          at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:189) 
                                                                          at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:216) 
                                                                          at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:167) 
                                                                          at com.yuh5.nih.testall.NeuralNetwork.<init>(NeuralNetwork.java:33) 
                                                                          at com.yuh5.nih.testall.Cells.<init>(Cells.java:209) 
                                                                          at com.yuh5.nih.testall.MainActivity.processImage(MainActivity.java:363) 
                                                                          at com.yuh5.nih.testall.MainActivity$1.onClick(MainActivity.java:243) 
                                                                          at android.view.View.performClick(View.java:5697) 
                                                                          at android.widget.TextView.performClick(TextView.java:10815) 
                                                                          at android.view.View$PerformClick.run(View.java:22526) 
                                                                          at android.os.Handler.handleCallback(Handler.java:739) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                          at android.os.Looper.loop(Looper.java:158) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:7229) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                       Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.yuh5.nih.testall-2/base.apk"],nativeLibraryDirectories=[/data/app/com.yuh5.nih.testall-2/lib/arm, /data/app/com.yuh5.nih.testall-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libjnind4jcpu.so"
                                                                          at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                          at java.lang.System.loadLibrary(System.java:1076)
                                                                          at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:945)
                                                                          at org.bytedeco.javacpp.Loader.load(Loader.java:750)
                                                                          at org.bytedeco.javacpp.Loader.load(Loader.java:657)
                                                                          at org.nd4j.nativeblas.Nd4jCpu.<clinit>(Nd4jCpu.java:10)
                                                                          at java.lang.Class.classForName(Native Method)
                                                                          at java.lang.Class.forName(Class.java:324)
                                                                          at org.bytedeco.javacpp.Loader.load(Loader.java:712)
                                                                          at org.bytedeco.javacpp.Loader.load(Loader.java:657)
                                                                          at org.nd4j.nativeblas.Nd4jCpu$NativeOps.<clinit>(Nd4jCpu.java:54)
                                                                          at java.lang.Class.classForName(Native Method)
                                                                          at java.lang.Class.forName(Class.java:324)
                                                                          at java.lang.Class.forName(Class.java:285)
                                                                          at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:23)
                                                                          at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:16) 
                                                                          at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:41) 
                                                                          at java.lang.Class.newInstance(Native Method) 
                                                                          at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5646) 
                                                                          at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5554) 
                                                                          at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:189) 
                                                                          at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:216) 
                                                                          at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:167) 
                                                                          at com.yuh5.nih.testall.NeuralNetwork.<init>(NeuralNetwork.java:33) 
                                                                          at com.yuh5.nih.testall.Cells.<init>(Cells.java:209) 
                                                                          at com.yuh5.nih.testall.MainActivity.processImage(MainActivity.java:363) 
                                                                          at com.yuh5.nih.testall.MainActivity$1.onClick(MainActivity.java:243) 
                                                                          at android.view.View.performClick(View.java:5697) 
                                                                          at android.widget.TextView.performClick(TextView.java:10815) 
                                                                          at android.view.View$PerformClick.run(View.java:22526) 
                                                                          at android.os.Handler.handleCallback(Handler.java:739) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                          at android.os.Looper.loop(Looper.java:158) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:7229) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                       Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.yuh5.nih.testall-2/base.apk"],nativeLibraryDirectories=[/data/app/com.yuh5.nih.testall-2/lib/arm, /data/app/com.yuh5.nih.testall-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libnd4jcpu.so"
                                                                          at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                          at java.lang.System.loadLibrary(System.java:1076)
                                                                          at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:945)
                                                                          at org.bytedeco.javacpp.Loader.load(Loader.java:738)
                                                                          at org.bytedeco.javacpp.Loader.load(Loader.java:657) 
                                                                          at org.nd4j.nativeblas.Nd4jCpu.<clinit>(Nd4jCpu.java:10) 
                                                                          at java.lang.Class.classForName(Native Method) 
                                                                          at java.lang.Class.forName(Class.java:324) 
                                                                          at org.bytedeco.javacpp.Loader.load(Loader.java:712) 
                                                                          at org.bytedeco.javacpp.Loader.load(Loader.java:657) 
                                                                          at org.nd4j.nativeblas.Nd4jCpu$NativeOps.<clinit>(Nd4jCpu.java:54) 
                                                                          at java.lang.Class.classForName(Native Method) 
                                                                          at java.lang.Class.forName(Class.java:324) 
                                                                          at java.lang.Class.forName(Class.java:285) 
                                                                          at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:23) 
                                                                          at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:16) 
                                                                          at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:41) 
                                                                          at java.lang.Class.newInstance(Native Method) 
                                                                          at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5646) 
                                                                          at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5554) 
                                                                          at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:189) 
                                                                          at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:216) 
                                                                          at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:167) 
                                                                          at com.yuh5.nih.testall.NeuralNetwork.<init>(NeuralNetwork.java:33) 
                                                                          at com.yuh5.nih.testall.Cells.<init>(Cells.java:209) 
                                                                          at com.yuh5.nih.testall.MainActivity.processImage(MainActivity.java:363) 
                                                                          at com.yuh5.nih.testall.MainActivity$1.onClick(MainActivity.java:243) 
                                                                          at android.view.View.performClick(View.java:5697) 
                                                                          at android.widget.TextView.performClick(TextView.java:10815) 
                                                                          at android.view.View$PerformClick.run(View.java:22526) 
                                                                          at android.os.Handler.handleCallback(Handler.java:739) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                          at android.os.Looper.loop(Looper.java:158) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:7229) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) `
```
Gradle:
Project:
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenCentral()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
App:
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "25.0.1"

    defaultConfig {
        applicationId "com.yuh5.nih.testall"
        minSdkVersion 19
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/INDEX.LIST'
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.2.1'
    compile project(':libraries:opencv')
    compile 'org.deeplearning4j:deeplearning4j-core:0.7.2'
    compile 'org.nd4j:nd4j-native:0.7.2'
    compile 'org.nd4j:nd4j-native:0.7.2:android-x86'
    compile 'org.nd4j:nd4j-native:0.7.2:android-arm'
}

```

**Comment by raver119** [comment]
Please do 2 things.
1) Post your gradle configuration
2) Please consider using latest dl4j/nd4j version, which is 0.8.0

**Comment by Yu-Hang** [comment]
@raver119 I changed to 0.8.0. But now it's giving me error: [](https://stackoverflow.com/questions/44977760/dupicate-files-copied-in-apk-when-building-with-gradle-in-android-studio)

**Comment by raver119** [comment]
@saudet any ideas about how to handle those duplicating files?

**Comment by saudet** [comment]
Just standard Android stuff, we need to pickFirst or exclude as explained on https://deeplearning4j.org/android

**Comment by Yu-Hang** [comment]
@saudet Yes. I'm already doing that. But it seems like there is one more file that still causing this issue, and I'm having problem sorting out which file I should exclude. Can you please help me with that?

**Comment by saudet** [comment]
Sure, but you're going to need to provide at least some information...

**Comment by Yu-Hang** [comment]
Of course, sorry about that. But I don't know what information are you looking for other than what I have in 
`[Here](https://stackoverflow.com/questions/44977760/dupicate-files-copied-in-apk-when-building-with-gradle-in-android-studio)`. Please let me know what you need, and I will post them asap.

**Comment by saudet** [comment]
Ah, sorry. You're including binaries for Windows, we can just remove those
artifacts.

**Comment by Yu-Hang** [comment]
@saudet Can you be more specific on that please?

**Comment by saudet** [comment]
Exclude all the dependencies with "windows" in their names. It might be easier to not include any dependencies with "platform" in their names though.

**Comment by Yu-Hang** [comment]
@saudet Thanks, your answer lead me to the right solution.  What I did to solve this issue is:

 pickFirst 'org/bytedeco/javacpp/windows-x86/msvcp120.dll'
        pickFirst 'org/bytedeco/javacpp/windows-x86_64/msvcp120.dll'
        pickFirst 'org/bytedeco/javacpp/windows-x86/msvcr120.dll'
        pickFirst 'org/bytedeco/javacpp/windows-x86_64/msvcr120.dll'

**Comment by Yu-Hang** [comment]
@saudet Thanks, your answer lead me to the right solution. What I did to solve this issue is:

pickFirst 'org/bytedeco/javacpp/windows-x86/msvcp120.dll'
pickFirst 'org/bytedeco/javacpp/windows-x86_64/msvcp120.dll'
pickFirst 'org/bytedeco/javacpp/windows-x86/msvcr120.dll'
pickFirst 'org/bytedeco/javacpp/windows-x86_64/msvcr120.dll'

**Comment by Yu-Hang** [comment]
@saudet I'm also wondering why Android app need those windows .dll files?

**Comment by saudet** [comment]
They don't, these probably come from some other dependency you are including.

**Comment by Yu-Hang** [comment]
@raver119 @saudet I'm reopening this issue here because it's giving me the same error again as before even if now I'm using 0.8.0. Error messages: Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.yuh5.nih.testall-2/base.apk"],nativeLibraryDirectories=[/data/app/com.yuh5.nih.testall-2/lib/arm, /data/app/com.yuh5.nih.testall-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libjnind4jcpu.so"

**Comment by saudet** [comment]
Is "libjnind4jcpu.so" actually in your APK file? If not, you'll need to figure out a way to put it there...

**Comment by Yu-Hang** [comment]
@raver119 @saudet I don't know where is this "libjnind4jcpu.so". How can I check if it is in my APK file?

**Comment by Yu-Hang** [comment]
@raver119 @saudet I don't know if this is useful info, but the program runs fine in the emulator, but gave that error when I ran on my Samsung Galaxy S6

**Comment by saudet** [comment]
We can use "unzip" on the APK to check the content. What does it contain?

**Comment by Yu-Hang** [comment]
![capture](https://user-images.githubusercontent.com/5137261/28526301-2344b660-7055-11e7-9536-37e6776b007e.JPG)

**Comment by Yu-Hang** [comment]
@saudet , then in the "lib" folder are all opencv related stuff:
![capture](https://user-images.githubusercontent.com/5137261/28526418-7ce31c20-7055-11e7-960f-54f6d8578899.JPG)

**Comment by saudet** [comment]
So you've got both armeabi and armeabi-v7a. Some versions of Android have bugs and might pick one or the other of the directory, so make sure you've got all the files you need in both of them, or just get rid of one of them.

**Comment by Yu-Hang** [comment]
@saudet It worked! Thanks so much! 

I thought it had something to do with nd4j since the error was: couldn't find "libjnind4jcpu.so". So, do you know why this error never came up until I added dl4j?

**Comment by saudet** [comment]
Like I said, this is a limitation in Android, nothing to do with DL4J.

**Comment by KirilaMenski** [comment]
Same problem. Can run on emulator but can't run on device.
@Yu-Hang Can you explain what exactly you do to solve it? How can I rid armeabi or armeabi-v7a and which one of them I should to rid?

**Comment by Yu-Hang** [comment]
@KirilaMenski Go to your app->src->main->jinLibs. They are in there, and you either keep all the ones with "-v7a" or the ones without it.
