### ISSUE TITLE
BinarySerde.toByteBuffer throws Exception for large NDArrays

### ISSUE THREAD

**Issue by turambar** [deeplearning4j/nd4j#1932]
#### Issue Description

Unable to serialize a large NDArray (rank 2, 3M x 1000) using `BinarySerde` -- the call to `toByteBuffer()` throws a `Length is >= Integer.MAX_VALUE` error. Stack trace and example code provided in comment thread.

#### Version Information

Latest mater for libnd4j, nd4j, datavec, and deeplearning4j.

**Comment by turambar** [comment]
Stack trace:

```
Exception in thread "main" java.lang.IllegalArgumentException: Length is >= Integer.MAX_VALUE: lengthLong() must be called instead
        at org.nd4j.linalg.api.ndarray.BaseNDArray.length(BaseNDArray.java:4361)
        at org.nd4j.linalg.api.ndarray.BaseNDArray.isView(BaseNDArray.java:2060)
        at org.nd4j.serde.binary.BinarySerde.toByteBuffer(BinarySerde.java:115)
        ...
```

**Comment by turambar** [comment]
Code to reproduce:

```
String outputFilePath = "largeMatrix.arr";
INDArray points = Nd4j.rand(3700000, 1100);
/**
  * Serialize array to bytes and save to output path.
  */
try(FileOutputStream os = new FileOutputStream(new File(outputFilePath))) {
    FileChannel channel = os.getChannel();
    ByteBuffer buffer = BinarySerde.toByteBuffer(points);
    channel.write(buffer);
    channel.force(true);
    channel.close();
}
```

**Comment by turambar** [comment]
@agibsonccc @raver119 FYI: this is not a blocker on my current project (I can just reduce dimensionality to proceed).

**Comment by turambar** [comment]
And I spoke too soon. It's bit more of a blocker now that I can't make a 3.8M x 120 matrix. :/

**Comment by saudet** [comment]
Sounds to me like the best/only way around that would be to create multiple views from the INDArray and iterate over them, something like this (untested):
```java
FileChannel fc = new RandomAccessFile(new File(outputFilePath), "rw").getChannel();
for (int i = 0; i < chunks; i++) {
    INDArray view = points.get(NDArrayIndex.interval(i * viewRows, (i + 1) * viewRows);
    ByteBuffer bb = BinarySerde.toByteBuffer(view);
    fc.position(i * chunkSize).write(bb);
}
fc.close();
```
