### ISSUE TITLE
indexOutOfBoundException when calling toString on a view

### ISSUE THREAD

**Issue by audreyloeffel** [deeplearning4j/nd4j#1944]
#### Issue Description

When I call toString() on a view that has been created with a newAxis index, I get an indexOutOfBoundException.

**Code**
```
INDArray arr = Nd4j.rand(new int[]{4, 2, 3});
INDArray view = arr.get(NDArrayIndex.newAxis(), NDArrayIndex.all(), NDArrayIndex.point(1));
System.out.println(view);
```

**Stack trace**
```
java.lang.IndexOutOfBoundsException: 24

	at org.bytedeco.javacpp.indexer.Indexer.checkIndex(Indexer.java:90)
	at org.bytedeco.javacpp.indexer.FloatRawIndexer.get(FloatRawIndexer.java:59)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.getDouble(BaseDataBuffer.java:885)
	at org.nd4j.linalg.api.shape.Shape.getDouble(Shape.java:165)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:1715)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:3578)
	at org.nd4j.linalg.string.NDArrayStrings.format(NDArrayStrings.java:113)
	at org.nd4j.linalg.string.NDArrayStrings.format(NDArrayStrings.java:127)
	at org.nd4j.linalg.string.NDArrayStrings.format(NDArrayStrings.java:127)
	at org.nd4j.linalg.string.NDArrayStrings.format(NDArrayStrings.java:95)
	at org.nd4j.linalg.string.NDArrayStrings.format(NDArrayStrings.java:91)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.toString(BaseNDArray.java:4713)
	at java.lang.String.valueOf(String.java:2994)
	at java.io.PrintStream.println(PrintStream.java:821)
	at org.nd4j.linalg.SparseNDArrayCOOTest.testWithDense(SparseNDArrayCOOTest.java:390)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

```

**Comment by agibsonccc** [comment]
Not seeing this anymore with new test fixes.
