### ISSUE TITLE
CNN error - linearView related

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/nd4j#196]
Getting following error on CNN's.

o.d.c.CNNIrisExample - Build model....
Exception in thread "main" java.lang.IllegalArgumentException: Illegal dimension for scalar 2
	at org.nd4j.linalg.api.ndarray.BaseNDArray.size(BaseNDArray.java:3980)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.vectorsAlongDimension(BaseNDArray.java:611)
	at org.nd4j.linalg.indexing.Indices.rowNumber(Indices.java:60)
	at org.nd4j.linalg.api.complex.LinearViewComplexNDArray.getComplex(LinearViewComplexNDArray.java:129)
	at org.nd4j.linalg.api.complex.BaseComplexNDArray.getReal(BaseComplexNDArray.java:1355)
	at org.nd4j.linalg.api.complex.BaseComplexNDArray.getReal(BaseComplexNDArray.java:1343)
	at org.nd4j.linalg.convolution.DefaultConvolutionInstance.convn(DefaultConvolutionInstance.java:136)
	at org.nd4j.linalg.convolution.BaseConvolution.convn(BaseConvolution.java:64)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.activate(ConvolutionLayer.java:145)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.activationFromPrevLayer(MultiLayerNetwork.java:479)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:367)
	at org.deeplearning4j.convolution.CNNIrisExample.main(CNNIrisExample.java:100)
Disconnected from the target VM, address: '127.0.0.1:62371', transport: 'socket'
-- org.jblas INFO Deleting /var/folders/sm/lj217l5j51j_2h_kxc8s_fxc0000gn/T/jblas7588902266358248243/libjblas.dylib
-- org.jblas INFO Deleting /var/folders/sm/lj217l5j51j_2h_kxc8s_fxc0000gn/T/jblas7588902266358248243/libjblas_arch_flavor.dylib
-- org.jblas INFO Deleting /var/folders/sm/lj217l5j51j_2h_kxc8s_fxc0000gn/T/jblas7588902266358248243

Process finished with exit code 1

*************
Appears linked to pulling values out of linearView at this point in the code: 
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-api/src/main/java/org/nd4j/linalg/api/complex/BaseComplexNDArray.java#L1343

getReal doesn't pull a scalar from linearView's values, it's pulling multiple values which is throwing the error under putScalar.  CNNs were working on 6/29 and not much has changed related to linearView between now and then.

**Comment by olafhel** [comment]
I tried to comment out 5316dfc but it doesn't seem to be the reason of failure. 
Still have the same  Illegal dimension for scalar 2

**Comment by nyghtowl** [comment]
Correction - that link was an older link that I had explored and agree it is not the point of problem. The actual link meant for this issue:  

https://github.com/deeplearning4j/nd4j/blob/master/nd4j-api/src/main/java/org/nd4j/linalg/api/complex/BaseComplexNDArray.java#L1343

**Comment by agibsonccc** [comment]
There were a few errors here. One of them was isScalar being too liberal. The other here is related to the center calculation in center. Will work on a fix.

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/commit/4da4780591b6a93f2f194eb4aef5a3095f820ee4
