### ISSUE TITLE
ND4J does not support sparse input files

### ISSUE THREAD

**Issue by kryton** [deeplearning4j/nd4j#202]
Nd4J does not seem to be able to support sparse input files and generates the following when you try
```
Exception in thread "main" java.lang.IllegalStateException: Illegal number of rows for array 1
	at org.nd4j.linalg.factory.BaseNDArrayFactory.vstack(BaseNDArrayFactory.java:1152)
	at org.nd4j.linalg.factory.Nd4j.vstack(Nd4j.java:3702)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:136)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:251)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:45)
```
this affects the Canova SVMLightRecordWriter & LibSvmRecordWriter which currently write sparse files, and have been marked with TODO's on this issue.

**Comment by agibsonccc** [comment]
This is fixed in canova.
