### ISSUE TITLE
No CUDA devices were found in system when -XMX > 973

### ISSUE THREAD

**Issue by dgl85** [deeplearning4j/nd4j#2025]
A "java.lang.RuntimeException: No CUDA devices were found in system" exception is thrown if the -xmx option is passed to the JVM with a value higher than 973g. If more information is needed to replicate please let me know.

**Comment by huitseeker** [comment]
As it will be difficult to reproduce your issue as stated without a machine with > 1TB memory, please give us a precise way to reproduce your issue: you pass those options to the JVM, yes, but what are the other arguments?

Ideally, this would include code / a script making this unambiguous.

**Comment by dgl85** [comment]
The only arguments I'm manually passing to the JVM are: -Xms20g -Xmx974g -XX:+UseG1GC. You don't need 1TB of physical RAM, you can use virtual memory.

I'm currently under nd4j-cuda-8.0-platform 0.8.0, but it was happening on 0.8.1-SNAPSHOT as well.

**Comment by huitseeker** [comment]
When I said other arguments, I'm afraid we are going to need your code or a minimized version of it to reproduce. I can 
`java -Xmx950g -cp /path/to/nd4j.jar HelloWorld` with a trivial `HelloWorld` class, and this won't result in an error.

**Comment by dgl85** [comment]
I can reproduce it with any dl4j example. I just tried it on the MLPMnistSingleLayerExample using the following arguments: -Xms20g -Xmx974g -XX:+UseG1GC
I'm using: 
- IntelliJ IDEA 2017.2.1
-Windows 10
-CUDA 8.0
-<nd4j.backend>nd4j-cuda-8.0-platform</nd4j.backend>
-<nd4j.version>0.8.0</nd4j.version>
-<java.version>1.8</java.version>

Output log:
`o.d.e.f.m.MLPMnistSingleLayerExample - Build model....
o.n.l.f.Nd4jBackend - Loaded [JCublasBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 32
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Windows 10]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [16]; Memory: [974.0GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [CUBLAS]
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.nd4j.jita.allocator.impl.AtomicAllocator.<init>(AtomicAllocator.java:72)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.<clinit>(AtomicAllocator.java:70)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<clinit>(BaseCudaDataBuffer.java:69)
	at org.nd4j.linalg.jcublas.buffer.factory.CudaDataBufferFactory.createDouble(CudaDataBufferFactory.java:226)
	at org.nd4j.rng.NativeRandom.<init>(NativeRandom.java:77)
	at org.nd4j.linalg.jcublas.rng.CudaNativeRandom.<init>(CudaNativeRandom.java:31)
	at org.nd4j.linalg.jcublas.rng.CudaNativeRandom.<init>(CudaNativeRandom.java:27)
	at org.nd4j.linalg.jcublas.rng.CudaNativeRandom.<init>(CudaNativeRandom.java:23)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.nd4j.linalg.factory.RandomFactory.getRandom(RandomFactory.java:28)
	at org.nd4j.linalg.factory.Nd4j.getRandom(Nd4j.java:507)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.seed(NeuralNetConfiguration.java:670)
	at org.deeplearning4j.examples.feedforward.mnist.MLPMnistSingleLayerExample.main(MLPMnistSingleLayerExample.java:61)
Caused by: java.lang.RuntimeException: No CUDA devices were found in system
	at org.nd4j.jita.conf.Configuration.<init>(Configuration.java:389)
	at org.nd4j.jita.conf.CudaEnvironment.<init>(CudaEnvironment.java:26)
	at org.nd4j.jita.conf.CudaEnvironment.<clinit>(CudaEnvironment.java:21)
	... 17 more

Process finished with exit code 1`

**Comment by huitseeker** [comment]
Can you please confirm you do *not* trigger this error with innocuous (small) `-Xmx` and `-Xms` settings ?

**Comment by dgl85** [comment]
Yes, using -Xms20g -Xmx973g -XX:+UseG1GC or anything smaller runs just fine. Here's the output:
```
o.d.e.f.m.MLPMnistSingleLayerExample - Build model....
o.n.l.f.Nd4jBackend - Loaded [JCublasBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 32
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Windows 10]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [16]; Memory: [973.0GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [CUBLAS]
o.n.l.j.o.e.CudaExecutioner - Device name: [TITAN X (Pascal)]; CC: [6.1]; Total/free memory: [10468982783]
o.d.e.f.m.MLPMnistSingleLayerExample - Train model....
o.n.n.Nd4jBlas - Number of threads used for BLAS: 0
o.d.o.l.ScoreIterationListener - Score at iteration 0 is 2.3464892121675605
o.d.o.l.ScoreIterationListener - Score at iteration 1 is 2.330546160146804
o.d.o.l.ScoreIterationListener - Score at iteration 2 is 2.3167860685073562
o.d.o.l.ScoreIterationListener - Score at iteration 3 is 2.271792666383223
o.d.o.l.ScoreIterationListener - Score at iteration 4 is 2.2650935806474672
o.d.o.l.ScoreIterationListener - Score at iteration 5 is 2.223670260200083
o.d.o.l.ScoreIterationListener - Score at iteration 6 is 2.2076702296442505
o.d.o.l.ScoreIterationListener - Score at iteration 7 is 2.155447027490796
o.d.o.l.ScoreIterationListener - Score at iteration 8 is 2.118660715243303
o.d.o.l.ScoreIterationListener - Score at iteration 9 is 2.0563207021435597
o.d.o.l.ScoreIterationListener - Score at iteration 10 is 2.0282559852918256
o.d.o.l.ScoreIterationListener - Score at iteration 11 is 1.9707869885360825
o.d.o.l.ScoreIterationListener - Score at iteration 12 is 1.9120086001591854
o.d.o.l.ScoreIterationListener - Score at iteration 13 is 1.845223165569066
o.d.o.l.ScoreIterationListener - Score at iteration 14 is 1.8279243717819662
o.d.o.l.ScoreIterationListener - Score at iteration 15 is 1.7829919141518382
o.d.o.l.ScoreIterationListener - Score at iteration 16 is 1.6984786378383747
o.d.o.l.ScoreIterationListener - Score at iteration 17 is 1.723271224021128
o.d.o.l.ScoreIterationListener - Score at iteration 18 is 1.6102212766522708
o.d.o.l.ScoreIterationListener - Score at iteration 19 is 1.657290270795942
o.d.o.l.ScoreIterationListener - Score at iteration 20 is 1.573548767640112
o.d.o.l.ScoreIterationListener - Score at iteration 21 is 1.5950976808897828
o.d.o.l.ScoreIterationListener - Score at iteration 22 is 1.4047756871313846
o.d.o.l.ScoreIterationListener - Score at iteration 23 is 1.4409703016327933
o.d.o.l.ScoreIterationListener - Score at iteration 24 is 1.4031825602583559
o.d.o.l.ScoreIterationListener - Score at iteration 25 is 1.3283995290933324
o.d.o.l.ScoreIterationListener - Score at iteration 26 is 1.2806685459160208
o.d.o.l.ScoreIterationListener - Score at iteration 27 is 1.2859820032229945
o.d.o.l.ScoreIterationListener - Score at iteration 28 is 1.2397411399646534
o.d.o.l.ScoreIterationListener - Score at iteration 29 is 1.1577892282287334
o.d.o.l.ScoreIterationListener - Score at iteration 30 is 1.1368395725866702
o.d.o.l.ScoreIterationListener - Score at iteration 31 is 1.057324183302071
o.d.o.l.ScoreIterationListener - Score at iteration 32 is 1.0796916110270962
o.d.o.l.ScoreIterationListener - Score at iteration 33 is 0.9977803566509008
o.d.o.l.ScoreIterationListener - Score at iteration 34 is 1.1370713576152445
o.d.o.l.ScoreIterationListener - Score at iteration 35 is 0.9935500012036149
o.d.o.l.ScoreIterationListener - Score at iteration 36 is 1.0205066323577725
o.d.o.l.ScoreIterationListener - Score at iteration 37 is 1.0391788137812223
o.d.o.l.ScoreIterationListener - Score at iteration 38 is 0.8550747417735486
o.d.o.l.ScoreIterationListener - Score at iteration 39 is 0.9312409686546025
o.d.o.l.ScoreIterationListener - Score at iteration 40 is 0.9595080087515984
o.d.o.l.ScoreIterationListener - Score at iteration 41 is 0.9127705297807939
o.d.o.l.ScoreIterationListener - Score at iteration 42 is 0.9421355463680963
o.d.o.l.ScoreIterationListener - Score at iteration 43 is 0.9527566895321601
o.d.o.l.ScoreIterationListener - Score at iteration 44 is 0.8701912148708626
o.d.o.l.ScoreIterationListener - Score at iteration 45 is 0.9056326252650232
o.d.o.l.ScoreIterationListener - Score at iteration 46 is 0.9747241945013736
o.d.o.l.ScoreIterationListener - Score at iteration 47 is 0.7505215114762285
o.d.o.l.ScoreIterationListener - Score at iteration 48 is 0.7895490933617894
o.d.o.l.ScoreIterationListener - Score at iteration 49 is 0.8677481906247931
o.d.o.l.ScoreIterationListener - Score at iteration 50 is 0.759180721540753
o.d.o.l.ScoreIterationListener - Score at iteration 51 is 0.775607709567061
o.d.o.l.ScoreIterationListener - Score at iteration 52 is 0.7080026982201608
o.d.o.l.ScoreIterationListener - Score at iteration 53 is 0.7944216313188998
o.d.o.l.ScoreIterationListener - Score at iteration 54 is 0.8775565269276525
o.d.o.l.ScoreIterationListener - Score at iteration 55 is 0.7518357923658628
o.d.o.l.ScoreIterationListener - Score at iteration 56 is 0.6952132914185142
o.d.o.l.ScoreIterationListener - Score at iteration 57 is 0.7317014101992327
o.d.o.l.ScoreIterationListener - Score at iteration 58 is 0.7276802459161922
o.d.o.l.ScoreIterationListener - Score at iteration 59 is 0.746150059134697
o.d.o.l.ScoreIterationListener - Score at iteration 60 is 0.7709556659254755
o.d.o.l.ScoreIterationListener - Score at iteration 61 is 0.7856983376550621
o.d.o.l.ScoreIterationListener - Score at iteration 62 is 0.7301468671381683
o.d.o.l.ScoreIterationListener - Score at iteration 63 is 0.649335544094622
o.d.o.l.ScoreIterationListener - Score at iteration 64 is 0.7150184897005416
o.d.o.l.ScoreIterationListener - Score at iteration 65 is 0.7228120918137925
o.d.o.l.ScoreIterationListener - Score at iteration 66 is 0.6625711632969983
o.d.o.l.ScoreIterationListener - Score at iteration 67 is 0.8033491646122927
o.d.o.l.ScoreIterationListener - Score at iteration 68 is 0.769820173538324
o.d.o.l.ScoreIterationListener - Score at iteration 69 is 0.6968015550464077
o.d.o.l.ScoreIterationListener - Score at iteration 70 is 0.7391611971122116
o.d.o.l.ScoreIterationListener - Score at iteration 71 is 0.5905331316476027
o.d.o.l.ScoreIterationListener - Score at iteration 72 is 0.6496614063317734
o.d.o.l.ScoreIterationListener - Score at iteration 73 is 0.6098038304751694
o.d.o.l.ScoreIterationListener - Score at iteration 74 is 0.5851742880547256
o.d.o.l.ScoreIterationListener - Score at iteration 75 is 0.5759605914628757
o.d.o.l.ScoreIterationListener - Score at iteration 76 is 0.6839456016147117
o.d.o.l.ScoreIterationListener - Score at iteration 77 is 0.5513702580427703
o.d.o.l.ScoreIterationListener - Score at iteration 78 is 0.687763436785256
o.d.o.l.ScoreIterationListener - Score at iteration 79 is 0.6505104624322045
o.d.o.l.ScoreIterationListener - Score at iteration 80 is 0.47784971226907125
o.d.o.l.ScoreIterationListener - Score at iteration 81 is 0.6411874381594683
o.d.o.l.ScoreIterationListener - Score at iteration 82 is 0.5657454090018015
o.d.o.l.ScoreIterationListener - Score at iteration 83 is 0.6223137202836317
o.d.o.l.ScoreIterationListener - Score at iteration 84 is 0.6193750782260312
o.d.o.l.ScoreIterationListener - Score at iteration 85 is 0.5089661016920686
o.d.o.l.ScoreIterationListener - Score at iteration 86 is 0.5988399384464662
o.d.o.l.ScoreIterationListener - Score at iteration 87 is 0.5710334636163742
o.d.o.l.ScoreIterationListener - Score at iteration 88 is 0.632814140500004
o.d.o.l.ScoreIterationListener - Score at iteration 89 is 0.6030639562399579
o.d.o.l.ScoreIterationListener - Score at iteration 90 is 0.5497698177442502
o.d.o.l.ScoreIterationListener - Score at iteration 91 is 0.7003242787271837
o.d.o.l.ScoreIterationListener - Score at iteration 92 is 0.5840122927413407
o.d.o.l.ScoreIterationListener - Score at iteration 93 is 0.5302230757882539
o.d.o.l.ScoreIterationListener - Score at iteration 94 is 0.6400582650183719
o.d.o.l.ScoreIterationListener - Score at iteration 95 is 0.5780675682272457
o.d.o.l.ScoreIterationListener - Score at iteration 96 is 0.5101745202986677
o.d.o.l.ScoreIterationListener - Score at iteration 97 is 0.520972538150268
o.d.o.l.ScoreIterationListener - Score at iteration 98 is 0.5311303418496559
o.d.o.l.ScoreIterationListener - Score at iteration 99 is 0.4984239414595245
o.d.o.l.ScoreIterationListener - Score at iteration 100 is 0.6418645851625909
o.d.o.l.ScoreIterationListener - Score at iteration 101 is 0.5185504796501074
o.d.o.l.ScoreIterationListener - Score at iteration 102 is 0.47137767324178675
o.d.o.l.ScoreIterationListener - Score at iteration 103 is 0.5674266629731809
o.d.o.l.ScoreIterationListener - Score at iteration 104 is 0.5534473841972892
o.d.o.l.ScoreIterationListener - Score at iteration 105 is 0.5262255034429013
o.d.o.l.ScoreIterationListener - Score at iteration 106 is 0.5353450518269974
o.d.o.l.ScoreIterationListener - Score at iteration 107 is 0.4900402539440231
o.d.o.l.ScoreIterationListener - Score at iteration 108 is 0.5499366412347677
o.d.o.l.ScoreIterationListener - Score at iteration 109 is 0.5507966536374964
o.d.o.l.ScoreIterationListener - Score at iteration 110 is 0.5549182315627667
o.d.o.l.ScoreIterationListener - Score at iteration 111 is 0.49317158058064825
o.d.o.l.ScoreIterationListener - Score at iteration 112 is 0.5466963192642915
o.d.o.l.ScoreIterationListener - Score at iteration 113 is 0.5817317856505984
o.d.o.l.ScoreIterationListener - Score at iteration 114 is 0.4441567588494777
o.d.o.l.ScoreIterationListener - Score at iteration 115 is 0.5725768174729514
o.d.o.l.ScoreIterationListener - Score at iteration 116 is 0.46001824733049257
o.d.o.l.ScoreIterationListener - Score at iteration 117 is 0.4631478519298328
o.d.o.l.ScoreIterationListener - Score at iteration 118 is 0.5786813265781231
o.d.o.l.ScoreIterationListener - Score at iteration 119 is 0.47994006628402125
o.d.o.l.ScoreIterationListener - Score at iteration 120 is 0.48494545995792016
o.d.o.l.ScoreIterationListener - Score at iteration 121 is 0.4890309144419572
o.d.o.l.ScoreIterationListener - Score at iteration 122 is 0.5199432282858887
o.d.o.l.ScoreIterationListener - Score at iteration 123 is 0.37714871220030555
o.d.o.l.ScoreIterationListener - Score at iteration 124 is 0.5000104892874104
...
```

**Comment by saudet** [comment]
IIRC, I think that's an issue with CUDA in general.

**Comment by saudet** [comment]
It might work with different versions of drivers, for example:
https://devtalk.nvidia.com/default/topic/889831/cuda-memory-allocation-issue-on-gtx-850m-on-windows-7-64-/

**Comment by agibsonccc** [comment]
Yeah that's a problem with your cuda install. I'm closing this. Make sure to follow the tutorials and run nvidia's litmus tests. Come back to us if you get those running successfully.
