### ISSUE TITLE
Having both cuda and cpu backends on the classpath causes exception

### ISSUE THREAD

**Issue by fahman** [deeplearning4j/nd4j#2065]
Related to this change: https://github.com/deeplearning4j/nd4j/blob/aff3295358fae7404cf2985002dd1145d31575ee/nd4j-backends/nd4j-backend-impls/nd4j-cuda/src/main/java/org/nd4j/linalg/jcublas/JCublasBackend.java#L58

Previously we were able to include both org.nd4j.nd4j-native AND org.nd4j.nd4j-cuda-8.0 in project dependencies statically and then, based on environment, just add native libraries (classifier "linux-x86_64", classifier "windows-x86_64").

Now this cause exception below if both nd4j-native AND nd4j-cuda is statically added to dependencies on a environment that does not have CUDA configured:

```
[error] Uncaught exception when running my.vectorize.thought.ThoughtCorpusIteratorTest: java.lang.ExceptionInInitializerError
sbt.ForkMain$ForkError: java.lang.ExceptionInInitializerError: null
        at org.nd4j.jita.concurrency.CudaAffinityManager.getNumberOfDevices(CudaAffinityManager.java:185)
        at org.nd4j.jita.constant.ConstantProtector.purgeProtector(ConstantProtector.java:38)
        at org.nd4j.jita.constant.ConstantProtector.<init>(ConstantProtector.java:31)
        at org.nd4j.jita.constant.ConstantProtector.<clinit>(ConstantProtector.java:20)
        at org.nd4j.jita.constant.ProtectedCudaConstantHandler.<clinit>(ProtectedCudaConstantHandler.java:48)
        at org.nd4j.jita.constant.CudaConstantHandler.<clinit>(CudaConstantHandler.java:17)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6150)
        at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6087)
        at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:201)
        at org.deeplearning4j.models.embeddings.inmemory.InMemoryLookupTable.<init>(InMemoryLookupTable.java:62)
        at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readWord2VecModel(WordVectorSerializer.java:2314)
        at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readWord2VecModel(WordVectorSerializer.java:2266)
        at my.vectorize.thought.ThoughtCorpusIteratorTest.<init>(ThoughtCorpusIteratorTest.scala:19)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:435)
        at sbt.ForkMain$Run$2.call(ForkMain.java:296)
        at sbt.ForkMain$Run$2.call(ForkMain.java:286)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: sbt.ForkMain$ForkError: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
        at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:51)
        at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:19)
        at org.nd4j.jita.concurrency.CudaAffinityManager.getNumberOfDevices(CudaAffinityManager.java:185)
        at org.nd4j.jita.constant.ConstantProtector.purgeProtector(ConstantProtector.java:38)
        at org.nd4j.jita.constant.ConstantProtector.<init>(ConstantProtector.java:31)
        at org.nd4j.jita.constant.ConstantProtector.<clinit>(ConstantProtector.java:20)
        at org.nd4j.jita.constant.ProtectedCudaConstantHandler.<clinit>(ProtectedCudaConstantHandler.java:48)
        at org.nd4j.jita.constant.CudaConstantHandler.<clinit>(CudaConstantHandler.java:17)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6150)
        at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6087)
        at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:201)
        at org.deeplearning4j.models.embeddings.inmemory.InMemoryLookupTable.<init>(InMemoryLookupTable.java:62)
        at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readWord2VecModel(WordVectorSerializer.java:2314)
        at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readWord2VecModel(WordVectorSerializer.java:2266)
        at my.vectorize.thought.ThoughtCorpusIteratorTest.<init>(ThoughtCorpusIteratorTest.scala:19)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:435)
        at sbt.ForkMain$Run$2.call(ForkMain.java:296)
        at sbt.ForkMain$Run$2.call(ForkMain.java:286)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: sbt.ForkMain$ForkError: java.lang.UnsatisfiedLinkError: no jnind4jcuda in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:976)
        at org.bytedeco.javacpp.Loader.load(Loader.java:777)
        at org.bytedeco.javacpp.Loader.load(Loader.java:684)
        at org.nd4j.nativeblas.Nd4jCuda.<clinit>(Nd4jCuda.java:10)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.bytedeco.javacpp.Loader.load(Loader.java:739)
        at org.bytedeco.javacpp.Loader.load(Loader.java:684)
        at org.nd4j.nativeblas.Nd4jCuda$NativeOps.<clinit>(Nd4jCuda.java:63)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:29)
        at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:19)
        at org.nd4j.jita.concurrency.CudaAffinityManager.getNumberOfDevices(CudaAffinityManager.java:185)
        at org.nd4j.jita.constant.ConstantProtector.purgeProtector(ConstantProtector.java:38)
        at org.nd4j.jita.constant.ConstantProtector.<init>(ConstantProtector.java:31)
        at org.nd4j.jita.constant.ConstantProtector.<clinit>(ConstantProtector.java:20)
        at org.nd4j.jita.constant.ProtectedCudaConstantHandler.<clinit>(ProtectedCudaConstantHandler.java:48)
        at org.nd4j.jita.constant.CudaConstantHandler.<clinit>(CudaConstantHandler.java:17)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6150)
        at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6087)
        at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:201)
        at org.deeplearning4j.models.embeddings.inmemory.InMemoryLookupTable.<init>(InMemoryLookupTable.java:62)
        at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readWord2VecModel(WordVectorSerializer.java:2314)
        at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readWord2VecModel(WordVectorSerializer.java:2266)
        at my.vectorize.thought.ThoughtCorpusIteratorTest.<init>(ThoughtCorpusIteratorTest.scala:19)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:435)
        at sbt.ForkMain$Run$2.call(ForkMain.java:296)
        at sbt.ForkMain$Run$2.call(ForkMain.java:286)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: sbt.ForkMain$ForkError: java.lang.UnsatisfiedLinkError: no nd4jcuda in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:976)
        at org.bytedeco.javacpp.Loader.load(Loader.java:765)
        at org.bytedeco.javacpp.Loader.load(Loader.java:684)
        at org.nd4j.nativeblas.Nd4jCuda.<clinit>(Nd4jCuda.java:10)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.bytedeco.javacpp.Loader.load(Loader.java:739)
        at org.bytedeco.javacpp.Loader.load(Loader.java:684)
        at org.nd4j.nativeblas.Nd4jCuda$NativeOps.<clinit>(Nd4jCuda.java:63)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:29)
        at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:19)
        at org.nd4j.jita.concurrency.CudaAffinityManager.getNumberOfDevices(CudaAffinityManager.java:185)
        at org.nd4j.jita.constant.ConstantProtector.purgeProtector(ConstantProtector.java:38)
        at org.nd4j.jita.constant.ConstantProtector.<init>(ConstantProtector.java:31)
        at org.nd4j.jita.constant.ConstantProtector.<clinit>(ConstantProtector.java:20)
        at org.nd4j.jita.constant.ProtectedCudaConstantHandler.<clinit>(ProtectedCudaConstantHandler.java:48)
        at org.nd4j.jita.constant.CudaConstantHandler.<clinit>(CudaConstantHandler.java:17)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6150)
        at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6087)
        at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:201)
        at org.deeplearning4j.models.embeddings.inmemory.InMemoryLookupTable.<init>(InMemoryLookupTable.java:62)
        at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readWord2VecModel(WordVectorSerializer.java:2314)
        at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readWord2VecModel(WordVectorSerializer.java:2266)
        at my.vectorize.thought.ThoughtCorpusIteratorTest.<init>(ThoughtCorpusIteratorTest.scala:19)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:435)
        at sbt.ForkMain$Run$2.call(ForkMain.java:296)
        at sbt.ForkMain$Run$2.call(ForkMain.java:286)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```
		
The remedy is to remove backend apis, add org.nd4j.nd4j-api and then add native apis, libs and javacpp-presets based on environment.

This change has additional effects:
- previously we could easily strictly type-check if CpuBackend or JCublasBackend is being loaded by Nd4jBackend.load() (to config backend specific stuff such as minibatch size or some mem settings) now this is not possible because JCublasBackend cannot be statically added as a dependency;
- currently it appears that it is possible to control loaded backend only with ENV variable which is less attractive than controlling it by means of java property if e.g. we have some tasks that should be executed by dl4j with GPU and other tasks on the same hardware that should be executed by dl4j without GPU;

**Comment by saudet** [comment]
We need to make sure that `backend.isAvailable()` returns `false` here:
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-context/src/main/java/org/nd4j/linalg/factory/Nd4jBackend.java#L179
I'm guessing that this is what isn't happening anymore.
