### ISSUE TITLE
Nd4j.vstack(List) Exception

### ISSUE THREAD

**Issue by cqiaoYc** [deeplearning4j/nd4j#2068]
#### Issue Description
Nd4j.vstack(rawSeriesList);
throw an exception. rawSeriesList.size()>100. It's ok, if changing to:
`
INDArray allData=this.rawSeriesList.get(0);
        for(int i=1;i<this.rawSeriesList.size();++i){
            allData= Nd4j.vstack(allData,this.rawSeriesList.get(i));
        }
`
Exception in thread "main" org.nd4j.linalg.exception.ND4JException: CUDA exception happened. Terminating. Last op: [null]
	at org.nd4j.jita.allocator.pointers.cuda.cudaEvent_t.register(cudaEvent_t.java:63)
	at org.nd4j.jita.flow.impl.SynchronousFlowController.registerAction(SynchronousFlowController.java:250)
	at org.nd4j.jita.handler.impl.CudaZeroHandler.registerAction(CudaZeroHandler.java:1258)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.registerAction(AtomicAllocator.java:1017)
	at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.concat(JCublasNDArrayFactory.java:680)
	at org.nd4j.linalg.factory.Nd4j.concat(Nd4j.java:5712)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.vstack(BaseNDArrayFactory.java:1222)
	at org.nd4j.linalg.factory.Nd4j.vstack(Nd4j.java:5531)
	at com.cq.mltrademodels.MultiSeriesDataSetIterator.getAllRawData(MultiSeriesDataSetIterator.java:63)
#### Version Information
 <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-api</artifactId>
            <version>0.9.1version>
        </dependency>
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-cuda-8.0</artifactId>
            <version>0.9.1version>
        </dependency>
        <dependency>
            <groupId>org.jcuda</groupId>
            <artifactId>jcuda</artifactId>
            <version>0.8.0</version>
        </dependency>
        <dependency>
            <groupId>org.jcuda</groupId>
            <artifactId>jcublas</artifactId>
            <version>0.8.0</version>
        </dependency>
* platform information (OS, etc)：win10/64

**Comment by agibsonccc** [comment]
@cqiaoYc I'm just going to note here you don't need jcuda here. I'm not sure why you felt the need to include it here. If you are using it for other things fine, but we don't actually use or need jcuda.

**Comment by raver119** [comment]
What's the dimensionality of your arrays in rawSeriesList?
