### ISSUE TITLE
Dot not implemented in nd4j-java backend

### ISSUE THREAD

**Issue by jarutis** [deeplearning4j/nd4j#209]
Leads to failing word2vec training with nd4j-java backend.

```
java.lang.UnsupportedOperationException
	at org.nd4j.linalg.java.blas.JavaLevel1.sdot(JavaLevel1.java:34)
	at org.nd4j.linalg.api.blas.impl.BaseLevel1.dot(BaseLevel1.java:32)
	at org.nd4j.linalg.factory.BaseBlasWrapper.dot(BaseBlasWrapper.java:185)
	at org.deeplearning4j.spark.models.embeddings.word2vec.SentenceBatch.iterateSample(SentenceBatch.java:179)
	at org.deeplearning4j.spark.models.embeddings.word2vec.SentenceBatch.skipGram(SentenceBatch.java:97)
	at org.deeplearning4j.spark.models.embeddings.word2vec.SentenceBatch.trainSentence(SentenceBatch.java:71)
	at org.deeplearning4j.spark.models.embeddings.word2vec.SentenceBatch.call(SentenceBatch.java:55)
	at org.deeplearning4j.spark.models.embeddings.word2vec.SentenceBatch.call(SentenceBatch.java:42)
	at org.apache.spark.api.java.JavaPairRDD$$anonfun$toScalaFunction$1.apply(JavaPairRDD.scala:1027)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at org.apache.spark.rdd.RDD$$anonfun$foreach$1$$anonfun$apply$28.apply(RDD.scala:870)
	at org.apache.spark.rdd.RDD$$anonfun$foreach$1$$anonfun$apply$28.apply(RDD.scala:870)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1765)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1765)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:63)
	at org.apache.spark.scheduler.Task.run(Task.scala:70)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by agibsonccc** [comment]
Added. https://github.com/deeplearning4j/nd4j/commit/aa22ca1fe341ace9917bc9afc8d633dbbe6932a4
