### ISSUE TITLE
testing gives an error with nd4j-jcublas-7.0

### ISSUE THREAD

**Issue by kryton** [deeplearning4j/nd4j#210]
running mvn install
gives the following error.
[INFO] nd4j-jcublas-7.0 .................................. FAILURE [01:46 min]
```
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.445 sec <<< FAILURE!
testMean(jcuda.jcublas.kernel.TestMatrixOperations)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoSuchMethodError: org.nd4j.linalg.api.ndarray.INDArray.mean(I)Lorg/nd4j/linalg/api/ndarray/INDArray;
	at jcuda.jcublas.kernel.TestMatrixOperations.testMean(TestMatrixOperations.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)


Results :

Failed tests:   testOnes(jcuda.jcublas.fft.JCudaFftTest): expected:<[[25.0 + 0.0i ,0.0 + 0.0i ,0.0 + 0.0i ,0.0 + 0.0i ,0.0 + 0.0i](..)
  test1d(jcuda.jcublas.fft.JCudaFftTest): expected:<[36.0 + 0.0i ,-4.0 + 9.656854629516602i ,-4.0 + 4.0i ,-4.0 + 1.656854271888733i ,-4.0 + 0.0i ,-4.0 - 1.656854271888733i ,-4.0 - 4.0i ,-4.0 - 9.656854629516602i](..)

Tests in error: 
  testMean(jcuda.jcublas.kernel.TestMatrixOperations): org.nd4j.linalg.api.ndarray.INDArray.mean(I)Lorg/nd4j/linalg/api/ndarray/INDArray;

Tests run: 7, Failures: 2, Errors: 1, Skipped: 0
```

**Comment by agibsonccc** [comment]
All tests pass now.
