### ISSUE TITLE
NullPointerException when initializing ND4J with CUDA backend

### ISSUE THREAD

**Issue by turambar** [deeplearning4j/nd4j#2100]
#### Issue Description

When I try to do, well, *anything* with ND4J using the CUDA backend, I get a NullPointerException inside of the `initWithBackend()` method.

No such error when running with CPU backend.

I'll post a stack trace, the line of code indicated by the stack trace, and minimal code needed to reproduce in the comments.

#### Version Information

Please indicate relevant versions, including, if relevant:

* ND4J master built from source (0.9.2-SNAPSHOT)
* Ubuntu 16.0.4
* Titan GTX X
* CUDA 8.0
* NVIDIA driver version: 375.66

**Comment by turambar** [comment]
Minimal code to reproduce:
```
import org.nd4j.linalg.factory.Nd4j;

public class ReproduceBug {
    public static void main(String[] args) {
        Nd4j.zeros(12, 34);
    }
}
```

**Comment by turambar** [comment]
Stack trace:
```
2017-09-05 14:41:15 INFO  Nd4jBackend:194 - Loaded [JCublasBackend] backend
2017-09-05 14:41:15 WARN  Reflections:181 - given scan urls are empty. set urls in the configuration
Exception in thread "main" java.lang.ExceptionInInitializerError
	at ai.skymind.cdg.dev.ReproduceBug.main(ReproduceBug.java:7)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6365)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6229)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:205)
	... 1 more
Caused by: java.lang.NullPointerException
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6286)
	... 3 more
```

**Comment by turambar** [comment]
Line 6286 from `Nd4j.initWithBackend()`:

```
sparseNDArrayClazz = (Class<? extends NDArrayFactory>) Class.forName(System.getProperty(SPARSE_NDARRAY_FACTORY_CLASS, props.getProperty(SPARSE_NDARRAY_FACTORY_CLASS).toString()));
```
