### ISSUE TITLE
DataBuffer.asBytes fails

### ISSUE THREAD

**Issue by migel** [deeplearning4j/nd4j#216]
```scala
  val a = Nd4j.rand(3,3)                          //> a  : org.nd4j.linalg.api.ndarray.INDArray = [[0.709028959274292, 0.665010392
                                                  //| 665863, 0.014407132752239704]
                                                  //|  [0.3749561309814453, 0.6186637878417969, 0.14666570723056793]
                                                  //|   ,[0.7870067954063416, 0.33182623982429504, 0.2005726546049118]]
                                                  //| 
  a.data().asBytes()                              //> java.lang.IllegalStateException: Double array is null!
                                                  //| 	at org.nd4j.linalg.api.buffer.BaseDataBuffer.asBytes(BaseDataBuffer.java
                                                  //| :441)
                                                  //| 	at serialize$$anonfun$main$1.apply$mcV$sp(serialize.scala:6)
                                                  //| 	at org.scalaide.worksheet.runtime.library.WorksheetSupport$$anonfun$$exe
                                                  //| cute$1.apply$mcV$sp(WorksheetSupport.scala:76)
                                                  //| 	at org.scalaide.worksheet.runtime.library.WorksheetSupport$.redirected(W
                                                  //| orksheetSupport.scala:65)
                                                  //| 	at org.scalaide.worksheet.runtime.library.WorksheetSupport$.$execute(Wor
                                                  //| ksheetSupport.scala:75)
                                                  //| 	at serialize$.main(serialize.scala:3)
                                                  //| 	at serialize.main(serialize.scala)
```

**Comment by agibsonccc** [comment]
Backend?

**Comment by migel** [comment]
jblas

**Comment by agibsonccc** [comment]
So I can't reproduce this:
https://github.com/deeplearning4j/nd4j/blob/30881bfb3874636cc20cc7a47e2958baf29a1f19/nd4j-tests/src/test/java/org/nd4j/linalg/api/buffer/DoubleDataBufferTest.java#L83-83

Let's use #218 as a point of discussion here.

**Comment by agibsonccc** [comment]
#218
