### ISSUE TITLE
Nothing running with CUDA-8 but runnig well on CPU

### ISSUE THREAD

**Issue by SarenArterius2** [deeplearning4j/nd4j#2242]
#### Issue Description

Hello, I am having an issue running my code using nd4j-cuda-8.0-platform. When I run the same code using CPU (nd4j-native-platform) it runs well. I am fairly new to all this and I could not find any fix. I would greatly appriciate if anyone helped me with the issue. When running on CUDA I get these errors in console:

Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.nd4j.jita.concurrency.CudaAffinityManager.getNumberOfDevices(CudaAffinityManager.java:185)
	at org.nd4j.jita.constant.ConstantProtector.purgeProtector(ConstantProtector.java:38)
	at org.nd4j.jita.constant.ConstantProtector.<init>(ConstantProtector.java:31)
	at org.nd4j.jita.constant.ConstantProtector.<clinit>(ConstantProtector.java:20)
	at org.nd4j.jita.constant.ProtectedCudaConstantHandler.<clinit>(ProtectedCudaConstantHandler.java:48)
	at org.nd4j.jita.constant.CudaConstantHandler.<clinit>(CudaConstantHandler.java:17)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6150)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6087)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:201)
	at feec.vutbr.cz.ELM_GPU.App.main(App.java:19)
Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:51)
	at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:19)
	... 12 more
Caused by: java.lang.NoSuchMethodError: org.bytedeco.javacpp.Loader.totalCores()I
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:39)
	... 13 more

#### Version Information

 Nd4j version 0.9.1
 OS is windows 10 64bit
 CUDA toolkit 9.0.176
 NVIDIA driver 388.00
 GPU is GTX 1080

**Comment by raver119** [comment]
It might sound strange, but you can’t run nd4j-cuda-8.0 backend, without CUDA Toolkit 8.0 installed. 
nVidia does NOT provide backward compatibility, so CUDA 9 you have installed doesn’t count as CUDA 8

**Comment by SarenArterius2** [comment]
So I did install CUDA toolkit 8.0.61. Everything shows, that I am running on CUDA 8.0 but errors persist.

**Comment by raver119** [comment]
Show new full error message please, and full pom.xml

**Comment by SarenArterius2** [comment]
Complete console readout is:

[Console output redirected to file:C:\Users\Jirka\Desktop\output]
30 [main] INFO org.nd4j.linalg.factory.Nd4jBackend - Loaded [JCublasBackend] backend
217 [main] INFO org.reflections.Reflections - Reflections took 142 ms to scan 53 urls, producing 35802 keys and 38643 values 
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.nd4j.jita.concurrency.CudaAffinityManager.getNumberOfDevices(CudaAffinityManager.java:185)
	at org.nd4j.jita.constant.ConstantProtector.purgeProtector(ConstantProtector.java:38)
	at org.nd4j.jita.constant.ConstantProtector.<init>(ConstantProtector.java:31)
	at org.nd4j.jita.constant.ConstantProtector.<clinit>(ConstantProtector.java:20)
	at org.nd4j.jita.constant.ProtectedCudaConstantHandler.<clinit>(ProtectedCudaConstantHandler.java:48)
	at org.nd4j.jita.constant.CudaConstantHandler.<clinit>(CudaConstantHandler.java:17)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6150)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6087)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:201)
	at feec.vutbr.cz.ELM_GPU.App.main(App.java:19)
Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:51)
	at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:19)
	... 12 more
Caused by: java.lang.NoSuchMethodError: org.bytedeco.javacpp.Loader.totalCores()I
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:39)
	... 13 more

Dont know how to get rid of that ...13 more tho. POM.xml is:

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>feec.vutbr.cz</groupId>
  <artifactId>EML_GPU</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>EML_GPU</name>
  <url>http://maven.apache.org</url>

  <properties>
    <nd4j.backend>nd4j-cuda-8.0-platform</nd4j.backend>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <nd4j.version>0.9.1</nd4j.version>
  </properties>

  <dependencies>

    <dependency>
      <groupId>org.nd4j</groupId>
      <artifactId>nd4j-cuda-8.0-platform</artifactId>
      <version>${nd4j.version}</version>
    </dependency>

    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>

    <dependency>
       <groupId>org.slf4j</groupId>
       <artifactId>slf4j-api</artifactId>
       <version>1.7.5</version>
    </dependency>

    <dependency>
       <groupId>org.slf4j</groupId>
       <artifactId>slf4j-simple</artifactId>
       <version>1.6.4</version>
    </dependency>

    <dependency>
     <groupId>org.bytedeco.javacpp-presets</groupId>
     <artifactId>cuda</artifactId>
     <version>9.0-7.0-1.3</version>
    </dependency>

  </dependencies>
</project>

**Comment by raver119** [comment]
Can you please exclude jcpp-presets from your pom.xml?
I think that’s where your version clash comes from.

**Comment by SarenArterius2** [comment]
Thank you that helped. What I got now is that I guess Blas is not using the GPU? Here is the error message. Happens with Nd4j.getBlasWrapper().lapack().gesvd(A3, S, U, V);

37 [main] INFO org.nd4j.linalg.factory.Nd4jBackend - Loaded [JCublasBackend] backend
285 [main] INFO org.reflections.Reflections - Reflections took 181 ms to scan 53 urls, producing 35785 keys and 38626 values 
1339 [main] INFO org.nd4j.nativeblas.NativeOpsHolder - Number of threads used for NativeOps: 32
4074 [main] INFO org.reflections.Reflections - Reflections took 113 ms to scan 11 urls, producing 31 keys and 227 values 
4194 [main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Windows 10]
4195 [main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Cores: [8]; Memory: [3,5GB];
4195 [main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Blas vendor: [CUBLAS]
4195 [main] INFO org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner - Device name: [GeForce GTX 1080]; CC: [6.1]; Total/free memory: [8589934592]
4485 [main] INFO org.reflections.Reflections - Reflections took 232 ms to scan 11 urls, producing 405 keys and 1596 values 
4505 [main] INFO org.nd4j.nativeblas.Nd4jBlas - Number of threads used for BLAS: 0
[[3.00,  3.00,  3.00],  
 [3.00,  3.00,  3.00],  
 [3.00,  3.00,  3.00]]
[[0.73,  0.73,  0.73],  
 [0.73,  0.73,  0.73],  
 [0.73,  0.73,  0.73]]
[[2.00,  -2.00,  1.00],  
 [5.00,  1.00,  4.00]]

Matrix Size: 2 rows, 3 Columns

Exception in thread "main" org.nd4j.linalg.api.blas.BlasException: cusolverDnSgesvd failed
	at org.nd4j.linalg.jcublas.blas.JcublasLapack.sgesvd(JcublasLapack.java:693)
	at org.nd4j.linalg.api.blas.impl.BaseLapack.gesvd(BaseLapack.java:205)
	at feec.vutbr.cz.ELM_GPU.App.main(App.java:33)

**Comment by raver119** [comment]
You see message yourself: Exception in thread "main" org.nd4j.linalg.api.blas.BlasException: cusolverDnSgesvd failed

That’s cuda error message. SVD call failed for some reason.

Отправлено с iPad

> 5 нояб. 2017 г., в 14:47, SarenArterius2 <notifications@github.com> написал(а):
> 
> Exception in thread "main" org.nd4j.linalg.api.blas.BlasException: cusolverDnSgesvd failed

**Comment by raver119** [comment]
Anyway. i’m closing this issue, feel free to open new one regarding svd. But i’m afraid that won’t be our fault :)

**Comment by SarenArterius2** [comment]
Thank you very much for your help.
