### ISSUE TITLE
SVD not running on CUDA-8

### ISSUE THREAD

**Issue by SarenArterius2** [deeplearning4j/nd4j#2244]
#### Issue Description

Hello. when I try to run SVD (Nd4j.getBlasWrapper().lapack().gesvd(Input, S, U, V);) on CPU everything runs well. When I finaly managed to swith to GPU and ran the code again, I get exception when it gets to SVD. Dont know where the issue is, hope someone can help.

40 [main] INFO org.nd4j.linalg.factory.Nd4jBackend - Loaded [JCublasBackend] backend
248 [main] INFO org.reflections.Reflections - Reflections took 154 ms to scan 53 urls, producing 35785 keys and 38626 values 
1144 [main] INFO org.nd4j.nativeblas.NativeOpsHolder - Number of threads used for NativeOps: 32
1792 [main] INFO org.reflections.Reflections - Reflections took 102 ms to scan 11 urls, producing 31 keys and 227 values 
1902 [main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Windows 10]
1902 [main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Cores: [8]; Memory: [3,5GB];
1902 [main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Blas vendor: [CUBLAS]
1902 [main] INFO org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner - Device name: [GeForce GTX 1080]; CC: [6.1]; Total/free memory: [8589934592]
2146 [main] INFO org.reflections.Reflections - Reflections took 194 ms to scan 11 urls, producing 405 keys and 1596 values 
2158 [main] INFO org.nd4j.nativeblas.Nd4jBlas - Number of threads used for BLAS: 0

Exception in thread "main" org.nd4j.linalg.api.blas.BlasException: cusolverDnSgesvd failed
	at org.nd4j.linalg.jcublas.blas.JcublasLapack.sgesvd(JcublasLapack.java:693)
	at org.nd4j.linalg.api.blas.impl.BaseLapack.gesvd(BaseLapack.java:205)
	at feec.vutbr.cz.ELM_GPU.App.main(App.java:33)

#### Version Information

Nd4j version 0.9.1
OS is windows 10 64bit
CUDA toolkit 8.0.61
NVIDIA driver 376.51
GPU is GTX 1080

**Comment by saudet** [comment]
@rcorbish ideas?

**Comment by saudet** [comment]
@SarenArterius2 Please post a code snippet to reproduce this. Thanks!

**Comment by SarenArterius2** [comment]
Here is the code I run:

        int nRows = 1;
    	int nColumns = 1;
    	
    	INDArray A = Nd4j.create(new float[] {2,-2,1,5,1,4}, new int[] {2,3});
    	nRows = A.rows();
    	nColumns = A.columns();
        System.out.println("A: " + A);
        
        
        INDArray S = Nd4j.zeros(1, nRows);
        INDArray U = Nd4j.zeros(nRows, nRows);
        INDArray V = Nd4j.zeros(nColumns, nColumns);
        Nd4j.getBlasWrapper().lapack().gesvd(A, S, U, V);
        
        System.out.println("\n S:" + S);
        System.out.println("\n U:" + U);
        System.out.println("\n V:" + V);

and here is pom.xml I use:
[pom.txt](https://github.com/deeplearning4j/nd4j/files/1446640/pom.txt)

I appreciate the help.

**Comment by SarenArterius2** [comment]
Not sure if it is relevant but I just tryed to run Nd4j.getBlasWrapper().lapack().getrf(A); and it worked well. So I think that something is wrong specificaly with SVD. Code I ran is:

        INDArray A = Nd4j.rand(3, 3);
        System.out.println("A: " + A);
        INDArray B = Nd4j.getBlasWrapper().lapack().getrf(A);
        System.out.println("\nA: " + B);

**Comment by rcorbish** [comment]
I'll have a look. I am traveling now - so response may not be immediate.
A = 2x3
U = 2x2
V = 3x3
S = 1x2

That all looks good to me. I need to check whether S is a diagonal matrix or a vector representing the diagonal. Can you try 1 thing for me - make S a 2x3 ( same size as orig )

**Comment by rcorbish** [comment]
Also - for GPU it expects the matrix to be in fol order - can you also try
 
 INDArray A = Nd4j.create(new float[] {2,-2,1,5,1,4}, new int[] {2,3}, 'f' ) ; // note 'f' param at end

**Comment by SarenArterius2** [comment]
None of those helped, but I actualy managed to find out why it wouldnt work. I found this discusion on StackOverflow:
https://stackoverflow.com/questions/38200307/how-can-solve-svd-from-row-major-matrix-using-cusolver-gesvd-function
So for [3,2] sized matrix it kinda works, but the outpus is kinda messy - all output is in vectors and signs differ from what I found around internet. It seems that SVD everywhere is a mess. I compared 2 different sites, they gave me same numbers, but different signs, Guess I'm gonna have to compare it with CPU version. Anyway, thank you for your help and if you have a better solution than inverting the input matrix and than trying to correct the output signs, I'd be glad to hear it.

**Comment by rcorbish** [comment]
The SVD is not a unique factorization. You may receive different answers using different algorithms. The direction of the eigen vectors can reverse. To test if the factors are correct - multiply the factors together ( U x S x V ) and check vs. original answer.  

I like ro check against gnu octave - a useful tool if you are doing any linear algebra.

**Comment by rcorbish** [comment]
If you are able to share why you need a SVD there may be other means to achieve what you need. It's possible it could be included in ND4j.

**Comment by SarenArterius2** [comment]
I need SVD in order to get Moore-Penrose matrix inverese. After a number of trial and error runs I managed to get it running, compairing with calculations I found around internet. Problem was that with different input matrix shape, SVD gives different output matrix size(U and V switches, ...). Moreover where CPU implementation gives you matrixes as an output, GPU gives you vectors with different ordering. So in the end it was just about what output SVD gives you for each input (CPU and GPU differece included). Also where SVD for CPU tells you whats wrong in an exception or error message, SVD for GPU simply responds with "cusolverDnSgesvd failed" if something is wrong. Not sure if I just overlooked it, but it would be good to include what exactly SVD gives you in the output ad what it wants in the input in documentation, making it easily available and saving time for beginners.
Anyway thank you for helping, it is much appeciated.

**Comment by rcorbish** [comment]
You can do the pseudo-inverse using a QR factorization too. Is that what you are looking for? If others agreed we could add it. It might be more numerically stable than SVD. Again though the pseudo-inverse has multiple solutions for underspecified cases


________________________________

**Comment by Liujish931** [comment]
i resolved this problem by making
   INDArray S = Nd4j.zeros( nRows,1,'f');
    INDArray U = Nd4j.zeros(nRows, nRows,'f');
    INDArray V = Nd4j.zeros(nColumns, nColumns,'f');
