### ISSUE TITLE
Getting "UnsatisfiedLinkError: no nd4jcuda in java.library.path" when using locally built nd4j.

### ISSUE THREAD

**Issue by stolsvik** [deeplearning4j/nd4j#2245]
With help of @raver119 (on whose request I am posting this bug), I've built dl4j from source. However, when trying to run with it, I get the following stack trace upon entering first line of Nd4j code (which is: Nd4j.getMemoryManager().setAutoGcWindow(10000))

```Java
java.lang.ExceptionInInitializerError
	at org.nd4j.jita.concurrency.CudaAffinityManager.getNumberOfDevices(CudaAffinityManager.java:185)
	at org.nd4j.jita.constant.ConstantProtector.purgeProtector(ConstantProtector.java:38)
	at org.nd4j.jita.constant.ConstantProtector.<init>(ConstantProtector.java:31)
	at org.nd4j.jita.constant.ConstantProtector.<clinit>(ConstantProtector.java:20)
	at org.nd4j.jita.constant.ProtectedCudaConstantHandler.<clinit>(ProtectedCudaConstantHandler.java:48)
	at org.nd4j.jita.constant.CudaConstantHandler.<clinit>(CudaConstantHandler.java:17)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6327)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6258)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:207)
	at TestingQuandl.runNetwork(TestingQuandl.groovy:1097)
	at TestingQuandl.runStatic(TestingQuandl.groovy:325)
	at TestingQuandl$runStatic.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at TestingQuandl.run(TestingQuandl.groovy:110)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:585)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:632)
	at com.stolsvik.machinelearning.tools.ExploratoryGroovyLooper$_loop_closure1.doCall(ExploratoryGroovyLooper.groovy:180)
	at com.stolsvik.machinelearning.tools.ExploratoryGroovyLooper$_loop_closure1.call(ExploratoryGroovyLooper.groovy)
	at groovy.lang.Closure.run(Closure.java:495)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:51)
	at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:19)
	... 24 more
Caused by: java.lang.UnsatisfiedLinkError: no jnind4jcuda in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1004)
	at org.bytedeco.javacpp.Loader.load(Loader.java:801)
	at org.bytedeco.javacpp.Loader.load(Loader.java:708)
	at org.nd4j.nativeblas.Nd4jCuda.<clinit>(Nd4jCuda.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:763)
	at org.bytedeco.javacpp.Loader.load(Loader.java:708)
	at org.nd4j.nativeblas.Nd4jCuda$NativeOps.<clinit>(Nd4jCuda.java:67)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:29)
	... 25 more
Caused by: java.lang.UnsatisfiedLinkError: no nd4jcuda in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1004)
	at org.bytedeco.javacpp.Loader.load(Loader.java:789)
	... 35 more
```

Furthermore, in my .javacpp/cache dir, this is the contents:
```shell
endre@EndreBox2017 ~/.javacpp/cache $ d
total 24
drwxrwxr-x 3 endre endre 4096 Aug 14 01:17 cuda-8.0-1.3-linux-x86_64.jar
drwxrwxr-x 3 endre endre 4096 Aug 17 23:45 cuda-8.0-6.0-1.3-linux-x86_64.jar
drwxrwxr-x 3 endre endre 4096 Aug 14 01:17 nd4j-cuda-8.0-0.8.0-linux-x86_64.jar
drwxrwxr-x 3 endre endre 4096 Aug 17 23:45 nd4j-cuda-8.0-0.9.1-linux-x86_64.jar
drwxrwxr-x 3 endre endre 4096 Aug 12 02:48 nd4j-native-0.8.0-linux-x86_64.jar
drwxrwxr-x 3 endre endre 4096 Aug 12 02:48 openblas-0.2.19-1.3-linux-x86_64.jar
```

So, no 0.9.2-SNAPSHOT version.

**Comment by saudet** [comment]
What does your pom.xml file look like?

**Comment by treo** [comment]
In order to keep all of this together:
> Samuel Audet @saudet 01:16
> @stolsvik @raver119 when using Gradle/sbt/Ivy/etc without the -platform artifacts we need to add the platform-specific artifacts manually: https://nd4j.org/dependencies

**Comment by stolsvik** [comment]
The build.gradle looks like this:
```
    // Deep Learning 4 Java
    compile "org.deeplearning4j:deeplearning4j-core:$dl4jVersion"
    // .. the ND4J implementation: Native
    compile "org.nd4j:nd4j-native:$dl4jVersion"
    compile "org.nd4j:nd4j-native:$dl4jVersion:linux-x86_64"
    // .. and the ND4J implementation: CUDA  (since both Native and CUDA are now present, evidently GPUs will be used if available)
    compile "org.nd4j:nd4j-cuda-8.0:$dl4jVersion"
    // .. along with the DL4J-CUDA add-on, which employs specialized 'cuDNN' constructs for CNNs (and later RNNs).
    compile "org.deeplearning4j:deeplearning4j-cuda-8.0:$dl4jVersion"
    // .. along with the UI
    compile "org.deeplearning4j:deeplearning4j-ui_2.11:$dl4jVersion"
```

**Comment by stolsvik** [comment]
.. AND add *-Dplay.crypto.secret='-randomstring-randomstring-randomstring-6b56adcc-efeb-4f6b-b997-b222f3877119'* to the startup config if you have the UI server added.
