### ISSUE TITLE
ND4JIllegalStateException: op.X length != op.Y length:

### ISSUE THREAD

**Issue by MatthiasDM** [deeplearning4j/nd4j#2246]
While trying to get the next rnnTimeStep of RecurrentLayer i get the following error:

[main] INFO org.nd4j.linalg.factory.Nd4jBackend - Loaded [CpuBackend] backend
[main] INFO org.reflections.Reflections - Reflections took 2861 ms to scan 271 urls, producing 130736 keys and 144630 values 
[main] INFO org.nd4j.nativeblas.NativeOpsHolder - Number of threads used for NativeOps: 2
[main] INFO org.reflections.Reflections - Reflections took 318 ms to scan 13 urls, producing 31 keys and 227 values 
[main] INFO org.nd4j.nativeblas.Nd4jBlas - Number of threads used for BLAS: 2
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Backend used: [CPU]; OS: [Windows 10]
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Cores: [4]; Memory: [1,8GB];
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Blas vendor: [OPENBLAS]
[main] INFO org.reflections.Reflections - Reflections took 529 ms to scan 13 urls, producing 387 keys and 1538 values 
[main] INFO stock.predict.StockPricePrediction - Load model...
[main] INFO org.reflections.Reflections - Reflections took 5321 ms to scan 248 urls, producing 5177 keys and 34416 values 
[main] INFO org.deeplearning4j.nn.multilayer.MultiLayerNetwork - Starting MultiLayerNetwork with WorkspaceModes set to [training: NONE; inference: SEPARATE]
[main] INFO stock.predict.StockPricePrediction - Testing...
Exception in thread "main" org.nd4j.linalg.exception.ND4JIllegalStateException: op.X length should be equal to op.Y length: [[2, 1, 5, 1, 1, 0, 1, 99]] != [[2, 1, 1, 1, 1, 0, 1, 97]]
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:578)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:100)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.muli(BaseNDArray.java:1640)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.muli(BaseNDArray.java:3098)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mul(BaseNDArray.java:2865)
	at stock.predict.StockPricePrediction.test1(StockPricePrediction.java:102)
	at Main.main(Main.java:17)

My version of nd4j is 0.9.1. I know there is one other case here with this same error but i haven't been able to fix mine with it.

Thank you

**Comment by AlexDBlack** [comment]
Based on that stack trace, it has nothing to do with rnnTimeStep:
```
at org.nd4j.linalg.api.ndarray.BaseNDArray.mul(BaseNDArray.java:2865)
at stock.predict.StockPricePrediction.test1(StockPricePrediction.java:102)
at Main.main(Main.java:17)
```

i.e., it's in your code - you are trying to do x.mul(y), where x has shape [1,5] and y has shape [1,2].

**Comment by MatthiasDM** [comment]
Thank you, solved the problem. I hadn't trained the network properly.
