### ISSUE TITLE
IntelMkl: undefined symbol: mkl_blas_dgemm_blk_info_bdz

### ISSUE THREAD

**Issue by horschi** [deeplearning4j/nd4j#2261]
#### Issue Description

I was trying to get the dl4j examples running, but I always get the following native lib issue:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopenblas in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:976)
	at org.bytedeco.javacpp.Loader.load(Loader.java:777)
	at org.bytedeco.javacpp.Loader.load(Loader.java:684)
	at org.bytedeco.javacpp.openblas.<clinit>(openblas.java:10)
	at org.nd4j.linalg.cpu.nativecpu.blas.CpuBlas.setMaxThreads(CpuBlas.java:117)
	at org.nd4j.nativeblas.Nd4jBlas.<init>(Nd4jBlas.java:35)
	at org.nd4j.linalg.cpu.nativecpu.blas.CpuBlas.<init>(CpuBlas.java:12)
	at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.createBlas(CpuNDArrayFactory.java:89)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.blas(BaseNDArrayFactory.java:67)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.getEnvironmentInformation(NativeOpExecutioner.java:1176)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.printEnvironmentInformation(DefaultOpExecutioner.java:562)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6210)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6087)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:201)
	at dl4jTest.XorExample.main(XorExample.java:59)
Caused by: java.lang.UnsatisfiedLinkError: no mkl_intel_thread in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:976)
	at org.bytedeco.javacpp.Loader.load(Loader.java:765)
	... 13 more
Caused by: java.lang.UnsatisfiedLinkError: /opt/intel/compilers_and_libraries_2017.5.239/linux/mkl/lib/intel64_lin/libmkl_intel_thread.so: /opt/intel/compilers_and_libraries_2017.5.239/linux/mkl/lib/intel64_lin/libmkl_intel_thread.so: undefined symbol: mkl_blas_dgemm_blk_info_bdz
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:956)
	... 14 more
```

I have openblas in my systems library path, which I compiled myself.
And I downloaded Intel mkl. I tried both the 2018 version and 2017u4.

#### Version Information

* Deeplearning4j: 0.9.1
* ND4j: 0.9.1
* Linux 4.4.0-98-generic #121-Ubuntu SMP x86_64 GNU/Linux, Linux Mint 18 (basically Ubuntu 16.04)
* I am not using CUDA
* I do not have anaconda installed
* OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
* OpenBlas: tried branch develop and optimized_for_deeplearning with the same results
* Intel mkl: tried the 2018 version and 2017 u4

#### Contributing

If you want I can upload my pom or share information about the native libraries on my machine. Let me know what you are interested in. I can also make changes and test.

To me it almost looks like IntelMKL is broken. I read somewhere that the missing symbol is defined in libiomp5mt.so or libiomp5md.so, which I do not have in my lib folders.

**Comment by horschi** [comment]
In the meantime I wiped and reinstalled my system. I only installed OpenBlas and added it to my systems lib path (I had to symlink it to /usr/lib, configuring openBlas via /etc/ld.so.conf did not work for me).
It seems to load OpenBlas now, but now I get:

`Loading class org.nd4j.nativeblas.Nd4jCpu
Loading class org.nd4j.nativeblas.Nd4jCpu
Loading /home/horschi/.javacpp/cache/nd4j-native-0.9.1-linux-x86_64.jar/org/nd4j/nativeblas/linux-x86_64/libgomp.so.1
Loading /home/horschi/.javacpp/cache/nd4j-native-0.9.1-linux-x86_64.jar/org/nd4j/nativeblas/linux-x86_64/libnd4jcpu.so
Loading /home/horschi/.javacpp/cache/nd4j-native-0.9.1-linux-x86_64.jar/org/nd4j/nativeblas/linux-x86_64/libjnind4jcpu.so
Registering org.nd4j.nativeblas.Nd4jCpu$NativeOps[address=0x7f14508f7310,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7f14508f7310,deallocatorAddress=0x7f14307f2270]]
Loading class org.bytedeco.javacpp.openblas
Loading library iomp5
Failed to load for iomp5: java.lang.UnsatisfiedLinkError: no iomp5 in java.library.path
Loading library mkl_avx
Failed to load for mkl_avx: java.lang.UnsatisfiedLinkError: no mkl_avx in java.library.path
Loading library mkl_avx2
Failed to load for mkl_avx2: java.lang.UnsatisfiedLinkError: no mkl_avx2 in java.library.path
Loading library mkl_avx512_mic
Failed to load for mkl_avx512_mic: java.lang.UnsatisfiedLinkError: no mkl_avx512_mic in java.library.path
Loading library mkl_def
Failed to load for mkl_def: java.lang.UnsatisfiedLinkError: no mkl_def in java.library.path
Loading library mkl_mc3
Failed to load for mkl_mc3: java.lang.UnsatisfiedLinkError: no mkl_mc3 in java.library.path
Loading library mkl_core
Failed to load for mkl_core: java.lang.UnsatisfiedLinkError: no mkl_core in java.library.path
Loading library mkl_gnu_thread
Failed to load for mkl_gnu_thread: java.lang.UnsatisfiedLinkError: no mkl_gnu_thread in java.library.path
Loading library mkl_intel_lp64
Failed to load for mkl_intel_lp64: java.lang.UnsatisfiedLinkError: no mkl_intel_lp64 in java.library.path
Loading library mkl_intel_thread
Failed to load for mkl_intel_thread: java.lang.UnsatisfiedLinkError: no mkl_intel_thread in java.library.path
Loading library mkl_rt
Failed to load for mkl_rt: java.lang.UnsatisfiedLinkError: no mkl_rt in java.library.path
Loading library mkl_rt
Failed to load for mkl_rt#openblas@.0: java.lang.UnsatisfiedLinkError: no mkl_rt in java.library.path
Loading /lib/x86_64-linux-gnu/libgcc_s.so.1
Loading /usr/lib/x86_64-linux-gnu/libquadmath.so.0
Loading /usr/lib/x86_64-linux-gnu/libgfortran.so.3
Loading /usr/lib/libopenblas.so.0
Loading library jniopenblas
Failed to load for jniopenblas: java.lang.UnsatisfiedLinkError: no jniopenblas in java.library.path
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopenblas in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:976)
	at org.bytedeco.javacpp.Loader.load(Loader.java:777)
	at org.bytedeco.javacpp.Loader.load(Loader.java:684)
	at org.bytedeco.javacpp.openblas.<clinit>(openblas.java:10)
	at org.nd4j.linalg.cpu.nativecpu.blas.CpuBlas.setMaxThreads(CpuBlas.java:117)
	at org.nd4j.nativeblas.Nd4jBlas.<init>(Nd4jBlas.java:35)
	at org.nd4j.linalg.cpu.nativecpu.blas.CpuBlas.<init>(CpuBlas.java:12)
	at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.createBlas(CpuNDArrayFactory.java:89)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.blas(BaseNDArrayFactory.java:67)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.getEnvironmentInformation(NativeOpExecutioner.java:1176)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.printEnvironmentInformation(DefaultOpExecutioner.java:562)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6210)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6087)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:201)
	at dl4jTest.XorExample.main(XorExample.java:60)
Caused by: java.lang.UnsatisfiedLinkError: no mkl_rt in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:976)
	at org.bytedeco.javacpp.Loader.load(Loader.java:765)
	... 13 more
`

Its looking for a "mkl_rt" library, which I can only find in Intel MKL. I am confused, as I was told that Intel MKL is optional.

**Comment by horschi** [comment]
@saudet, @raver119: I am now getting:
`Caused by: java.lang.UnsatisfiedLinkError: no mkl_rt in java.library.path`

Raver119 told me that Intel MKL is optional on gitter. Assuming this information is correct, which I assume it is, why does it want a libmkl_rt? Does this seem right?

**Comment by treo** [comment]
@horschi can you also post your pom.xml?

**Comment by horschi** [comment]
@treo : These are all the dependencies from my pom:

`		<dependency>
			<groupId>org.deeplearning4j</groupId>
			<artifactId>deeplearning4j-core</artifactId>
			<version>0.9.1</version>
		</dependency>
		<dependency>
			<groupId>org.nd4j</groupId>
			<artifactId>nd4j-native</artifactId>
			<version>0.9.1</version>
		</dependency>
		<dependency>
			<groupId>org.nd4j</groupId>
			<artifactId>nd4j-native-platform</artifactId>
			<version>0.9.1</version>
			<exclusions>
				<exclusion>  
				    <groupId>org.bytedeco.javacpp-presets</groupId>
				    <artifactId>openblas</artifactId>
				</exclusion>
			</exclusions> 
		</dependency>
		<dependency>
			<groupId>org.bytedeco.javacpp-presets</groupId>
			<artifactId>openblas</artifactId>
			<version>0.2.20-1.3</version>
		</dependency>
		<dependency>
		    <groupId>org.bytedeco.javacpp-presets</groupId>
		    <artifactId>openblas-platform</artifactId>
		    <version>0.2.20-1.3</version>
		</dependency>
		
		<dependency>
		    <groupId>org.datavec</groupId>
		    <artifactId>datavec-api</artifactId>
		    <version>0.9.1</version>
		</dependency>`

I changed the version to 0.2.20 of the openblas dependency, because the default version reports as a corrupted jar.

**Comment by treo** [comment]
@horschi 
usually you don't have to explicitly add openblas as a dependency.

As a sanity check, can you try running this minimal example? https://github.com/treo/dl4j-minimal-example

**Comment by horschi** [comment]
@treo: Sure I can. It gives me the same error: Caused by: java.lang.UnsatisfiedLinkError: no mkl_rt in java.library.path


I explicitly added openblas because if I dont I get the following:
```
[ERROR] error reading /home/horschi/.m2/repository/org/bytedeco/javacpp-presets/openblas/0.2.19-1.3/openblas-0.2.19-1.3-linux-x86.jar; invalid LOC header (bad signature)
[ERROR] error reading /home/horschi/.m2/repository/org/bytedeco/javacpp-presets/openblas/0.2.19-1.3/openblas-0.2.19-1.3-linux-x86_64.jar; invalid LOC header (bad signature)
[ERROR] error reading /home/horschi/.m2/repository/org/bytedeco/javacpp-presets/openblas/0.2.19-1.3/openblas-0.2.19-1.3-linux-armhf.jar; invalid LOC header (bad signature)
[ERROR] error reading /home/horschi/.m2/repository/org/bytedeco/javacpp-presets/openblas/0.2.19-1.3/openblas-0.2.19-1.3-linux-ppc64le.jar; invalid LOC header (bad signature)
[ERROR] error reading /home/horschi/.m2/repository/org/bytedeco/javacpp-presets/openblas/0.2.19-1.3/openblas-0.2.19-1.3-macosx-x86_64.jar; invalid LOC header (bad signature)
```
With 0.2.20 I dont get this. But with both versions, it fails with "no mkl_rt".

**Comment by treo** [comment]
> I only installed OpenBlas and added it to my systems lib path (I had to symlink it to /usr/lib, configuring openBlas via /etc/ld.so.conf did not work for me).

Why exactly did you actively install it? DL4J Provides you with a packaged version that is downloaded and loaded automatically. 

Going with the log, it looks like nd4j can't load your installed version.

Whats the output of `ldd /usr/lib/libopenblas.so.0` ?

**Comment by horschi** [comment]
Hi Treo,

it will tell my that openblas is missing, if I do not have it in my lib path:
```
Loading class org.bytedeco.javacpp.openblas
Loading library iomp5
Failed to load for iomp5: java.lang.UnsatisfiedLinkError: no iomp5 in java.library.path
Loading library mkl_avx
Failed to load for mkl_avx: java.lang.UnsatisfiedLinkError: no mkl_avx in java.library.path
Loading library mkl_avx2
Failed to load for mkl_avx2: java.lang.UnsatisfiedLinkError: no mkl_avx2 in java.library.path
Loading library mkl_avx512_mic
Failed to load for mkl_avx512_mic: java.lang.UnsatisfiedLinkError: no mkl_avx512_mic in java.library.path
Loading library mkl_def
Failed to load for mkl_def: java.lang.UnsatisfiedLinkError: no mkl_def in java.library.path
Loading library mkl_mc3
Failed to load for mkl_mc3: java.lang.UnsatisfiedLinkError: no mkl_mc3 in java.library.path
Loading library mkl_core
Failed to load for mkl_core: java.lang.UnsatisfiedLinkError: no mkl_core in java.library.path
Loading library mkl_gnu_thread
Failed to load for mkl_gnu_thread: java.lang.UnsatisfiedLinkError: no mkl_gnu_thread in java.library.path
Loading library mkl_intel_lp64
Failed to load for mkl_intel_lp64: java.lang.UnsatisfiedLinkError: no mkl_intel_lp64 in java.library.path
Loading library mkl_intel_thread
Failed to load for mkl_intel_thread: java.lang.UnsatisfiedLinkError: no mkl_intel_thread in java.library.path
Loading library mkl_rt
Failed to load for mkl_rt: java.lang.UnsatisfiedLinkError: no mkl_rt in java.library.path
Loading library mkl_rt
Failed to load for mkl_rt#openblas@.0: java.lang.UnsatisfiedLinkError: no mkl_rt in java.library.path
Loading library gcc_s
Failed to load for gcc_s@.1: java.lang.UnsatisfiedLinkError: no gcc_s in java.library.path
Loading library quadmath
Failed to load for quadmath@.0: java.lang.UnsatisfiedLinkError: no quadmath in java.library.path
Loading library gfortran
Failed to load for gfortran@.3: java.lang.UnsatisfiedLinkError: no gfortran in java.library.path
Loading library openblas
Failed to load for openblas@.0: java.lang.UnsatisfiedLinkError: no openblas in java.library.path
Loading library jniopenblas
Failed to load for jniopenblas: java.lang.UnsatisfiedLinkError: no jniopenblas in java.library.path
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopenblas in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:976)
	at org.bytedeco.javacpp.Loader.load(Loader.java:777)
	at org.bytedeco.javacpp.Loader.load(Loader.java:684)
	at org.bytedeco.javacpp.openblas.<clinit>(openblas.java:10)
	at org.nd4j.linalg.cpu.nativecpu.blas.CpuBlas.setMaxThreads(CpuBlas.java:117)
	at org.nd4j.nativeblas.Nd4jBlas.<init>(Nd4jBlas.java:35)
	at org.nd4j.linalg.cpu.nativecpu.blas.CpuBlas.<init>(CpuBlas.java:12)
	at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.createBlas(CpuNDArrayFactory.java:89)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.blas(BaseNDArrayFactory.java:67)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.getEnvironmentInformation(NativeOpExecutioner.java:1176)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.printEnvironmentInformation(DefaultOpExecutioner.java:562)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6210)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6087)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:201)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertWritables(RecordReaderMultiDataSetIterator.java:377)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertFeaturesOrLabels(RecordReaderMultiDataSetIterator.java:271)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.nextMultiDataSet(RecordReaderMultiDataSetIterator.java:234)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.next(RecordReaderMultiDataSetIterator.java:177)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:306)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:393)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:51)
	at tech.dubs.App.main(App.java:51)
Caused by: java.lang.UnsatisfiedLinkError: no openblas in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:976)
	at org.bytedeco.javacpp.Loader.load(Loader.java:765)
	... 20 more
```

The output of ldd on libopenblas is:
```
horschi@erazer ~ $  ldd /usr/lib/libopenblas.so.0
	linux-vdso.so.1 =>  (0x00007ffcf5fc9000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fdf59b5a000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fdf5993d000)
	libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007fdf59611000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdf59247000)
	/lib64/ld-linux-x86-64.so.2 (0x000055e3567e6000)
	libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007fdf59008000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fdf58df1000)
```

Where should that packaged openBlas be? Should it be extracted to ~/.javacpp/ ?
```
horschi@erazer ~/.javacpp $ find .
.
./cache
./cache/.lock
./cache/nd4j-native-0.9.1-linux-x86_64.jar
./cache/nd4j-native-0.9.1-linux-x86_64.jar/org
./cache/nd4j-native-0.9.1-linux-x86_64.jar/org/nd4j
./cache/nd4j-native-0.9.1-linux-x86_64.jar/org/nd4j/nativeblas
./cache/nd4j-native-0.9.1-linux-x86_64.jar/org/nd4j/nativeblas/linux-x86_64
./cache/nd4j-native-0.9.1-linux-x86_64.jar/org/nd4j/nativeblas/linux-x86_64/libnd4jcpu.so
./cache/nd4j-native-0.9.1-linux-x86_64.jar/org/nd4j/nativeblas/linux-x86_64/libgomp.so
./cache/nd4j-native-0.9.1-linux-x86_64.jar/org/nd4j/nativeblas/linux-x86_64/libjnind4jcpu.so
./cache/nd4j-native-0.9.1-linux-x86_64.jar/org/nd4j/nativeblas/linux-x86_64/libgomp.so.1
horschi@erazer ~/.javacpp $ 
```

**Comment by saudet** [comment]
Yes, could you post your pom.xml as is please?

**Comment by treo** [comment]
@horschi can you also try clearing your .m2 folder and the javacpp cache?

I just tried the same minimal example on a freshly installed Linux (Ubuntu 17.04 in that case) and installed just openjdk-8-jdk and maven via apt. And the examples run just fine with that.

**Comment by horschi** [comment]
@saudet: I am currently testing with the minimal-example that Treo linked me. I did not make any changes to that pom.

@treo: I cannot believe it, removing my .m2 did work. Now its extracting libopenblas.so to .javacpp as it should.

I think this is the error:
```
horschi@erazer ~/.m2 $ md5sum ./repository/org/bytedeco/javacpp-presets/openblas/0.2.19-1.3/openblas-0.2.19-1.3-linux-x86_64.jar  ./repository.bak/org/bytedeco/javacpp-presets/openblas/0.2.19-1.3/openblas-0.2.19-1.3-linux-x86_64.jar
f8538f4dfd4c81bccfd54a88c9fc249d  ./repository/org/bytedeco/javacpp-presets/openblas/0.2.19-1.3/openblas-0.2.19-1.3-linux-x86_64.jar
24340d2241567456dd180dedcd678b69  ./repository.bak/org/bytedeco/javacpp-presets/openblas/0.2.19-1.3/openblas-0.2.19-1.3-linux-x86_64.jar
horschi@erazer ~/.m2 $ 
```
(repository.bak is the old(broken) repo)


And when I try to extract the old openblas.jar, then I get:
```
warning [/home/horschi/.m2/repository.bak/org/bytedeco/javacpp-presets/openblas/0.2.19-1.3/openblas-0.2.19-1.3-linux-x86_64.jar]:  3900102 extra bytes at beginning or within zipfile
  (attempting to process anyway)
file #1:  bad zipfile offset (local header sig):  3900102
  (attempting to re-compensate)
```
So it was a corrupt jar file all the time. 

I apologize for the inconvenience I caused. The error made me believe I had to install openblas myself. I hope at least this error is documented well enough now, that it will help someone else in the future. :-)

**Comment by saudet** [comment]
Strange, Maven is supposed to check for the integrity of the artifacts in its cache. That should maybe be reported upstream... In any case, thanks for the feedback!
