### ISSUE TITLE
Failed to `getFloat(2)` from an INDArray 2 x 2 with illegalArgumentException

### ISSUE THREAD

**Issue by taisukeoe** [deeplearning4j/nd4j#228]
In current latest version in master branch, INDArray doesn't return values in each index properly as follows.

```scala
scala> import org.nd4j.linalg.factory.Nd4j
import org.nd4j.linalg.factory.Nd4j

scala> Nd4j.create(Array(1f,2f,3f,4f),Array(2,2))
res7: org.nd4j.linalg.api.ndarray.INDArray = 
[[1.0, 2.0]
 [3.0, 4.0]]

scala> res7.shape
res8: Array[Int] = Array(2, 2)

scala> res7.getFloat(0)
res9: Float = 1.0

//This should return 2.0.
scala> res7.getFloat(1)
res10: Float = 3.0

//This should return 3.0.
scala> res7.getFloat(2)
java.lang.IllegalArgumentException: Illegal index 4 derived from 2 with offset of 0 and stride of 2
	at org.nd4j.linalg.api.ndarray.BaseNDArray.linearIndex(BaseNDArray.java:2972)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:3421)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getFloat(BaseNDArray.java:3434)
	at .<init>(<console>:13)
	at .<clinit>(<console>)
	at .<init>(<console>:7)
	at .<clinit>(<console>)
	at $print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:734)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:983)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:604)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:568)
	at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:760)
	at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:805)
	at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:717)
	at scala.tools.nsc.interpreter.ILoop.processLine$1(ILoop.scala:581)
	at scala.tools.nsc.interpreter.ILoop.innerLoop$1(ILoop.scala:588)
	at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:591)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:882)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:837)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:837)
	at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
	at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:837)
	at scala.tools.nsc.interpreter.ILoop.main(ILoop.scala:904)
	at xsbt.ConsoleInterface.run(ConsoleInterface.scala:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
	at sbt.compiler.AnalyzingCompiler.console(AnalyzingCompiler.scala:76)
	at sbt.Console.sbt$Console$$console0$1(Console.scala:22)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply$mcV$sp(Console.scala:23)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23)
	at sbt.Logger$$anon$4.apply(Logger.scala:85)
	at sbt.TrapExit$App.run(TrapExit.scala:248)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by taisukeoe** [comment]
As long as I checked:

This bug happens due to a change in `nd4j-jblas/src/main/resources/nd4j-jblas.properties` in:
https://github.com/deeplearning4j/nd4j/commit/e1cca08476534a9d0f4baa77be1d67ece2691c42

So it seems to be a bug in `BaseNDArray#linearView(int i)` if its ndarray is in 'c' ordering.

```scala
//res45-47 repressions should return 3.0. 
scala> Nd4j.factory.setOrder('c')

scala> Nd4j.create(Array(1f,2f,3f,4f),Array(2,2),'f').getFloat(1)
res45: Float = 3.0

scala> Nd4j.create(Array(1f,2f,3f,4f),Array(2,2),'c').getFloat(1)
res46: Float = 3.0

scala> Nd4j.create(Array(1f,2f,3f,4f),Array(2,2)).getFloat(1)
res47: Float = 3.0


//Fortran ordering works fine.
scala> Nd4j.factory.setOrder('f')

scala> Nd4j.create(Array(1f,2f,3f,4f),Array(2,2),'f').getFloat(1)
res50: Float = 2.0

scala> Nd4j.create(Array(1f,2f,3f,4f),Array(2,2),'c').getFloat(1)
res51: Float = 2.0

scala> Nd4j.create(Array(1f,2f,3f,4f),Array(2,2)).getFloat(1)
res52: Float = 2.0
```

Of note, `Nd4j#create(int[] data, int[] shape, char ordering)` also ignores ordering in argument as shown above.

**Comment by taisukeoe** [comment]
I've just prepared workarounded nd4j fork at my repo to avoid this issue until it's fixed.

https://github.com/taisukeoe/nd4j/tree/workarounds

**Comment by taisukeoe** [comment]
@agibsonccc 
Is there any detailed spec about `BaseNDArray#linearView`?
While I'm working to fix this, I couldn't find enough document about how it should behave in Fortran ordering and C ordering.

**Comment by agibsonccc** [comment]
So linearView is a static row by row element wise operation. You can't do getFloat(2) on a matrix. You'd have to do linearView().getFloat(2) which will give you back a 1 x length vector. If it's c ordering it creates a view. If it's fortran order it creates a LinewViewNDArray which is a forced row by row view of the ndarray.  Come on gitter if you'd like a better explanation:

https://gitter.im/deeplearning4j/deeplearning4j

**Comment by taisukeoe** [comment]
@agibsonccc 
Thanks for enlightening me.
Since current nd4j behavior is right and nd4s has to follow it, I've sent a PR to fix nd4s.
https://github.com/deeplearning4j/nd4s/pull/28

Separately, let me send a PR to nd4j to fix ignored ordering field
