### ISSUE TITLE
UnsatisfiedLinkError: no jniopenblas in java.library.path with deeplearning4j

### ISSUE THREAD

**Issue by achatterjee104** [deeplearning4j/nd4j#2283]
#### Issue Description

I am new with this deeplearning4j. I am getting the below error while running dl4j examples. I followed step by step guide as defined in the website and did all the configuration for nd4j as well (refer to nd4j getting started material). Below is the stacktrace,

o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 2
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopenblas in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:976)
	at org.bytedeco.javacpp.Loader.load(Loader.java:777)
	at org.bytedeco.javacpp.Loader.load(Loader.java:684)
	at org.bytedeco.javacpp.openblas.<clinit>(openblas.java:10)
	at org.nd4j.linalg.cpu.nativecpu.blas.CpuBlas.setMaxThreads(CpuBlas.java:117)
	at org.nd4j.nativeblas.Nd4jBlas.<init>(Nd4jBlas.java:35)
	at org.nd4j.linalg.cpu.nativecpu.blas.CpuBlas.<init>(CpuBlas.java:12)
	at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.createBlas(CpuNDArrayFactory.java:89)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.blas(BaseNDArrayFactory.java:67)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.getEnvironmentInformation(NativeOpExecutioner.java:1176)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.printEnvironmentInformation(DefaultOpExecutioner.java:562)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6210)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6087)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:201)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertWritables(RecordReaderMultiDataSetIterator.java:377)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertFeaturesOrLabels(RecordReaderMultiDataSetIterator.java:271)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.nextMultiDataSet(RecordReaderMultiDataSetIterator.java:234)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.next(RecordReaderMultiDataSetIterator.java:177)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:306)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:393)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:51)
	at org.deeplearning4j.examples.dataexamples.CSVExample.main(CSVExample.java:52)
Caused by: java.lang.UnsatisfiedLinkError: no gfortran in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:976)
	at org.bytedeco.javacpp.Loader.load(Loader.java:765)
	... 20 more

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version : 0.9.1
* platform information (OS, etc) : **Linux Mint** [4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux]
* CUDA version : NA
* NVIDIA driver version : dont know

I also want to mention that 

- to configure OpenBlas i did execute script from "http://pastebin.com/F0Rv2uEk" and then followed the steps as mentioned in nd4j guide. 

- I also have added gfortran and libblas.so.3 and liblapack.so.3 in /usr/lib, usr/bin and my project folder mypath/deeplearning.dl4j/script/OpenBLAS (where i built the openblas from git). 

- I can also see my java.library.path includes "usr/lib" (though i also tried by explicitly adding all of the above folders using System.setProperty())

Is there any problem from my side?

**Comment by saudet** [comment]
You shouldn't need to build OpenBLAS or anything. It's saying it can't find
libgfortran.so. Could you post the content of your ~/.javacpp/cache
directory?

**Comment by raver119** [comment]
Closed due to inactivity.
