### ISSUE TITLE
TensorFlowImport.importGraph throws error with inferred shapes

### ISSUE THREAD

**Issue by eraly** [deeplearning4j/nd4j#2290]
TF uses -1 to imply that the size of the array in that dimension should be inferred upon loading.

```
o.n.a.e.NativeGraphExecutioner - Graph inputs: [input, bias]
o.n.a.e.NativeGraphExecutioner - Input varId: -1; varName: input;

org.nd4j.linalg.exception.ND4JIllegalStateException: Invalid shape: Requested INDArray shape [-1, 4] contains dimension size values < 1 (all dimensions must be 1 or more)
        at org.nd4j.linalg.factory.Nd4j.checkShapeValues(Nd4j.java:5059)
	at org.nd4j.linalg.factory.Nd4j.createUninitialized(Nd4j.java:5089)
	at org.nd4j.weightinit.impl.ZeroInitScheme.doCreate(ZeroInitScheme.java:22)
	at org.nd4j.weightinit.BaseWeightInitScheme.create(BaseWeightInitScheme.java:34)
	at org.nd4j.autodiff.samediff.SDVariable.getArr(SDVariable.java:141)
	at org.nd4j.autodiff.execution.NativeGraphExecutioner.convertToFlatBuffers(NativeGraphExecutioner.java:85)
	at org.nd4j.autodiff.execution.NativeGraphExecutioner.executeGraph(NativeGraphExecutioner.java:218)
	at org.nd4j.autodiff.execution.NativeGraphExecutioner.executeGraph(NativeGraphExecutioner.java:60)
	at org.nd4j.imports.TFGraphTestAll.testSingle(TFGraphTestAll.java:73)
	at org.nd4j.imports.TFGraphTestSingle.testOne(TFGraphTestSingle.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        ....
```

I have a simple example checked in under the eralyONNX branch. Run TFGraphTestSingle.testOne to duplicate.

All relevant files for this are under:
nd4j-backends/nd4j-tests/src/test/resources/tf_graphs/examples/bias_add

Link to graph in txt:
https://github.com/deeplearning4j/nd4j/blob/eralyONNX/nd4j-backends/nd4j-tests/src/test/resources/tf_graphs/examples/bias_add/model.txt#L15

**Comment by raver119** [comment]
Should be fixed long ago.
