### ISSUE TITLE
DL4J ModelSerializer: broken by ILossFunction JSON issues

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2291]
All of these fail currently: https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/test/java/org/deeplearning4j/util/ModelSerializerTest.java

Why?
Loss functions now extend DifferentiableFunction...
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/lossfunctions/impl/LossL2.java#L36

which has a whole bunch of stuff we don't want included in the DL4J JSON representation...
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/autodiff/functions/DifferentialFunction.java

```
java.lang.RuntimeException: org.nd4j.shade.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: org.deeplearning4j.nn.conf.ComputationGraphConfiguration["vertices"]->java.util.LinkedHashMap["out"]->org.deeplearning4j.nn.conf.graph.LayerVertex["layerConf"]->org.deeplearning4j.nn.conf.NeuralNetConfiguration["layer"]->org.deeplearning4j.nn.conf.layers.OutputLayer["lossFn"]->org.nd4j.linalg.lossfunctions.impl.LossMCXENT["outputVertexIds"])

	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration.toJson(ComputationGraphConfiguration.java:145)
	at org.deeplearning4j.util.ModelSerializer.writeModel(ModelSerializer.java:88)
	at org.deeplearning4j.util.ModelSerializer.writeModel(ModelSerializer.java:54)
	at org.deeplearning4j.util.ModelSerializerTest.testRestoreUnsavedNormalizerFromInputStream(ModelSerializerTest.java:225)
...
Caused by: org.nd4j.shade.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: org.deeplearning4j.nn.conf.ComputationGraphConfiguration["vertices"]->java.util.LinkedHashMap["out"]->org.deeplearning4j.nn.conf.graph.LayerVertex["layerConf"]->org.deeplearning4j.nn.conf.NeuralNetConfiguration["layer"]->org.deeplearning4j.nn.conf.layers.OutputLayer["lossFn"]->org.nd4j.linalg.lossfunctions.impl.LossMCXENT["outputVertexIds"])
```

```
java.lang.RuntimeException: org.nd4j.shade.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: org.deeplearning4j.nn.conf.MultiLayerConfiguration["confs"]->java.util.ArrayList[1]->org.deeplearning4j.nn.conf.NeuralNetConfiguration["layer"]->org.deeplearning4j.nn.conf.layers.OutputLayer["lossFn"]->org.nd4j.linalg.lossfunctions.impl.LossMSE["outputVertexIds"])

	at org.deeplearning4j.nn.conf.MultiLayerConfiguration.toJson(MultiLayerConfiguration.java:128)
	at org.deeplearning4j.util.ModelSerializer.writeModel(ModelSerializer.java:86)
	at org.deeplearning4j.util.ModelSerializer.writeModel(ModelSerializer.java:54)
...
Caused by: org.nd4j.shade.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: org.deeplearning4j.nn.conf.MultiLayerConfiguration["confs"]->java.util.ArrayList[1]->org.deeplearning4j.nn.conf.NeuralNetConfiguration["layer"]->org.deeplearning4j.nn.conf.layers.OutputLayer["lossFn"]->org.nd4j.linalg.lossfunctions.impl.LossMSE["outputVertexIds"])
```

**Comment by agibsonccc** [comment]
Fixed. https://github.com/deeplearning4j/nd4j/pull/2292
