### ISSUE TITLE
TF graph example with multiple outs import error

### ISSUE THREAD

**Issue by eraly** [deeplearning4j/nd4j#2366]
Python relevant stuff:

in0 = tf.placeholder("float", [2, 3, 4, 5], name="input_0")
unstacked = tf.unstack(in0, axis=-2)
unstack1 = unstacked[0]
unstack2 = unstacked[1]  # 2x3x5 now
n1 = unstack1 + tf.Variable(tf.zeros([2, 3, 5]))
n2 = unstack2
output = tf.stack([n1,n2,unstacked[2],unstacked[3]], axis=-4,name="output")

Checked in under "node_multiple_out" in test resources. 

Also noticed that when the output of a node is a list like with unstacked. the tensor name "unstack" with no number implies the first element in the list i.e. it is implied that this is unstack:0

Trying to import gives:

```
java.lang.RuntimeException: org.nd4j.linalg.exception.ND4JIllegalStateException: Illegal number of arguments imported 4 with function args being resolved to 2

	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.mapNodeType(TFGraphMapper.java:393)
	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.mapNodeType(TFGraphMapper.java:32)
	at org.nd4j.imports.graphmapper.BaseGraphMapper.importGraph(BaseGraphMapper.java:207)
	at org.nd4j.imports.graphmapper.BaseGraphMapper.importGraph(BaseGraphMapper.java:67)
	at org.nd4j.imports.TFGraphTestAllHelper.getGraphAfterExec(TFGraphTestAllHelper.java:137)
	at org.nd4j.imports.TFGraphTestAllHelper.checkOnlyOutput(TFGraphTestAllHelper.java:96)
	at org.nd4j.imports.TFGraphTestList.testOutputOnly(TFGraphTestList.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: org.nd4j.linalg.exception.ND4JIllegalStateException: Illegal number of arguments imported 4 with function args being resolved to 2
	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.mapNodeType(TFGraphMapper.java:385)
	... 41 more
```

**Comment by raver119** [comment]
Here's problem node:

```
node {
  name: "output"
  op: "Pack"
  input: "add"
  input: "unstack:1"
  input: "unstack:2"
  input: "unstack:3"
  attr {
    key: "N"
    value {
      i: 4
    }
  }
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "axis"
    value {
      i: -4
    }
  }
}
```

Problem is on Java side:

https://github.com/deeplearning4j/nd4j/blob/8b50467169d6c101dd61369837b45207eb416319/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/imports/graphmapper/tf/TFGraphMapper.java#L343

In this code `unstack:1`, `unstack:2`, `unstack:3` turn into the same `unstack` node, and output index is missed. Then, duplicates are removed, and we'll have only 2 outputs left. And that's causing exception.

**Comment by raver119** [comment]
Should be fixed long ago.
