### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: org.nd4j.Nd4jRegistrator

### ISSUE THREAD

**Issue by alg-jmx** [deeplearning4j/nd4j#2379]
I want to submit my jar on spark cluster using yarn , but get an error and my pom.xml like this:
[https://gist.github.com/alg-jmx/74d926432ae554407ccdbd72e74af1f9](https://gist.github.com/alg-jmx/74d926432ae554407ccdbd72e74af1f9)
I set sparkConf like this, using kryo serializer:
`val spark = SparkSession.builder()
      //.master("local[6]")
      .appName("test")
      .config("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
      .config("spark.kryo.registrator", "org.nd4j.Nd4jRegistrator")
      .getOrCreate()`

**Comment by AlexDBlack** [comment]
The config and (subset of) the pom file looks fine to me. My first guess would be how you are building the uber-jar. Double check that it's actually present in the JAR that you are submitting.

**Comment by alg-jmx** [comment]
I have checked my JAR that I submit, the org.nd4j.Nd4jRegistrator actually in it.
![image](https://user-images.githubusercontent.com/11658913/34034062-ea7536f0-e1b7-11e7-9c0e-8863b600e727.png)

**Comment by saudet** [comment]
Is `nd4j-native.properties` also there somewhere?

**Comment by alg-jmx** [comment]
nd4j-native.properties is still there, but my project is based on scala

**Comment by AlexDBlack** [comment]
Yeah, that looks fine - and again, that should be all you need. So let's confirm that it's *actually* present on the classpath at runtime - maybe try a ```Class.forName("org.nd4j.Nd4jRegistrator")``` (on the driver and ideally on the executors too, via a map function) and see if you get a NoClassDefFoundException.

And if that's OK, I'm not sure what could be up (something weird with class loading on the cluster?)

**Comment by CStrue** [comment]
got the same issue ... did you solve this?

**Comment by AlexDBlack** [comment]
@CStrue did you check the same things that I asked @alg-jmx ?
i.e., have you confirmed it's (a) in the JAR, and (b) available on the classpath (via Class.forName)?

**Comment by CStrue** [comment]
@AlexDBlack looks like when I use the minimizeJar option of shaded plugin that it removes the ND4JRegistrator class

Removing the option <minimizeJar>true</minimizeJar> helps and leads to NPE with AnalyzeSpark.analyzeQuality() method in Datavec. This might be some clusterproblem (not sure - needs further analysis)
 
18/01/19 23:46:43 WARN Reflections: could not create Dir using jarFile from url file:<hadoop_installation_path>/hadoop/lib/hadoop-lzo-0.6.0.2.5.3.0-37.jar. skipping.
java.lang.NullPointerException
	at java.util.zip.ZipFile.<init>(ZipFile.java:208)
	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:130)
	at org.reflections.vfs.Vfs$DefaultUrlTypes$1.createDir(Vfs.java:212)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:99)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:91)
	at org.reflections.Reflections.scan(Reflections.java:237)
	at org.reflections.Reflections.scan(Reflections.java:204)
	at org.reflections.Reflections.<init>(Reflections.java:129)
	at org.reflections.Reflections.<init>(Reflections.java:170)
	at org.nd4j.versioncheck.VersionCheck.listGitPropertiesFiles(VersionCheck.java:201)
	at org.nd4j.versioncheck.VersionCheck.getVersionInfos(VersionCheck.java:220)
	at org.nd4j.versioncheck.VersionCheck.checkVersions(VersionCheck.java:92)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6098)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6087)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:201)
	at org.nd4j.Nd4jRegistrator.registerClasses(Nd4jRegistrator.java:20)
	at org.apache.spark.serializer.KryoSerializer$$anonfun$newKryo$6.apply(KryoSerializer.scala:125)
	at org.apache.spark.serializer.KryoSerializer$$anonfun$newKryo$6.apply(KryoSerializer.scala:125)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at org.apache.spark.serializer.KryoSerializer.newKryo(KryoSerializer.scala:125)
	at org.apache.spark.serializer.KryoSerializerInstance.borrowKryo(KryoSerializer.scala:274)
	at org.apache.spark.serializer.KryoSerializerInstance.<init>(KryoSerializer.scala:259)
	at org.apache.spark.serializer.KryoSerializer.newInstance(KryoSerializer.scala:175)
	at org.apache.spark.rdd.RDD$$anonfun$aggregate$1.apply(RDD.scala:1086)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
	at org.apache.spark.rdd.RDD.aggregate(RDD.scala:1084)
	at org.apache.spark.api.java.JavaRDDLike$class.aggregate(JavaRDDLike.scala:425)
	at org.apache.spark.api.java.AbstractJavaRDDLike.aggregate(JavaRDDLike.scala:45)
	at org.datavec.spark.transform.AnalyzeSpark.analyzeQuality(AnalyzeSpark.java:377)

**Comment by AlexDBlack** [comment]
@CStrue ok, that's a separate issue, open an issue in DataVec. Looks like a warning though, not an actual exception?
or does this actually stop you from running anything?

**Comment by raver119** [comment]
Closing this issue due to inactivity. Feel free to reopen it if needed.
