### ISSUE TITLE
Exception when initializing Parallelism thresholds

### ISSUE THREAD

**Issue by gagatust** [deeplearning4j/nd4j#2383]
```java
 public static void main(String[] args) {        
        //Nd4j.create(1);  // - works
        NativeOpsHolder.getInstance().getDeviceNativeOps().setElementThreshold(164);
        NativeOpsHolder.getInstance().getDeviceNativeOps().setTADThreshold(4);        
}
```
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.mycompany.mavenproject1.main.main(main.java:19)
Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:51)
	at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:19)
	... 1 more
Caused by: java.lang.NullPointerException
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:28)
	... 2 more
```

```xml
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-native</artifactId>
            <version>0.9.2-SNAPSHOT</version>
        </dependency>
```

**Comment by raver119** [comment]
I think i'll just announce this methods in OpExecutioner interface, and remove NativeOpsHolder from that page.

**Comment by raver119** [comment]
```
Nd4.getExecutioner().setElementsThreshold(xxx);
Nd4.getExecutioner().setTadThreshold(yyy)
```

**Comment by gagatust** [comment]
Nd4**j**
```java
Nd4j.getExecutioner().setElementsThreshold(xxx);
Nd4j.getExecutioner().setTadThreshold(yyy)
```

**Comment by raver119** [comment]
Ye, sorry
