### ISSUE TITLE
maxNumber() fails with large matrices on GPU

### ISSUE THREAD

**Issue by mossaab0** [deeplearning4j/nd4j#2394]
The following snippet of code crashes without much useful information.

```
package com.walmart.labs.search.perceive.embeddings;

import org.nd4j.linalg.factory.Nd4j;

public class Test {

    public static void main(String[] args) {
        System.out.println(Nd4j.ones(100000, 100000).max(0).maxNumber());
    }
}
```

```
CUDA error at /home/me/workspace/dl4j/all-multiplatform@2_linux-x86_64/stream1/libnd4j/blas/cuda/NativeOps.cu:4885 code=77(<unknown>) "result" 
CUDA error at /home/me/workspace/dl4j/all-multiplatform@2_linux-x86_64/stream1/libnd4j/blas/cuda/NativeOps.cu:4895 code=77(<unknown>) "result" 
Exception in thread "UniGC thread 1" Exception in thread "main" org.nd4j.linalg.exception.ND4JException: CUDA exception happened. Terminating. Last op: [null]
	at org.nd4j.jita.allocator.pointers.cuda.cudaEvent_t.synchronize(cudaEvent_t.java:55)
	at org.nd4j.jita.flow.impl.SynchronousFlowController.waitTillReleased(SynchronousFlowController.java:206)
	at org.nd4j.jita.flow.impl.GridFlowController.waitTillReleased(GridFlowController.java:62)
	at org.nd4j.jita.handler.impl.CudaZeroHandler.purgeZeroObject(CudaZeroHandler.java:1143)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.purgeZeroObject(AtomicAllocator.java:499)
	at org.nd4j.jita.allocator.impl.AtomicAllocator$UnifiedGarbageCollectorThread.run(AtomicAllocator.java:712)
org.nd4j.linalg.exception.ND4JException: CUDA exception happened. Terminating. Last op: [null]
	at org.nd4j.jita.allocator.pointers.cuda.cudaStream_t.synchronize(cudaStream_t.java:24)
	at org.nd4j.jita.handler.impl.CudaZeroHandler.alloc(CudaZeroHandler.java:302)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:470)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:396)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<init>(BaseCudaDataBuffer.java:216)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<init>(BaseCudaDataBuffer.java:327)
	at org.nd4j.linalg.jcublas.buffer.CudaIntDataBuffer.<init>(CudaIntDataBuffer.java:53)
	at org.nd4j.jita.allocator.tad.BasicTADManager.getTADOnlyShapeInfo(BasicTADManager.java:58)
	at org.nd4j.jita.allocator.tad.DeviceTADManager.getTADOnlyShapeInfo(DeviceTADManager.java:75)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.naiveExec(CudaExecutioner.java:223)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.exec(CudaExecutioner.java:609)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.exec(CudaGridExecutioner.java:671)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.max(BaseNDArray.java:3878)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.maxNumber(BaseNDArray.java:1173)
	at Test.main(Test.java:8)
```
Configuration:

- Tesla K80. Driver Version: 367.57
- Cuda 8.0
- ND4J 0.9.1
- Ubuntu 16.04.1 LTS

**Comment by AlexDBlack** [comment]
Relevant discussion from gitter:
```
Alex Black @AlexDBlack 12:43
yeah, I wonder if it's something to do with integer vs long indexing in reductions...
ah, though... 100k^2 is 10 billion elements. So probably simply be memory related (unless you have > 40GB GPU memory)
same with the all cosine now that I think about it
which is an N^2 result array
even if that's the case, we probably want an issue, if only to throw an actually useful exception and not crash everything

mossaab0 @mossaab0 12:48
OK. What I find strange, though, is that Nd4j.ones(100000, 100000).max(0) works fine. Only when I try to get some value inside when it crashes.

Alex Black @AlexDBlack 12:49
that's due to grid executor, probably
```

**Comment by raver119** [comment]
I'm not quite sure how you've managed to create that 100k, 100k matrix.  That's 40GB of data.
Probably it was created in pinned host memory, but i'm not sure if CUDA 8 allows addressing for such allocations. Will check though.

**Comment by mossaab0** [comment]
FYI, I have 1TB of RAM in my host.
