### ISSUE TITLE
SameDiff: Output with -1s (effectively DenseLayer) fails

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2402]
Test below works OK when input shape is [3,3] but not when input shape is [-1,3]
```
    @Test
    public void testShapeResolutionMinus1(){

        int nIn = 3;
        int nOut = 4;

        int minibatch = 3;

        for(boolean useMinus1 : new boolean[]{false, true}) {
            log.info("Starting: {}", (useMinus1 ? "minibatch -1" : "minibatch 3"));

            int[] inShape;
            if(useMinus1){
                inShape = new int[]{-1, nIn};
            } else {
                inShape = new int[]{minibatch, nIn};
            }
            int[] wShape = new int[]{nIn, nOut};
            int[] bShape = new int[]{1, nOut};

            SameDiff sd = SameDiff.create();
            SDVariable layerInput = sd.var("in", inShape);
            SDVariable weights = sd.var("W", wShape);
            SDVariable bias = sd.var("b", bShape);

            SDVariable mmul = sd.mmul("mmul", layerInput, weights);
            SDVariable z = mmul.add("z", bias);
            SDVariable out = sd.sigmoid("out", z);

            Map<String, INDArray> m = new HashMap<>();
            INDArray in = Nd4j.rand(new int[]{minibatch, nIn});
            INDArray w = Nd4j.rand(wShape);
            INDArray b = Nd4j.rand(bShape);

            sd.associateArrayWithVariable(in, sd.getVariable("in"));
            sd.associateArrayWithVariable(w, sd.getVariable("W"));
            sd.associateArrayWithVariable(b, sd.getVariable("b"));

            INDArray outArr = sd.execAndEndResult();

            assertArrayEquals(new int[]{minibatch, nOut}, outArr.shape());
        }
    }
```

Output/failure for the -1 case:
```
Provided output array for [matmul] has length of 4, but actual result has length of 12

org.nd4j.linalg.exception.ND4JIllegalStateException: Op execution failed: ND4J_STATUS_BAD_OUTPUT

	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1565)
	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:4068)
	at org.nd4j.autodiff.samediff.SameDiff.execAndEndResult(SameDiff.java:3260)
	at org.deeplearning4j.samediff.SameDiffTest.testShapeResolutionMinus1(SameDiffTest.java:126)
```

----------------

Related: execWithPlaceholder: This gives the same error for the -1 case
```
    @Test
    public void testShapeResolutionMinus1(){

        int nIn = 3;
        int nOut = 4;

        int minibatch = 3;

        for(boolean useMinus1 : new boolean[]{false, true}) {
//        for(boolean useMinus1 : new boolean[]{true}) {
            log.info("Starting: {}", (useMinus1 ? "minibatch -1" : "minibatch 3"));

            int[] inShape;
            if(useMinus1){
                inShape = new int[]{-1, nIn};
            } else {
                inShape = new int[]{minibatch, nIn};
            }
            int[] wShape = new int[]{nIn, nOut};
            int[] bShape = new int[]{1, nOut};

            SameDiff sd = SameDiff.create();
            SDVariable layerInput = sd.var("in", inShape);
            SDVariable weights = sd.var("W", wShape);
            SDVariable bias = sd.var("b", bShape);

            SDVariable mmul = sd.mmul("mmul", layerInput, weights);
            SDVariable z = mmul.add("z", bias);
            SDVariable out = sd.sigmoid("out", z);

            INDArray in = Nd4j.rand(new int[]{minibatch, nIn});
            INDArray w = Nd4j.rand(wShape);
            INDArray b = Nd4j.rand(bShape);

            Map<String, INDArray> m = new HashMap<>();
            m.put("in", in);
            m.put("W", w);
            m.put("b", b);

            sd.addAsPlaceHolder("in");
            sd.addAsPlaceHolder("W");
            sd.addAsPlaceHolder("b");

            sd.execWithPlaceHolder(m);

            INDArray outArr = sd.getVariable("out").getArr();

            assertArrayEquals(new int[]{minibatch, nOut}, outArr.shape());
        }
    }
```

```
Provided output array for [matmul] has length of 4, but actual result has length of 12

org.nd4j.linalg.exception.ND4JIllegalStateException: Op execution failed: ND4J_STATUS_BAD_OUTPUT

	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1565)
	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:4068)
	at org.nd4j.autodiff.samediff.SameDiff.execWithPlaceHolder(SameDiff.java:3890)
	at org.deeplearning4j.samediff.SameDiffTest.testShapeResolutionMinus1(SameDiffTest.java:137)
```

Removing the sd.addAsPlaceHolder calls, the following output is obtained:
```
java.lang.IllegalStateException: Not all variables specified. 3 variables were specified, but needed 0
	at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at org.nd4j.autodiff.samediff.SameDiff.resolveVariablesWith(SameDiff.java:3749)
	at org.nd4j.autodiff.samediff.SameDiff.execWithPlaceHolder(SameDiff.java:3889)
	at org.deeplearning4j.samediff.SameDiffTest.testShapeResolutionMinus1(SameDiffTest.java:137)
```

**Comment by AlexDBlack** [comment]
I think this may ultimately be the cause:
```
    @Test
    public void debug2() {
        int[] inShape = new int[]{-1, 3};

        SameDiff sd = SameDiff.create();
        SDVariable layerInput = sd.var("in", inShape);

        int[] actShape = layerInput.getShape(); //Getting: [1,3]
        assertArrayEquals(inShape, actShape);
    }
```

mmul.calculateOutputShape() is getting [1,3] and [3,4] as shapes for the input, instead of [-1,3] and [3,4]

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/pull/2413
