### ISSUE TITLE
SameDiff: Mmul with transpose bug (with dimension 1)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2411]
The issue here seems to be the cause of the failure in SameDiffTests.testLogisticRegression()
https://github.com/deeplearning4j/nd4j/blob/c9b3c692fa9c7cb9254902a6d00229314b77eeb0/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/autodiff/samediff/SameDiffTests.java#L857

```[2,3]^T x [2,4] = [3,4]``` passes and produces expected result
```[1,3]^T x [1,4] = [3,4]``` fails with exception

```
    @Test
    public void testMmulWithTranspose(){
        //Here: [x,3]^T * [x,4] = [3,4]

        for( int i : new int[]{2,1}) {
            System.out.println("i = " + i);
            INDArray first = Nd4j.linspace(1, 3*i, 3*i).reshape('c', i,3);      //To [1,3] or [2,3]
            INDArray second = Nd4j.linspace(4, 4 + 4*i, 4*i).reshape('c',i,4);  //To [1,4] or [2,4]

            System.out.println("Shapes: " + Arrays.toString(first.shape()) + "\t" + Arrays.toString(second.shape()));

            SameDiff sd = SameDiff.create();
            SDVariable f = sd.var("in1", first);
            SDVariable s = sd.var("in2", second);

            MMulTranspose mt = MMulTranspose.builder()
                    .transposeA(true)
                    .transposeB(false)
                    .transposeResult(false)
                    .a(first)
                    .b(second)
                    .build();
            SDVariable mmul = sd.f().mmul(f, s, mt);
            sd.updateVariableNameAndReference(mmul, "mmul");

            INDArray out = sd.execAndEndResult();

            INDArray exp = first.transpose().mmul(second);
            assertEquals(exp, out);
            System.out.println("----- Finished: i = " + i + " ------");
        }
    }
```

```
i = 2
Shapes: [2, 3]	[2, 4]
15:51:30.665 [main] INFO  org.nd4j.autodiff.samediff.SameDiff - Executing op mmul
15:51:30.666 [main] INFO  org.nd4j.autodiff.samediff.SameDiff -  Input shape for in1 is  [2, 3] Input shape for in2 is  [2, 4] Output shape for mmul is  [3, 4]
----- Finished: i = 2 ------
i = 1
Shapes: [1, 3]	[1, 4]
15:51:30.678 [main] ERROR o.n.l.c.n.ops.NativeOpExecutioner - Failed to execute. Please see above message (printed out from c++) for a possible cause of error.
java.lang.RuntimeException: Unknown exception.
	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.execCustomOpDouble(Native Method) ~[classes/:na]
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1565) ~[classes/:na]
	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:4054) [classes/:na]
	at org.nd4j.autodiff.samediff.SameDiff.execAndEndResult(SameDiff.java:3270) [classes/:na]
	at org.nd4j.autodiff.samediff.SameDiffTests.testMmulWithTranspose(SameDiffTests.java:1424)

15:51:30.678 [main] INFO  org.nd4j.autodiff.samediff.SameDiff - Executing op mmul
15:51:30.679 [main] INFO  org.nd4j.autodiff.samediff.SameDiff -  Input shape for in1 is  [1, 3] Input shape for in2 is  [1, 4] Output shape for mmul is  [3, 4]

java.lang.AssertionError:  <Click to see difference>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.nd4j.autodiff.samediff.SameDiffTests.testMmulWithTranspose(SameDiffTests.java:1427)
```

**Comment by raver119** [comment]
Should be fixed now. Waiting for confirmation.

**Comment by AlexDBlack** [comment]
Confirmed fixed + passing
