### ISSUE TITLE
SameDiff - Conv2d expects 2 inputs only, fails with 3 (i.e., with optional bias)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2432]
Reproducable using this test:
https://github.com/deeplearning4j/nd4j/blob/1423a945c44b9c943b0fce925c31f574238d566e/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/autodiff/samediff/SameDiffTests.java#L1607-L1644

Note that if I remove the optional bias, the (admittedly very simple) test passes.

```
org.nd4j.linalg.exception.ND4JIllegalStateException: Op failure for conv2d Number of inputs is invalid for execution. Specified 3 but should be 2
	at org.nd4j.linalg.api.ops.DynamicCustomOp.assertValidForExecution(DynamicCustomOp.java:422)
	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:4117)
	at org.nd4j.autodiff.samediff.SameDiff.execAndEndResult(SameDiff.java:3340)
	at org.nd4j.autodiff.samediff.SameDiffTests.testConv2dBasic(SameDiffTests.java:1640)
```

![image](https://user-images.githubusercontent.com/2360237/34297351-c019ecde-e76b-11e7-9fd4-38f7ed711705.png)

**Comment by AlexDBlack** [comment]
Closing this - seems to be resolved now.
