### ISSUE TITLE
SameDiff: issue with reductions + placeholders

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2445]
```
    @Test
    public void testPlaceholderReduceSimple(){
        SameDiff sd = SameDiff.create();
        SDVariable v = sd.var("in", new int[]{-1,10});
        SDVariable vSum = sd.sum(v, 1);                             //Exception here
    }
```

```
java.lang.NullPointerException
	at org.nd4j.linalg.api.shape.Shape.isWholeArray(Shape.java:218)
	at org.nd4j.linalg.api.shape.Shape.getReducedShape(Shape.java:230)
	at org.nd4j.linalg.api.ops.BaseAccumulation.calculateOutputShape(BaseAccumulation.java:179)
	at org.nd4j.autodiff.samediff.SameDiff.generateOutputVariableForOp(SameDiff.java:3391)
	at org.nd4j.linalg.api.ops.BaseOp.outputVariables(BaseOp.java:357)
	at org.nd4j.autodiff.functions.DifferentialFunction.outputVariables(DifferentialFunction.java:144)
	at org.nd4j.autodiff.functions.DifferentialFunctionFactory.sum(DifferentialFunctionFactory.java:117)
	at org.nd4j.autodiff.samediff.SameDiff.sum(SameDiff.java:2913)
	at org.nd4j.autodiff.samediff.SameDiff.sum(SameDiff.java:2014)
	at org.deeplearning4j.samediff.TestSameDiffOutput.testPlaceholderReduceSimple
```

**Comment by AlexDBlack** [comment]
Fixed here: https://github.com/deeplearning4j/nd4j/pull/2433
