### ISSUE TITLE
SameDiff: automatic naming issue with chained mean ops

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2447]
Looks like it attempts to call the second mean "mean_1" also.

```
    @Test
    public void testSequentialMeans(){
        SameDiff sd = SameDiff.create();
        SDVariable in = sd.var("in", new int[]{10,10,10});
        SDVariable mean1 = sd.mean(in, 2);      //[10,10] out
        SDVariable mean2 = sd.mean(mean1, 1);   //[10,1] out - ***exception here***
    }
```
```
org.nd4j.linalg.exception.ND4JIllegalStateException: Function by id already exists!

	at org.nd4j.autodiff.samediff.SameDiff.putFunctionForId(SameDiff.java:395)
	at org.nd4j.autodiff.functions.DifferentialFunction.setInstanceId(DifferentialFunction.java:259)
	at org.nd4j.autodiff.functions.DifferentialFunction.<init>(DifferentialFunction.java:117)
	at org.nd4j.linalg.api.ops.BaseOp.<init>(BaseOp.java:71)
	at org.nd4j.linalg.api.ops.BaseAccumulation.<init>(BaseAccumulation.java:59)
	at org.nd4j.linalg.api.ops.BaseAccumulation.<init>(BaseAccumulation.java:98)
	at org.nd4j.linalg.api.ops.impl.accum.Sum.<init>(Sum.java:39)
	at org.nd4j.linalg.api.ops.impl.accum.Mean.<init>(Mean.java:36)
	at org.nd4j.autodiff.functions.DifferentialFunctionFactory.mean(DifferentialFunctionFactory.java:127)
	at org.nd4j.autodiff.samediff.SameDiff.mean(SameDiff.java:2902)
	at org.nd4j.autodiff.samediff.SameDiff.mean(SameDiff.java:2013)
	at org.deeplearning4j.samediff.TestSameDiffOutput.testMultipleMean
```

**Comment by AlexDBlack** [comment]
Confirmed fixed here: https://github.com/deeplearning4j/nd4j/pull/2433
