### ISSUE TITLE
SameDiff - Reduction result arrays: incorrect shapes

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2448]
```
    @Test
    public void testReductionShapes1() {

        SameDiff sd = SameDiff.create();
        SDVariable in = sd.var("in", new int[]{10,9,8});
        SDVariable mean1 = sd.mean(in, 2);      //[10,9] out
        SDVariable mean2 = sd.mean(mean1, 1);   //[10,1] out
        sd.execAndEndResult();  //***Exception***

        INDArray m1 = mean1.getArr();
        INDArray m2 = mean2.getArr();

        assertArrayEquals(new int[]{10,9}, m1.shape());
        assertArrayEquals(new int[]{10,1}, m2.shape());
    }
```
```
org.nd4j.linalg.exception.ND4JIllegalStateException: Shape of target array for reduction [[1, 9]] doesn't match expected [[10, 1]]

	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:308)
	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:5701)
	at org.nd4j.autodiff.samediff.SameDiff.execAndEndResult(SameDiff.java:3616)
	at org.deeplearning4j.samediff.TestSameDiffOutput.testReductionShapes1(TestSameDiffOutput.java:84)
```

```
    @Test
    public void testReductionShapes2(){

        SameDiff sd2 = SameDiff.create();
        SDVariable in2 = sd2.var("in", new int[]{10,9,8});
        SDVariable meanA = sd2.mean(in2, 0);      //[9,8] out
        SDVariable meanB = sd2.mean(meanA, 0);   //[1,8] out
        sd2.execAndEndResult(); //***Exception***

        INDArray mA = meanA.getArr();
        INDArray mB = meanB.getArr();

        assertArrayEquals(new int[]{9,8}, mA.shape());
        assertArrayEquals(new int[]{1,8}, mB.shape());
    }
```

```
org.nd4j.linalg.exception.ND4JIllegalStateException: Shape of target array for reduction [[9, 1]] doesn't match expected [[1, 8]]

	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:308)
	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:5701)
	at org.nd4j.autodiff.samediff.SameDiff.execAndEndResult(SameDiff.java:3616)
	at org.deeplearning4j.samediff.TestSameDiffOutput.testReductionShapes2(TestSameDiffOutput.java:100)
```

**Comment by AlexDBlack** [comment]
Confirmed fixed here: https://github.com/deeplearning4j/nd4j/pull/2433
