### ISSUE TITLE
SameDiff - NPE with reduce + placeholders

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2449]
```
    @Test
    public void testSequentialMeansPlaceholder() {
        for( int dim0 : new int[]{10, -1}){
            String msg = "Dimension 0 = " + dim0;
            System.out.println(msg);
            SameDiff sd = SameDiff.create();
            SDVariable in = sd.var("in", new int[]{dim0, 9, 8});
            SDVariable mean1 = sd.mean(in, 2);                  //[10,9,8] -> [10,9]
            SDVariable mean2 = sd.mean(mean1, 1);               //[10,9] -> [10,1]

            INDArray inArr = Nd4j.create(10, 9, 8);
            sd.associateArrayWithVariable(inArr, in);

            INDArray out = sd.execAndEndResult();     //Exception here, dim0=-1 case only

            assertArrayEquals(msg, new int[]{10,1}, out.shape());
        }
    }
```

```
java.lang.NullPointerException
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:254)
	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:5701)
	at org.nd4j.autodiff.samediff.SameDiff.execAndEndResult(SameDiff.java:3616)
	at org.deeplearning4j.samediff.TestSameDiffOutput.testSequentialMeansPlaceholder
```

**Comment by AlexDBlack** [comment]
Confirmed fixed here: https://github.com/deeplearning4j/nd4j/pull/2433
