### ISSUE TITLE
SameDiff: exception during execution

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2450]
```
    @Test
    public void test(){

        SameDiff sd = SameDiff.create();

        int nIn = 3;
        int nOut = 4;
        int minibatch = 3;
        SDVariable input = sd.var("in", new int[]{-1,nIn});
        SDVariable label = sd.var("label", new int[]{-1, nOut});
        SDVariable weights = sd.var("W", new int[]{nIn,nOut});
        SDVariable bias = sd.var("b", new int[]{1,nOut});


        SDVariable mmul = sd.mmul("mmul", input, weights);
        SDVariable z = mmul.add("z", bias);
        SDVariable out = sd.tanh(z);

        SDVariable diff = out.sub(label);
        SDVariable sqDiff = diff.mul(diff);
        SDVariable msePerEx = sd.mean("msePerEx", sqDiff, 1);
        SDVariable avgMSE = sd.mean("loss", msePerEx, 0);

        INDArray inputArr = Nd4j.rand(minibatch, nIn);
        INDArray labelArr = Nd4j.rand(minibatch, nOut);
        INDArray weightsArr = Nd4j.rand(nIn, nOut);
        INDArray biasArr = Nd4j.rand(1,nOut);

        sd.associateArrayWithVariable(inputArr, input);
        sd.associateArrayWithVariable(labelArr, label);
        sd.associateArrayWithVariable(weightsArr, weights);
        sd.associateArrayWithVariable(biasArr, bias);

        INDArray result = sd.execAndEndResult();
    }
```

```
org.nd4j.linalg.exception.ND4JIllegalStateException: Op failure for add Number of inputs is invalid for execution. Specified 0 but should be 2

	at org.nd4j.linalg.api.ops.DynamicCustomOp.assertValidForExecution(DynamicCustomOp.java:448)
	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:5670)
	at org.nd4j.autodiff.samediff.SameDiff.execAndEndResult(SameDiff.java:3621)
	at org.deeplearning4j.samediff.TestSameDiffOutput.test
```

**Comment by AlexDBlack** [comment]
Appears to be fixed - test is passing on https://github.com/deeplearning4j/nd4j/pull/2433
