### ISSUE TITLE
SameDiff: "Found null variable at index 0" after Conv2d

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2453]
Tested on: https://github.com/deeplearning4j/nd4j/pull/2433

Conv2d itself passes (i.e., remove the 'out' variable in test below), but anything after it seems to fail.

```
org.nd4j.linalg.exception.ND4JIllegalStateException: Found null variable at index 0
	at org.nd4j.autodiff.samediff.SameDiff.getInputVariablesForFunction(SameDiff.java:483)
	at org.nd4j.autodiff.functions.DifferentialFunction.args(DifferentialFunction.java:222)
	at org.nd4j.autodiff.functions.DifferentialFunction.arg(DifferentialFunction.java:233)
	at org.nd4j.linalg.api.ops.BaseTransformOp.calculateOutputShape(BaseTransformOp.java:198)
	at org.nd4j.autodiff.samediff.SameDiff.generateOutputVariableForOp(SameDiff.java:3499)
	at org.nd4j.linalg.api.ops.BaseOp.outputVariables(BaseOp.java:360)
	at org.nd4j.autodiff.functions.DifferentialFunction.outputVariables(DifferentialFunction.java:149)
	at org.nd4j.autodiff.functions.DifferentialFunctionFactory.tanh(DifferentialFunctionFactory.java:280)
	at org.nd4j.autodiff.samediff.SameDiff.tanh(SameDiff.java:2660)
	at org.deeplearning4j.samediff.TestSameDiffConv.testConv2dBasic(TestSameDiffConv.java:264)
```

```
    @Test
    public void testConv2dBasic() {
        int nIn = 3;
        int nOut = 4;
        int kH = 2;
        int kW = 2;

        int mb = 3;
        int imgH = 28;
        int imgW = 28;

        SameDiff sd = SameDiff.create();
        INDArray wArr = Nd4j.create(nOut, nIn, kH, kW); //As per DL4J
        INDArray bArr = Nd4j.create(1, nOut);
        INDArray inArr = Nd4j.create(mb, nIn, imgH, imgW);

        SDVariable in = sd.var("in", inArr);
        SDVariable w = sd.var("W", wArr);
        SDVariable b = sd.var("b", bArr);

        SDVariable[] vars = new SDVariable[]{in, w, b};

        Conv2DConfig c = Conv2DConfig.builder()
                .kh(kH).kw(kW)
                .ph(0).pw(0)
                .sy(1).sx(1)
                .dh(1).dw(1)
                .isSameMode(false)
                .build();

        SDVariable conv = sd.conv2d(vars, c);

        // Any/all of the following ops after the conv2d fails
        SDVariable out = sd.tanh("tanh", conv);
//        SDVariable out = conv.add("out", 1.0);
//        SDVariable out = sd.sum(conv, 1,2,3);

        INDArray outArr = sd.execAndEndResult();
        //Expected output size: out = (in - k + 2*p)/s + 1 = (28-2+0)/1+1 = 27
        int[] outShape = outArr.shape();
        assertArrayEquals(new int[]{mb, nOut, 27, 27}, outShape);
    }
```

**Comment by AlexDBlack** [comment]
Looks like what is happening here:
It's doing a getVariable("706b2286..."), which does a lookup in SameDiff.variableMap
However, the key in that map is "conv2d(in-,W-,b-,", but the associated SDVariable varName doesn't match this...

Perhaps name is being updated after creation - but not in all locations...

![image](https://user-images.githubusercontent.com/2360237/34472901-7620a0da-efbf-11e7-944c-f2eb43e45909.png)

**Comment by AlexDBlack** [comment]
Fixed here: https://github.com/deeplearning4j/nd4j/pull/2454
