### ISSUE TITLE
SameDiff: Conv2d - lack of validation for input shapes

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2455]
If I try to feed a 2d array into conv2d op (instead of the correct 4d array) I get an obscure invalid shape exception. Not a very high priority, but this should be handled properly...

```
org.nd4j.linalg.exception.ND4JIllegalStateException: Invalid shape: Requested INDArray shape [3, 4, 2, 0] contains dimension size values < 1 (all dimensions must be 1 or more)

	at org.nd4j.linalg.factory.Nd4j.checkShapeValues(Nd4j.java:5086)
	at org.nd4j.linalg.factory.Nd4j.createUninitialized(Nd4j.java:5116)
	at org.nd4j.weightinit.impl.ZeroInitScheme.doCreate(ZeroInitScheme.java:26)
	at org.nd4j.weightinit.BaseWeightInitScheme.create(BaseWeightInitScheme.java:34)
	at org.nd4j.autodiff.samediff.SDVariable.getArr(SDVariable.java:181)
	at org.nd4j.autodiff.samediff.SDVariable.storeAndAllocateNewArray(SDVariable.java:139)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.attemptToGetOrCreateArrForVar(DynamicCustomOp.java:215)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.outputVariables(DynamicCustomOp.java:198)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.outputVariables(DynamicCustomOp.java:133)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.populateInputsAndOutputsFromSameDiff(DynamicCustomOp.java:514)
	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:5737)
	at org.nd4j.autodiff.samediff.SameDiff.execAndEndResult(SameDiff.java:3681)
	at org.deeplearning4j.samediff.TestSameDiffConv.testConv2dBasicBadInput(TestSameDiffConv.java:312)
```

```
    @Test
    public void testConv2dBasicBadInput() {
        int nIn = 3;
        int nOut = 4;
        int kH = 2;
        int kW = 2;

        int mb = 3;
        int imgH = 28;
        int imgW = 28;

        SameDiff sd = SameDiff.create();
        INDArray wArr = Nd4j.create(nOut, nIn, kH, kW); //As per DL4J
        INDArray bArr = Nd4j.create(1, nOut);
        INDArray inArr = Nd4j.create(mb, nIn);          //***This is totally invalid - should be 4d, not 2d***

        SDVariable in = sd.var("in", inArr);
        SDVariable w = sd.var("W", wArr);
        SDVariable b = sd.var("b", bArr);

        //Order: https://github.com/deeplearning4j/libnd4j/blob/6c41ea5528bb1f454e92a9da971de87b93ff521f/include/ops/declarable/generic/convo/conv2d.cpp#L20-L22
        //in, w, b - bias is optional
        SDVariable[] vars = new SDVariable[]{in, w, b};

        Conv2DConfig c = Conv2DConfig.builder()
                .kh(kH).kw(kW)
                .ph(0).pw(0)
                .sy(1).sx(1)
                .dh(1).dw(1)
                .isSameMode(false)
                .build();

        SDVariable conv = sd.conv2d(vars, c);
        SDVariable out = sd.tanh("tanh", conv);

        sd.execAndEndResult();
    }
```

**Comment by AlexDBlack** [comment]
Related: Convolution.im2col methods don't seem to have validation. For example, it's possible to pass a 4d array where a 6d (output) array is expected.

**Comment by raver119** [comment]
Shape functions do not have validation. It happens on op execution.
