### ISSUE TITLE
SameDiff: IndexOutOfBoundsException on backwards

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2462]
```
    @Test
    public void testMseBackwards(){

        SameDiff sd = SameDiff.create();

        int nOut = 4;
        int minibatch = 3;
        SDVariable input = sd.var("in", new int[]{-1,nOut});
        SDVariable label = sd.var("label", new int[]{-1, nOut});

        SDVariable diff = input.sub(label);
        SDVariable sqDiff = diff.mul(diff);
        SDVariable msePerEx = sd.mean("msePerEx", sqDiff, 1);
        SDVariable avgMSE = sd.mean("loss", msePerEx, 0);

        INDArray inputArr = Nd4j.rand(minibatch, nOut);
        INDArray labelArr = Nd4j.rand(minibatch, nOut);

        sd.associateArrayWithVariable(inputArr, input);
        sd.associateArrayWithVariable(labelArr, label);

        INDArray result = sd.execAndEndResult();
        assertEquals(1, result.length());

        Pair<Map<SDVariable, DifferentialFunction>, List<DifferentialFunction>> p = sd.execBackwards();
    }
```

```
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.nd4j.autodiff.functions.DifferentialFunctionFactory.one(DifferentialFunctionFactory.java:101)
	at org.nd4j.linalg.api.ops.impl.accum.Mean.doDiff(Mean.java:79)
	at org.nd4j.autodiff.functions.DifferentialFunction.diff(DifferentialFunction.java:255)
	at org.nd4j.autodiff.samediff.SameDiff$3.define(SameDiff.java:4016)
	at org.nd4j.autodiff.samediff.SameDiff.defineFunction(SameDiff.java:3885)
	at org.nd4j.autodiff.samediff.SameDiff.defineFunction(SameDiff.java:3868)
	at org.nd4j.autodiff.samediff.SameDiff.execBackwards(SameDiff.java:3944)
	at org.deeplearning4j.samediff.TestSameDiffLoss.testMseBackwards(TestSameDiffLoss.java:82)
```

**Comment by AlexDBlack** [comment]
Fixed here: https://github.com/deeplearning4j/nd4j/pull/2433
