### ISSUE TITLE
SameDiff: wrong shape / exception for sum/stdev/variance backwards

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2465]
mean, min, max, prod seem to be ok (at least as far as the shapes).

Exception is on the "execBackwards" call.
```
RealDiv: shapes should be equal, or broadcastable. But got [9, 1] vs [3, 1] instead
```

```
    @Test
    public void testReductionsBackwards() {

        for (int i = 0; i < 7; i++) {

            SameDiff sd = SameDiff.create();

            int nOut = 4;
            int minibatch = 3;
            SDVariable input = sd.var("in", new int[]{-1, nOut});
            SDVariable label = sd.var("label", new int[]{-1, nOut});

            SDVariable diff = input.sub(label);
            SDVariable sqDiff = diff.mul(diff);
            SDVariable msePerEx = sd.mean("msePerEx", sqDiff, 1);

            SDVariable loss;
            String name;
            switch (i) {
                case 0:
                    loss = sd.mean("loss", msePerEx, 0);
                    name = "mean";
                    break;
                case 1:
                    loss = sd.sum("loss", msePerEx, 0);
                    name = "sum";
                    break;
                case 2:
                    loss = sd.standardDeviation("loss", msePerEx, true, 0);
                    name = "stdev";
                    break;
                case 3:
                    loss = sd.min("loss", msePerEx, 0);
                    name = "min";
                    break;
                case 4:
                    loss = sd.max("loss", msePerEx, 0);
                    name = "max";
                    break;
                case 5:
                    loss = sd.variance("loss", msePerEx, true, 0);
                    name = "variance";
                    break;
                case 6:
                    loss = sd.prod("loss", msePerEx, 0);
                    name = "prod";
                    break;
                default:
                    throw new RuntimeException();
            }


            String msg = "test: " + i + " - " + name;
            log.info("*** Starting test: " + msg);

            INDArray inputArr = Nd4j.rand(minibatch, nOut);
            INDArray labelArr = Nd4j.rand(minibatch, nOut);

            sd.associateArrayWithVariable(inputArr, input);
            sd.associateArrayWithVariable(labelArr, label);

            INDArray result = sd.execAndEndResult();
            assertEquals(1, result.length());

            Pair<Map<SDVariable, DifferentialFunction>, List<DifferentialFunction>> p = sd.execBackwards();
        }
    }
```

```
o.d.s.TestSameDiffLoss - *** Starting test: test: 1 - sum
o.n.a.s.SameDiff - Executing op subtract
o.n.a.s.SameDiff -  Input shape for in is  [3, 4] Input shape for label is  [3, 4] Output shape for sub(in-,label-, is  [3, 4]
o.n.a.s.SameDiff - Executing op multiply
o.n.a.s.SameDiff -  Input shape for sub(in-,label-, is  [3, 4] Input shape for sub(in-,label-, is  [3, 4] Output shape for mul(sub(in-,label-,-,sub(in-,label-,-, is  [3, 4]
o.n.a.s.SameDiff - Executing op mean
o.n.a.s.SameDiff -  Input shape for mul(sub(in-,label-,-,sub(in-,label-,-, is  [3, 4] Output shape for msePerEx is  [3, 1]
o.n.a.s.SameDiff - Executing op sum
o.n.a.s.SameDiff -  Input shape for msePerEx is  [3, 1] Output shape for loss is  [1, 1]
o.n.a.s.SameDiff - Action op state is null
o.n.a.s.SameDiff - Executing op subtract
o.n.a.s.SameDiff -  Input shape for in is  [3, 4] Input shape for label is  [3, 4] Output shape for sub(in-,label-, is  [3, 4]
o.n.a.s.SameDiff - Executing op multiply
o.n.a.s.SameDiff -  Input shape for sub(in-,label-, is  [3, 4] Input shape for sub(in-,label-, is  [3, 4] Output shape for mul(sub(in-,label-,-,sub(in-,label-,-, is  [3, 4]
o.n.a.s.SameDiff - Executing op mean
o.n.a.s.SameDiff -  Input shape for mul(sub(in-,label-,-,sub(in-,label-,-, is  [3, 4] Output shape for msePerEx is  [3, 1]
o.n.a.s.SameDiff - Executing op sum
o.n.a.s.SameDiff -  Input shape for msePerEx is  [3, 1] Output shape for loss is  [1, 1]
o.n.a.s.SameDiff - Executing op tile
o.n.a.s.SameDiff -  Input shape for one-var is  [1, 1] Output shape for msePerEx-grad is  [3, 1]
o.n.a.s.SameDiff - Executing op tile
o.n.a.s.SameDiff -  Input shape for msePerEx is  [3, 1] Output shape for tile_1:1 is  [9, 1]
o.n.a.s.SameDiff - Executing op mul_scalar
o.n.a.s.SameDiff -  Input shape for one-97b7da30-568f-4229-943f-62bb47dd3775 is  [3, 1] Output shape for mul_scalar is  [3, 1]
RealDiv: shapes should be equal, or broadcastable. But got [9, 1] vs [3, 1] instead
o.n.l.c.n.o.NativeOpExecutioner - Failed to execute. Please see above message (printed out from c++) for a possible cause of error.

org.nd4j.linalg.exception.ND4JIllegalStateException: Unknown status given: 50

	at org.nd4j.linalg.api.ops.executioner.OpStatus.byNumber(OpStatus.java:56)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1565)
	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:5739)
	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:3918)
	at org.nd4j.autodiff.samediff.SameDiff.execBackwards(SameDiff.java:4035)
	at org.deeplearning4j.samediff.TestSameDiffLoss.testReductionsBackwards(TestSameDiffLoss.java:122)
```

For comparison, the mean case (which works correctly) gives:
```
o.n.a.s.SameDiff -  Input shape for one-a6f89d32-303e-425d-a02b-07af0bccec9c is  [1, 1] Output shape for mul_scalar_1 is  [1, 1]
```

Edit: the full array (not along dimension 0), which is mathematically equivalent, results in the same exception.

**Comment by AlexDBlack** [comment]
Fixed here: https://github.com/deeplearning4j/nd4j/pull/2468
