### ISSUE TITLE
SameDiff: auto broadcast not functioning for all cases

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2472]
[4,5] + [3,4,5] works
[3,5] + [3,4,5] fails
[3,4] + [3,4,5] fails

```
    @Test
    public void testAutoBroadcast2_3(){

        int[] threeShape = new int[]{3, 4, 5};
        for( int dim : new int[]{0,1,2}) {
            String msg = "dimension: " + dim;
            log.info("***** Starting test: " + msg);

            int[] twoShape = ArrayUtil.removeIndex(threeShape, dim);

            SameDiff sd = SameDiff.create();
            SDVariable in3 = sd.var("in3", Nd4j.rand(threeShape));
            SDVariable in2 = sd.var("in2", Nd4j.rand(twoShape));

            SDVariable addBc = in3.add(in2);

            //Compare vs. manual broadcast:
            int[] bcDim = ArrayUtil.removeIndex(new int[]{0,1,2}, dim);
            INDArray result = Nd4j.create(threeShape);
            INDArray expOut = Nd4j.getExecutioner().execAndReturn(new BroadcastAddOp(in3.getArr(), in2.getArr(), result, bcDim));

            INDArray out = sd.execAndEndResult();
            assertArrayEquals(threeShape, out.shape());

            assertEquals(expOut, out);
        }
    }
```

[4,5] + [3,4,5] output (correct)
```
14:35:21.358 [main] INFO  o.n.a.gradcheck.GradCheckReductions - ***** Starting test: dimension: 0
tz: [3, 3, 4, 5, 20, 5, 1, 0, 1, 99]
14:35:21.492 [main] INFO  org.nd4j.autodiff.samediff.SameDiff - Executing op add
14:35:21.492 [main] INFO  org.nd4j.autodiff.samediff.SameDiff -  Input shape for in3 is  [3, 4, 5] Input shape for in2 is  [4, 5] Output shape for add(in3-,in2-, is  [3, 4, 5]
```

[3,5]+[3,4,5] output (exception)
```
14:35:22.069 [main] INFO  o.n.a.gradcheck.GradCheckReductions - ***** Starting test: dimension: 1
RealDiv: shapes should be equal, or broadcastable. But got [3, 4, 5] vs [3, 5] instead
14:35:22.070 [main] ERROR o.n.l.c.n.ops.NativeOpExecutioner - Failed to execute. Please see above message (printed out from c++) for a possible cause of error.

org.nd4j.linalg.exception.ND4JIllegalStateException: Unknown status given: 50

	at org.nd4j.linalg.api.ops.executioner.OpStatus.byNumber(OpStatus.java:56)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1565)
	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:5775)
	at org.nd4j.autodiff.samediff.SameDiff.execAndEndResult(SameDiff.java:3711)
	at org.nd4j.autodiff.gradcheck.GradCheckReductions.testAutoBroadcast2_3(GradCheckReductions.java:409)
```

Side note: this is *add* not *RealDiv* (error message is wrong)

**Comment by agibsonccc** [comment]
This doesn't work even with numpy:
ValueError: operands could not be broadcast together with shapes (3,5) (3,4,5)

**Comment by raver119** [comment]
same for other one:
ValueError: operands could not be broadcast together with shapes (3,4) (3,4,5)

**Comment by raver119** [comment]
```
import numpy as np

a = np.linspace(1, 12, 12).reshape((3,4))
b = np.linspace(1, 60, 60).reshape((3, 4, 5))

c = a + b

print "c shape: ", c.shape()
print "c data", c
```

**Comment by AlexDBlack** [comment]
You are both right - apologies. So, I re-read Numpy's broadcast rules - seems like this these other cases are indeed not valid. My understanding (incorrect) was that single-dimension reductions should be reversible by auto-broadcast - apparently not so. (This was coming up in reduction backprop, fwiw - we'll need manual broadcast functionality as a result)

Starting from the end dimension and working backwards, you need equal shapes *or* ones, and for different shapes, you can ommit leading 1s but that's it...
Thus [3,5]+[3,4,5] is not valid but [3,1,5]+[3,4,5] is.

**Comment by raver119** [comment]
> manual broadcast functionality

That's, actually, very good thing. I like our Broadcast*Op functionality. In C++ it's still available, so we just should make sure SameDiff is aware of this mechanics.

**Comment by AlexDBlack** [comment]
Re: manual broadcast - I'll close this in favor of a new/dedicated issue here: https://github.com/deeplearning4j/nd4j/issues/2492
