### ISSUE TITLE
SameDiff: Issue with reductions + placeholder shapes

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2476]
Reproducable using this test:
https://github.com/deeplearning4j/nd4j/blob/79eb921012122cbe903aecb609cf9e960234aa3b/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/autodiff/gradcheck/GradCheckReductions.java#L156-L247

Note that if we replace
```
SDVariable in = sd.var("in", new int[]{-1, d1, d2});
```
with the non-placeholder equivalent
```
SDVariable in = sd.var("in", new int[]{d0, d1, d2});
```
then the test executes (though does not pass - but that's a separate issue).

```
java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:4454)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.outputVariables(DynamicCustomOp.java:199)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.outputVariables(DynamicCustomOp.java:134)
	at org.nd4j.autodiff.gradcheck.GradCheckUtil.checkGradients(GradCheckUtil.java:149)
	at org.nd4j.autodiff.gradcheck.GradCheckUtil.checkGradients(GradCheckUtil.java:136)
	at org.nd4j.autodiff.gradcheck.GradCheckUtil.checkGradients(GradCheckUtil.java:132)
	at org.nd4j.autodiff.gradcheck.GradCheckReductions.testReductionGradients2(GradCheckReductions.java:242)
```

This seems to be due to shape inference during backward pass (calculateOutputShape() returning an empty list for one of the variables)

**Comment by AlexDBlack** [comment]
Confirmed fixed on master.
