### ISSUE TITLE
SameDiff: Unknown exception with min/max reduction ops

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2490]
I'm seeing an 'unknown exception' in the code below. This could quite possibly be due to my recent changes to reductions backprop, for min/max ops.

```
    @Test
    public void testReductionDebug() {
        Nd4j.getRandom().setSeed(12345);

        int d0 = 3;
        int d1 = 4;
        int d2 = 5;

        int reduceDim = 0;
        int[] outShape = new int[]{d1, d2};

        SameDiff sd = SameDiff.create();

        SDVariable in = sd.var("in", new int[]{-1, d1, d2});
        SDVariable label = sd.var("label", outShape);
        SDVariable second = in.mul(2);

        SDVariable reduced = sd.min("reduced", second, reduceDim);    //EXCEPTION
//        SDVariable reduced = sd.mean("reduced", second, reduceDim); //OK
//        SDVariable reduced = sd.standardDeviation("reduced", second, true, reduceDim);    //OK
//        SDVariable reduced = sd.max("reduced", second, reduceDim);  //EXCEPTION

        SDVariable add = reduced.add(1.0);

        SDVariable diff = label.sub(add);
        SDVariable sqDiff = diff.mul(diff);
        SDVariable mseLoss = sd.mean("loss", sqDiff);

        INDArray inputArr = Nd4j.rand(new int[]{d0, d1, d2});
        INDArray labelArr = Nd4j.randn(outShape);
        sd.associateArrayWithVariable(inputArr, in);
        sd.associateArrayWithVariable(labelArr, label);

        INDArray out = sd.execAndEndResult();
        sd.execBackwards();
    }
```

```
21:35:16.450 [main] WARN  org.nd4j.autodiff.samediff.SameDiff - Action op state is null
21:35:16.450 [main] INFO  org.nd4j.autodiff.samediff.SameDiff - Executing op mul_scalar
21:35:16.450 [main] INFO  org.nd4j.autodiff.samediff.SameDiff -  Input shape for in is  [3, 4, 5] Output shape for multiply_1 is  [3, 4, 5]
21:35:16.450 [main] INFO  org.nd4j.autodiff.samediff.SameDiff - Executing op max
21:35:16.450 [main] INFO  org.nd4j.autodiff.samediff.SameDiff -  Input shape for multiply_1 is  [3, 4, 5] Output shape for reduced is  [4, 5]
21:35:16.450 [main] INFO  org.nd4j.autodiff.samediff.SameDiff - Executing op add_scalar
21:35:16.450 [main] INFO  org.nd4j.autodiff.samediff.SameDiff -  Input shape for reduced is  [4, 5] Output shape for add_1 is  [4, 5]
21:35:16.450 [main] INFO  org.nd4j.autodiff.samediff.SameDiff - Executing op subtract
21:35:16.450 [main] INFO  org.nd4j.autodiff.samediff.SameDiff -  Input shape for label is  [4, 5] Input shape for add_1 is  [4, 5] Output shape for subtract_1 is  [4, 5]
21:35:16.450 [main] INFO  org.nd4j.autodiff.samediff.SameDiff - Executing op multiply
21:35:16.450 [main] INFO  org.nd4j.autodiff.samediff.SameDiff -  Input shape for subtract_1 is  [4, 5] Input shape for subtract_1 is  [4, 5] Output shape for multiply_2 is  [4, 5]
21:35:16.466 [main] INFO  org.nd4j.autodiff.samediff.SameDiff - Executing op mean
21:35:16.466 [main] INFO  org.nd4j.autodiff.samediff.SameDiff -  Input shape for multiply_2 is  [4, 5] Output shape for loss is  [1, 1]
21:35:16.466 [main] INFO  org.nd4j.autodiff.samediff.SameDiff - Executing op div_scalar
21:35:16.466 [main] INFO  org.nd4j.autodiff.samediff.SameDiff -  Input shape for one-b1cb5728-aac9-4209-af07-1943b4d0844b is  [4, 5] Output shape for divide_1 is  [4, 5]
21:35:16.466 [main] INFO  org.nd4j.autodiff.samediff.SameDiff - Executing op multiply
21:35:16.466 [main] INFO  org.nd4j.autodiff.samediff.SameDiff -  Input shape for divide_1 is  [4, 5] Input shape for one-var is  [1, 1] Output shape for multiply_2-grad is  [4, 5]
21:35:16.466 [main] INFO  org.nd4j.autodiff.samediff.SameDiff - Executing op multiply
21:35:16.466 [main] INFO  org.nd4j.autodiff.samediff.SameDiff -  Input shape for multiply_2-grad is  [4, 5] Input shape for subtract_1 is  [4, 5] Output shape for label-grad is  [4, 5]
21:35:16.466 [main] INFO  org.nd4j.autodiff.samediff.SameDiff - Executing op multiply
21:35:16.466 [main] INFO  org.nd4j.autodiff.samediff.SameDiff -  Input shape for multiply_2-grad is  [4, 5] Input shape for subtract_1 is  [4, 5] Output shape for multiply_2:1 is  [4, 5]
tz: [2, 4, 5, 5, 1, 0, 1, 99]
21:35:16.466 [main] INFO  org.nd4j.autodiff.samediff.SameDiff - Executing op add
21:35:16.466 [main] INFO  org.nd4j.autodiff.samediff.SameDiff -  Input shape for label-grad is  [4, 5] Input shape for multiply_2:1 is  [4, 5] Output shape for add_2 is  [4, 5]
21:35:16.466 [main] INFO  org.nd4j.autodiff.samediff.SameDiff - Executing op neg
21:35:16.466 [main] INFO  org.nd4j.autodiff.samediff.SameDiff -  Input shape for label-grad is  [4, 5] Output shape for reduced-grad is  [4, 5]
21:35:16.466 [main] ERROR o.n.l.c.n.ops.NativeOpExecutioner - Failed to execute. Please see above message (printed out from c++) for a possible cause of error.

java.lang.RuntimeException: Unknown exception.

	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.execCustomOpDouble(Native Method)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1565)
	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:4538)
	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:3976)
	at org.nd4j.autodiff.samediff.SameDiff.execBackwards(SameDiff.java:4093)
	at org.nd4j.autodiff.gradcheck.GradCheckReductions.testReductionGradientsDebug(GradCheckReductions.java:285)
```

**Comment by AlexDBlack** [comment]
Update here: yes, this is due to my recent changes - incorrect use of doRepeat/tile.
To fix: I need either expandDims (https://github.com/deeplearning4j/nd4j/issues/2491) or manual broadcast functionality (can't use auto-broadcast due to limitations there).

**Comment by AlexDBlack** [comment]
Seems to be fixed/passing here: https://github.com/deeplearning4j/nd4j/pull/2543
