### ISSUE TITLE
SameDiff: ExpandDims does not work

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2491]
Note that it fails with the same exception for all cases...

```
    @Test
    public void testExpandDims(){
        for( int i=0; i<=2; i++ ) {
            SameDiff sd = SameDiff.create();
            SDVariable in = sd.var("in", Nd4j.create(2, 3));
            SDVariable expanded = sd.f().expandDims(in, i);

            INDArray out = sd.execAndEndResult();
            switch (i){
                case 0:
                    assertArrayEquals(new int[]{1,2,3}, out.shape());
                    break;
                case 1:
                    assertArrayEquals(new int[]{2,1,3}, out.shape());
                    break;
                case 2:
                    assertArrayEquals(new int[]{2,3,1}, out.shape());
                    break;
                default:
                    throw new RuntimeException();
            }
        }
    }
```

```
java.lang.RuntimeException: vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)

	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.calculateOutputShapesDouble(Native Method)
	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.calculateOutputShapesDouble(Nd4jCpu.java:901)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.calculateOutputShape(NativeOpExecutioner.java:1659)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.calculateOutputShape(DynamicCustomOp.java:440)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.outputVariables(DynamicCustomOp.java:195)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.outputVariables(DynamicCustomOp.java:134)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.populateInputsAndOutputsFromSameDiff(DynamicCustomOp.java:523)
	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:4536)
	at org.nd4j.autodiff.samediff.SameDiff.execAndEndResult(SameDiff.java:3736)
	at org.nd4j.autodiff.gradcheck.GradCheckReductions.testExpandDims(GradCheckReductions.java:296)
```

**Comment by AlexDBlack** [comment]
Confirmed fixed here: https://github.com/deeplearning4j/nd4j/commit/5fd331f0daa8aaba93ef286d7b6463e04b57a9fd
