### ISSUE TITLE
Runtime casting errors with complex NDArrays

### ISSUE THREAD

**Issue by wpm** [deeplearning4j/nd4j#251]
A number of unit tests fail because of runtime casting errors between complex and real-valued NDArrays. This can be seen by running the `ComplexNDArrayTestsC` and `ComplexNDArrayTestsFortran` test cases.

Take `ComplexNDArrayTestsC.testPutComplex` as an example. It fails with the following stack:

    java.lang.ClassCastException: org.nd4j.linalg.netlib.NetlibBlasNDArray cannot be cast to org.nd4j.linalg.api.complex.IComplexNDArray
	at org.nd4j.linalg.api.complex.BaseComplexNDArray.vectorAlongDimension(BaseComplexNDArray.java:1817)
	at org.nd4j.linalg.ComplexNDArrayTestsC.testPutComplex(ComplexNDArrayTestsC.java:186) <3 internal calls>
	at org.nd4j.linalg.BaseNd4jTest.runBare(BaseNd4jTest.java:100) <16 internal calls>

The error comes from the following method in `BaseComplexNDArray`

    public IComplexNDArray vectorAlongDimension(int index, int dimension) {
        return (IComplexNDArray) super.vectorAlongDimension(index,dimension);
    }

The superclass is `BaseNDArray`, whose `vectorAlongDimension` return type is `INDArray`. The explicit cast above suppressed a compiler error, but the runtime error happens anyway. This cast in `vectorAlongDimension` appears to be the source of all these runtime errors.

Similar errors occur in the `FFTTests` when run on complex arrays.

Not sure why the runtime error is happening.  Obviously, complex arrays are going to support methods that real-valued arrays do not, however, in all the cases I've looked at, the underlying data type of the thing being cast really is a complex number, so I'm not sure why the runtime error is being generated.

**Comment by wpm** [comment]
Looking at `BaseComplexNDArray.vectorAlongDimension`.

        INDArray ret =  tensorAlongDimension(index, dimension);
        //column vector
        if(dimension == 0) {
            return Nd4j.create(ret.data(),ArrayUtil.reverseCopy(ret.shape()),ret.stride(),ret.offset());
        }

The runtime type of `ret` is `ComplexNDArray`. However, in the `dimension == 0` case we call the static `Nd4j.create` method and don't pass it any instance information telling it to create a complex-valued array. It creates a real-valued array, when then fails the type cast.

I'm not sure what this if clause is doing. Turning a row vector into a column vector? Regardless the edge case appears to be doing the low-level numerical manipulation here.

**Comment by wpm** [comment]
You can put this in `BaseNDArray.vectorAlongDimension`.

        if(dimension == 0) {
            if (this instanceof BaseComplexNDArray)
                return Nd4j.createComplex(ret.data(), ArrayUtil.reverseCopy(ret.shape()), ret.stride(), ret.offset());
            else
                return Nd4j.create(ret.data(),ArrayUtil.reverseCopy(ret.shape()),ret.stride(),ret.offset());
        }

This gets you past some of the runtime errors, but you hit other ones, ultimately because `BaseNDArray.get` is also making calls to `Nd4j.create` which return real-valued subarrays.
