### ISSUE TITLE
SameDiff: NPE with reduction gradients along dimension

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2515]
Reproducable using these tests:
https://github.com/deeplearning4j/nd4j/blob/31582d4529a4d40d5b4966e824dfc8d88165c0a8/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/autodiff/gradcheck/GradCheckReductions.java#L98-L315

Typical error/output:
```
11:18:48.290 [main] INFO  o.n.a.gradcheck.GradCheckReductions - *** Starting test: (test 9 - normmax, dimension=2)
11:18:48.290 [main] WARN  o.n.linalg.api.ops.DynamicCustomOp - No input found for subtract and op name multiply
11:18:48.290 [main] WARN  o.n.linalg.api.ops.DynamicCustomOp - No input found for subtract and op name multiply
11:18:48.292 [main] WARN  org.nd4j.autodiff.samediff.SameDiff - Action op state is null
java.lang.NullPointerException
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1523)
	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:4620)
	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:4055)
	at org.nd4j.autodiff.samediff.SameDiff.execBackwards(SameDiff.java:4172)
	at org.nd4j.autodiff.gradcheck.GradCheckUtil.checkGradients(GradCheckUtil.java:175)
	at org.nd4j.autodiff.gradcheck.GradCheckReductions.testReductionGradients2(GradCheckReductions.java:299)
```

**Comment by AlexDBlack** [comment]
Another observation: switching addi to add here avoids the NPE:
https://github.com/deeplearning4j/nd4j/blob/a3e8d0aa3766869a8dbf2a7cd636e02232772963/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/autodiff/functions/DifferentialFunction.java#L460

**Comment by AlexDBlack** [comment]
Fixed here: https://github.com/deeplearning4j/nd4j/pull/2543
