### ISSUE TITLE
ND4J throws divide by zero exception in dl4j-spark-ml 

### ISSUE THREAD

**Issue by aurelienwaite** [deeplearning4j/nd4j#253]
Here is a repeat of the issue using the scala console

scala> import org.nd4j.linalg.factory.Nd4j
import org.nd4j.linalg.factory.Nd4j

scala> val vectorA = Nd4j.create(Nd4j.createBuffer(Array(1.0,2.0,3.0)))
vectorA: org.nd4j.linalg.api.ndarray.INDArray = [ 1.00, 2.00, 3.00]

scala> val vectorB = Nd4j.create(Nd4j.createBuffer(Array(3.0,2.0,1.0)))
vectorB: org.nd4j.linalg.api.ndarray.INDArray = [ 3.00, 2.00, 1.00]

scala> Nd4j.vstack(vectorA, vectorB)
java.lang.ArithmeticException: / by zero
  at org.nd4j.linalg.api.ndarray.BaseNDArray.tensorAlongDimension(BaseNDArray.java:721)
  at org.nd4j.linalg.api.ndarray.BaseNDArray.vectorAlongDimension(BaseNDArray.java:795)
  at org.nd4j.linalg.api.ndarray.BaseNDArray.getRow(BaseNDArray.java:4201)
  at org.nd4j.linalg.factory.BaseNDArrayFactory.vstack(BaseNDArrayFactory.java:1168)
  at org.nd4j.linal

**Comment by agibsonccc** [comment]
Fixed. See tests: https://github.com/deeplearning4j/nd4j/blob/master/nd4j-tests/src/test/java/org/nd4j/linalg/shape/concat/ConcatTestsC.java#L54-53

**Comment by edudar** [comment]
I do reads from `numpy` output as `Nd4j.readNumpy(IOUtils.toInputStream(...), " ");` and see very similar exception occasionally. Stacktrace is different because of refactoring in the project I guess but it leads to the very same place after all:
```
Caused by: java.lang.ArithmeticException: / by zero
	at org.nd4j.linalg.api.ndarray.BaseNDArray.tensorssAlongDimension(BaseNDArray.java:725)
	at org.nd4j.linalg.api.ops.impl.accum.StandardDeviation.exec(StandardDeviation.java:91)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.exec(DefaultOpExecutioner.java:245)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.std(BaseNDArray.java:3357)
```
I was not able to reproduce it consistently. Same `numpy` output downloaded to dev machine was processed just fine.

**Comment by agibsonccc** [comment]
Reading from numpy is likely the issue. I haven't looked too closely with this in a while. Open a new issue please.
