### ISSUE TITLE
SameDiff strided slice: new axis test failure

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2540]
The following two tests fail:
https://github.com/deeplearning4j/nd4j/blob/86de11c3a44401a5a5afa70e43c0591b18bbcb33/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/autodiff/samediff/SameDiffTests.java#L2451-L2473

```
java.lang.RuntimeException: vector::_M_range_check: __n (which is 3) >= this->size() (which is 3)

	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.calculateOutputShapesDouble(Native Method)
	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.calculateOutputShapesDouble(Nd4jCpu.java:910)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.calculateOutputShape(NativeOpExecutioner.java:1669)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.calculateOutputShape(DynamicCustomOp.java:441)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.outputVariables(DynamicCustomOp.java:195)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.outputVariables(DynamicCustomOp.java:134)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.populateInputsAndOutputsFromSameDiff(DynamicCustomOp.java:524)
	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:4720)
	at org.nd4j.autodiff.samediff.SameDiff.execAndEndResult(SameDiff.java:3920)
	at org.nd4j.autodiff.samediff.SameDiffTests.testStridedSliceNewAxisMask(SameDiffTests.java:2458)
```

However, it seems to be considered valid in tensorflow - see d3_na_0 and d3_na_1 tests here:

![image](https://user-images.githubusercontent.com/2360237/34984015-86f7d8f2-fb03-11e7-9192-678037981574.png)

**Comment by raver119** [comment]
In your case problem is order of arguments. Masks should go first.

`SDVariable slice = sd.stridedSlice(in, new int[] {0,0,0,1,0}, new int[]{-999,0,0,0},new int[]{-999,3,4,5}, new int[]{-999,1,1,1});`

But indeed there's a problem in TF input format, when begin/end/strides are passed in as NDArrays. Looking into it.

**Comment by raver119** [comment]
Nvm my comment. With proper order there's the same bug as with TF input format.

**Comment by raver119** [comment]
Fixed, will be merged later, with other fixes/tweaks/new ops: https://github.com/deeplearning4j/libnd4j/pull/707
