### ISSUE TITLE
Nullpointer Exception when running Transforms.allEuclideanDistances using CUDA (0.9.1)

### ISSUE THREAD

**Issue by treo** [deeplearning4j/nd4j#2605]
Trying to run
```java
        System.out.println(Transforms.allEuclideanDistances(Nd4j.create(400, 20), Nd4j.ones(1, 20), 1));
```
results in 
```
Exception in thread "main" java.lang.NullPointerException
    at org.nd4j.nativeblas.LongPointerWrapper.<init>(LongPointerWrapper.java:13)
    at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.naiveExec(CudaExecutioner.java:398)
    at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.pushToGrid(CudaGridExecutioner.java:238)
    at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.processAsGridOp(CudaGridExecutioner.java:346)
    at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.exec(CudaGridExecutioner.java:674)
    at org.nd4j.linalg.ops.transforms.Transforms.allEuclideanDistances(Transforms.java:83)
    at tech.dubs.example.App.main(App.java:14)
```

**Comment by raver119** [comment]
Fixed. Will be merged a bit later.

Thanks for highlighting this issue.
