### ISSUE TITLE
Nd4j.createComplex and Nd4j.getConvolution.convn don't work

### ISSUE THREAD

**Issue by alespuh** [deeplearning4j/nd4j#2620]
#### Issue Description

I'm trying to run a code:
```
Nd4j.getConvolution.convn(Nd4j.randn(1, 100), Nd4j.ones(10).divi(10), Convolution.Type.VALID)
```
and it fails with:
```	
java.lang.UnsupportedOperationException
	at org.nd4j.linalg.api.complex.BaseComplexNDArray.putScalar(BaseComplexNDArray.java:1947)
	at org.nd4j.linalg.api.complex.BaseComplexNDArray.putScalar(BaseComplexNDArray.java:1804)
	at org.nd4j.linalg.api.complex.BaseComplexNDArray.copyFromReal(BaseComplexNDArray.java:545)
	at org.nd4j.linalg.api.complex.BaseComplexNDArray.<init>(BaseComplexNDArray.java:159)
	at org.nd4j.linalg.api.complex.BaseComplexNDArray.<init>(BaseComplexNDArray.java:167)
	at org.nd4j.linalg.cpu.nativecpu.complex.ComplexNDArray.<init>(ComplexNDArray.java:104)
	at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.createComplex(CpuNDArrayFactory.java:166)
	at org.nd4j.linalg.factory.Nd4j.createComplex(Nd4j.java:3345)
	at org.nd4j.linalg.convolution.DefaultConvolutionInstance.convn(DefaultConvolutionInstance.java:116)
	at org.nd4j.linalg.convolution.BaseConvolution.convn(BaseConvolution.java:66)
```
seems that Nd4j.createComplex(Nd4j.randn(1, 100)) doesn't work either with same stack trace
#### Version Information
* Deeplearning4j version 0.9.1
* platform is macOS High Sierra 10.13.3, cpu backend

Is it possible to run convolutions in Nd4j at the moment?

**Comment by AlexDBlack** [comment]
Complex number support is not currently supported/maintained in ND4J. The API these is a bit of a hold-over from older releases, and should be removed - https://github.com/deeplearning4j/nd4j/issues/2624


With regard to convolutions - are you looking specifically for convolutional neural network operations? If so, then yes, they are supported (though, may not be a 1-line method depending on exactly what you want).

**Comment by alespuh** [comment]
I tried to do vectorized EMA and found this implementation in python using numpy:
```
def ExpMovingAverage(values, window):
    weights = np.exp(np.linspace(-1., 0., window))
    weights /= weights.sum()
    a =  np.convolve(values, weights, mode='full')[:len(values)]
    a[:window] = a[window]
    return a
```

And then tested similar code in nd4j which led to the decsribed behaviour.
