### ISSUE TITLE
Selecting the backend with env variables, hit termination condition

### ISSUE THREAD

**Issue by xttam** [deeplearning4j/nd4j#2657]
I'm using BACKEND_PRIORITY_CPU and BACKEND_PRIORITY_GPU to select the backend, but cuda classes are always in the classpath.

The issue I found is I see a "Hit termination condition on iteration 0: score=0.0, oldScore=0.0" while working with the CPU, wheareas with the GPU it works for multiple iterations.

Here is an extract of a WARNING I'm getting that may be related:

```
00:16:50.951 [main] WARN  o.d.nn.layers.recurrent.LSTM - Could not initialize CudnnLSTMHelper
java.lang.ExceptionInInitializerError: null
	at org.deeplearning4j.nn.layers.BaseCudnnHelper$CudnnContext.<init>(BaseCudnnHelper.java:66) ~[deeplearning4j-cuda-8.0-0.9.1.jar:na]
	at org.deeplearning4j.nn.layers.recurrent.CudnnLSTMHelper$CudnnLSTMContext.<init>(CudnnLSTMHelper.java:76) ~[deeplearning4j-cuda-8.0-0.9.1.jar:na]
	at org.deeplearning4j.nn.layers.recurrent.CudnnLSTMHelper.<init>(CudnnLSTMHelper.java:156) ~[deeplearning4j-cuda-8.0-0.9.1.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_91]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_91]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_91]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_91]
	at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_91]
	at org.deeplearning4j.nn.layers.recurrent.LSTM.initializeHelper(LSTM.java:64) [deeplearning4j-nn-0.9.1.jar:na]
	at org.deeplearning4j.nn.layers.recurrent.LSTM.<init>(LSTM.java:53) [deeplearning4j-nn-0.9.1.jar:na]
	at org.deeplearning4j.nn.conf.layers.LSTM.instantiate(LSTM.java:62) [deeplearning4j-nn-0.9.1.jar:na]
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:620) [deeplearning4j-nn-0.9.1.jar:na]
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:539) [deeplearning4j-nn-0.9.1.jar:na]
```

**Comment by saudet** [comment]
You can ignore these warnings, that's another issue: https://github.com/deeplearning4j/deeplearning4j/issues/4390. They shouldn't cause anything to work incorrectly. Could you provide steps to reproduce the actual issue that you are experiencing with the termination condition?

**Comment by raver119** [comment]
Any updates on this? Or can we close this issue?
