### ISSUE TITLE
Clashing Findbugs dependencies

### ISSUE THREAD

**Issue by treo** [deeplearning4j/nd4j#2667]
#### Issue Description
When trying to build a release version their app for Android, @JayadevHaddadi ran into the issue this issue:

```
Caused by: java.util.zip.ZipException: duplicate entry: edu/umd/cs/findbugs/annotations/CheckForNull.class
        at com.android.builder.packaging.JarMerger.write(JarMerger.java:170)
        at com.android.builder.packaging.JarMerger.addJar(JarMerger.java:156)
        at com.android.builder.packaging.JarMerger.addJar(JarMerger.java:121)
        at com.android.build.gradle.internal.transforms.JarMergingTransform.transform(JarMergingTransform.java:97)
        ... 116 more
```

It is cause by two Findbugs versions being included in the dependency tree, which both use the same package structure.

```
[INFO]    \- org.nd4j:nd4j-api:jar:0.9.1:compile
[INFO]       +- org.slf4j:slf4j-api:jar:1.7.10:compile
[INFO]       +- org.nd4j:jackson:jar:0.9.1:compile
[INFO]       |  +- org.yaml:snakeyaml:jar:1.12:compile
[INFO]       |  +- org.codehaus.woodstox:stax2-api:jar:3.1.4:compile
[INFO]       |  \- joda-time:joda-time:jar:2.2:compile
[INFO]       +- org.projectlombok:lombok:jar:1.16.16:compile
[INFO]       +- org.nd4j:nd4j-context:jar:0.9.1:compile
[INFO]       |  \- org.nd4j:nd4j-common:jar:0.9.1:compile
[INFO]       |     +- commons-io:commons-io:jar:2.4:compile
[INFO]       |     +- com.github.stephenc.findbugs:findbugs-annotations:jar:1.3.9-1:compile <-------------
[INFO]       |     +- org.apache.commons:commons-math3:jar:3.4.1:compile
[INFO]       |     \- org.apache.commons:commons-lang3:jar:3.3.1:compile
[INFO]       +- net.ericaro:neoitertools:jar:1.0.0:compile
[INFO]       \- org.reflections:reflections:jar:0.9.10:compile
[INFO]          +- com.google.guava:guava:jar:15.0:compile
[INFO]          +- org.javassist:javassist:jar:3.19.0-GA:compile
[INFO]          \- com.google.code.findbugs:annotations:jar:2.0.1:compile <--------------
```

#### Version Information
Both 0.9.1 and 0.9.2-SNAPSHOT

As far as I can tell the stephenc version of findbugs is used due to licensing issues (LGPL vs Apache). And the transitive dependency to the google version is excluded in nd4j-common. Nd4j-api however, has also a direct dependency on org.reflections:reflections and doesn't exclude it. So that's how that those both version seem to end up here.

For 0.9.2-SNAPSHOT I guess the best way is to simply exclude it. For 0.9.1 it should be documented how to manually exclude it (esp. for android).

**Comment by treo** [comment]
Fixed by https://github.com/deeplearning4j/nd4j/pull/2798
