### ISSUE TITLE
KY/KX mapping issue

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/nd4j#2671]
We have mapping issue for Conv2D (and similar ops) which parse shapes of Tensors.
Here's simple python script for graph creation:

```
import tensorflow as tf
import numpy as np


input = np.ones((1, 224, 224, 3), dtype=np.float32)
w_conv0 = np.ones((5, 5, 3, 30), dtype=np.float32)
w_depth0 = np.ones((3, 3, 30, 60), dtype=np.float32)
w_conv1 = np.ones((3, 3, 1800, 30), dtype=np.float32)


l_conv0 = tf.nn.conv2d(input, w_conv0, (1, 1, 1, 1), padding="SAME")
l_max_pool0 = tf.nn.max_pool(l_conv0, ksize=(1, 5, 5, 1), strides=(1, 1, 1, 1), padding="SAME")
l_depth = tf.nn.depthwise_conv2d(l_max_pool0, w_depth0, strides=(1, 3, 3, 1), padding="SAME")
l_avg_pool0 = tf.nn.avg_pool(l_depth, ksize=(1, 5, 5, 1), strides=(1, 3, 3, 1), padding="SAME")
l_conv1 = tf.nn.conv2d(l_avg_pool0, w_conv1, strides=(1, 1, 1, 1), padding="SAME")

with tf.Session() as sess:
    print "Shape", l_conv1.shape
    print l_conv1.eval()
    tf.train.write_graph(tf.Session().graph_def, "../../models", "profiling_conv.pb.txt", True)
```

Here's java code to load graph:
```
val tg = TFGraphMapper.getInstance().importGraph(new File("/home/.../models/profiling_conv.pb.txt"));
assertNotNull(tg);
```

Here's exception:
```
java.lang.RuntimeException: java.lang.IllegalStateException: Indexes length must be > 1 for non vectors and scalars
	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.mapNodeType(TFGraphMapper.java:533)
	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.mapNodeType(TFGraphMapper.java:36)
	at org.nd4j.imports.graphmapper.BaseGraphMapper.importGraph(BaseGraphMapper.java:219)
	at org.nd4j.imports.graphmapper.BaseGraphMapper.importGraph(BaseGraphMapper.java:69)
	at org.nd4j.imports.graphmapper.BaseGraphMapper.importGraph(BaseGraphMapper.java:107)
	at org.nd4j.imports.TensorFlowImportTest.testProfConv(TensorFlowImportTest.java:916)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.IllegalStateException: Indexes length must be > 1 for non vectors and scalars
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:1751)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getInt(BaseNDArray.java:1722)
	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.mapProperty(TFGraphMapper.java:177)
	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.mapProperty(TFGraphMapper.java:36)
	at org.nd4j.imports.graphmapper.BaseGraphMapper.mapProperties(BaseGraphMapper.java:55)
	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.mapNodeType(TFGraphMapper.java:525)
	... 28 more
```

Relevant piece of code:
https://github.com/deeplearning4j/nd4j/blob/840139517dd15b55683026692c600ede1b274aa9/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/imports/graphmapper/tf/TFGraphMapper.java#L149-L185

As i can see, instead of parsing shape, for some reason mapper tries to read 0 value from filters tensor.

**Comment by agibsonccc** [comment]
@raver119 can you confirm this is fixed?

**Comment by raver119** [comment]
Oh ye, it is. 

Thank you very much.
