### ISSUE TITLE
CUDA - Orthogonal distribution issue

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2675]
See also: https://github.com/deeplearning4j/deeplearning4j/issues/4735

The following code runs fine on CPU, but fails on CUDA:
```
new OrthogonalDistribution(1.1).sample(new int[]{50,200});
```

```
org.nd4j.linalg.api.blas.BlasException: cusolverDnDgesvd failed3: -200

	at org.nd4j.linalg.jcublas.blas.JcublasLapack.dgesvd(JcublasLapack.java:782)
	at org.nd4j.linalg.api.blas.impl.BaseLapack.gesvd(BaseLapack.java:203)
	at org.nd4j.linalg.api.rng.distribution.impl.OrthogonalDistribution.sample(OrthogonalDistribution.java:238)
```

**Comment by saudet** [comment]
@rcorbish Would you have any ideas?

**Comment by rcorbish** [comment]
I'll take a look.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by saudet** [comment]
It's only in the latest source code:
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/rng/distribution/impl/OrthogonalDistribution.java
So make sure to look at 0.9.2-SNAPSHOT: https://deeplearning4j.org/snapshots

**Comment by rcorbish** [comment]
I see the 9.2 snapshot. There's a few changes to get things going, I'll keep at it. Does this work with CUDA 9.1 ?

**Comment by saudet** [comment]
CUDA version, good question, @AlexDBlack ?

I see the update() method on this line:
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/rng/distribution/impl/OrthogonalDistribution.java#L222

ClassNotFoundException probably means your artifacts are not in sync. Be sure to run "mvn -U" to get all the latest goodies.

BTW, we can get rid of the reflection shenanigans since we're not supporting CUDA 7.5 anymore.

**Comment by AlexDBlack** [comment]
I haven't tried CUDA 9.1, but I guess I can download and install it. I'd be surprised if it depended on the CUDA version though.

**Comment by AlexDBlack** [comment]
I can confirm that the exact same exception is encountered on CUDA 9.1 (version 9.1.85 on Kubuntu 17.10, GTX 970)

**Comment by rcorbish** [comment]
Cuda only supports tall arrays ( M>=N ). I'll add in a transpose to fix this
A = U S V'    so A' = V S' U'
I will need a review to see whether we can reduce any array copy/dups
