### ISSUE TITLE
MNIST iterator CUDA exception

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2689]
Kubuntu 17.04, CUDA 9.1, GTX 970 - fresh build today. It's not bad MNIST data as far as I can tell (test deletes + re-downloads; manual delete doesn't help).

Running this test:

https://github.com/deeplearning4j/deeplearning4j/blob/3634b963d92c3293ee8431c46a08b83f28a1575c/deeplearning4j-core/src/test/java/org/deeplearning4j/base/MnistFetcherTest.java

This worked for me last week. Other tests (such as gradient checks) that don't rely on MNIST seem fine.

```
o.n.l.f.Nd4jBackend - Loaded [JCublasBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 32
o.n.n.Nd4jBlas - Number of threads used for BLAS: 0
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Linux]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [12]; Memory: [7.0GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [CUBLAS]
o.n.l.j.o.e.CudaExecutioner - Device opName: [GeForce GTX 970]; CC: [5.2]; Total/free memory: [4239392768]
o.n.l.j.o.e.CudaExecutioner - Device opName: [GeForce GTX 970]; CC: [5.2]; Total/free memory: [4224516096]
o.d.b.MnistFetcher - Downloading MNIST...
CUDA error at /repos/libnd4j/blas/cuda/NativeOps.cu:948 code=73(<unknown>) "cudaStreamSynchronize(*stream)" 
CUDA error at /repos/libnd4j/blas/cuda/NativeOps.cu:4505 code=73(<unknown>) "result" 
CUDA error at /repos/libnd4j/blas/cuda/NativeOps.cu:4662 code=73(<unknown>) "result" 
CUDA error at /repos/libnd4j/blas/cuda/NativeOps.cu:4662 code=73(<unknown>) "result" 
Exception in thread "UniGC thread 0" Exception in thread "UniGC thread 1" org.nd4j.linalg.exception.ND4JException: CUDA exception happened. Terminating. Last op: [null]
	at org.nd4j.jita.allocator.pointers.cuda.cudaEvent_t.synchronize(cudaEvent_t.java:55)
	at org.nd4j.jita.flow.impl.SynchronousFlowController.waitTillFinished(SynchronousFlowController.java:106)
	at org.nd4j.jita.flow.impl.GridFlowController.waitTillFinished(GridFlowController.java:47)
	at org.nd4j.jita.flow.impl.SynchronousFlowController.waitTillReleased(SynchronousFlowController.java:203)
	at org.nd4j.jita.flow.impl.GridFlowController.waitTillReleased(GridFlowController.java:62)
	at org.nd4j.jita.handler.impl.CudaZeroHandler.purgeDeviceObject(CudaZeroHandler.java:1113)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.purgeDeviceObject(AtomicAllocator.java:515)
	at org.nd4j.jita.allocator.impl.AtomicAllocator$UnifiedGarbageCollectorThread.run(AtomicAllocator.java:714)
org.nd4j.linalg.exception.ND4JException: CUDA exception happened. Terminating. Last op: [null]
	at org.nd4j.jita.allocator.pointers.cuda.cudaEvent_t.synchronize(cudaEvent_t.java:55)
	at org.nd4j.jita.flow.impl.SynchronousFlowController.waitTillFinished(SynchronousFlowController.java:106)
	at org.nd4j.jita.flow.impl.GridFlowController.waitTillFinished(GridFlowController.java:47)
	at org.nd4j.jita.flow.impl.SynchronousFlowController.waitTillReleased(SynchronousFlowController.java:203)
	at org.nd4j.jita.flow.impl.GridFlowController.waitTillReleased(GridFlowController.java:62)
	at org.nd4j.jita.handler.impl.CudaZeroHandler.purgeDeviceObject(CudaZeroHandler.java:1113)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.purgeDeviceObject(AtomicAllocator.java:515)
	at org.nd4j.jita.allocator.impl.AtomicAllocator$UnifiedGarbageCollectorThread.run(AtomicAllocator.java:714)

java.lang.NullPointerException
	at org.nd4j.jita.allocator.pointers.CudaPointer.<init>(CudaPointer.java:22)
	at org.nd4j.jita.allocator.pointers.cuda.cudaEvent_t.<init>(cudaEvent_t.java:33)
	at org.nd4j.jita.concurrency.EventsProvider.getEvent(EventsProvider.java:34)
	at org.nd4j.jita.flow.impl.SynchronousFlowController.registerAction(SynchronousFlowController.java:249)
	at org.nd4j.jita.handler.impl.CudaZeroHandler.registerAction(CudaZeroHandler.java:1258)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.registerAction(AtomicAllocator.java:1017)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.naiveExec(CudaExecutioner.java:366)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.exec(CudaExecutioner.java:639)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.exec(CudaGridExecutioner.java:675)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.exec(CudaGridExecutioner.java:107)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.execAndReturn(DefaultOpExecutioner.java:233)
	at org.deeplearning4j.base.MnistFetcherTest.testMnist(MnistFetcherTest.java:30)
```

**Comment by AlexDBlack** [comment]
Fixed here: https://github.com/deeplearning4j/libnd4j/pull/809/files

Not sure why, but for some reason nd4j_printf was causing this crash... test now passes on CUDA after only making that change.
