### ISSUE TITLE
Duplicate op name - "select"

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2696]
The controlFlow select below was added recently... perhaps it needs a different name?

https://github.com/deeplearning4j/nd4j/blob/20e3d53dbcd56a14dd1b7572dd52d5e200e9a4ba/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/shape/Select.java#L56

https://github.com/deeplearning4j/nd4j/blob/206199b295c1adfbd72388abdd0405f6f7c9b5c8/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/controlflow/Select.java#L34

```
java.lang.ExceptionInInitializerError
	at org.nd4j.linalg.api.ops.factory.DefaultOpFactory.createTransform(DefaultOpFactory.java:298)
	at org.nd4j.linalg.api.ops.factory.DefaultOpFactory.createTransform(DefaultOpFactory.java:249)
	at org.nd4j.linalg.lossfunctions.impl.LossL1.scoreArray(LossL1.java:74)
	at org.nd4j.linalg.lossfunctions.impl.LossL1.computeScore(LossL1.java:94)
	at org.deeplearning4j.nn.layers.BaseOutputLayer.computeScore(BaseOutputLayer.java:92)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:2409)
	at org.deeplearning4j.gradientcheck.GradientCheckUtil.checkGradients(GradientCheckUtil.java:186)
	at org.deeplearning4j.gradientcheck.GradientCheckUtil.checkGradients(GradientCheckUtil.java:117)
	at org.deeplearning4j.gradientcheck.GradientCheckTestsMasking.testPerOutputMaskingMLP(GradientCheckTestsMasking.java:264)
...
Caused by: java.lang.RuntimeException: org.nd4j.linalg.exception.ND4JIllegalStateException: OpName duplicate found: select
	at org.nd4j.imports.converters.DifferentialFunctionClassHolder.<init>(DifferentialFunctionClassHolder.java:210)
	at org.nd4j.imports.converters.DifferentialFunctionClassHolder.<clinit>(DifferentialFunctionClassHolder.java:27)
	... 33 more
Caused by: org.nd4j.linalg.exception.ND4JIllegalStateException: OpName duplicate found: select
	at org.nd4j.imports.converters.DifferentialFunctionClassHolder.<init>(DifferentialFunctionClassHolder.java:145)
	... 34 more
```

**Comment by AlexDBlack** [comment]
Confirmed fixed.
