### ISSUE TITLE
SameDiff: DivOp doesn't seem to have any outputs

### ISSUE THREAD

**Issue by treo** [deeplearning4j/nd4j#2704]
While creating the reproduction code for https://github.com/deeplearning4j/nd4j/issues/2703 I ran into the issue that I can't use `SDVariable.div` as it results in the following exception:

```
Exception in thread "main" org.nd4j.linalg.exception.ND4JIllegalStateException: No output variables found!
	at org.nd4j.autodiff.samediff.SameDiff.generateOutputVariableForOp(SameDiff.java:3926)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.outputVariables(DynamicCustomOp.java:159)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.outputVariables(DynamicCustomOp.java:141)
	at org.nd4j.autodiff.functions.DifferentialFunctionFactory.div(DifferentialFunctionFactory.java:940)
	at org.nd4j.autodiff.samediff.SDVariable.div(SDVariable.java:702)
	at tech.dubs.example.App.main(App.java:17)
```

It can be reproduced with this code:

```java
package tech.dubs.example;

import org.nd4j.autodiff.samediff.SDVariable;
import org.nd4j.autodiff.samediff.SameDiff;
import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.factory.Nd4j;

public class App 
{
    public static void main( String[] args ) {
        final INDArray networkOutput = Nd4j.linspace(1, 10, 10).reshape(2, 5);

        final SameDiff sd = SameDiff.create();
        final SDVariable sdNetworkOutput = sd.var("networkOutput", networkOutput);
        sdNetworkOutput.div(sdNetworkOutput);

        System.out.println(sd.execAndEndResult());
    }
}
```

**Comment by raver119** [comment]
Can you please confirm if it's still the problem on current master?

**Comment by treo** [comment]
Works fine now.
