### ISSUE TITLE
ExceptionInInitializerError

### ISSUE THREAD

**Issue by fcnorman** [deeplearning4j/nd4j#2723]
#### ExceptionInInitializerError caused by java.nio.channels.OverlappingFileLockException

Training the icu-mortality dl4j model on 7 docker containers running on a Mac.
- Node 1:  hadoop-3.0.0 master node with spark-2.3.0 master
- Nodes 2-6:  hadoop-3.0.0 slave nodes with spark 2.3.0 workers
- Node 7: dl4j ui

Running with the Spark master set to "yarn-cluster".  physionet2012 data files being read from hdfs.

I expected that the training job would finish.
Instead, after 3 minutes, the job failed with:

```
18/03/09 18:54:37 INFO Client: Application report for application_1520619475936_0001 (state: RUNNING)
18/03/09 18:54:38 INFO Client: Application report for application_1520619475936_0001 (state: FINISHED)
18/03/09 18:54:38 INFO Client:
	 client token: N/A
	 diagnostics: User class threw exception: java.lang.ExceptionInInitializerError
	at org.nd4j.linalg.cpu.nativecpu.blas.CpuBlas.setMaxThreads(CpuBlas.java:117)
	at org.nd4j.nativeblas.Nd4jBlas.<init>(Nd4jBlas.java:35)
	at org.nd4j.linalg.cpu.nativecpu.blas.CpuBlas.<init>(CpuBlas.java:12)
	at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.createBlas(CpuNDArrayFactory.java:89)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.blas(BaseNDArrayFactory.java:67)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.getEnvironmentInformation(NativeOpExecutioner.java:1176)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.printEnvironmentInformation(DefaultOpExecutioner.java:562)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6210)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6087)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:201)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.seed(NeuralNetConfiguration.java:777)
	at org.deeplearning4j.icumortality.SparkLSTMClinicalTimeSeriesClassificationExampleHDFS.entryPoint(SparkLSTMClinicalTimeSeriesClassificationExampleHDFS.java:102)
	at org.deeplearning4j.rnn.SparkMainForLocalSparkClusterDeploy.mainEntryPoint(SparkMainForLocalSparkClusterDeploy.java:67)
	at org.deeplearning4j.rnn.SparkMainForLocalSparkClusterDeploy.main(SparkMainForLocalSparkClusterDeploy.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$4.run(ApplicationMaster.scala:706)
Caused by: java.nio.channels.OverlappingFileLockException
	at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
	at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
	at sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1063)
	at java.nio.channels.FileChannel.lock(FileChannel.java:1053)
	at org.bytedeco.javacpp.Loader.cacheResource(Loader.java:429)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:944)
	at org.bytedeco.javacpp.Loader.load(Loader.java:765)
	at org.bytedeco.javacpp.Loader.load(Loader.java:684)
	at org.bytedeco.javacpp.openblas.<clinit>(openblas.java:10)
	... 19 more

	 ApplicationMaster host: 172.22.0.4
	 ApplicationMaster RPC port: 0
	 queue: root.hduser
	 start time: 1520621562364
	 final status: FAILED
	 tracking URL: http://master:18088/proxy/application_1520619475936_0001/
	 user: hduser
Exception in thread "main" org.apache.spark.SparkException: Application application_1520619475936_0001 finished with failed status
	at org.apache.spark.deploy.yarn.Client.run(Client.scala:1159)
	at org.apache.spark.deploy.yarn.YarnClusterApplication.start(Client.scala:1518)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:879)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:197)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:227)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:136)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
18/03/09 18:54:38 INFO ShutdownHookManager: Shutdown hook called
18/03/09 18:54:38 INFO ShutdownHookManager: Deleting directory /tmp/spark-678c0fac-5e7a-4a96-bec9-5bb0a1c08a45
18/03/09 18:54:38 INFO ShutdownHookManager: Deleting directory /tmp/spark-89c98808-c3a9-4dd1-b1d0-ddfb91167e49
```

#### Version Information
hadoop-3.0.0 built with native libraries for Ubuntu 14.04 (the OS for the docker containers)
spark-2.3.0
dl4j 0.9.1
scala 2.11
java 8
all running on Mac OS 10.13.3
running latest docker for mac 17.12.0-ce-mac55 (23011)
CUDA on Mac installed (CUDA Driver Version: 387.128), but not used.  Using Cpu backend.
NVIDIA driver version installed 387.10.10.10.25.156, but not being used.  Using Cpu backend.

#### Contributing

Can provide code snippets as needed.

**Comment by fcnorman** [comment]
The stack trace shows it is dying during the building of the neural net.  Here is the network configuration:

```
// Neural Network Configuration

        MultiLayerConfiguration conf = new NeuralNetConfiguration.Builder()
                .seed(RANDOM_SEED)
                .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
                .learningRate(LEARNING_RATE)
                .weightInit(WeightInit.XAVIER)
                .updater(Updater.ADAM)
                .dropOut(0.25)
                .list()
                .layer(0, new GravesLSTM.Builder().nIn(NB_INPUTS).nOut(lstmLayerSize).activation(Activation.TANH).build())
                .layer(1, new RnnOutputLayer.Builder(LossFunctions.LossFunction.MCXENT).activation(Activation.SOFTMAX)
                        .nIn(lstmLayerSize).nOut(nClasses).build())
                .pretrain(false).backprop(true)
                .build();

        // Set Training Master

        TrainingMaster tm = new ParameterAveragingTrainingMaster.Builder(1)
                .averagingFrequency(3)
                .workerPrefetchNumBatches(2)
                .batchSizePerWorker(BATCH_SIZE)
                .build();

```

**Comment by fcnorman** [comment]
yarn logs are here:

[pastebin yarn logs](https://pastebin.com/tbbTKDJq)

**Comment by saudet** [comment]
> Caused by: java.nio.channels.OverlappingFileLockException

Oops, this has been fixed in commit https://github.com/bytedeco/javacpp/commit/3d182d51e3ac5697bc7548c9476200ad366a896e

Add a dependency on JavaCPP 1.4.1-SNAPSHOT (or 1.4.1 after the release).

**Comment by fcnorman** [comment]
That was fast!  Thank you!
