### ISSUE TITLE
ND4J CUDA error: Can't allocate [DEVICE] allocation buffer memory! 

### ISSUE THREAD

**Issue by nfrik** [deeplearning4j/nd4j#2728]
Runnin ND4J LapackTest on CUDA returns initialization error:

java.lang.ExceptionInInitializerError
	at com.nd4jtest.LapackTest.testSgetrf1(LapackTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6212)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6087)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:201)
	... 23 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6188)
	... 25 more
Caused by: java.lang.ExceptionInInitializerError
	at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.<init>(JCublasNDArrayFactory.java:86)
	... 30 more
Caused by: java.lang.IllegalStateException: Can't allocate [DEVICE] allocation buffer memory!
	at org.nd4j.jita.allocator.context.impl.BasicContextPool.getDeviceBuffers(BasicContextPool.java:290)
	at org.nd4j.jita.allocator.context.impl.LimitedContextPool.fillPoolWithResources(LimitedContextPool.java:95)
	at org.nd4j.jita.allocator.context.impl.LimitedContextPool.<init>(LimitedContextPool.java:56)
	at org.nd4j.jita.handler.impl.CudaZeroHandler.<init>(CudaZeroHandler.java:131)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.<init>(AtomicAllocator.java:128)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.<clinit>(AtomicAllocator.java:74)
	... 31 more

System parameters:
ND4J version 0.9.1
Cuda 8.0.61
NVIDIA driver 387.34
OS: Ubuntu 16.04

**Comment by raver119** [comment]
What's your GPU?

**Comment by nfrik** [comment]
The system has two 1080Ti cards.

**Comment by raver119** [comment]
show your pom.xml and source code.

**Comment by nfrik** [comment]
pom.xml:
`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.nd4jtest</groupId>
  <artifactId>nd4jtest</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>nd4jtest</name>
  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <nd4j.version>0.9.1</nd4j.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.nd4j</groupId>
      <artifactId>nd4j-cuda-8.0</artifactId>
      <version>${nd4j.version}</version>
    </dependency>

    <dependency>
      <groupId>org.nd4j</groupId>
      <artifactId>nd4j-cuda-8.0-platform</artifactId>
      <version>${nd4j.version}</version>
    </dependency>

  </dependencies>
</project>
`
LapackTest.java:
`package com.nd4jtest;

import org.junit.Ignore;
import org.junit.Test;
import org.nd4j.linalg.api.iter.NdIndexIterator;
import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.factory.Nd4j;

import static org.junit.Assert.assertEquals;


/**
 * @author rcorbish
 */
@Ignore
public class LapackTest {

    private java.util.Random rng = new java.util.Random(1230);

    @Test
    public void testSgetrf1() {
        int m = 3;
        int n = 3;
        INDArray arr = Nd4j.create(new float[]{
                        1.f, 4.f, 7.f,
                        2.f, 5.f, -2.f,
                        3.f, 0.f, 3.f},
                new int[]{m, n}, 'f');

        Nd4j.getBlasWrapper().lapack().getrf(arr);

        // The above matrix factorizes to :
        //   7.00000  -2.00000   3.00000
        //   0.57143   6.14286  -1.71429
        //   0.14286   0.37209   3.20930

        assertEquals(7.00000f, arr.getFloat(0), 0.00001f);
        assertEquals(0.57143f, arr.getFloat(1), 0.00001f);
        assertEquals(0.14286f, arr.getFloat(2), 0.00001f);
        assertEquals(-2.00000f, arr.getFloat(3), 0.00001f);
        assertEquals(6.14286f, arr.getFloat(4), 0.00001f);
        assertEquals(0.37209f, arr.getFloat(5), 0.00001f);
        assertEquals(3.00000f, arr.getFloat(6), 0.00001f);
        assertEquals(-1.71429f, arr.getFloat(7), 0.00001f);
        assertEquals(3.20930f, arr.getFloat(8), 0.00001f);
    }

    @Test
    public void testGetrf() {
        int m = 150;
        int n = 100;
        float f[] = new float[m * n];
        for (int i = 0; i < f.length; i++)
            f[i] = rng.nextInt(5) + 1;
        // there is a very very small (non-zero) chance that the random matrix is singular
        // and may fail a test
        long start = System.currentTimeMillis();

        INDArray IPIV = null;
        INDArray arr = null;
        final int N = 100;
        for (int i = 0; i < N; i++) {
            arr = Nd4j.create(f, new int[]{m, n}, 'f');
            IPIV = Nd4j.getBlasWrapper().lapack().getrf(arr);
        }

        INDArray L = Nd4j.getBlasWrapper().lapack().getLFactor(arr);
        INDArray U = Nd4j.getBlasWrapper().lapack().getUFactor(arr);
        INDArray P = Nd4j.getBlasWrapper().lapack().getPFactor(m, IPIV);

        INDArray orig = P.mmul(L).mmul(U);

        assertEquals("PxLxU is not the expected size - rows", orig.size(0), arr.size(0));
        assertEquals("PxLxU is not the expected size - cols", orig.size(1), arr.size(1));

        arr = Nd4j.create(f, new int[]{m, n}, 'f');
        for (int r = 0; r < orig.size(0); r++) {
            for (int c = 0; c < orig.size(1); c++) {
                assertEquals("Original & recombined matrices differ", orig.getFloat(r, c), arr.getFloat(r, c), 0.001f );
            }
        }
    }


    @Test
    public void testSvdTallFortran() {
        testSvd(5, 3, 'f');
    }

    @Test
    public void testSvdTallC() {
        testSvd(5, 3, 'c');
    }


    @Test
    public void testSvdWideFortran() {
        testSvd(3, 5, 'f');
    }


    @Test
    public void testSvdWideC() {
        testSvd(3, 5, 'c');
    }


    @Test
    public void testEigsFortran() {
        testEv(5, 'f');
    }


    @Test
    public void testEigsC() {
        testEv(5, 'c');
    }

    //
    // Helper functions - not direct test cases
    //
    void testSvd(int M, int N, char matrixOrder) {
        INDArray A = Nd4j.rand(M, N, matrixOrder);
        INDArray Aorig = A.dup();
        INDArray U = Nd4j.create(M, M, matrixOrder);
        INDArray S = Nd4j.create(N, matrixOrder);
        INDArray VT = Nd4j.create(N, N, matrixOrder);

        Nd4j.getBlasWrapper().lapack().gesvd(A, S, U, VT);

        INDArray SS = Nd4j.create(M, N);
        for (int i = 0; i < Math.min(M, N); i++) {
            SS.put(i, i, S.getDouble(i));
        }

        INDArray AA = U.mmul(SS).mmul(VT);
        NdIndexIterator iter = new NdIndexIterator(AA.shape());
        while(iter.hasNext()){
            int[] pos = iter.next();
            assertEquals("SVD did not factorize properly", AA.getDouble(pos), Aorig.getDouble(pos), 1e-5);
        }
    }

    void testEv(int N, char matrixOrder) {
        INDArray A = Nd4j.rand(N, N, matrixOrder);
        for (int r = 1; r < N; r++) {
            for (int c = 0; c < r; c++) {
                double v = A.getDouble(r, c);
                A.putScalar(c, r, v);
            }
        }

        INDArray Aorig = A.dup();
        INDArray V = Nd4j.create(N);

        Nd4j.getBlasWrapper().lapack().syev('V', 'U', A, V);

        INDArray VV = Nd4j.create(N, N);
        for (int i = 0; i < N; i++) {
            VV.put(i, i, V.getDouble(i));
        }

        INDArray L = Aorig.mmul(A);
        INDArray R = A.mmul(VV);

        NdIndexIterator iter = new NdIndexIterator(L.shape());
        while(iter.hasNext()){
            int[] pos = iter.next();
            assertEquals("SVD did not factorize properly", L.getDouble(pos), R.getDouble(pos), 1e-5);
        }
    }

}`

**Comment by raver119** [comment]
Please use https://gist.github.com/

Otherwise it's barely readable as you can see.

**Comment by nfrik** [comment]
Ok the output is reformatted.

**Comment by raver119** [comment]
Can you please remove nd4j-cuda-8.0 dependency, and keep only platform dep?

Also, please tell me, are you building jar and running on the same box, or building on one box, and running on another one?

**Comment by nfrik** [comment]
After removing nd4j-cuda-8.0 dependency error changed:
```
java.lang.ExceptionInInitializerError
	at com.nd4jtest.LapackTest.testSgetrf1(LapackTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6212)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6087)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:201)
	... 23 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6188)
	... 25 more
Caused by: java.lang.ExceptionInInitializerError
	at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.<init>(JCublasNDArrayFactory.java:86)
	... 30 more
Caused by: java.lang.IllegalStateException: Can't create new cuBLAS handle! cusolverDn errorCode: [7] from cusolverDnCreate()
	at org.nd4j.jita.allocator.context.impl.BasicContextPool.createNewSolverHandle(BasicContextPool.java:205)
	at org.nd4j.jita.allocator.context.impl.LimitedContextPool.fillPoolWithResources(LimitedContextPool.java:91)
	at org.nd4j.jita.allocator.context.impl.LimitedContextPool.<init>(LimitedContextPool.java:56)
	at org.nd4j.jita.handler.impl.CudaZeroHandler.<init>(CudaZeroHandler.java:131)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.<init>(AtomicAllocator.java:128)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.<clinit>(AtomicAllocator.java:74)
	... 31 more
```

I build jar on the same machine and java 8.

**Comment by raver119** [comment]
That's perfect. 

Show me `nvidia-smi` output please, and `nvcc --version` output as well.

**Comment by raver119** [comment]
and one more thing: is libcublas installed? it's separate .deb if you're using apt for installation instead of nVidia website

**Comment by nfrik** [comment]
nvcc --version:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
```
nvidia-smi:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 387.34                 Driver Version: 387.34                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:01:00.0  On |                  N/A |
| 28%   39C    P8    14W / 250W |  10709MiB / 11171MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:02:00.0 Off |                  N/A |
| 28%   36C    P8    16W / 250W |  10623MiB / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       494      G   ...ntEnd/Binaries/Linux-x86-64/Mathematica     7MiB |
|    0      1898      G   /usr/lib/xorg/Xorg                           504MiB |
|    0      3439      G   /opt/teamviewer/tv_bin/TeamViewer             15MiB |
|    0      3559      G   compiz                                       153MiB |
|    0      4937      G   ...-token=D5A5A768A708E9EBE21A04E2AD649278   189MiB |
|    0      8208      G   ...-token=E1B2AC4838D9174E872EFE1D71933C01    58MiB |
|    0     10073      C   ...ck/anaconda3/envs/tensorflow/bin/python  9767MiB |
|    1     10073      C   ...ck/anaconda3/envs/tensorflow/bin/python 10611MiB |
+-----------------------------------------------------------------------------+

```

Yes I have libcublas binaries in /usr/local/cuda-8.0/lib64/ folder.

**Comment by raver119** [comment]
Nothing to do here.

Both your gpus are occupied by TF. So, cuBLAS fails to initialize.

**Comment by nfrik** [comment]
Thank you for pointing that out.
