### ISSUE TITLE
PANIC 1 inf value on std.min(1)

### ISSUE THREAD

**Issue by xttam** [deeplearning4j/nd4j#2733]
I'm working with version 0.9.1

I'm getting "P.A.N.I.C.! Op.Z() contains 1 Inf value(s)" in std.min(1) as shown below.

On a side note, the backend is cuda and the datatype is float. if I change the datatype to double it works, but I think it shouldn't be necessary. Also I tried with cpu backend and it's strange, in that case it works but the first element of std is 0.44, which is wrong, all values in the first column are the same so std should be 0.

Backtrace: 

```
Exception in thread "main" org.nd4j.linalg.exception.ND4JIllegalStateException: P.A.N.I.C.! Op.Z() contains 1 Inf value(s)
	at org.nd4j.linalg.api.ops.executioner.OpExecutionerUtil.checkForInf(OpExecutionerUtil.java:99)
	at org.nd4j.linalg.api.ops.executioner.OpExecutionerUtil.checkForInf(OpExecutionerUtil.java:119)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.profilingHookOut(DefaultOpExecutioner.java:478)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.invoke(CudaExecutioner.java:1378)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.pushToGrid(CudaGridExecutioner.java:245)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.processAsGridOp(CudaGridExecutioner.java:346)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.exec(CudaGridExecutioner.java:112)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.assign(BaseNDArray.java:3296)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.valueArrayOf(BaseNDArrayFactory.java:953)
	at org.nd4j.linalg.factory.Nd4j.valueArrayOf(Nd4j.java:5365)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.buildZ(CudaGridExecutioner.java:629)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.exec(CudaGridExecutioner.java:673)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.min(BaseNDArray.java:3894)
	at org.nd4j.linalg.dataset.api.preprocessor.stats.DistributionStats.<init>(DistributionStats.java:38)
	at org.nd4j.linalg.dataset.api.preprocessor.stats.DistributionStats$Builder.build(DistributionStats.java:149)
	at org.nd4j.linalg.dataset.api.preprocessor.stats.DistributionStats$Builder.build(DistributionStats.java:71)
	at org.nd4j.linalg.dataset.api.preprocessor.AbstractDataSetNormalizer.fit(AbstractDataSetNormalizer.java:98)
	at com.trader.optimizer.model.Model.prepareDatasets(Model.java:291)
```

Std is this:

```
[0.00,  27.37,  267665904.00,  27.38,  27.35,  27.37,  27.37,  4008.84,  1120756.88,  25.27,  461239456.00,  25.28,  25.25,  25.27,  25.27,  7086.83,  1932493.50,  77.48,  972040.94,  90.70,  1752469.00,  28.47,  0.18,  0.08,  0.25,  0.11,  0.14,  0.06,  0.20,  0.08,  6605.01,  6536.96,  6626.22,  6626.22,  0.00,  1.36,  0.18,  0.08,  987677.88,  4034.36,  0.45,  0.19,  1320399.12,  2578.25,  0.63,  0.26,  1573133.50,  5489.06,  0.25,  0.11,  1674888.25,  7416.12,  0.61,  0.25,  2611585.50,  7691.12,  0.88,  0.37,  2658110.75,  12748.04,  0.07,  0.03,  178916.41,  14.84,  0.30,  0.13,  654585.75,  48.50,  0.51,  0.21,  1013165.69,  78.86,  0.09,  0.04,  373189.12,  12.01,  0.40,  0.17,  1172857.25,  47.64,  0.68,  0.28,  1428176.75,  66.76,  14.18,  4034.41,  22.81,  2578.46,  27.65,  5489.19,  16.56,  7416.17,  26.81,  7691.27,  30.22,  12748.17,  0.57,  0.24,  0.16,  0.07,  0.23,  0.10,  27.37,  27.38,  27.39,  27.36,  27.34,  25.27,  25.28,  25.30,  25.25,  25.23,  33.00,  33.43,  114.31,  152.03,  0.90,  1.52,  0.86,  0.94,  1.48,  0.81,  2.49,  1.34,  1.56,  1.80,  1.07,  0.97,  1.86,  1.11,  0.99,  2.34,  1.30,  1.44,  1.88,  1.17,  1.00,  1.85,  1.17,  0.95,  0.32,  77.48,  77.48,  0.07,  0.25,  1202764.00,  1283523.75,  154675.81,  0.33,  90.70,  90.71,  0.09,  0.24,  2274444.00,  2369492.75,  304881.34,  0.11,  0.05,  337141.78,  30.80,  0.15,  0.06,  690418.19,  57.00,  0.24,  0.10,  476815.72,  39.71,  0.32,  0.13,  583211.62,  25.26,  0.33,  0.14,  869660.38,  46.78,  0.45,  0.19,  1595908.25,  43.67,  0.08,  0.04,  0.11,  0.05,  0.21,  0.09,  0.29,  0.12,  0.06,  0.02,  0.09,  0.04,  0.18,  0.07,  0.08,  0.04,  0.17,  0.07,  0.08,  0.03,  0.13,  0.05,  0.25,  0.11,  0.12,  0.05,  0.24,  0.10,  0.20,  0.08,  0.21,  0.09,  0.26,  0.11,  0.21,  0.09,  0.25,  0.11,  0.28,  0.12,  0.30,  0.12,  0.36,  0.15,  0.30,  0.13,  0.36,  0.15,  0.16,  0.07,  198266.28,  82860.80,  0.23,  0.10,  399862.62,  166899.62,  5.30,  2.83,  4.54,  2.37]
```

**Comment by raver119** [comment]
Can you please post your source code i could run locally?
