### ISSUE TITLE
Cannot resolve nd4j-cuda-8.0-platform in sbt

### ISSUE THREAD

**Issue by Atry** [deeplearning4j/nd4j#2767]
#### Issue Description

``` 
// build.sbt
libraryDependencies += "org.nd4j" % "nd4j-cuda-8.0-platform" % "0.9.1"
```

- expected behavior

No error

- encountered behavior

```
$ sbt update
[info] Updated file /private/tmp/merged/project/build.properties: set sbt.version to 1.1.1
[info] Loading settings from idea.sbt ...
[info] Loading global plugins from /Users/twer/.sbt/1.0/plugins
[info] Updating ProjectRef(uri("file:/Users/twer/.sbt/1.0/plugins/"), "global-plugins")...
[info] Done updating.
[info] Loading project definition from /private/tmp/merged/project
[info] Updating ProjectRef(uri("file:/private/tmp/merged/project/"), "merged-build")...
[info] Done updating.
[info] Loading settings from build.sbt ...
[info] Set current project to merged (in build file:/private/tmp/merged/)
[info] Updating ...
[info] downloading https://repo1.maven.org/maven2/org/nd4j/nd4j-cuda-8.0-platform/0.9.1/nd4j-cuda-8.0-platform-0.9.1.jar ...
[info] downloading https://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/cuda-platform/8.0-6.0-1.3/cuda-platform-8.0-6.0-1.3.jar ...
[info] downloading https://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/cuda/8.0-6.0-1.3/cuda-8.0-6.0-1.3-macosx-x86_64.jar ...
[info] downloading https://repo1.maven.org/maven2/org/nd4j/nd4j-cuda-8.0/0.9.1/nd4j-cuda-8.0-0.9.1-linux-ppc64le.jar ...
[info] 	[SUCCESSFUL ] org.nd4j#nd4j-cuda-8.0-platform;0.9.1!nd4j-cuda-8.0-platform.jar (1725ms)
[info] 	[SUCCESSFUL ] org.bytedeco.javacpp-presets#cuda-platform;8.0-6.0-1.3!cuda-platform.jar (1949ms)
[info] 	[SUCCESSFUL ] org.bytedeco.javacpp-presets#cuda;8.0-6.0-1.3!cuda.jar (11674ms)
[info] downloading https://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/cuda/8.0-6.0-1.3/cuda-8.0-6.0-1.3-linux-x86_64.jar ...
[info] 	[SUCCESSFUL ] org.bytedeco.javacpp-presets#cuda;8.0-6.0-1.3!cuda.jar (7262ms)
[info] downloading https://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/cuda/8.0-6.0-1.3/cuda-8.0-6.0-1.3-windows-x86_64.jar ...
[info] 	[SUCCESSFUL ] org.bytedeco.javacpp-presets#cuda;8.0-6.0-1.3!cuda.jar (8012ms)
[info] downloading https://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/cuda/8.0-6.0-1.3/cuda-8.0-6.0-1.3.jar ...
[info] 	[SUCCESSFUL ] org.bytedeco.javacpp-presets#cuda;8.0-6.0-1.3!cuda.jar (1465ms)
[info] downloading https://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/cuda/8.0-6.0-1.3/cuda-8.0-6.0-1.3-linux-ppc64le.jar ...
[info] 	[SUCCESSFUL ] org.bytedeco.javacpp-presets#cuda;8.0-6.0-1.3!cuda.jar (9667ms)
[warn] 	Detected merged artifact: [NOT FOUND  ] org.bytedeco.javacpp-presets#cuda;8.0-6.0-1.3!cuda.jar (330ms).
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/cuda/8.0-6.0-1.3/cuda-8.0-6.0-1.3-${dependency.platform}.jar
[info] 	[SUCCESSFUL ] org.nd4j#nd4j-cuda-8.0;0.9.1!nd4j-cuda-8.0.jar (184176ms)
[info] downloading https://repo1.maven.org/maven2/org/nd4j/nd4j-cuda-8.0/0.9.1/nd4j-cuda-8.0-0.9.1.jar ...
[info] 	[SUCCESSFUL ] org.nd4j#nd4j-cuda-8.0;0.9.1!nd4j-cuda-8.0.jar (1578ms)
[info] downloading https://repo1.maven.org/maven2/org/nd4j/nd4j-cuda-8.0/0.9.1/nd4j-cuda-8.0-0.9.1-linux-x86_64.jar ...
[info] 	[SUCCESSFUL ] org.nd4j#nd4j-cuda-8.0;0.9.1!nd4j-cuda-8.0.jar (233303ms)
[info] downloading https://repo1.maven.org/maven2/org/nd4j/nd4j-cuda-8.0/0.9.1/nd4j-cuda-8.0-0.9.1-macosx-x86_64.jar ...
[info] 	[SUCCESSFUL ] org.nd4j#nd4j-cuda-8.0;0.9.1!nd4j-cuda-8.0.jar (213468ms)
[info] downloading https://repo1.maven.org/maven2/org/nd4j/nd4j-cuda-8.0/0.9.1/nd4j-cuda-8.0-0.9.1-windows-x86_64.jar ...
[info] 	[SUCCESSFUL ] org.nd4j#nd4j-cuda-8.0;0.9.1!nd4j-cuda-8.0.jar (235485ms)
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::              FAILED DOWNLOADS            ::
[warn] 	:: ^ see resolution messages for details  ^ ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.bytedeco.javacpp-presets#cuda;8.0-6.0-1.3!cuda.jar
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[error] sbt.librarymanagement.ResolveException: download failed: org.bytedeco.javacpp-presets#cuda;8.0-6.0-1.3!cuda.jar
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:331)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:205)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
[error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:190)
[error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:46)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:99)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:112)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:112)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:95)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:126)
[error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2383)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (update) sbt.librarymanagement.ResolveException: download failed: org.bytedeco.javacpp-presets#cuda;8.0-6.0-1.3!cuda.jar
[error] Total time: 880 s, completed Mar 20, 2018 12:10:16 PM
```

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version - 0.9.1
* platform information (OS, etc): Failed on both Ubuntu 16.04 and macOS
* CUDA version, if used - 8.0
* NVIDIA driver version, if in use - N/A

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by saudet** [comment]
https://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/cuda/8.0-6.0-1.3/cuda-8.0-6.0-1.3.jar works just fine here. It doesn't work from your end?

**Comment by saudet** [comment]
> https://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/cuda/8.0-6.0-1.3/cuda-8.0-6.0-1.3-${dependency.platform}.jar
Ah yes this happens with Ivy sometimes. Deleting the cache usually works around that.
