### ISSUE TITLE
Indexing NDArrays using NDArrayIndex...indexes will result in OutOfMemorException

### ISSUE THREAD

**Issue by tmbo** [deeplearning4j/nd4j#278]
What I did: Current master of nd4j + deeplearning4j + canova
Create a simple network, try to run it.

It fails rather quickly with an OutOfMemory error. When trying to index `NDArrays` with the newly introduced `NDArrayIndex...indexes` the shape of the array to be returned is calculated wrongly resulting in the above error. I pinned it down to the recent changes in `ShapeOffsetResolution.java`. 

Along the way the passed `indexes` change their shape (e.g. passing a shape of (4000) for the `indexes` to NDArray.get will result in a shape of (4000,1) in `ShapeOffsetResolution.exec`, I assume due to the `...` syntax).

Example: Weight vector of shape (1,400000) and indices (0,...,300000) which have shape (300000). This will result in an allocation of an array of size (300000, 400000) hence the OutOfMemory.

https://github.com/deeplearning4j/nd4j/blob/ee58adee922cf50737f5271c5c0286ac7ff7341c/nd4j-api/src/main/java/org/nd4j/linalg/api/ndarray/BaseNDArray.java#L3759

https://github.com/deeplearning4j/nd4j/blob/ee58adee922cf50737f5271c5c0286ac7ff7341c/nd4j-api/src/main/java/org/nd4j/linalg/indexing/ShapeOffsetResolution.java#L35

**Comment by AlexDBlack** [comment]
Could you post a full stack trace for the OutOfMemory exception? Network config wouldn't hurt either.

**Comment by tmbo** [comment]
Stacktrace:
```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:194)
	at org.nd4j.linalg.api.buffer.FloatBuffer.<init>(FloatBuffer.java:39)
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createFloat(DefaultDataBufferFactory.java:42)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:884)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:872)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:1468)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:2725)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.create(BaseNDArray.java:1629)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.get(BaseNDArray.java:3678)
	at org.deeplearning4j.nn.layers.BaseLayer.setParams(BaseLayer.java:304)
	at org.deeplearning4j.optimize.solvers.BackTrackLineSearch.setScoreFor(BackTrackLineSearch.java:133)
	at org.deeplearning4j.optimize.solvers.BackTrackLineSearch.optimize(BackTrackLineSearch.java:221)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.optimize(BaseOptimizer.java:156)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.layers.BaseLayer.fit(BaseLayer.java:493)
	at org.deeplearning4j.nn.layers.feedforward.rbm.RBM.fit(RBM.java:395)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.pretrain(MultiLayerNetwork.java:215)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1250)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1283)
```

I created a minimal failing example at https://gist.github.com/tmbo/2391e493d998d611e989

**Comment by tmbo** [comment]
Your change on the branch in line https://github.com/deeplearning4j/deeplearning4j/commit/95d19bae67b0179825c0699025f215d35680059e#diff-9692eca0251806b9353c6edd74cc4d90R302 will probably fix it.

**Comment by AlexDBlack** [comment]
Thanks, that helps a lot. Yep, indexing in setParams() - i.e., single indexing on a row vector; not sure if the convention is to consider this incorrect (i.e., should throw an exception here), or whether this is a valid/special case that is not being handled correctly.

**Comment by tmbo** [comment]
It would be good if there is a check in nd4j. The thing is, if this doesn't lead to OutOfMemory, eg. if the dimensions are smaller this will lead to other errors eg.

```
Exception in thread "main" java.lang.IllegalStateException: Parameter W should have been of length 1000 but was 1254000
	at org.deeplearning4j.nn.layers.BaseLayer.setParams(BaseLayer.java:306)
```

**Comment by agibsonccc** [comment]
Yeah I can fix this at the nd4j leve.

**Comment by agibsonccc** [comment]
Fixed. https://github.com/deeplearning4j/nd4j/commit/3e6f46d9dedd42c256d4e9ce9315d808b1ee4b1b
