### ISSUE TITLE
Im2Col (OpExecutioner?) integer overflow

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2833]
https://gist.github.com/yquemener/5bcfade9cafa7ff6bd23f03f5720e60e

Looks like integer indexing might be used somewhere here? This was produced with VGG and a large batch size (1000 examples).

**Comment by raver119** [comment]
Post code that reproduces this exception please. But yes, that looks like request for big array allocation somewhere 

With best regards,
Vyacheslav K.

**Comment by AlexDBlack** [comment]
Hm... I assumed this would be easy to reproduce. Apparently not :/
```
        INDArray img = Nd4j.create(256, 32, 256, 256);
        INDArray im2col = Convolution.im2col(img, new int[]{64, 64}, new int[]{1,1}, new int[]{0,0});
```
Gives OOM as expected, but no overflow...
```
Exception in thread "main" java.lang.OutOfMemoryError: Cannot allocate new FloatPointer(1249869037568): totalBytes = 2G, physicalBytes = 2G
```
That's approx 1.2TB by my count :)

As for using VGG16 itself: I can crash the JVM with large input size (on 1.0.0-alpha), but can't reproduce it...
```
        ZooModel zooModel = new VGG16();
        ComputationGraph vgg16 = (ComputationGraph) zooModel.initPretrained();
        vgg16.outputSingle(Nd4j.create(1000, 3, 224, 224));
```

```
8:49:07,940 INFO  ~ Using cached model at C:\Users\Alex\.deeplearning4j\vgg16_dl4j_inference.zip
18:49:07,941 INFO  ~ Verifying download...
18:49:08,419 INFO  ~ Checksum local is 3501732770, expecting 3501732770
18:49:08,460 INFO  ~ Loaded [CpuBackend] backend
18:49:08,949 INFO  ~ Number of threads used for NativeOps: 8
18:49:09,219 INFO  ~ Number of threads used for BLAS: 8
18:49:09,225 INFO  ~ Backend used: [CPU]; OS: [Windows 10]
18:49:09,225 INFO  ~ Cores: [16]; Memory: [7.1GB];
18:49:09,226 INFO  ~ Blas vendor: [OPENBLAS]
18:49:23,156 INFO  ~ Starting ComputationGraph with WorkspaceModes set to [training: NONE; inference: SINGLE]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000069c6981e, pid=14708, tid=0x00000000000013f4
#
# JRE version: Java(TM) SE Runtime Environment (8.0_151-b12) (build 1.8.0_151-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.151-b12 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [libnd4jcpu.dll+0x7e981e]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\DL4J\Git\dl4j-examples\hs_err_pid14708.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

https://gist.github.com/AlexDBlack/27e2eef07b747c8686355a897210c98b

**Comment by AlexDBlack** [comment]
Closing this as not reproducable - we can reopen if @yquemener runs into this again.

**Comment by AlexDBlack** [comment]
I was able to reproduce this using the benchmark repo, test case 2 (on native/cpu) here:
https://github.com/deeplearning4j/dl4j-benchmark/blob/master/dl4j-core-benchmark/src/main/java/org/deeplearning4j/sets/StandardMemBenchmarks.java

This was minibatch size 32... sizes 1-16 run fine.

```
o.d.n.m.MultiLayerNetwork - Starting MultiLayerNetwork with WorkspaceModes set to [training: SINGLE; inference: SINGLE], cacheMode set to [NONE]
o.d.m.BaseMemoryBenchmark - Inference test: Starting minibatch size: 1
o.d.m.BaseMemoryBenchmark - Inference test: Starting minibatch size: 2
o.d.m.BaseMemoryBenchmark - Inference test: Starting minibatch size: 4
o.d.m.BaseMemoryBenchmark - Inference test: Starting minibatch size: 8
o.d.m.BaseMemoryBenchmark - Inference test: Starting minibatch size: 16
o.d.m.BaseMemoryBenchmark - Inference test: Starting minibatch size: 32
Bad number of bytes requested for allocation: -595591168
o.d.m.BaseMemoryBenchmark - Hit exception for minibatch size: 32
java.lang.RuntimeException: Number of bytes for allocation should be positive
	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.execCustomOpFloat(Native Method) ~[nd4j-native-1.0.0-SNAPSHOT.jar:na]
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1695) ~[nd4j-native-1.0.0-SNAPSHOT.jar:na]
	at org.nd4j.linalg.convolution.Convolution.im2col(Convolution.java:213) ~[nd4j-api-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.preOutput(ConvolutionLayer.java:348) ~[deeplearning4j-nn-1.0.0-SNAPSHOT.jar:na]
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.activate(ConvolutionLayer.java:392) ~[deeplearning4j-nn-1.0.0-SNAPSHOT.jar:na]
o.d.m.BaseMemoryBenchmark - Inference test: Starting minibatch size: 64
o.d.m.BaseMemoryBenchmark - =============================
o.d.m.BaseMemoryBenchmark - ===== Benchmark Results =====
o.d.m.BaseMemoryBenchmark - =============================
```
