### ISSUE TITLE
RuntimeException: Number of bytes for allocation should be positive

### ISSUE THREAD

**Issue by holgerbrandl** [deeplearning4j/nd4j#2873]
When increasing the input size for `model.eval()` over a certain limit the following error occurs:
```
Bad number of bytes requested for allocation: -1728412096
Exception in thread "main" java.lang.RuntimeException: Number of bytes for allocation should be positive
    at org.nd4j.nativeblas.Nd4jCpu$NativeOps.execCustomOpFloat(Native Method)
    at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1695)
    at org.nd4j.linalg.convolution.Convolution.im2col(Convolution.java:213)
    at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.preOutput(ConvolutionLayer.java:387)
    at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.preOutput(ConvolutionLayer.java:278)
    at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.activate(ConvolutionLayer.java:442)
    at org.deeplearning4j.nn.layers.AbstractLayer.activate(AbstractLayer.java:310)
    at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.activationFromPrevLayer(MultiLayerNetwork.java:815)
    at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForwardToLayer(MultiLayerNetwork.java:987)
    at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.silentOutput(MultiLayerNetwork.java:2053)
    at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.output(MultiLayerNetwork.java:2041)
```

The shape of my data was Rank: 4,Offset: 0
 Order: c Shape: [500,3,224,224],  stride: [150528,50176,224,1]

The commit to reproduce this problem is deposited under https://github.com/holgerbrandl/yelp_restaurant_labels/blob/d2e4b7dcfe80944cb6daeae1271be1c0656c1c3b/src/main/kotlin/PredictYelpLabels.kt#L69 

I could share the used model and input data (both serialized with dl4j) if needed. 

1.0.0-alpha was used. Unfortunately I’m not able to use the snapshot-builds (absence of -platform artifacts) to run my example.

**Comment by raver119** [comment]
Thanks for highlighting this problem. I basically need to know input image size and number of output channels. So model source code would be awesome to have

**Comment by holgerbrandl** [comment]
Input image size is 224x224 with 3 channels. The model has just two output nodes, but since the error may occur in-between layers, here's the full spec:

```
==========================================================================================================================================================================================================================================================
LayerName (LayerType)                   nIn,nOut  TotalParams ParamsShape                             
==========================================================================================================================================================================================================================================================
layer0 (ConvolutionLayer)               3,20        2180      b:{1,20}, W:{20,3,6,6}                  
layer1 (SubsamplingLayer)               -,-         0         -                                       
layer2 (ConvolutionLayer)               20,50       36050     b:{1,50}, W:{50,20,6,6}                 
layer3 (SubsamplingLayer)               -,-         0         -                                       
layer4 (DenseLayer)                     7200,500    3600500   W:{7200,500}, b:{1,500}                 
layer5 (OutputLayer)                    500,2       1002      W:{500,2}, b:{1,2}                      
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
            Total Parameters:  3639732
        Trainable Parameters:  3639732
           Frozen Parameters:  0
==========================================================================================================================================================================================================================================================

{
  "cacheMode" : "NONE",
  "epochCount" : 0,
  "iterationCount" : 0,
  "l1ByParam" : { },
  "l2ByParam" : { },
  "layer" : {
    "convolution" : {
      "activationFn" : {
        "ReLU" : { }
      },
      "biasInit" : 0.0,
      "biasUpdater" : null,
      "constraints" : null,
      "convolutionMode" : "Truncate",
      "cudnnAlgoMode" : "PREFER_FASTEST",
      "cudnnAllowFallback" : true,
      "cudnnBwdDataAlgo" : null,
      "cudnnBwdFilterAlgo" : null,
      "cudnnFwdAlgo" : null,
      "dilation" : [ 1, 1 ],
      "dist" : null,
      "gradientNormalization" : "None",
      "gradientNormalizationThreshold" : 1.0,
      "hasBias" : true,
      "idropout" : {
        "@class" : "org.deeplearning4j.nn.conf.dropout.Dropout",
        "p" : 0.5,
        "pschedule" : null
      },
      "iupdater" : {
        "@class" : "org.nd4j.linalg.learning.config.Nesterovs",
        "learningRate" : 0.01,
        "momentum" : 0.9
      },
      "kernelSize" : [ 6, 6 ],
      "l1" : 0.0,
      "l1Bias" : 0.0,
      "l2" : 0.0,
      "l2Bias" : 0.0,
      "layerName" : "layer0",
      "nin" : 3,
      "nout" : 20,
      "padding" : [ 0, 0 ],
      "stride" : [ 2, 2 ],
      "weightInit" : "XAVIER",
      "weightNoise" : null
    }
  },
  "maxNumLineSearchIterations" : 5,
  "miniBatch" : true,
  "minimize" : true,
  "optimizationAlgo" : "STOCHASTIC_GRADIENT_DESCENT",
  "pretrain" : false,
  "seed" : 12345,
  "stepFunction" : null,
  "variables" : [ "0_W", "0_b", "2_W", "2_b", "4_W", "4_b", "5_W", "5_b" ]
}
```

**Comment by raver119** [comment]
This issue is basically caused by int overflow in ShapeInfo-related calculations.

I.e. when you have array of shape {256, 64, 384, 386} - most of operations related to shape will fail. 

Solution is known and already planned: migration to long shapes.

**Comment by holgerbrandl** [comment]
Is it about the product of the 4 shape dimensions exceeding some limit (like Int.MAX_VALUE)? If so, is dl4j currently able to make use of high memory machines?

I like the milestone. :-)

**Comment by raver119** [comment]
Yes it is. This problem was on our roadmap anyway.

**Comment by shugeo** [comment]
Possible vector object with zero count of elements using constructor with non-zero expected.

**Comment by raver119** [comment]
I've answered above. I.e. 4D shape of [256, 64, 384, 384} exceeds MAX_INT value, so shapeInfo might get negative values as well as int product of shape will exceed it as well.

That's why we have PR for long shapes now.
