### ISSUE TITLE
0.9.1 -> 1.0.0-alpha: java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by p6majo** [deeplearning4j/nd4j#2893]
Problem with 1.0.0-alpha

I use the nd4j-native-platform api. All programs run successfully with the 0.9.1 stable release.
However, I want to implement DynamicCustomOps as suggested in

https://github.com/deeplearning4j/nd4j/issues/2313

It is not available in 0.9.1.
When I switch to the latest alpha-version, I get the above error message for a standard call:

 `Nd4j.rand(new int[]{outDepth,inDepth,kernelHeight,kernelWidth}, new NormalDistribution(0, 0.5f));`

I'm working on a linux platform (Ubuntu 16x)

**Comment by saudet** [comment]
Please also provide the whole stack trace!

**Comment by p6majo** [comment]
Exception in thread "main" java.lang.AbstractMethodError: org.nd4j.linalg.api.ops.impl.transforms.comparison.OldMax.name()Ljava/lang/String;
	at org.nd4j.linalg.api.ops.factory.DefaultOpFactory.<init>(DefaultOpFactory.java:80)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6192)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6087)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:201)
	at org.nd4j.linalg.api.rng.distribution.impl.NormalDistribution.<init>(NormalDistribution.java:123)
	at org.nd4j.linalg.api.rng.distribution.impl.NormalDistribution.<init>(NormalDistribution.java:105)
	at com.p6majo.math.network2.layers.ConvolutionLayer.<init>(ConvolutionLayer.java:99)
	at com.p6majo.mnist.MNISTVisualization3.main(MNISTVisualization3.java:43)

**Comment by p6majo** [comment]
Similar error with:
`INDArray test = Nd4j.linspace(1,b*d*c*r,b*d*b*c*r).reshape('c',b,d,c,r);`

java.lang.AbstractMethodError
	at org.nd4j.linalg.api.ops.factory.DefaultOpFactory.<init>(DefaultOpFactory.java:80)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6192)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6087)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:201)
	at com.p6majo.tensor.ReverseOperation.reverseOp(ReverseOperation.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by AlexDBlack** [comment]
> Exception in thread "main" java.lang.AbstractMethodError: 

That usually means you have mixed versions on your classpath... some 0.9.1, some 1.0.0-alpha.

If you're not sure where/why, post your pom.xml and the output of ```mvn dependency:tree``` (both in gists - gist.github.com)
