### ISSUE TITLE
Bad validation for Euclidean distance on CUDA?

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2894]
Reproducible using test here:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nearestneighbors-parent/nearestneighbor-core/src/test/java/org/deeplearning4j/clustering/randomprojection/RPUtilsTest.java

Test passes on CPU. Result array shape looks OK to me, assuming it hsould be doing the "one row vs all rows" distance.

```
org.nd4j.linalg.exception.ND4JIllegalStateException: Shape of target array for reduction [[1, 4]] doesn't match expected [[1, 1]]

	at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.buildZ(CudaGridExecutioner.java:641)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.exec(CudaGridExecutioner.java:677)
	at org.deeplearning4j.clustering.randomprojection.RPUtils.computeDistanceMulti(RPUtils.java:316)
	at org.deeplearning4j.clustering.randomprojection.RPUtilsTest.testDistanceComputeBatch(RPUtilsTest.java:16)
```

![image](https://user-images.githubusercontent.com/2360237/39923664-fd25b8f0-5567-11e8-82dc-f02157058e6e.png)

**Comment by raver119** [comment]
I think i had tests for this use case in nd4j-tests. Will check it out.
