### ISSUE TITLE
Error in the runtime: java.lang.NoClassDefFoundError: Could not initialize class org.nd4j.linalg.factory.Nd4j

### ISSUE THREAD

**Issue by pwittchen** [deeplearning4j/nd4j#2932]
#### Issue Description

Encountered behavior:

I'm using deeplearning4j with Apache Flink. Recently I upgraded Apache Flink from 1.10.1 to 1.11.2 and I have issues with deeplearning4j. I don't know, how to fix this. Upgrade was done for Apache Flink, but errors come from deeplearning4j. Before upgrades it worked fine.

I'm invoking the following method:

```java
MultiLayerNetwork model = KerasModelImport.importKerasSequentialModelAndWeights(fullPath);
```

where `fullPath` is path to the `*.h5` file.

and getting the following error:

```
java.lang.NoClassDefFoundError: Could not initialize class org.nd4j.linalg.factory.Nd4j
	at org.deeplearning4j.nn.modelimport.keras.Hdf5Archive.readDataSet(Hdf5Archive.java:300)
	at org.deeplearning4j.nn.modelimport.keras.Hdf5Archive.readDataSet(Hdf5Archive.java:114)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelUtils.importWeights(KerasModelUtils.java:285)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:149)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:57)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildSequential(KerasModelBuilder.java:322)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:223)
...
here goes stacktrace in my code
```

**Please note**: application is compiled correctly without any errors. This error is thrown in the **runtime** on the Apache Flink server.

Expected behavior:

I would like to have `MultiLayerNetwork` created and no errors thrown.

#### Version Information

* Deeplearning4j version: 1.0.0-beta6
* platform information (OS, etc): linux-x86_64

I have no idea how to fix this at this point. I'm looking forward to your help.

Kind Regards,
Piotr

**Comment by saudet** [comment]
Please try 1.0.0-beta7

**Comment by pwittchen** [comment]
Thanks. This dependency was upgraded to 1.0.0-beta7 and project needed a few additional adjustments. I think, this is the way to go in that case.
