### ISSUE TITLE
DL4JClassLoading of CuDNN 1.0.0-M1 bug

### ISSUE THREAD

**Issue by jljljl** [deeplearning4j/nd4j#2944]
Hi! I found an issue and a way how to fix it.

#### Issue Description

Class org.deeplearning4j.common.config.DL4JClassLoading contains multiple createNewInstance() methods. Looks like they're overloaded in a wrong way.

1.    public static <T> T createNewInstance(String className, Object... args);
2.   public static <T> T createNewInstance(String className, Class<? super T> superclass);
3.    public static <T> T createNewInstance(String className, Class<? super T> superclass, Object [] args);
4.    public static <T> T createNewInstance(String className,  Class<? super T> superclass, Class<?>[] parameterTypes, Object [] args);

`at org.deeplearning4j.nn.layers.HelperUtils.createHelper(HelperUtils.java:57)`
```helperRet =  DL4JClassLoading.createNewInstance(cudnnHelperClassName, layerHelperSuperClass, arguments);``` is meant to invoke 3rd method, but in fuct thread jumps to first method because it matches arguments. After that is mess arguments array and arguments Object[] { DataType } becomes Object[] { Class, Object[] }. So it throws that here is no method `org.deeplearning4j.cuda.convolution.CudnnConvolutionHelper.<init>(java.lang.Class,[Ljava.lang.Object;)`.

<details>

<summary>Screenshots</summary>

![bug0](https://user-images.githubusercontent.com/6739086/119870587-fb4bf680-bf3a-11eb-9332-02eedf0ddc21.jpg)
![bug1](https://user-images.githubusercontent.com/6739086/119870593-fc7d2380-bf3a-11eb-8ec4-e1dd12ef7ccc.jpg)

</details>

#### Suggestion

Best way here is to rename first method. Methods with dynamic array arguments "x()" can be renamed to "xArgs()".

<details>

<summary>Output</summary>

```
o.d.e.q.m.c.LeNetMNISTReLu - Data load...
o.d.e.q.m.c.LeNetMNISTReLu - Data vectorization...
o.d.i.r.BaseImageRecordReader - ImageRecordReader: 10 label classes inferred using label generator ParentPathLabelGenerator
o.d.i.r.BaseImageRecordReader - ImageRecordReader: 10 label classes inferred using label generator ParentPathLabelGenerator
o.d.e.q.m.c.LeNetMNISTReLu - Network configuration and training...
o.n.l.f.Nd4jBackend - Loaded [JCublasBackend] backend
o.n.c.c.ND4JClassLoading - Cannot find class [org.nd4j.linalg.jblas.JblasBackend] of provided class-loader.
o.n.c.c.ND4JClassLoading - Cannot find class [org.canova.api.io.data.DoubleWritable] of provided class-loader.
o.n.c.c.ND4JClassLoading - Cannot find class [org.nd4j.linalg.jblas.JblasBackend] of provided class-loader.
o.n.c.c.ND4JClassLoading - Cannot find class [org.canova.api.io.data.DoubleWritable] of provided class-loader.
o.n.n.NativeOpsHolder - Number of threads used for linear algebra: 32
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Windows 10]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [8]; Memory: [8,0GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [CUBLAS]
o.n.l.j.JCublasBackend - ND4J CUDA build version: 11.2.142
o.n.l.j.JCublasBackend - CUDA device 0: [NVIDIA GeForce RTX 3060]; cc: [8.6]; Total memory: [12884901888]
o.n.l.j.JCublasBackend - Backend build information:
 MSVC: 192829915
STD version: 201402L
CUDA: 11.2.142
DEFAULT_ENGINE: samediff::ENGINE_CUDA
HAVE_FLATBUFFERS
o.d.n.m.MultiLayerNetwork - Starting MultiLayerNetwork with WorkspaceModes set to [training: ENABLED; inference: ENABLED], cacheMode set to [NONE]
o.d.c.c.DL4JClassLoading - Cannot create instance of class 'org.deeplearning4j.cuda.convolution.CudnnConvolutionHelper'.
java.lang.NoSuchMethodException: org.deeplearning4j.cuda.convolution.CudnnConvolutionHelper.<init>(java.lang.Class,[Ljava.lang.Object;)
	at java.base/java.lang.Class.getConstructor0(Class.java:3508)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2711)
	at org.deeplearning4j.common.config.DL4JClassLoading.createNewInstance(DL4JClassLoading.java:103)
	at org.deeplearning4j.common.config.DL4JClassLoading.createNewInstance(DL4JClassLoading.java:89)
	at org.deeplearning4j.common.config.DL4JClassLoading.createNewInstance(DL4JClassLoading.java:74)
Exception in thread "main" java.lang.RuntimeException: java.lang.NoSuchMethodException: org.deeplearning4j.cuda.convolution.CudnnConvolutionHelper.<init>(java.lang.Class,[Ljava.lang.Object;)
	at org.deeplearning4j.common.config.DL4JClassLoading.createNewInstance(DL4JClassLoading.java:108)
	at org.deeplearning4j.common.config.DL4JClassLoading.createNewInstance(DL4JClassLoading.java:89)
	at org.deeplearning4j.common.config.DL4JClassLoading.createNewInstance(DL4JClassLoading.java:74)
	at org.deeplearning4j.nn.layers.HelperUtils.createHelper(HelperUtils.java:57)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.initializeHelper(ConvolutionLayer.java:72)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.<init>(ConvolutionLayer.java:67)
	at org.deeplearning4j.nn.conf.layers.ConvolutionLayer.instantiate(ConvolutionLayer.java:173)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:714)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:604)
	at org.deeplearning4j.examples.quickstart.modeling.convolution.LeNetMNISTReLu.main(LeNetMNISTReLu.java:148)
Caused by: java.lang.NoSuchMethodException: org.deeplearning4j.cuda.convolution.CudnnConvolutionHelper.<init>(java.lang.Class,[Ljava.lang.Object;)
	at java.base/java.lang.Class.getConstructor0(Class.java:3508)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2711)
	at org.deeplearning4j.common.config.DL4JClassLoading.createNewInstance(DL4JClassLoading.java:103)
	... 9 more
```
  
</details>

#### Version Information

* org.deeplearning4j:deeplearning4j-cuda-11.2:1.0.0-M1
* cudnn-11.2-windows-x64-v8.1.1.33
* Windows 10
* Nvidia driver version 466
* Java SE 1.8
* User\.p2\pool\plugins\org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_15.0.2.v20210201-0955\jre\bin\javaw.exe

I tried to commit it, but I cannot commit because here is no repository for deeplearning4j-cuda-11.2:1.0.0-M1 has been found. Here is only cuda-11.0 for SNAPSHOT version in repository which is not compiled correctly due to IDE settings difference.

It might not only be a bug of this version. It may also be in previous versions.

Also it may be cause by difference in JVMs behavior so they don't run overloaded methods in a same way.

**Comment by jljljl** [comment]
```
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>cuda-platform-redist</artifactId>
            <version>11.2-8.1-1.5.5</version>
        </dependency>
```
seems to work

**Comment by jljljl** [comment]
Moved to https://github.com/eclipse/deeplearning4j/issues/9331
