### ISSUE TITLE
Error loading ND4J Compressors via service loader

### ISSUE THREAD

**Issue by koushik1703** [deeplearning4j/nd4j#2946]
I am getting the following error while trying to run the model : 

Caused by: java.lang.RuntimeException: Error loading ND4J Compressors via service loader: No compressors were found. This usually occurs when running ND4J UI from an uber-jar, which was built incorrectly (without services resource files being included)
		at org.nd4j.linalg.compression.BasicNDArrayCompressor.loadCompressors(BasicNDArrayCompressor.java:64)
		at org.nd4j.linalg.compression.BasicNDArrayCompressor.<init>(BasicNDArrayCompressor.java:44)
		at org.nd4j.linalg.compression.BasicNDArrayCompressor.<clinit>(BasicNDArrayCompressor.java:37)

I am using version 1.0.0-beta4

Please help me on this.

**Comment by koushik1703** [comment]
There is service resource file for NDArrayCompressor in [nd4j-native-api ](https://github.com/deeplearning4j/nd4j/tree/master/nd4j-backends/nd4j-api-parent/nd4j-native-api/src/main/resources/META-INF/services) but, since there is no service resource file for NDArrayCompressor in [nd4j-api](https://github.com/deeplearning4j/nd4j/tree/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/resources), the service loader is not finding any implementation for compressor.
