### ISSUE TITLE
java.lang.NoClassDefFoundError: org/bytedeco/javacpp/openblas

### ISSUE THREAD

**Issue by mik3hall** [deeplearning4j/nd4j#2947]
#### Issue Description

I built ND4J standalone on OS/X Catalina and am attempting to do some simple standalone testing.
I get an exception as shown.

Please describe your issue, along with:
I built ND4J 
I set up a test directory with a simple test. I started copying in whatever jars seemed necessary and wrote a first simple test.
This reproduces the error...

import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.factory.Nd4j;
//import org.nd4j.linalg.api.buffer.DataType;

public class ND4J1 {

	public static void main(String... args) {	
		INDArray x =Nd4j.zeros(3,4);
		
		// The number of axes (dimensions) of the array.
		int dimensions = x.rank();
		
		// The dimensions of the array. The size in each dimension.
		long[] shape = x.shape();
		
		// The total number of elements.
		long length = x.length();
		
		// The type of the array elements. 
		//DataType dt = x.dataType();		
	}
}

Although currently I am trying to run a different example class with the same result.

Run as...
java -cp .:nd4j-uberjar-1.0.0-SNAPSHOT.jar:nd4j-buffer-1.0.0-SNAPSHOT.jar:nd4j-api-1.0.0-SNAPSHOT.jar:nd4j-native-1.0.0-SNAPSHOT.jar:nd4j-backend-impls-1.0.0-SNAPSHOT.jar:openblas.jar:nd4j-native-platform-1.0.0-SNAPSHOT-macosx-x86_64.jar:nd4j-context-1.0.0-SNAPSHOT.jar:slf4j-api-1.7.25.jar:log4j-1.2.17.jar:openblas-macosx-x86_64.jar:slf4j-log4j12-1.7.5.jar:nd4j-common-1.0.0-SNAPSHOT.jar:javacpp.jar:nd4j-native-api-1.0.0-SNAPSHOT.jar:commons-math3-3.6.1.jar:nd4j-native-1.0.0-SNAPSHOT-macosx-x86_64.jar -Djava.library.path=lib org.nd4j.examples.quickstart.Nd4jEx1_INDArrayBasics

current lib directory...
 ls lib
libjnind4jcpu.dylib			libnd4jcpu.dylib			libopenblas_haswellp-r0.3.18.dev.dylib

- expected behavior
Test runs

- encountered behavior
Exception thrown

Exception in thread "main" java.lang.NoClassDefFoundError: org/bytedeco/javacpp/openblas
	at org.nd4j.linalg.cpu.nativecpu.blas.CpuBlas.setMaxThreads(CpuBlas.java:120)
	at org.nd4j.nativeblas.Nd4jBlas.<init>(Nd4jBlas.java:35)
	at org.nd4j.linalg.cpu.nativecpu.blas.CpuBlas.<init>(CpuBlas.java:15)
	at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.createBlas(CpuNDArrayFactory.java:94)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.blas(BaseNDArrayFactory.java:68)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.getEnvironmentInformation(NativeOpExecutioner.java:1251)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.printEnvironmentInformation(DefaultOpExecutioner.java:652)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6940)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6810)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:213)
	at org.nd4j.examples.quickstart.Nd4jEx1_INDArrayBasics.main(Nd4jEx1_INDArrayBasics.java:54)
Caused by: java.lang.ClassNotFoundException: org.bytedeco.javacpp.openblas
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 11 more

This seems similar to this issue 
https://github.com/eclipse/deeplearning4j-examples/issues/605

Although I'm not quite sure how that was resolved.
Note that to maven build I first had to figure out that I additionally needed javacpp and libnd4j. Since then I have also tried  javacpp-presets and OpenBLAS. There appear to be presets that might have the missing openblas class. But with different packages.

It also seemed to need this changed
<lombok.version>1.18.20</lombok.version>

#### Version Information
Current downloads of maven related for nd4j, libnd4j and javacpp. 

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version.                  N/A
* platform information (OS, etc)       Mac OS/X Catalina (10.15.7)
* CUDA version, if used                     N/A
* NVIDIA driver version, if in use.     N/A

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by mik3hall** [comment]
This can be closed.
Was attempting build of old version.
Worked with current.
