### ISSUE TITLE
Unable to get linear index >= 10000

### ISSUE THREAD

**Issue by jaksky** [deeplearning4j/nd4j#299]
While I was trying the Deepautoencoder tutorial http://deeplearning4j.org/deepautoencoder.html I was getting following exception

Exception in thread "main" java.lang.IllegalArgumentException: Unable to get linear index >= 10000
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:3388)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.apply(DefaultOpExecutioner.java:531)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.exec(DefaultOpExecutioner.java:59)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subi(BaseNDArray.java:2821)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subi(BaseNDArray.java:2801)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.sub(BaseNDArray.java:2570)
	at org.deeplearning4j.nn.layers.OutputLayer.backwardGradient(OutputLayer.java:96)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.doBackWard(MultiLayerNetwork.java:1086)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1255)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1283)

**Comment by agibsonccc** [comment]
Likely fixed. Lotta indexing issues fixed. Please try again.

**Comment by jaksky** [comment]
It is fixed. 
Thx

**Comment by jaksky** [comment]
Issue is still present. Did fresh build from origin master for all canova, ndj dl4j and issue still there
