### ISSUE TITLE
im2col Different array size error on Subsampling Test

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/nd4j#302]
Error captured from running ActivateSubsamplingTests Max & Mean:

```
java.lang.IllegalArgumentException: Different array sizes
	at org.nd4j.linalg.util.ArrayUtil.dotProduct(ArrayUtil.java:255)
	at org.nd4j.linalg.indexing.ShapeOffsetResolution.exec(ShapeOffsetResolution.java:132)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.get(BaseNDArray.java:3698)
	at org.nd4j.linalg.convolution.Convolution.im2col(Convolution.java:162)
	at org.nd4j.linalg.convolution.Convolution.im2col(Convolution.java:121)
	at org.deeplearning4j.nn.layers.convolution.subsampling.SubsamplingLayer.activate(SubsamplingLayer.java:139)
	at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:352)
	at org.deeplearning4j.nn.layers.convolution.SubsamplingLayerTest.testSubSampleMaxActivate(SubsamplingLayerTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

-- org.jblas INFO Deleting /var/folders/sm/lj217l5j51j_2h_kxc8s_fxc0000gn/T/jblas671629782324457091/libjblas.dylib
-- org.jblas INFO Deleting /var/folders/sm/lj217l5j51j_2h_kxc8s_fxc0000gn/T/jblas671629782324457091/libjblas_arch_flavor.dylib
-- org.jblas INFO Deleting /var/folders/sm/lj217l5j51j_2h_kxc8s_fxc0000gn/T/jblas671629782324457091
```

**Comment by EronWright** [comment]
A lot of tests fail in dl4j-core due to this same issue.
```
java.lang.IllegalArgumentException: Different array sizes
	at org.nd4j.linalg.util.ArrayUtil.dotProduct(ArrayUtil.java:255)
	at org.nd4j.linalg.indexing.ShapeOffsetResolution.exec(ShapeOffsetResolution.java:132)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.get(BaseNDArray.java:3698)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.slice(BaseNDArray.java:2914)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.tensorAlongDimension(BaseNDArray.java:747)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.concat(BaseNDArrayFactory.java:1003)
	at org.nd4j.linalg.factory.Nd4j.concat(Nd4j.java:3904)
	at org.nd4j.linalg.factory.Nd4j.append(Nd4j.java:298)
	at org.nd4j.linalg.factory.Nd4j.pad(Nd4j.java:203)
	at org.nd4j.linalg.factory.Nd4j.pad(Nd4j.java:163)
	at org.nd4j.linalg.convolution.Convolution.im2col(Convolution.java:149)
	at org.nd4j.linalg.convolution.Convolution.im2col(Convolution.java:121)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.createFeatureMapColumn(ConvolutionLayer.java:113)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.activate(ConvolutionLayer.java:139)
	at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:352)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayerTest.testFeatureMapShape(ConvolutionLayerTest.java:71)
```

**Comment by agibsonccc** [comment]
That line doesn't exist anymore. Would try again.
