### ISSUE TITLE
NullPointerException on permute + reshape operations

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#315]
Doing a reshape operation after a permute operation results in a null pointer exception. Conversely, doing same operation on an array with the same shape as the permuted array works. Exception thrown on both netlib and x86.

```java
@Test
public void testReshapePermute(){
	INDArray arrNoPermute = Nd4j.ones(5,3,4);
	INDArray reshaped2dNoPermute = arrNoPermute.reshape(5*3,4);	//OK
	assertArrayEquals(reshaped2dNoPermute.shape(),new int[]{5*3,4});
	
	INDArray arr = Nd4j.ones(5,4,3);
	INDArray permuted = arr.permute(0,2,1);
	assertArrayEquals(arrNoPermute.shape(),permuted.shape());
	INDArray reshaped2D = permuted.reshape(5*3,4);	//NullPointerException
	assertArrayEquals(reshaped2D.shape(),new int[]{5*3,4});
}
```
java.lang.NullPointerException
	at org.nd4j.linalg.api.shape.Shape.getOrder(Shape.java:593)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.reshape(BaseNDArray.java:3342)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.reshape(BaseNDArray.java:3371)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.reshape(BaseNDArray.java:3604)
	at adb.informaltest2.ReshapePermute.testReshapePermute(ReshapePermute.java:20)

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/commit/afc4462a8d72447b69894778b08a8278be2bc118
