### ISSUE TITLE
mvn test failure

### ISSUE THREAD

**Issue by sato-cloudian** [deeplearning4j/nd4j#340]
I got the following error when running "mvn test".

````junit
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.nd4j.linalg.Nd4jTestSuite
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.536 sec <<< FAILURE!
initializationError(org.nd4j.linalg.Nd4jTestSuite)  Time elapsed: 0.006 sec  <<< ERROR!
java.lang.NoSuchMethodException: org.nd4j.linalg.shape.StaticShapeTests.<init>(java.lang.String, org.nd4j.linalg.factory.Nd4jBackend)
	at java.lang.Class.getConstructor0(Class.java:2892)
	at java.lang.Class.getConstructor(Class.java:1723)
	at org.nd4j.linalg.Nd4jTestSuite.suite(Nd4jTestSuite.java:151)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.internal.runners.SuiteMethod.testFromSuiteMethod(SuiteMethod.java:35)
	at org.junit.internal.runners.SuiteMethod.<init>(SuiteMethod.java:24)
	at org.junit.runners.AllTests.<init>(AllTests.java:25)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:250)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)


Results :

Tests in error: 
  initializationError(org.nd4j.linalg.Nd4jTestSuite): org.nd4j.linalg.shape.StaticShapeTests.<init>(java.lang.String, org.nd4j.linalg.factory.Nd4jBackend)

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] nd4j ............................................... SUCCESS [  0.737 s]
[INFO] nd4j-bytebuddy ..................................... SUCCESS [  1.830 s]
[INFO] nd4j-api ........................................... SUCCESS [  0.222 s]
[INFO] nd4j-jblas ......................................... FAILURE [  5.427 s]
````

I confirmed no such constructor exists on the source code.

Here's the branch I worked on.

````bash
$ git branch -v
* master a78c73b [maven-release-plugin] prepare for next development iteration
````

**Comment by agibsonccc** [comment]
Fixed thanks! https://github.com/deeplearning4j/nd4j/pull/342
