### ISSUE TITLE
Could not create .ptx file

### ISSUE THREAD

**Issue by assaad** [deeplearning4j/nd4j#346]
Hello, I am getting the following exception when using nd4j with JCuBLAS
Thanks for your help

java.io.IOException: Could not create .ptx file: 
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:282)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:317)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:194)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.load(KernelFunctionLoader.java:160)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.getInstance(KernelFunctionLoader.java:77)
	at org.nd4j.linalg.jcublas.SimpleJCublas.init(SimpleJCublas.java:110)
	at org.nd4j.linalg.jcublas.SimpleJCublas.<clinit>(SimpleJCublas.java:65)
	at org.nd4j.linalg.jcublas.ops.executioner.JCudaExecutioner.<init>(JCudaExecutioner.java:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at java.lang.Class.newInstance(Class.java:438)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:4312)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:4263)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:135)
	at org.kevoree.brain.matrix.TestMatrix.main(TestMatrix.java:28)
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.nd4j.linalg.jcublas.ops.executioner.JCudaExecutioner.<init>(JCudaExecutioner.java:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at java.lang.Class.newInstance(Class.java:438)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:4312)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:4263)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:135)
	at org.kevoree.brain.matrix.TestMatrix.main(TestMatrix.java:28)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Could not create .ptx file: 
	at org.nd4j.linalg.jcublas.SimpleJCublas.<clinit>(SimpleJCublas.java:67)
	... 10 more
Caused by: java.lang.RuntimeException: java.io.IOException: Could not create .ptx file: 
	at org.nd4j.linalg.jcublas.SimpleJCublas.init(SimpleJCublas.java:112)
	at org.nd4j.linalg.jcublas.SimpleJCublas.<clinit>(SimpleJCublas.java:65)
	... 10 more
Caused by: java.io.IOException: Could not create .ptx file: 
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:282)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:317)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:194)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.load(KernelFunctionLoader.java:160)
	at org.nd4j.linalg.jcublas.SimpleJCublas.init(SimpleJCublas.java:110)
	... 11 more

**Comment by agibsonccc** [comment]
Permissions issue?

**Comment by assaad** [comment]
7.5

**Comment by agibsonccc** [comment]
Closing tihs as not reproducible. There have been a lot of cuda fixes, please look at it again.

**Comment by Ingwar** [comment]
I'm getting the very similar issue. I am using the the nd4j-jcublas-7.0, version 04-rc3.7.

**Comment by Ingwar** [comment]
Here is the error:
```
/tmp/kernels/float/add_strided.cu(12): error: too many arguments in function call

1 error detected in the compilation of "/tmp/tmpxft_00005444_00000000-299_add_strided.cpp1.ii".

23:34:59.865 [run-main-0] INFO  o.n.l.j.kernel.KernelFunctionLoader - outputMessage:

[error] (run-main-0) java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError
        at org.nd4j.linalg.jcublas.ops.executioner.JCudaExecutioner.<init>(JCudaExecutioner.java:58)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at java.lang.Class.newInstance(Class.java:442)
        at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:4551)
        at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:4499)
        at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:140)
        at org.deeplearning4j.nn.conf.MultiLayerConfiguration$Builder.build(MultiLayerConfiguration.java:282)
        at org.deeplearning4j.nn.conf.NeuralNetConfiguration$ListBuilder.build(NeuralNetConfiguration.java:161)
        at 
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Could not create .ptx file: /tmp/kernels/float/add_strided.cu(12): error: too many arguments in function call

1 error detected in the compilation of "/tmp/tmpxft_00005444_00000000-299_add_strided.cpp1.ii".

        at org.nd4j.linalg.jcublas.SimpleJCublas.<clinit>(SimpleJCublas.java:67)
        at org.nd4j.linalg.jcublas.ops.executioner.JCudaExecutioner.<init>(JCudaExecutioner.java:58)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at java.lang.Class.newInstance(Class.java:442)
        at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:4551)
        at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:4499)
        at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:140)
        at org.deeplearning4j.nn.conf.MultiLayerConfiguration$Builder.build(MultiLayerConfiguration.java:282)
        at org.deeplearning4j.nn.conf.NeuralNetConfiguration$ListBuilder.build(NeuralNetConfiguration.java:161)
        at 
Caused by: java.lang.RuntimeException: java.io.IOException: Could not create .ptx file: /tmp/kernels/float/add_strided.cu(12): error: too many arguments in function call

1 error detected in the compilation of "/tmp/tmpxft_00005444_00000000-299_add_strided.cpp1.ii".

        at org.nd4j.linalg.jcublas.SimpleJCublas.init(SimpleJCublas.java:112)
        at org.nd4j.linalg.jcublas.SimpleJCublas.<clinit>(SimpleJCublas.java:65)
        at org.nd4j.linalg.jcublas.ops.executioner.JCudaExecutioner.<init>(JCudaExecutioner.java:58)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at java.lang.Class.newInstance(Class.java:442)
        at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:4551)
        at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:4499)
        at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:140)
        at org.deeplearning4j.nn.conf.MultiLayerConfiguration$Builder.build(MultiLayerConfiguration.java:282)
        at org.deeplearning4j.nn.conf.NeuralNetConfiguration$ListBuilder.build(NeuralNetConfiguration.java:161)
        at 
Caused by: java.io.IOException: Could not create .ptx file: /tmp/kernels/float/add_strided.cu(12): error: too many arguments in function call

1 error detected in the compilation of "/tmp/tmpxft_00005444_00000000-299_add_strided.cpp1.ii".

        at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:282)
        at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:317)
        at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:194)
        at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.load(KernelFunctionLoader.java:160)
        at org.nd4j.linalg.jcublas.SimpleJCublas.init(SimpleJCublas.java:110)
        at org.nd4j.linalg.jcublas.SimpleJCublas.<clinit>(SimpleJCublas.java:65)
        at org.nd4j.linalg.jcublas.ops.executioner.JCudaExecutioner.<init>(JCudaExecutioner.java:58)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at java.lang.Class.newInstance(Class.java:442)
        at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:4551)
        at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:4499)
        at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:140)
        at org.deeplearning4j.nn.conf.MultiLayerConfiguration$Builder.build(MultiLayerConfiguration.java:282)
        at org.deeplearning4j.nn.conf.NeuralNetConfiguration$ListBuilder.build(NeuralNetConfiguration.java:161)
        at 

```
