### ISSUE TITLE
exception in DataSet.binarize()

### ISSUE THREAD

**Issue by aritasimoes** [deeplearning4j/nd4j#37]
On 0.0.3.5.5.3-SNAPSHOT, the following exception is thrown when calling ```.binarize(0)``` on a DataSet:

```java
Exception in thread "main" java.lang.IllegalArgumentException: Unable to do linear indexing with dimensions greater than 1
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getScalar(BaseNDArray.java:1673)
	at org.nd4j.linalg.dataset.DataSet.binarize(DataSet.java:261)
	at BoW_DBN.main(BoW_DBN.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

Replacing line 261 in DataSet.java by:

```java
double curr = data.getFeatures().getDouble(i);
```

solves the problem for me.

**Comment by agibsonccc** [comment]
Fixed.
