### ISSUE TITLE
Nd4j.sum with row/column vector

### ISSUE THREAD

**Issue by migel** [deeplearning4j/nd4j#43]
I get the following results when using ```Nd4j.sum```:

```scala
scala> val m1 = Nd4j.rand(2,2)
m1: org.nd4j.linalg.api.ndarray.INDArray =
[[0.5065258540001533, 1.9942128950445461]
 [-0.4765064602250793, -0.2165105757052097]]

scala> Nd4j.sum(m1, 0)
res0: org.nd4j.linalg.api.ndarray.INDArray =
[0.030019393775073955, 1.7777023193393364]


scala> Nd4j.sum(m1, 1)
res1: org.nd4j.linalg.api.ndarray.INDArray =
[2.5007387490446993, -0.693017035930289]


scala> val m2 = Nd4j.rand(1,2)
m2: org.nd4j.linalg.api.ndarray.INDArray =
[-1.2997101524213759, 1.8985879742017755]


scala> Nd4j.sum(m2, 0)
res2: org.nd4j.linalg.api.ndarray.INDArray = 0.5988778217803996

scala> Nd4j.sum(m2, 1)
res3: org.nd4j.linalg.api.ndarray.INDArray = 0.5988778217803996

scala> val m3 = Nd4j.rand(2,1)
m3: org.nd4j.linalg.api.ndarray.INDArray =
[[-1.560695524421142,
  -1.5865038444613484]]


scala> Nd4j.sum(m3, 0)
res4: org.nd4j.linalg.api.ndarray.INDArray = -3.1471993688824904

scala> Nd4j.sum(m3, 1)
res5: org.nd4j.linalg.api.ndarray.INDArray = -3.1471993688824904

```
I expected that the results ```res2``` and ```res5``` will be arrays. Comparing to Numpy:
```python
In [67]: a1 = np.random.uniform(size=(1,2))

In [68]: np.sum(a1, axis=0)
Out[68]: array([ 0.11115371,  0.1535297 ])

In [69]: np.sum(a1, axis=1)
Out[69]: array([ 0.2646834])

In [70]: a2 = np.random.uniform(size=(2,1))

In [71]: np.sum(a2, axis=0)
Out[71]: array([ 0.54788375])

In [72]: np.sum(a2, axis=1)
Out[72]: array([ 0.40779894,  0.14008481])
```

**Comment by agibsonccc** [comment]
Here's a test of this passing.

https://github.com/deeplearning4j/nd4j/blob/master/nd4j-api/src/main/java/org/nd4j/linalg/api/test/NDArrayTests.java#L716-716

Here's more tests with the op executioner (the lower level interface to the dimension wise ops):
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/tests/OpExecutionerTests.java#L264

Which version are you using and which backend?

**Comment by migel** [comment]
The test you pointed out is for a sum operation on a 2x2 matrix; The issue is not with these but with e.g. 1x2 or 2x1 vectors. If, for example, a function that needs to sum by columns in a matrix gets an MxN matrix, the ```matrix.sum(0)``` op should return a vector regardless if M=1 or M>1 (for N>1); otherwise every similar function will have to treat M=1 as a special case.

**Comment by agibsonccc** [comment]
Ahh I see now. I encountered a similar edge case before. I'll push a fix for that today. Thanks again!

**Comment by agibsonccc** [comment]
Fixed.

**Comment by migel** [comment]
Hi, thanks for the quick fixes. I get an exception with column vectors:

```scala
  val m2 = Nd4j.rand(1, 2)                        //> m2  : org.nd4j.linalg.api.ndarray.INDArray = [0.3582044243812561, 0.8265518
                                                  //| 546104431]
                                                  //|  
  Nd4j.sum(m2, 0)                                 //> res0: org.nd4j.linalg.api.ndarray.INDArray = [0.3582044243812561, 0.8265518
                                                  //| 546104431]
                                                  //|  
  Nd4j.sum(m2, 1)                                 //> res1: org.nd4j.linalg.api.ndarray.INDArray = 1.1847563

  val m3 = Nd4j.rand(2, 1)                        //> m3  : org.nd4j.linalg.api.ndarray.INDArray = [[-0.2484026998281479,
                                                  //|   -1.2237846851348877]]
                                                  //|  
  Nd4j.sum(m3, 0)                                 //> res2: org.nd4j.linalg.api.ndarray.INDArray = -1.4721874
  Nd4j.sum(m3, 1)                                 //> java.lang.IllegalArgumentException: Illegal index 2 derived from 1 with off
                                                  //| set of 0 and stride of 2
                                                  //| 	at org.nd4j.linalg.api.ndarray.BaseNDArray.linearIndex(BaseNDArray.java:
                                                  //| 2607)
                                                  //| 	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:28
                                                  //| 89)
                                                  //| 	at org.nd4j.linalg.api.ndarray.BaseNDArray.toString(BaseNDArray.java:389
                                                  //| 3)
                                                  //| 	at scala.runtime.ScalaRunTime$.scala$runtime$ScalaRunTime$$inner$1(Scala
                                                  //| RunTime.scala:332)
                                                  //| 	at scala.runtime.ScalaRunTime$.stringOf(ScalaRunTime.scala:337)
                                                  //| 	at scala.runtime.ScalaRunTime$.stringOf(ScalaRunTime.scala:262)
                                                  //| 	at org.scalaide.worksheet.runtime.library.WorksheetSupport$.$show(Worksh
                                                  //| eetSupport.scala:90)
                                                  //| 	at jackson$$anonfun$main$1.apply$mcV$sp(jackson.scala:95)
                                                  //| 	at org.scalaide.worksheet.runtime.library.WorksheetSupport$$anonfun$$exe
                                                  //| cute$1.apply$mcV$sp(WorksheetSupport.scala:76)
                                                  //| 	at org.scalaide.worksheet.runtime.library.WorksheetSupport$.redirected(W
                                                  //| orksheetSupport.scala:65)
                                                  //| 	at org.scalaide.worksheet.runtime.library.WorksheetSupport$.$execute(Wor
                                                  //| ksheetSupport.scala:75)
                                                  //| 	at jackson$.main(jackson.scala:27)
                                                  //| 	at jackson.main(jackson.scala)

```

**Comment by agibsonccc** [comment]
I'm running that code and not able to reproduce it. The error is related to
the striding stuff from earlier. Would you mind pulling again to make sure?
If not open a separate issue.

Thanks!
ᐧ
