### ISSUE TITLE
Illegal index

### ISSUE THREAD

**Issue by jarutis** [deeplearning4j/nd4j#441]
I get this error on nd4j-java backend on Spark.
nd4j-x86 seems to work fine on the other hand.

```
Lost task 7.0 in stage 8.0 (TID 387, rr-wh-hdp1.vinted.net): java.lang.IllegalArgumentException: Illegal index [0, 0, 5]
	at org.nd4j.linalg.api.ndarray.BaseNDArray.putScalar(BaseNDArray.java:1116)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.putScalar(BaseNDArray.java:1097)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.broadcast(BaseNDArray.java:3946)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.preOutput(ConvolutionLayer.java:123)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.activate(ConvolutionLayer.java:135)
	at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:347)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.activationFromPrevLayer(MultiLayerNetwork.java:484)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForward(MultiLayerNetwork.java:546)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForward(MultiLayerNetwork.java:559)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:1570)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:117)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:56)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1342)
	at org.deeplearning4j.spark.ml.classification.NeuralNetworkClassification$$anonfun$1.apply(MultiLayerNetworkClassification.scala:127)
	at org.deeplearning4j.spark.ml.classification.NeuralNetworkClassification$$anonfun$1.apply(MultiLayerNetworkClassification.scala:113)
	at org.deeplearning4j.spark.ml.nn.ParameterAveragingTrainingStrategy$$anonfun$train$1$$anonfun$apply$mcVI$sp$1.apply(TrainingStrategy.scala:89)
	at org.deeplearning4j.spark.ml.nn.ParameterAveragingTrainingStrategy$$anonfun$train$1$$anonfun$apply$mcVI$sp$1.apply(TrainingStrategy.scala:81)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:898)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:898)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1848)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1848)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by agibsonccc** [comment]
Clsong this. Fixed by now.
