### ISSUE TITLE
CNN's throwing an index out of bounds error on Nd4j master

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/nd4j#449]
Currently CNN examples in snapshot throw the index out of bounds error on -1. From digging the following points are what I've found so far on where this issue is coming from:

- in Convolution under preOutput the calc to add bias to z
- based on addi call, in DefaultOpExecutioner it lands in the for loop to apply "putScalarUnsafe" method on line 90
- After one iteration it goes to BaseNDArray elementWiseStride and attemptedToFindElementWiseStride is true so it returns elementWiseStride of -1
It's failing on BaseNDArray getDoubleUnsafe (called on x) because it's passing in -1. So it's trying to pull a value out of data vector at position -1.

The issue started on PST morning of Oct 7th and if we roll back to the sha: b63252824c3cd6761008cba2abfc3aae6c32509c then it will work. So the commits on Oct 6th are where the problem started.

**Comment by drlebedev** [comment]
It looks similar to what I get on current master:

```
-1
java.lang.ArrayIndexOutOfBoundsException: -1
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.getDouble(BaseDataBuffer.java:554)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDoubleUnsafe(BaseNDArray.java:3313)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.exec(DefaultOpExecutioner.java:90)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subi(BaseNDArray.java:2747)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subi(BaseNDArray.java:2728)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.sub(BaseNDArray.java:2506)
	at org.deeplearning4j.nn.layers.BaseOutputLayer.getGradientsAndDelta(BaseOutputLayer.java:141)
	at org.deeplearning4j.nn.layers.BaseOutputLayer.backpropGradient(BaseOutputLayer.java:120)
	at org.deeplearning4j.nn.layers.recurrent.RnnOutputLayer.backpropGradient(RnnOutputLayer.java:65)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.truncatedBPTTGradient(MultiLayerNetwork.java:1200)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:1578)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:117)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:56)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.doTruncatedBPTT(MultiLayerNetwork.java:1154)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1342)
```

Not sure that it is the same problem. If not I can create a new ticket.

**Comment by nyghtowl** [comment]
@drlebedev That's exactly it. I had rolled back to the earlier sha to work on something else and haven't had a chance to go back to pull the exact error yet. So thanks for adding.

**Comment by drlebedev** [comment]
I updated GravesLSTM tests to reproduce this issue and submitted PR: 

https://github.com/deeplearning4j/deeplearning4j/pull/773

**Comment by nyghtowl** [comment]
@drlebedev you rock

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/pull/454
