### ISSUE TITLE
mvn test error

### ISSUE THREAD

**Issue by junbochen** [deeplearning4j/nd4j#455]
Hello,
I'm following the nd4j installation instruction, by:

git clone https://github.com/deeplearning4j/nd4j.git
mvn clean install -DskipTests -Dmaven.javadoc.skip=true
mvn test

in the test phase, there's an error reported:

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.474 sec <<< FAILURE!
initializationError(org.nd4j.linalg.Nd4jTestSuite)  Time elapsed: 0.005 sec  <<< ERROR!
java.lang.NoSuchMethodException: org.nd4j.linalg.shape.loop.LoopTests.<init>(java.lang.String, org.nd4j.linalg.factory.Nd4jBackend)
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getConstructor(Class.java:1825)
	at org.nd4j.linalg.Nd4jTestSuite.suite(Nd4jTestSuite.java:151)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.internal.runners.SuiteMethod.testFromSuiteMethod(SuiteMethod.java:35)
	at org.junit.internal.runners.SuiteMethod.<init>(SuiteMethod.java:24)
	at org.junit.runners.AllTests.<init>(AllTests.java:25)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:250)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Results :

Tests in error: 
  initializationError(org.nd4j.linalg.Nd4jTestSuite): org.nd4j.linalg.shape.loop.LoopTests.<init>(java.lang.String, org.nd4j.linalg.factory.Nd4jBackend)

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] nd4j ............................................... SUCCESS [  0.423 s]
[INFO] nd4j-bytebuddy ..................................... SUCCESS [  1.321 s]
[INFO] nd4j-api ........................................... SUCCESS [  0.168 s]
[INFO] nd4j-jblas ......................................... FAILURE [  4.496 s]

**Comment by chrisvnicholson** [comment]
Thanks for flagging. We ask you to skip the tests in the install line because some of the tests fail.

**Comment by AlexDBlack** [comment]
also don't build from source unless you have a very good reason to (instead: use versions from maven central)

**Comment by junbochen** [comment]
Got it.
