### ISSUE TITLE
Getting ArrayIndexOutOfBoundsException: -1 on CNN examples in DefaultOpExecutioner 

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/nd4j#462]
Error generated after the bias broadcast fix is merged in.

DefaultOpExecutioner under doTransformOp

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: -1
	at org.nd4j.linalg.api.parallel.tasks.cpu.BaseCPUAction.blockUntilComplete(BaseCPUAction.java:33)
	at org.nd4j.linalg.api.parallel.tasks.cpu.BaseCPUAction.blockUntilComplete(BaseCPUAction.java:8)
	at org.nd4j.linalg.api.parallel.tasks.cpu.BaseCPUAction.blockUntilComplete(BaseCPUAction.java:38)
	at org.nd4j.linalg.api.parallel.tasks.cpu.BaseCPUAction.blockUntilComplete(BaseCPUAction.java:8)
	at org.nd4j.linalg.api.parallel.tasks.BaseTask.invokeBlocking(BaseTask.java:9)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.doTransformOp(DefaultOpExecutioner.java:410)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.exec(DefaultOpExecutioner.java:62)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.execAndReturn(DefaultOpExecutioner.java:186)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.activate(ConvolutionLayer.java:136)
	at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:341)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayerTest.testCNNInputSetupMNIST(ConvolutionLayerTest.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
Caused by: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.nd4j.linalg.api.parallel.tasks.cpu.BaseCPUAction.blockUntilComplete(BaseCPUAction.java:31)
	... 32 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at org.nd4j.linalg.api.parallel.tasks.cpu.transform.CPUTransformOpAction.execute(CPUTransformOpAction.java:242)
	at org.nd4j.linalg.api.parallel.tasks.cpu.transform.CPUTransformOpAction.call(CPUTransformOpAction.java:60)
	at org.nd4j.linalg.api.parallel.tasks.cpu.transform.CPUTransformOpAction.call(CPUTransformOpAction.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by agibsonccc** [comment]
This will be fixed after alex's branch is merged in.

**Comment by AlexDBlack** [comment]
fixed
https://github.com/deeplearning4j/nd4j/pull/463
