### ISSUE TITLE
Broadcast unit tests not passing

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#471]
Nd4jTestsC.testBroadCasting():
java.lang.IllegalArgumentException: Unable to get linear index >= 1
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:3165)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.broadcast(BaseNDArray.java:3906)
	at org.nd4j.linalg.Nd4jTestsC.testBroadCasting(Nd4jTestsC.java:333)

Nd4jTestsC.testBroadCast():
java.lang.IllegalArgumentException: Unable to get linear index >= 1
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:3165)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.broadcast(BaseNDArray.java:3906)
	at org.nd4j.linalg.Nd4jTestsC.testBroadCast(Nd4jTestsC.java:1770)

same stack trace for NDArrayTestsFortran.testBroadCast() / NDArrayTestsFortran.testBroadCasting()

see also:
https://github.com/deeplearning4j/nd4j/issues/464

**Comment by agibsonccc** [comment]
Fixed.
