### ISSUE TITLE
scalar concatenation edge cases

### ISSUE THREAD

**Issue by migel** [deeplearning4j/nd4j#49]
Hi, I'm trying to concatenate scalars (as a special case of e.g. Mx1 or Nx1 vectors where M=1 or N=1). When the operation is applied to dim=0 the result is a row vector instead of a column vector and for dim=1 an exception is raised:

```scala
  val v1 = Nd4j.arange(0,1).reshape(1,1)          //> v1  : org.nd4j.linalg.api.ndarray.INDArray = 0.0
  val v2 = Nd4j.arange(0,1).reshape(1,1)          //> v2  : org.nd4j.linalg.api.ndarray.INDArray = 0.0

  Nd4j.concat(0, v1, v2)                          //> res0: org.nd4j.linalg.api.ndarray.INDArray = [0.0, 0.0]
                                                  //|  
  Nd4j.concat(1, v1, v2)                          //> java.lang.IllegalArgumentException: Unable to remove index 1 was >= data.len
                                                  //| gth
                                                  //| 	at org.nd4j.linalg.util.ArrayUtil.removeIndex(ArrayUtil.java:394)
                                                  //| 	at org.nd4j.linalg.factory.BaseNDArrayFactory.validateConcat(BaseNDArray
                                                  //| Factory.java:92)
                                                  //| 	at org.nd4j.linalg.factory.BaseNDArrayFactory.concat(BaseNDArrayFactory.
                                                  //| java:909)
                                                  //| 	at org.nd4j.linalg.factory.Nd4j.concat(Nd4j.java:1802)
                                                  //| 	at t1002.agi.tstsc.tst_net$$anonfun$main$1.apply$mcV$sp(t1002.agi.tstsc.
                                                  //| tst_net.scala:17)
                                                  //| 	at org.scalaide.worksheet.runtime.library.WorksheetSupport$$anonfun$$exe
                                                  //| cute$1.apply$mcV$sp(WorksheetSupport.scala:76)
                                                  //| 	at org.scalaide.worksheet.runtime.library.WorksheetSupport$.redirected(W
                                                  //| orksheetSupport.scala:65)
                                                  //| 	at org.scalaide.worksheet.runtime.library.WorksheetSupport$.$execute(Wor
                                                  //| ksheetSupport.scala:75)
                                                  //| 	at t1002.agi.tstsc.tst_net$.main(t1002.agi.tstsc.tst_net.scala:8)
                                                  //| 	at t1002.agi.tstsc.tst_net.main(t1002.agi.tstsc.tst_net.scala)
```

Comparing to numpy:
```python
In [140]: v1 = np.array([[0]])

In [141]: v2 = np.array([[0]])

In [142]: np.concatenate((v1,v2), axis=0)
Out[142]: 
array([[0],
       [0]])

In [144]: np.concatenate((v1,v2), axis=1)
Out[144]: array([[0, 0]])
```

**Comment by agibsonccc** [comment]
Fixed.
