### ISSUE TITLE
Lenet MNIST Error

### ISSUE THREAD

**Issue by maitri982** [deeplearning4j/nd4j#498]
here's the trace:

o.d.e.c.CNNMnistExample - Load data....
o.d.e.c.CNNMnistExample - Build model....
o.d.e.c.CNNMnistExample - Train model....
o.d.o.s.BaseOptimizer - Objective function automatically set to minimize. Set stepFunction in neural net configuration to change default settings.
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
	at org.nd4j.linalg.api.parallel.tasks.cpu.misc.CPUIm2ColTask.blockUntilComplete(CPUIm2ColTask.java:715)
	at org.nd4j.linalg.api.parallel.tasks.cpu.misc.CPUIm2ColTask.invokeBlocking(CPUIm2ColTask.java:702)
	at org.nd4j.linalg.api.parallel.tasks.cpu.misc.CPUIm2ColTask.invokeBlocking(CPUIm2ColTask.java:19)
	at org.nd4j.linalg.convolution.Convolution.im2col(Convolution.java:137)
	at org.nd4j.linalg.convolution.Convolution.im2col(Convolution.java:100)
	at org.deeplearning4j.nn.layers.convolution.subsampling.SubsamplingLayer.activate(SubsamplingLayer.java:147)
	at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:347)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.activationFromPrevLayer(MultiLayerNetwork.java:488)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForward(MultiLayerNetwork.java:570)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForward(MultiLayerNetwork.java:583)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:1602)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:124)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:56)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1374)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1404)
	at org.deeplearning4j.examples.convolution.LenetMnistExample.main(LenetMnistExample.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
Caused by: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:942)
	at org.nd4j.linalg.api.parallel.tasks.cpu.misc.CPUIm2ColTask.blockUntilComplete(CPUIm2ColTask.java:713)
	... 21 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at sun.reflect.GeneratedConstructorAccessor7.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:536)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:941)
	... 22 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at sun.reflect.GeneratedConstructorAccessor7.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:536)
	at java.util.concurrent.ForkJoinTask.reportResult(ForkJoinTask.java:596)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:640)
	at org.nd4j.linalg.api.parallel.tasks.cpu.misc.CPUIm2ColTask.splitOrExecute(CPUIm2ColTask.java:202)
	at org.nd4j.linalg.api.parallel.tasks.cpu.misc.CPUIm2ColTask.compute(CPUIm2ColTask.java:100)
	at org.nd4j.linalg.api.parallel.tasks.cpu.misc.CPUIm2ColTask.compute(CPUIm2ColTask.java:19)
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:93)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:334)
	at java.util.concurrent.ForkJoinWorkerThread.execTask(ForkJoinWorkerThread.java:604)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:784)
	at java.util.concurrent.ForkJoinPool.work(ForkJoinPool.java:646)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:398)
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at sun.reflect.GeneratedConstructorAccessor7.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:536)
	at java.util.concurrent.ForkJoinTask.reportResult(ForkJoinTask.java:596)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:640)
	at org.nd4j.linalg.api.parallel.tasks.cpu.misc.CPUIm2ColTask.splitOrExecute(CPUIm2ColTask.java:202)
	at org.nd4j.linalg.api.parallel.tasks.cpu.misc.CPUIm2ColTask.compute(CPUIm2ColTask.java:100)
	at org.nd4j.linalg.api.parallel.tasks.cpu.misc.CPUIm2ColTask.compute(CPUIm2ColTask.java:19)
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:93)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:334)
	at java.util.concurrent.ForkJoinWorkerThread.execTask(ForkJoinWorkerThread.java:604)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:762)
	... 2 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
	... 15 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	... 14 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
	... 16 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
	... 16 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
	... 16 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 20000
	at org.nd4j.linalg.api.parallel.tasks.cpu.misc.CPUIm2ColTask.doHeapDouble(CPUIm2ColTask.java:438)
	at org.nd4j.linalg.api.parallel.tasks.cpu.misc.CPUIm2ColTask.execute(CPUIm2ColTask.java:222)
	at org.nd4j.linalg.api.parallel.tasks.cpu.misc.CPUIm2ColTask.splitOrExecute(CPUIm2ColTask.java:207)
	... 8 more

**Comment by AlexDBlack** [comment]
Thanks for reporting this. I looked into the issue - turns out it was an issue with the network configuration, not ND4J. I'll be pushing an updated config to the example repo shortly.
