### ISSUE TITLE
ArrayIndexOutOfBoundsException in ArrayUtil.removeIndex() from StandardDeviation

### ISSUE THREAD

**Issue by edudar** [deeplearning4j/nd4j#501]
Version: `0.4-rc3.6`

I have the following NDArray:
```
shape = {int[2]@7257} 
  0 = 1
  1 = 600
data = {org.nd4j.linalg.api.buffer.FloatBuffer@7259} 
  [6.26399,6.266993,7.008971,7.3896317,...]
rows = 1
columns = 600
length = 600
```

`stdNumber()` for it results into:
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at org.nd4j.linalg.util.ArrayUtil.removeIndex(ArrayUtil.java:608)
	at org.nd4j.linalg.api.ops.impl.accum.StandardDeviation.exec(StandardDeviation.java:85)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.exec(DefaultOpExecutioner.java:245)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.std(BaseNDArray.java:3400)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.stdNumber(BaseNDArray.java:930)
```

`ArrayUtil.removeIndex` allocates `ret=int[1]` because of `{1, 600}.length - {2147483647}.length` but none of `data` values are in `index` array so both go to `ret`.

**Comment by edudar** [comment]
`std(1).getDouble(0)` works instead

**Comment by AlexDBlack** [comment]
Thanks for reporting this. Fixed
https://github.com/deeplearning4j/nd4j/pull/504
