### ISSUE TITLE
serializing/deserializing fails with double

### ISSUE THREAD

**Issue by migel** [deeplearning4j/nd4j#51]
```java.io.EOFException``` is raised when deserializing a double array:
```scala
  Nd4j.dtype = DataBuffer.DOUBLE

  val a0 = Nd4j.create(
    Array[Float](-1f, 1f, 1f, -1f),
    Array[Int](1, 4))                             //> a0  : org.nd4j.linalg.api.ndarray.INDArray = [-1.0, 1.0, 1.0, -1.0]
                                                  //|  
  val byteOutStream = new ByteArrayOutputStream   //> byteOutStream  : java.io.ByteArrayOutputStream = 
  val dataOutStream = new DataOutputStream(byteOutStream)
                                                  //> dataOutStream  : java.io.DataOutputStream = java.io.DataOutputStream@28b24e
                                                  //| bd
  Nd4j.write(a0, dataOutStream)

  val byteInStream = new ByteArrayInputStream(byteOutStream.toByteArray())
                                                  //> byteInStream  : java.io.ByteArrayInputStream = java.io.ByteArrayInputStream
                                                  //| @524f6f2a
  val dataInStream = new DataInputStream(byteInStream)
                                                  //> dataInStream  : java.io.DataInputStream = java.io.DataInputStream@b89b904
  Nd4j.read(dataInStream)                         //> java.io.EOFException
                                                  //| 	at java.io.DataInputStream.readFully(DataInputStream.java:197)
                                                  //| 	at java.io.DataInputStream.readLong(DataInputStream.java:416)
                                                  //| 	at java.io.DataInputStream.readDouble(DataInputStream.java:468)
                                                  //| 	at org.nd4j.linalg.util.ArrayUtil.readDouble(ArrayUtil.java:568)
                                                  //| 	at org.nd4j.linalg.factory.Nd4j.read(Nd4j.java:956)
                                                  //| 	at jackson$$anonfun$main$1.apply$mcV$sp(jackson.scala:40)
                                                  //| 	at org.scalaide.worksheet.runtime.library.WorksheetSupport$$anonfun$$exe
                                                  //| cute$1.apply$mcV$sp(WorksheetSupport.scala:76)
                                                  //| 	at org.scalaide.worksheet.runtime.library.WorksheetSupport$.redirected(W
                                                  //| orksheetSupport.scala:65)
                                                  //| 	at org.scalaide.worksheet.runtime.library.WorksheetSupport$.$execute(Wor
                                                  //| ksheetSupport.scala:75)
                                                  //| 	at jackson$.main(jackson.scala:26)
                                                  //| 	at jackson.main(jackson.scala)

```

It works with float:
```scala
  Nd4j.dtype = DataBuffer.FLOAT

  val a0 = Nd4j.create(
    Array[Float](-1f, 1f, 1f, -1f),
    Array[Int](1, 4))                             //> a0  : org.nd4j.linalg.api.ndarray.INDArray = [-1.0, 1.0, 1.0, -1.0]
                                                  //|  
  val byteOutStream = new ByteArrayOutputStream   //> byteOutStream  : java.io.ByteArrayOutputStream = 
  val dataOutStream = new DataOutputStream(byteOutStream)
                                                  //> dataOutStream  : java.io.DataOutputStream = java.io.DataOutputStream@524f6f
                                                  //| 2a
  Nd4j.write(a0, dataOutStream)

  val byteInStream = new ByteArrayInputStream(byteOutStream.toByteArray())
                                                  //> byteInStream  : java.io.ByteArrayInputStream = java.io.ByteArrayInputStream
                                                  //| @5d0b589d
  val dataInStream = new DataInputStream(byteInStream)
                                                  //> dataInStream  : java.io.DataInputStream = java.io.DataInputStream@7ed1bb86
  Nd4j.read(dataInStream)                         //> res0: org.nd4j.linalg.api.ndarray.INDArray = [-1.0, 1.0, 1.0, -1.0]
                                                  //|  
```

**Comment by agibsonccc** [comment]
Fixed.
