### ISSUE TITLE
CUDA failure on GravesLSTM example

### ISSUE THREAD

**Issue by thealy** [deeplearning4j/nd4j#515]
Code copied from deeplearning4j-examples GravesLSTMCharModellingExample.java 
Fails with:
ava.lang.ExceptionInInitializerError
	at org.nd4j.linalg.jcublas.ops.executioner.JCudaExecutioner.<init>(JCudaExecutioner.java:57)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)

[More lines below]

-----------------------------------------------------------------------------------------------------------------
Running on Ubuntu Linux 14.04
NVIDIA Quadro K2000
nvidia-352 driver
cuda 7.5 

Relevant parts of pom.xml

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <nd4j.version>0.4-rc3.7</nd4j.version>
        <dl4j.version>0.4-rc3.7</dl4j.version>
        <canova.version>0.0.0.13</canova.version>
        <jackson.version>2.5.1</jackson.version>
    </properties>
 .....

            <dependency>
                <groupId>org.nd4j</groupId>
                <artifactId>nd4j-jcublas-7.5</artifactId>
                <version>${nd4j.version}</version>
            </dependency>

            <dependency>
                <groupId>org.nd4j</groupId>
                <artifactId>nd4j-jcublas-common</artifactId>
                <version>${nd4j.version}</version>
            </dependency>
.....
<code>

-----------------------------------------------------------------------------------------------------------------
15:02:16.079 [main] INFO  o.n.l.j.kernel.KernelFunctionLoader - Compiling cuda kernels
15:02:16.082 [main] DEBUG o.n.l.j.kernel.KernelFunctionLoader - Loading std_strided
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.nd4j.linalg.jcublas.ops.executioner.JCudaExecutioner.<init>(JCudaExecutioner.java:57)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:4551)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:4499)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:140)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.seed(NeuralNetConfiguration.java:385)
	at gov.bnl.snowstorm.GravesLSTMCharModelling.main(GravesLSTMCharModelling.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalStateException: Unable to find path /tmp/nd4j-kernels/output/std_strided.cubin. Recompiling
	at org.nd4j.linalg.jcublas.SimpleJCublas.<clinit>(SimpleJCublas.java:49)
	... 16 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalStateException: Unable to find path /tmp/nd4j-kernels/output/std_strided.cubin. Recompiling
	at org.nd4j.linalg.jcublas.SimpleJCublas.init(SimpleJCublas.java:94)
	at org.nd4j.linalg.jcublas.SimpleJCublas.<clinit>(SimpleJCublas.java:47)
	... 16 more
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Unable to find path /tmp/nd4j-kernels/output/std_strided.cubin. Recompiling
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:274)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:200)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.load(KernelFunctionLoader.java:167)
	at org.nd4j.linalg.jcublas.SimpleJCublas.init(SimpleJCublas.java:92)
	... 17 more
</code>

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/issues/555
