### ISSUE TITLE
nd4j.create fails when specifying ordering

### ISSUE THREAD

**Issue by migel** [deeplearning4j/nd4j#52]
```scala
  Nd4j.dtype = DataBuffer.FLOAT

  val a0 = Nd4j.create(
    Array[Float](-1f, 1f, 1f, -1f),
    Array[Int](1, 4))                             //> a0  : org.nd4j.linalg.api.ndarray.INDArray = [-1.0, 1.0, 1.0, -1.0]
                                                  //|  
  val a1 = Nd4j.create(
    Array[Float](-1f, 1f, 1f, -1f),
    Array[Int](1, 4),
    'f')                                          //> java.lang.IllegalArgumentException: invalid offset: must be < data.length
                                                  //| 	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:259)
                                                  //| 	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:403)
                                                  //| 	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:149)
                                                  //| 	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:321)
                                                  //| 	at org.nd4j.linalg.jblas.NDArray.<init>(NDArray.java:178)
                                                  //| 	at org.nd4j.linalg.jblas.JblasNDArrayFactory.create(JblasNDArrayFactory.
                                                  //| java:444)
                                                  //| 	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:2495)
                                                  //| 	at jackson$$anonfun$main$1.apply$mcV$sp(jackson.scala:36)
                                                  //| 	at org.scalaide.worksheet.runtime.library.WorksheetSupport$$anonfun$$exe
                                                  //| cute$1.apply$mcV$sp(WorksheetSupport.scala:76)
                                                  //| 	at org.scalaide.worksheet.runtime.library.WorksheetSupport$.redirected(W
                                                  //| orksheetSupport.scala:65)
                                                  //| 	at org.scalaide.worksheet.runtime.library.WorksheetSupport$.$execute(Wor
                                                  //| k
                                                  //| Output exceeds cutoff limit.
```

**Comment by agibsonccc** [comment]
Fixed.

**Comment by migel** [comment]
There is still some issue:

```scala
  Nd4j.dtype = DataBuffer.DOUBLE

  val b0 = Nd4j.arange(0, 12).reshape(3, 4)       //> b0  : org.nd4j.linalg.api.ndarray.INDArray = [[0.0, 3.0, 6.0, 9.0]
                                                  //|  [1.0, 4.0, 7.0, 10.0]
                                                  //|   ,[2.0, 5.0, 8.0, 11.0]]
                                                  //| 

  val b1 =
    Nd4j.create(
      b0.data().asFloat(),
      Array[Int](3, 4))                           //> b1  : org.nd4j.linalg.api.ndarray.INDArray = [[0.0, 3.0, 6.0, 9.0]
                                                  //|  [1.0, 4.0, 7.0, 10.0]
                                                  //|   ,[2.0, 5.0, 8.0, 11.0]]
                                                  //| 
  val b2 =
    Nd4j.create(
      b0.data().asFloat(),
      Array[Int](3, 4),
      'f')                                        //> b2  : org.nd4j.linalg.api.ndarray.INDArray = [[0.0, 3.0, 6.0, 9.0]
                                                  //|  [1.0, 4.0, 7.0, 10.0]
                                                  //|   ,[2.0, 5.0, 8.0, 11.0]]
                                                  //| 

  val b3 =
    Nd4j.create(
      b0.data().asDouble(),
      Array[Int](3, 4))                           //> b3  : org.nd4j.linalg.api.ndarray.INDArray = [[0.0, 3.0, 6.0, 9.0]
                                                  //|  [1.0, 4.0, 7.0, 10.0]
                                                  //|   ,[2.0, 5.0, 8.0, 11.0]]
                                                  //| 
  val b4 =
    Nd4j.create(
      b0.data().asDouble(),
      Array[Int](3, 4),
      'f')                                        //> java.lang.IllegalArgumentException: Illegal index 102 derived from 0 with o
                                                  //| ffset of 102 and stride of 3
                                                  //| 	at org.nd4j.linalg.api.ndarray.BaseNDArray.linearIndex(BaseNDArray.java:
                                                  //| 2596)
                                                  //| 	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:28
                                                  //| 78)
                                                  //| 	at org.nd4j.linalg.api.ndarray.BaseNDArray.toString(BaseNDArray.java:388
                                                  //| 2)
                                                  //| 	at org.nd4j.linalg.api.ndarray.BaseNDArray.toString(BaseNDArray.java:391
                                                  //| 0)
                                                  //| 	at scala.runtime.ScalaRunTime$.scala$runtime$ScalaRunTime$$inner$1(Scala
                                                  //| RunTime.scala:332)
                                                  //| 	at scala.runtime.ScalaRunTime$.stringOf(ScalaRunTime.scala:337)
                                                  //| 	at scala.runtime.ScalaRunTime$.stringOf(ScalaRunTime.scala:262)
                                                  //| 	at org.scalaide.worksheet.runtime.library.WorksheetSupport$.$show(Worksh
                                                  //| eetSupport.scala:90)
                                                  //| 	at jackson$$anonfun$main$1.apply$mcV$sp(jackson.scala:51)
                                                  //| 	at org.scalaide.worksheet.runtime.library.WorksheetSupport$$anonfun$$exe
                                                  //| cute$1.apply$mcV$sp(WorksheetSupport.
                                                  //| Output exceeds cutoff limit. 
```

**Comment by agibsonccc** [comment]
Was missing a constructor...appreciate the help!
