### ISSUE TITLE
can't print result of a vector after sum

### ISSUE THREAD

**Issue by migel** [deeplearning4j/nd4j#54]
Hi, the exception shows up when trying to print the results; maybe that's why you didn't reproduce it:

```scala
scala> import org.nd4j.linalg.factory.Nd4j
import org.nd4j.linalg.factory.Nd4j

scala> :silent
Switched off result printing.

scala> val m3 = Nd4j.rand(2, 1)

scala> val s = Nd4j.sum(m3, 1)

scala> println(s)
java.lang.IllegalArgumentException: Illegal index 2 derived from 1 with offset of 0 and stride of 2
  at org.nd4j.linalg.api.ndarray.BaseNDArray.linearIndex(BaseNDArray.java:2607)
  at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:2889)
  at org.nd4j.linalg.api.ndarray.BaseNDArray.toString(BaseNDArray.java:3893)
  at java.lang.String.valueOf(String.java:2847)
  at java.io.PrintStream.println(PrintStream.java:821)
  at scala.Console$.println(Console.scala:148)
  at scala.Predef$.println(Predef.scala:310)
  ... 33 elided

scala> 
```

**Comment by agibsonccc** [comment]
This works in more recent pushes. Closing.

**Comment by migel** [comment]
Hi, It doesn't crash but the result (```res3``` below) should be a vector (see #43):

```scala
  val m2 = Nd4j.rand(1, 2)                        //> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
                                                  //| SLF4J: Defaulting to no-operation (NOP) logger implementation
                                                  //| SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further de
                                                  //| tails.
                                                  //| m2  : org.nd4j.linalg.api.ndarray.INDArray = [-0.07823017239570618, -0.32133
                                                  //| 28421115875]
                                                  //|  
  Nd4j.sum(m2, 0)                                 //> res0: org.nd4j.linalg.api.ndarray.INDArray = [-0.07823017239570618, -0.32133
                                                  //| 28421115875]
                                                  //|  
  Nd4j.sum(m2, 1)                                 //> res1: org.nd4j.linalg.api.ndarray.INDArray = -0.399563

  val m3 = Nd4j.rand(2, 1)                        //> m3  : org.nd4j.linalg.api.ndarray.INDArray = [[0.6266587376594543,
                                                  //|   1.7959911823272705]]
                                                  //|  
  Nd4j.sum(m3, 0)                                 //> res2: org.nd4j.linalg.api.ndarray.INDArray = 2.4226499
  Nd4j.sum(m3, 1)                                 //> res3: org.nd4j.linalg.api.ndarray.INDArray = 2.4226499
```

otherwise it is not consistent when the number columns > 1, e.g.:
```scala
  val m4 = Nd4j.rand(2, 3)                        //> m4  : org.nd4j.linalg.api.ndarray.INDArray = [[-0.6015039086341858, 1.438815
                                                  //| 2360916138, -0.6803320646286011]
                                                  //|  [0.5994485020637512, 0.782534658908844, -0.5892616510391235]]
                                                  //| 
  Nd4j.sum(m4, 1)                                 //> res4: org.nd4j.linalg.api.ndarray.INDArray = [0.1569792628288269, 0.79272150
                                                  //| 99334717]
                                                  //|  
```
