### ISSUE TITLE
IllegalArgumentException due to integer overflow when building a large Word2Vec model

### ISSUE THREAD

**Issue by shashankchaudhry** [deeplearning4j/nd4j#556]
I trained a model using the original C code and was importing it into my deeplearning4j code and got the following exception:

Exception in thread "main" java.lang.IllegalArgumentException: Unable to create a buffer of length <= 0
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:195)
	at org.nd4j.linalg.api.buffer.FloatBuffer.<init>(FloatBuffer.java:39)
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createFloat(DefaultDataBufferFactory.java:43)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:988)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:223)
	at org.nd4j.linalg.jblas.NDArray.<init>(NDArray.java:107)
	at org.nd4j.linalg.jblas.JblasNDArrayFactory.create(JblasNDArrayFactory.java:224)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3801)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3770)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3044)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readBinaryModel(WordVectorSerializer.java:182)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.loadGoogleModel(WordVectorSerializer.java:97)
	at com.shc.ift.misclass.wordnet.FeatureBuilder.<init>(FeatureBuilder.java:46)
	at com.shc.ift.misclass.wordnet.TestFileProcessor.main(TestFileProcessor.java:164)

I've found the cause to be due the the file:
nd4j/nd4j-api/src/main/java/org/nd4j/linalg/util/ArrayUtil.java

The product calculation function int prod(int[] mult) overflows due to the limit on Integer.MAX_VALUE.

There is no issue when the trained model is used it the original C code from google.

**Comment by agibsonccc** [comment]
This is a limitation of java itself. We are working on libnd4j which will store the arrays natively. File a more general issue on nd4j mentioning this if this is important to you. Otherwise this will be fixed when we implement the new storage.
