### ISSUE TITLE
NullPointerException: shapeInformation in BaseNDArray is null

### ISSUE THREAD

**Issue by marbon87** [deeplearning4j/nd4j#575]
The CpuNDArrayFactory calls the super-constructor from BaseNDArray with 2 arguments.
The problem is that only one of the four constructros from BaseNDArray sets the field shapeInformation.

I am using version  0.4-rc3.9-SNAPSHOT

That is the exception:

```
Exception in thread "main" java.lang.NullPointerException
	at org.nd4j.linalg.api.shape.Shape.rank(Shape.java:988)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.shape(BaseNDArray.java:3713)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.init(BaseNDArray.java:1822)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:122)
	at org.nd4j.linalg.cpu.NDArray.<init>(NDArray.java:65)
	at org.nd4j.linalg.cpu.CpuNDArrayFactory.create(CpuNDArrayFactory.java:169)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3304)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.loadTxt(WordVectorSerializer.java:1030)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.loadTxtVectors(WordVectorSerializer.java:965)
	at fh.muenster.tiit.spark.reuters.spark.SparkRunnerWord2Vec.loadVectors(SparkRunnerWord2Vec.scala:67)
	at fh.muenster.tiit.spark.reuters.app.App$.main(App.scala:45)
	at fh.muenster.tiit.spark.reuters.app.App.main(App.scala)
```

**Comment by Moddus** [comment]
This happens because ```shapeInformation``` is null. shapeInformation is only set by the ```BaseNDArray``` construcor in line 133 ``` public BaseNDArray(DataBuffer buffer, int[] shape, int[] stride, int offset, char ordering)```.
We use ```WordVectorSerializer.loadTxtVectors(new File(path))``` which leads to the call of the ```BaseNDArray``` constructor in line 119 ```public BaseNDArray(DataBuffer buffer)```. This constructor doesn't set ```shapeInformation```.

**Comment by agibsonccc** [comment]
Shape information bug should be fixed now. We use a data buffer instead as well.
