### ISSUE TITLE
IComplexNDArray linearView().reshape throws NullPointerException

### ISSUE THREAD

**Issue by taisukeoe** [deeplearning4j/nd4j#580]
Confirmed in Nd4j 0.4-rc3.8.

```scala
scala> val nc = Nd4j.createComplex(2,2)
nc: org.nd4j.linalg.api.complex.IComplexNDArray =
[[0.0 + 0.0i ,0.0 + 0.0i]
[0.0 + 0.0i ,0.0 + 0.0i]
]

scala> nc.linearView.reshape(2,2)
java.lang.NullPointerException
  at org.nd4j.linalg.util.ArrayUtil.copy(ArrayUtil.java:376)
  at org.nd4j.linalg.api.shape.Shape.newShapeNoCopy(Shape.java:898)
  at org.nd4j.linalg.api.ndarray.BaseNDArray.reshape(BaseNDArray.java:3210)
  at org.nd4j.linalg.api.complex.BaseComplexNDArray.reshape(BaseComplexNDArray.java:3083)
  at org.nd4j.linalg.api.complex.BaseComplexNDArray.reshape(BaseComplexNDArray.java:55)
  at org.nd4j.linalg.api.ndarray.BaseNDArray.reshape(BaseNDArray.java:3258)
  at org.nd4j.linalg.api.complex.BaseComplexNDArray.reshape(BaseComplexNDArray.java:3078)
  at org.nd4j.linalg.api.complex.BaseComplexNDArray.reshape(BaseComplexNDArray.java:3233)
  ... 43 elided
```

Since I understand IComplexNDArray is not prioritized to maintain/debug, please let me just create a issue atm.

**Comment by agibsonccc** [comment]
We aren't supporting complex at the moment. We are going to look at this at a later date.
