### ISSUE TITLE
Issue with Nd4j create in terms of calling shape on an array that no longer exists

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/nd4j#605]
Calling BaseDataBuffer array on shape information but there isn't a java array there. This impacts image load (jpg)

Potentially just need to return int data or issue with how its allocated.

java.lang.UnsupportedOperationException
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.array(BaseDataBuffer.java:1195)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:100)
	at org.nd4j.linalg.api.buffer.IntBuffer.<init>(IntBuffer.java:79)
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.create(DefaultDataBufferFactory.java:47)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:958)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:132)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:378)
	at org.nd4j.linalg.cpu.NDArray.<init>(NDArray.java:306)
	at org.nd4j.linalg.cpu.CpuNDArrayFactory.create(CpuNDArrayFactory.java:330)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3407)
	at org.canova.image.loader.ImageLoader.toINDArrayBGR(ImageLoader.java:416)
	at org.canova.image.loader.ImageLoader.asRowVector(ImageLoader.java:116)
	at org.canova.image.recordreader.BaseImageRecordReader.next(BaseImageRecordReader.java:212)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:149)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:288)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:42)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1148)
	at org.dl4j.benchmarks.ModelSpecific.AlexNetBVLC.execute(AlexNetBVLC.java:199)
	at org.dl4j.benchmarks.ModelSpecific.AlexNetBVLC.main(AlexNetBVLC.java:233)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Exception in thread "main" java.lang.IllegalArgumentException: Unable to create a buffer of length <= 0
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:418)
	at org.nd4j.linalg.api.buffer.FloatBuffer.<init>(FloatBuffer.java:39)
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createFloat(DefaultDataBufferFactory.java:205)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1151)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:945)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:2745)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:2613)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.getDataSet(RecordReaderDataSetIterator.java:186)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:150)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:288)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:42)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1148)
	at org.dl4j.benchmarks.ModelSpecific.AlexNetBVLC.execute(AlexNetBVLC.java:199)
	at org.dl4j.benchmarks.ModelSpecific.AlexNetBVLC.main(AlexNetBVLC.java:233)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
	
	
	
	https://github.com/deeplearning4j/Canova/blob/master/canova-nd4j/canova-nd4j-image/src/main/java/org/canova/image/loader/ImageLoader.java#L416

**Comment by agibsonccc** [comment]
This is already fixed. You need to use libnd4j with the latest cmake.

**Comment by nyghtowl** [comment]
Closed by PR #122 in Canova
