### ISSUE TITLE
Nd4j native: (CUDA)

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/nd4j#647]
Fails in intellij when linked against libnd4j with:
./buildnativeoperations.sh blas cuda

Run this with:
https://github.com/deeplearning4j/nd4j/blob/e29dd5ecb9f993378fcb953b8fff44296580e75d/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/Nd4jTestsC.java#L1800-L1800

and the cuda backend with the jvm argument:
-Dorg.nd4j.linalg.tests.backendstorun=org.nd4j.linalg.jcublas.JCublasBackend

org.nd4j.linalg.Nd4jTestsC,testElementWiseOps
o.n.l.BaseNd4jTest - Running org.nd4j.linalg.Nd4jTestsC on backend org.nd4j.linalg.jcublas.JCublasBackend
o.n.j.c.CudaEnvironment - Devices found: 1
o.n.j.a.i.AtomicAllocator - Mapping device [0] to thread [1]
o.n.l.BaseNd4jTest - Ending org.nd4j.linalg.Nd4jTestsC

jcuda.CudaException: cudaErrorInvalidValue

	at jcuda.runtime.JCuda.checkResult(JCuda.java:434)
	at jcuda.runtime.JCuda.cudaHostGetDevicePointer(JCuda.java:3760)
	at org.nd4j.jita.mover.UmaMover.alloc(UmaMover.java:82)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.getDevicePointer(AtomicAllocator.java:495)
	at org.nd4j.linalg.jcublas.buffer.AddressRetriever.retrieveDeviceAddress(AddressRetriever.java:22)
	at org.nd4j.linalg.jcublas.ops.executioner.JCudaExecutioner.invoke(JCudaExecutioner.java:446)
	at org.nd4j.linalg.jcublas.ops.executioner.JCudaExecutioner.exec(JCudaExecutioner.java:261)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.addi(BaseNDArray.java:1338)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.addi(BaseNDArray.java:2676)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.addi(BaseNDArray.java:2663)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.add(BaseNDArray.java:2432)
	at org.nd4j.linalg.Nd4jTestsC.testElementWiseOps(Nd4jTestsC.java:1800)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

Process finished with exit code 255

**Comment by raver119** [comment]
Fixed: https://github.com/deeplearning4j/nd4j/pull/651 and merged into master
