### ISSUE TITLE
NullPointerException when using Maxout (0.4-rc3.8)

### ISSUE THREAD

**Issue by treo** [deeplearning4j/nd4j#655]
When using dl4j and nd4j version 0.4-rc3.8 this example results in the following stacktrace:

```java
package com.example;

import org.deeplearning4j.nn.conf.MultiLayerConfiguration;
import org.deeplearning4j.nn.conf.NeuralNetConfiguration;
import org.deeplearning4j.nn.conf.layers.DenseLayer;
import org.deeplearning4j.nn.conf.layers.OutputLayer;
import org.deeplearning4j.nn.multilayer.MultiLayerNetwork;
import org.deeplearning4j.nn.weights.WeightInit;
import org.deeplearning4j.optimize.listeners.ScoreIterationListener;
import org.nd4j.linalg.dataset.DataSet;
import org.nd4j.linalg.factory.Nd4j;
import org.nd4j.linalg.lossfunctions.LossFunctions;


public class CrashMaxout {

    public static void main(String[] args) {
        int size = 12000;

        MultiLayerConfiguration conf = new NeuralNetConfiguration.Builder()
                .list(2).layer(0,
                        new DenseLayer.Builder()
                                .nIn(size)
                                .nOut(2500)
                                .activation("maxout")
                                .weightInit(WeightInit.XAVIER)
                                .build())
                        .layer(1,
                        new OutputLayer.Builder(LossFunctions.LossFunction.NEGATIVELOGLIKELIHOOD)
                                .nIn(2500)
                                .nOut(250)
                                .weightInit(WeightInit.XAVIER)
                                .activation("sigmoid")
                                .build())
                .backprop(true).pretrain(true)
                .build();

        MultiLayerNetwork model = new MultiLayerNetwork(conf);
        model.init();
        model.setListeners(new ScoreIterationListener(1));

        model.fit(new DataSet(Nd4j.create(1, size), Nd4j.create(1, 250)));

    }
}
```

Stacktrace:
```
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at org.nd4j.linalg.api.parallel.tasks.cpu.BaseCPUAction.blockUntilComplete(BaseCPUAction.java:139)
	at org.nd4j.linalg.api.parallel.tasks.cpu.BaseCPUAction.invokeBlocking(BaseCPUAction.java:154)
	at org.nd4j.linalg.api.parallel.tasks.cpu.BaseCPUAction.invokeBlocking(BaseCPUAction.java:13)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.doTransformOp(DefaultOpExecutioner.java:410)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.exec(DefaultOpExecutioner.java:62)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.execAndReturn(DefaultOpExecutioner.java:186)
	at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:337)
	at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:356)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.activationFromPrevLayer(MultiLayerNetwork.java:513)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForwardToLayer(MultiLayerNetwork.java:636)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForward(MultiLayerNetwork.java:590)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForward(MultiLayerNetwork.java:649)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.finetune(MultiLayerNetwork.java:1429)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1482)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1529)
	at com.example.CrashMaxout.main(CrashMaxout.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at org.nd4j.linalg.api.parallel.tasks.cpu.BaseCPUAction.blockUntilComplete(BaseCPUAction.java:137)
	... 20 more
Caused by: java.lang.NullPointerException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	... 21 more
Caused by: java.lang.NullPointerException
	at org.nd4j.linalg.api.ops.impl.transforms.MaxOut.setMax(MaxOut.java:112)
	at org.nd4j.linalg.api.ops.impl.transforms.MaxOut.op(MaxOut.java:101)
	at org.nd4j.linalg.api.parallel.tasks.cpu.transform.CPUTransformOpAction.execute(CPUTransformOpAction.java:231)
	at org.nd4j.linalg.api.parallel.tasks.cpu.transform.CPUTransformOpAction.compute(CPUTransformOpAction.java:89)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1107)
	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2046)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:390)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at org.nd4j.linalg.api.parallel.tasks.cpu.transform.CPUTransformOpAction.compute(CPUTransformOpAction.java:85)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1107)
	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2046)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:390)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at org.nd4j.linalg.api.parallel.tasks.cpu.transform.CPUTransformOpAction.compute(CPUTransformOpAction.java:85)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

Also note: using the current Snapshot of rc3.9 this does not happen.

**Comment by eraly** [comment]
Closing as outdated. As not observed in rc3.9
