### ISSUE TITLE
Slow SequenceVectors in rc3.9 - Hashtable might block thread

### ISSUE THREAD

**Issue by LukasMasuch** [deeplearning4j/nd4j#659]
I recently updated from rc3.8 to rc3.9-SNAPSHOT and I noticed that word2vec/doc2vec seems to be about 4 times slower with the current version (tested on 3GB of data and with same configuration and same VM). On both VM's the algorithm is utilizing about 99% of CPU, but after inspecting the multiple stack traces with jstack, I noticed that rc3.9 seems to be quite often blocking on this Hashtable (I haven't seen this blocking state in rc3.8): 
```
VectorCalculationsThread 1" #18 prio=5 os_prio=0 tid=0x00000000635c0800 nid=0x1128 waiting for monitor entry [0x0000000061d3e000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.util.Hashtable.get(Hashtable.java:362)
	- locked <0x000000018077c590> (a java.util.Properties)
	at java.util.Properties.getProperty(Properties.java:969)
	at org.nd4j.linalg.api.buffer.util.AllocUtil.getAllocationModeFromContext(AllocUtil.java:44)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:309)
	at org.nd4j.linalg.api.buffer.IntBuffer.<init>(IntBuffer.java:141)
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createInt(DefaultDataBufferFactory.java:303)
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createInt(DefaultDataBufferFactory.java:247)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1140)
	at org.nd4j.linalg.api.shape.Shape.createShapeInformation(Shape.java:1249)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:132)
	at org.nd4j.linalg.cpu.NDArray.<init>(NDArray.java:72)
	at org.nd4j.linalg.cpu.CpuNDArrayFactory.create(CpuNDArrayFactory.java:239)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3299)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.create(BaseNDArray.java:1615)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subArray(BaseNDArray.java:1768)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.get(BaseNDArray.java:3558)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.slice(BaseNDArray.java:2858)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.iterateSample(SkipGram.java:178)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.skipGram(SkipGram.java:154)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.learnSequence(SkipGram.java:129)
	at com.sap.ekg.intelligence.embeddings.deeplearning4j.SequenceVectors.trainSequence(SequenceVectors.java:230)
	at com.sap.ekg.intelligence.embeddings.deeplearning4j.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:911)
```

**Comment by raver119** [comment]
This issue isn't about dl4j/w2v, but about current nd4j mechanics. 

Just a note for further check.

**Comment by LukasMasuch** [comment]
btw. here is the full thread dump:
```
2016-03-10 23:37:20
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.73-b02 mixed mode):

"VectorCalculationsThread 3" #20 prio=5 os_prio=0 tid=0x0000000051a20000 nid=0x9d4 runnable [0x0000000061f3f000]
   java.lang.Thread.State: RUNNABLE
	at com.github.fommil.netlib.NativeSystemBLAS.sdot_offsets(Native Method)
	at com.github.fommil.netlib.NativeSystemBLAS.sdot(NativeSystemBLAS.java:423)
	at org.nd4j.linalg.cpu.blas.CpuLevel1.sdot(CpuLevel1.java:38)
	at org.nd4j.linalg.api.blas.impl.BaseLevel1.dot(BaseLevel1.java:33)
	at org.nd4j.linalg.factory.BaseBlasWrapper.dot(BaseBlasWrapper.java:188)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.iterateSample(SkipGram.java:234)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.skipGram(SkipGram.java:154)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.learnSequence(SkipGram.java:129)
	at com.sap.ekg.intelligence.embeddings.deeplearning4j.SequenceVectors.trainSequence(SequenceVectors.java:230)
	at com.sap.ekg.intelligence.embeddings.deeplearning4j.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:911)

"VectorCalculationsThread 2" #19 prio=5 os_prio=0 tid=0x0000000063f0c000 nid=0x1614 waiting for monitor entry [0x0000000061e3f000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.util.Hashtable.get(Hashtable.java:362)
	- waiting to lock <0x000000018077c590> (a java.util.Properties)
	at java.util.Properties.getProperty(Properties.java:969)
	at org.nd4j.linalg.api.buffer.util.AllocUtil.getAllocationModeFromContext(AllocUtil.java:44)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:309)
	at org.nd4j.linalg.api.buffer.IntBuffer.<init>(IntBuffer.java:141)
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createInt(DefaultDataBufferFactory.java:303)
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createInt(DefaultDataBufferFactory.java:247)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1140)
	at org.nd4j.linalg.api.shape.Shape.createShapeInformation(Shape.java:1249)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:132)
	at org.nd4j.linalg.cpu.NDArray.<init>(NDArray.java:72)
	at org.nd4j.linalg.cpu.CpuNDArrayFactory.create(CpuNDArrayFactory.java:239)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3299)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.create(BaseNDArray.java:1615)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subArray(BaseNDArray.java:1768)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.get(BaseNDArray.java:3558)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.slice(BaseNDArray.java:2858)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.iterateSample(SkipGram.java:250)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.skipGram(SkipGram.java:154)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.learnSequence(SkipGram.java:129)
	at com.sap.ekg.intelligence.embeddings.deeplearning4j.SequenceVectors.trainSequence(SequenceVectors.java:230)
	at com.sap.ekg.intelligence.embeddings.deeplearning4j.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:911)

"VectorCalculationsThread 1" #18 prio=5 os_prio=0 tid=0x00000000635c0800 nid=0x1128 waiting for monitor entry [0x0000000061d3e000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.util.Hashtable.get(Hashtable.java:362)
	- locked <0x000000018077c590> (a java.util.Properties)
	at java.util.Properties.getProperty(Properties.java:969)
	at org.nd4j.linalg.api.buffer.util.AllocUtil.getAllocationModeFromContext(AllocUtil.java:44)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:309)
	at org.nd4j.linalg.api.buffer.IntBuffer.<init>(IntBuffer.java:141)
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createInt(DefaultDataBufferFactory.java:303)
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createInt(DefaultDataBufferFactory.java:247)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1140)
	at org.nd4j.linalg.api.shape.Shape.createShapeInformation(Shape.java:1249)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:132)
	at org.nd4j.linalg.cpu.NDArray.<init>(NDArray.java:72)
	at org.nd4j.linalg.cpu.CpuNDArrayFactory.create(CpuNDArrayFactory.java:239)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3299)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.create(BaseNDArray.java:1615)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subArray(BaseNDArray.java:1768)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.get(BaseNDArray.java:3558)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.slice(BaseNDArray.java:2858)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.iterateSample(SkipGram.java:178)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.skipGram(SkipGram.java:154)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.learnSequence(SkipGram.java:129)
	at com.sap.ekg.intelligence.embeddings.deeplearning4j.SequenceVectors.trainSequence(SequenceVectors.java:230)
	at com.sap.ekg.intelligence.embeddings.deeplearning4j.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:911)

"VectorCalculationsThread 0" #17 prio=5 os_prio=0 tid=0x00000000511de800 nid=0xcd0 runnable [0x0000000061c3f000]
   java.lang.Thread.State: RUNNABLE
	at org.nd4j.linalg.api.shape.Shape.elementWiseStride(Shape.java:618)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:134)
	at org.nd4j.linalg.cpu.NDArray.<init>(NDArray.java:72)
	at org.nd4j.linalg.cpu.CpuNDArrayFactory.create(CpuNDArrayFactory.java:239)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3299)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.create(BaseNDArray.java:1615)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subArray(BaseNDArray.java:1768)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.get(BaseNDArray.java:3558)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.slice(BaseNDArray.java:2858)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.iterateSample(SkipGram.java:255)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.skipGram(SkipGram.java:154)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.learnSequence(SkipGram.java:129)
	at com.sap.ekg.intelligence.embeddings.deeplearning4j.SequenceVectors.trainSequence(SequenceVectors.java:230)
	at com.sap.ekg.intelligence.embeddings.deeplearning4j.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:911)

"AsyncSequencer thread" #16 prio=5 os_prio=0 tid=0x0000000050af8000 nid=0xb40 waiting on condition [0x0000000061b3f000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at com.sap.ekg.intelligence.embeddings.deeplearning4j.SequenceVectors$AsyncSequencer.run(SequenceVectors.java:826)

"Monitor Ctrl-Break" #10 daemon prio=5 os_prio=0 tid=0x0000000050366000 nid=0x1804 runnable [0x0000000050dcf000]
   java.lang.Thread.State: RUNNABLE
	at java.net.DualStackPlainSocketImpl.accept0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketAccept(DualStackPlainSocketImpl.java:131)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:199)
	- locked <0x00000001802730c8> (a java.net.SocksSocketImpl)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at com.intellij.rt.execution.application.AppMain$1.run(AppMain.java:90)
	at java.lang.Thread.run(Thread.java:745)

"Service Thread" #9 daemon prio=9 os_prio=0 tid=0x000000004ec6d800 nid=0x1bfc runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread2" #8 daemon prio=9 os_prio=2 tid=0x000000004ec51000 nid=0x1bf8 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #7 daemon prio=9 os_prio=2 tid=0x000000004d44d800 nid=0x1bf4 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #6 daemon prio=9 os_prio=2 tid=0x000000004d449800 nid=0x1bf0 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Attach Listener" #5 daemon prio=5 os_prio=2 tid=0x000000004d448000 nid=0x1bec waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=2 tid=0x000000004d447800 nid=0x1be8 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=1 tid=0x0000000002b26000 nid=0x1be4 in Object.wait() [0x000000004e76f000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x0000000180273b20> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x0000000180273b20> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=2 tid=0x0000000002b1d000 nid=0x1be0 in Object.wait() [0x000000004e66f000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x0000000180273b60> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:157)
	- locked <0x0000000180273b60> (a java.lang.ref.Reference$Lock)

"main" #1 prio=5 os_prio=0 tid=0x00000000028dd800 nid=0x1bbc in Object.wait() [0x0000000002a2e000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x0000000183f034f8> (a com.sap.ekg.intelligence.embeddings.deeplearning4j.SequenceVectors$AsyncSequencer)
	at java.lang.Thread.join(Thread.java:1245)
	- locked <0x0000000183f034f8> (a com.sap.ekg.intelligence.embeddings.deeplearning4j.SequenceVectors$AsyncSequencer)
	at java.lang.Thread.join(Thread.java:1319)
	at com.sap.ekg.intelligence.embeddings.deeplearning4j.SequenceVectors.fit(SequenceVectors.java:190)
	at com.sap.ekg.intelligence.embeddings.word.WordEmbedding.createVectorSpace(WordEmbedding.java:156)
	at com.sap.ekg.intelligence.embeddings.word.WordEmbedding.createVectorSpace(WordEmbedding.java:112)
	at com.sap.ekg.intelligence.embeddings.word.WordEmbeddingEvaluation.createVectorSpace(WordEmbeddingEvaluation.java:172)
	at com.sap.ekg.intelligence.embeddings.word.WordEmbeddingEvaluation.evaluate(WordEmbeddingEvaluation.java:83)
	at com.sap.ekg.toolbox.experiments.ParamOptExperiment.evaluate(ParamOptExperiment.java:46)
	at com.sap.ekg.toolbox.experiments.Experiment.run(Experiment.java:51)
	at com.sap.ekg.intelligence.test.TestWordEmbeddingsExperiment.main(TestWordEmbeddingsExperiment.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

"VM Thread" os_prio=2 tid=0x000000004d3c7800 nid=0x1bdc runnable 

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x0000000002a46800 nid=0x1bc0 runnable 

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x0000000002a48000 nid=0x1bc4 runnable 

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x0000000002a49800 nid=0x1bc8 runnable 

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x0000000002a4b000 nid=0x1bcc runnable 

"VM Periodic Task Thread" os_prio=2 tid=0x000000004ecb7000 nid=0x16d8 waiting on condition 

JNI global references: 239
```

**Comment by raver119** [comment]
This shouldn't be an issue anymore.
