### ISSUE TITLE
Cuda Crashing Examples

### ISSUE THREAD

**Issue by treo** [deeplearning4j/nd4j#663]
In this issue I'll collect some examples of applications that crash the current state of the cuda implementation, they are meant to be used as an aid in debugging those problems :)

When running the following example program using the current state of the jita_cuda_1_1 branch, it crashes with the following stacktrace:

```java
package com.example;

import org.deeplearning4j.nn.conf.MultiLayerConfiguration;
import org.deeplearning4j.nn.conf.NeuralNetConfiguration;
import org.deeplearning4j.nn.conf.layers.AutoEncoder;
import org.deeplearning4j.nn.conf.layers.OutputLayer;
import org.deeplearning4j.nn.multilayer.MultiLayerNetwork;
import org.deeplearning4j.nn.weights.WeightInit;
import org.deeplearning4j.optimize.listeners.ScoreIterationListener;
import org.nd4j.linalg.dataset.DataSet;
import org.nd4j.linalg.factory.Nd4j;
import org.nd4j.linalg.lossfunctions.LossFunctions;

public class Crash {

    public static void main(String[] args) {
        int size = 12;

        MultiLayerConfiguration conf = new NeuralNetConfiguration.Builder()
                .list(
                        new AutoEncoder.Builder().nIn(size).nOut(10)
                                .weightInit(WeightInit.XAVIER).lossFunction(LossFunctions.LossFunction.RMSE_XENT)
                                .corruptionLevel(0.1)
                                .build(),
                        new OutputLayer.Builder(LossFunctions.LossFunction.NEGATIVELOGLIKELIHOOD)
                                .nIn(10)
                                .nOut(5)
                                .weightInit(WeightInit.XAVIER)
                                .activation("sigmoid")
                                .build())
                .backprop(true).pretrain(true)
                .build();

        MultiLayerNetwork model = new MultiLayerNetwork(conf);
        model.init();
        model.setListeners(new ScoreIterationListener(1));

        model.fit(new DataSet(Nd4j.create(1, size), Nd4j.create(1, 5)));

    }
}
```

```
Exception in thread "main" jcuda.CudaException: cudaErrorLaunchFailure
	at jcuda.runtime.JCuda.checkResult(JCuda.java:435)
	at jcuda.runtime.JCuda.cudaStreamSynchronize(JCuda.java:6661)
	at org.nd4j.linalg.jcublas.context.CudaContext.syncOldStream(CudaContext.java:70)
	at org.nd4j.jita.mover.UmaMover.relocate(UmaMover.java:202)
	at org.nd4j.jita.mover.UmaMover.copyback(UmaMover.java:306)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.trySynchronizeHostData(AtomicAllocator.java:730)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.asNio(BaseCudaDataBuffer.java:891)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:138)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<init>(BaseCudaDataBuffer.java:152)
	at org.nd4j.linalg.jcublas.buffer.CudaFloatDataBuffer.<init>(CudaFloatDataBuffer.java:57)
	at org.nd4j.linalg.jcublas.buffer.factory.CudaDataBufferFactory.create(CudaDataBufferFactory.java:53)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:960)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:131)
	at org.nd4j.linalg.jcublas.JCublasNDArray.<init>(JCublasNDArray.java:321)
	at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.create(JCublasNDArrayFactory.java:210)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3300)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.create(BaseNDArray.java:1615)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.permute(BaseNDArray.java:4026)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.transposei(BaseNDArray.java:3174)
	at org.deeplearning4j.nn.layers.feedforward.autoencoder.AutoEncoder.decode(AutoEncoder.java:84)
	at org.deeplearning4j.nn.layers.feedforward.autoencoder.AutoEncoder.computeGradientAndScore(AutoEncoder.java:122)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:146)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.optimize(BaseOptimizer.java:165)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:51)
	at org.deeplearning4j.nn.layers.BaseLayer.fit(BaseLayer.java:501)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.pretrain(MultiLayerNetwork.java:226)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1378)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1431)
	at com.example.Crash.main(Crash.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
 ** On entry to SGEMM  parameter number 10 had an illegal value
```

And another example from an outdated version of the examples repo, that results in cudaErrorLaunchFailure:
```java
package org.deeplearning4j.examples.mlp;


import org.deeplearning4j.datasets.iterator.DataSetIterator;
import org.deeplearning4j.datasets.iterator.impl.MnistDataSetIterator;
import org.deeplearning4j.eval.Evaluation;
import org.deeplearning4j.nn.api.OptimizationAlgorithm;
import org.deeplearning4j.nn.conf.GradientNormalization;
import org.deeplearning4j.nn.conf.MultiLayerConfiguration;
import org.deeplearning4j.nn.conf.NeuralNetConfiguration;
import org.deeplearning4j.nn.conf.layers.DenseLayer;
import org.deeplearning4j.nn.conf.layers.OutputLayer;
import org.deeplearning4j.nn.multilayer.MultiLayerNetwork;
import org.deeplearning4j.nn.weights.WeightInit;
import org.deeplearning4j.optimize.api.IterationListener;
import org.deeplearning4j.optimize.listeners.ScoreIterationListener;
import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.dataset.DataSet;
import org.nd4j.linalg.dataset.SplitTestAndTrain;
import org.nd4j.linalg.factory.Nd4j;
import org.nd4j.linalg.lossfunctions.LossFunctions.LossFunction;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.*;


/**
 * Created by agibsonccc on 9/11/14.
 *
 * Diff from small single layer
 */
public class MLPMnistSingleLayerExample {

    private static Logger log = LoggerFactory.getLogger(MLPMnistSingleLayerExample.class);

    public static void main(String[] args) throws Exception {
        Nd4j.ENFORCE_NUMERICAL_STABILITY = true;
        final int numRows = 28;
        final int numColumns = 28;
        int outputNum = 10;
        int numSamples =10000;
        int batchSize = 500;
        int iterations = 10;
        int seed = 123;
        int listenerFreq = iterations/5;
        int splitTrainNum = (int) (batchSize*.8);
        DataSet mnist;
        SplitTestAndTrain trainTest;
        DataSet trainInput;
        List<INDArray> testInput = new ArrayList<>();
        List<INDArray> testLabels = new ArrayList<>();

        log.info("Load data....");
        DataSetIterator mnistIter = new MnistDataSetIterator(batchSize, numSamples,true);

        log.info("Build model....");
        MultiLayerConfiguration conf = new NeuralNetConfiguration.Builder()
                .seed(seed)
                .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
                .iterations(iterations)
                .gradientNormalization(GradientNormalization.RenormalizeL2PerLayer)
                .learningRate(1e-1f)
                .momentum(0.5)
                .momentumAfter(Collections.singletonMap(3, 0.9))
                .useDropConnect(true)
                .list(2)
                .layer(0, new DenseLayer.Builder()
                        .nIn(numRows * numColumns)
                        .nOut(1000)
                        .activation("relu")
                        .weightInit(WeightInit.XAVIER)
                        .build())
                .layer(1, new OutputLayer.Builder(LossFunction.NEGATIVELOGLIKELIHOOD)
                        .nIn(1000)
                        .nOut(outputNum)
                        .activation("softmax")
                        .weightInit(WeightInit.XAVIER)
                        .build())
                .build();

        MultiLayerNetwork model = new MultiLayerNetwork(conf);
        model.init();
        model.setListeners(Collections.singletonList((IterationListener) new ScoreIterationListener(listenerFreq)));

        log.info("Train model....");
        model.setListeners(Collections.singletonList((IterationListener) new ScoreIterationListener(listenerFreq)));
        while(mnistIter.hasNext()) {
            mnist = mnistIter.next();
            trainTest = mnist.splitTestAndTrain(splitTrainNum, new Random(seed)); // train set that is the result
            trainInput = trainTest.getTrain(); // get feature matrix and labels for training
            testInput.add(trainTest.getTest().getFeatureMatrix());
            testLabels.add(trainTest.getTest().getLabels());
            model.fit(trainInput);
        }

        log.info("Evaluate model....");
        Evaluation eval = new Evaluation(outputNum);
        for(int i = 0; i < testInput.size(); i++) {
            INDArray output = model.output(testInput.get(i));
            eval.eval(testLabels.get(i), output);
        }

        log.info(eval.stats());
        log.info("****************Example finished********************");
    }
}
```

```
Exception in thread "main" java.lang.RuntimeException: jcuda.CudaException: cudaErrorLaunchFailure
	at org.nd4j.linalg.jcublas.blas.JcublasLevel3.sgemm(JcublasLevel3.java:80)
	at org.nd4j.linalg.api.blas.impl.BaseLevel3.gemm(BaseLevel3.java:56)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmuli(BaseNDArray.java:2524)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmul(BaseNDArray.java:2333)
	at org.deeplearning4j.nn.layers.BaseLayer.preOutput(BaseLayer.java:327)
	at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:338)
	at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:358)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.activationFromPrevLayer(MultiLayerNetwork.java:520)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForwardToLayer(MultiLayerNetwork.java:643)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForward(MultiLayerNetwork.java:597)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForward(MultiLayerNetwork.java:656)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.finetune(MultiLayerNetwork.java:1325)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1379)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1431)
	at org.deeplearning4j.examples.mlp.MLPMnistSingleLayerExample.main(MLPMnistSingleLayerExample.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: jcuda.CudaException: cudaErrorLaunchFailure
	at jcuda.runtime.JCuda.checkResult(JCuda.java:435)
	at jcuda.runtime.JCuda.cudaStreamSynchronize(JCuda.java:6661)
	at org.nd4j.linalg.jcublas.context.CudaContext.syncOldStream(CudaContext.java:70)
	at org.nd4j.linalg.jcublas.blas.JcublasLevel3.sgemm(JcublasLevel3.java:68)
	... 19 more
```

**Comment by treo** [comment]
When trying to simplify the prior example I ran into the following:

```java
package com.example;

import org.deeplearning4j.nn.conf.MultiLayerConfiguration;
import org.deeplearning4j.nn.conf.NeuralNetConfiguration;
import org.deeplearning4j.nn.conf.layers.AutoEncoder;
import org.deeplearning4j.nn.conf.layers.OutputLayer;
import org.deeplearning4j.nn.multilayer.MultiLayerNetwork;
import org.deeplearning4j.nn.weights.WeightInit;
import org.deeplearning4j.optimize.listeners.ScoreIterationListener;
import org.nd4j.linalg.dataset.DataSet;
import org.nd4j.linalg.factory.Nd4j;
import org.nd4j.linalg.lossfunctions.LossFunctions;

public class CrashNP {

    public static void main(String[] args) {
        int size = 12;

        MultiLayerConfiguration conf = new NeuralNetConfiguration.Builder()
                .list(
                        new AutoEncoder.Builder().nIn(size).nOut(10)
                                .weightInit(WeightInit.XAVIER).lossFunction(LossFunctions.LossFunction.RMSE_XENT)
                                .corruptionLevel(0.1)
                                .build(),
                        new OutputLayer.Builder(LossFunctions.LossFunction.NEGATIVELOGLIKELIHOOD)
                                .nIn(10)
                                .nOut(5)
                                .weightInit(WeightInit.XAVIER)
                                .activation("sigmoid")
                                .build())
                .backprop(true).pretrain(true)
                .build();

        MultiLayerNetwork model = new MultiLayerNetwork(conf);
        model.init();
        model.setListeners(new ScoreIterationListener(1));

        model.fit(new DataSet(Nd4j.create(1, size), Nd4j.create(1, 5)));
    }
}
```

which resulted in this stacktrace:

```
Exception in thread "main" java.lang.NullPointerException
	at org.nd4j.linalg.jcublas.ops.executioner.JCudaExecutioner.exec(JCudaExecutioner.java:80)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.sum(BaseNDArray.java:3352)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.sumNumber(BaseNDArray.java:995)
	at org.nd4j.linalg.lossfunctions.LossCalculation.score(LossCalculation.java:38)
	at org.deeplearning4j.nn.layers.BasePretrainNetwork.setScoreWithZ(BasePretrainNetwork.java:121)
	at org.deeplearning4j.nn.layers.feedforward.autoencoder.AutoEncoder.computeGradientAndScore(AutoEncoder.java:134)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:146)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.optimize(BaseOptimizer.java:165)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:51)
	at org.deeplearning4j.nn.layers.BaseLayer.fit(BaseLayer.java:501)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.pretrain(MultiLayerNetwork.java:226)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1378)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1431)
	at com.example.CrashNP.main(CrashNP.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
 ** On entry to SGEMM  parameter number 10 had an illegal value
 ** On entry to SGEMM  parameter number 10 had an illegal value
 ** On entry to SGEMM  parameter number 8 had an illegal value
 ** On entry to SGEMM  parameter number 8 had an illegal value
```

**Comment by treo** [comment]
And another test program that seems to run into illegal SGEMM parameter values, though its ultimate crash reason is an UnsupportedOperationException:

```java
package com.example;

import org.deeplearning4j.nn.conf.MultiLayerConfiguration;
import org.deeplearning4j.nn.conf.NeuralNetConfiguration;
import org.deeplearning4j.nn.conf.layers.DenseLayer;
import org.deeplearning4j.nn.conf.layers.OutputLayer;
import org.deeplearning4j.nn.multilayer.MultiLayerNetwork;
import org.deeplearning4j.nn.weights.WeightInit;
import org.deeplearning4j.optimize.listeners.ScoreIterationListener;
import org.nd4j.linalg.dataset.DataSet;
import org.nd4j.linalg.factory.Nd4j;
import org.nd4j.linalg.lossfunctions.LossFunctions;

public class CrashMaxout {

    public static void main(String[] args) {
        int size = 12000;

        MultiLayerConfiguration conf = new NeuralNetConfiguration.Builder()
                .list(2).layer(0,
                        new DenseLayer.Builder()
                                .nIn(size)
                                .nOut(2500)
                                .activation("maxout")
                                .weightInit(WeightInit.XAVIER)
                                .build())
                        .layer(1,
                        new OutputLayer.Builder(LossFunctions.LossFunction.NEGATIVELOGLIKELIHOOD)
                                .nIn(2500)
                                .nOut(250)
                                .weightInit(WeightInit.XAVIER)
                                .activation("sigmoid")
                                .build())
                .backprop(true).pretrain(true)
                .build();

        MultiLayerNetwork model = new MultiLayerNetwork(conf);
        model.init();
        model.setListeners(new ScoreIterationListener(1));


        model.fit(new DataSet(Nd4j.create(1, size), Nd4j.create(1, 250)));
    }
}
```

```
Exception in thread "main" java.lang.UnsupportedOperationException
	at org.nd4j.linalg.api.ops.impl.transforms.MaxOut.opNum(MaxOut.java:60)
	at org.nd4j.linalg.jcublas.ops.executioner.JCudaExecutioner.invoke(JCudaExecutioner.java:497)
	at org.nd4j.linalg.jcublas.ops.executioner.JCudaExecutioner.execAndReturn(JCudaExecutioner.java:277)
	at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:339)
	at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:358)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.activationFromPrevLayer(MultiLayerNetwork.java:520)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForwardToLayer(MultiLayerNetwork.java:643)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForward(MultiLayerNetwork.java:597)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForward(MultiLayerNetwork.java:656)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.finetune(MultiLayerNetwork.java:1325)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1379)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1431)
	at com.example.CrashMaxout.main(CrashMaxout.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
 ** On entry to SGEMM  parameter number 10 had an illegal value
```

**Comment by agibsonccc** [comment]
@treo could you update this issue when you get the chance?

**Comment by treo** [comment]
All, but the maxout examples run fine. I'll create a new Issue for it on libnd4j, as that is a new problem.
