### ISSUE TITLE
java.lang.RuntimeException: java.io.StreamCorruptedException: invalid stream header: 00000002

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/nd4j#690]
ST: Exception in thread "main" java.lang.RuntimeException: java.io.StreamCorruptedException: invalid stream header: 00000002
	at org.nd4j.linalg.util.SerializationUtils.readObject(SerializationUtils.java:58)
	at org.nd4j.linalg.factory.Nd4j.read(Nd4j.java:1941)
	at org.deeplearning4j.examples.nb15.streaming.NB15Streaming.main(NB15Streaming.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.io.StreamCorruptedException: invalid stream header: 00000002
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:806)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
	at org.nd4j.linalg.util.SerializationUtils.readObject(SerializationUtils.java:53)

When using nd4j 3.9 snapshot the above is caused when Nd4j.read(new DataInputStream(new FileInputStream(new File(filename)))));

Filename contains text that was stored using DataOuputStream & FileOutputStream and Nd4j.write 

Note: Potential problem because using Nd4j.write in 3.8 to store file and Nd4j.read in 3.9 to read.

**Comment by nyghtowl** [comment]
Resolved somewhere along the development way
