### ISSUE TITLE
NullPointerException in Pow Op

### ISSUE THREAD

**Issue by treo** [deeplearning4j/nd4j#718]
While trying my usual crashing scenarios, I've ran into a NullPointerException:
```
Exception in thread "main" java.lang.NullPointerException
	at org.nd4j.linalg.ops.transforms.Transforms.exec(Transforms.java:617)
	at org.nd4j.linalg.ops.transforms.Transforms.pow(Transforms.java:527)
	at org.nd4j.linalg.ops.transforms.Transforms.pow(Transforms.java:300)
	at com.example.App.main(App.java:20)
```

It looks like it is due to Pow overriding the init method, such that when BaseOp calls init, it actually calls Pow's init on Pow instead of it own, which in turn results in x, y, z and n not being set and hence the Null Pointer Exception.

You can easily reproduce it with: `Transforms.pow(Nd4j.ones(1), 1);`

**Comment by AlexDBlack** [comment]
Looks like this was fixed here: https://github.com/deeplearning4j/nd4j/pull/721
