### ISSUE TITLE
mmuli doesn't work

### ISSUE THREAD

**Issue by ultrasuperpingu** [deeplearning4j/nd4j#740]
```
INDArray t1=Nd4j.rand(2, 2);
INDArray t2=Nd4j.rand(2, 2);
t1.mmuli(t2);

```
Result: 	Exception in thread "main" java.lang.IllegalStateException: C is not order f
	at org.nd4j.linalg.api.blas.params.GemmParams.validate(GemmParams.java:103)
	at org.nd4j.linalg.api.blas.params.GemmParams.<init>(GemmParams.java:50)
	at org.nd4j.linalg.api.blas.impl.BaseLevel3.gemm(BaseLevel3.java:38)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmuli(BaseNDArray.java:2537)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmuli(BaseNDArray.java:2465)
        

In the pom.xml : 
```
<dependency>
       <groupId>org.nd4j</groupId>
       <artifactId>nd4j-x86</artifactId>
       <version>0.4-rc3.8</version>
</dependency>
```
tested with:

```
<dependency>
       <groupId>org.nd4j</groupId>
       <artifactId>nd4j-jblast</artifactId>
       <version>0.4-rc3.6</version>
</dependency>
```
with the same result.

**Comment by agibsonccc** [comment]
This isn't an issue on master. I'm closing this.
