### ISSUE TITLE
Exception in Nd4j.argMax function in rc3.9-SNAPSHOOT

### ISSUE THREAD

**Issue by liguo2012** [deeplearning4j/nd4j#804]
java.lang.UnsupportedOperationException: Operation should use exec special
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.exec(DefaultOpExecutioner.java:298)
	at org.nd4j.linalg.factory.Nd4j.argMax(Nd4j.java:588)
	at org.deaplearning.algo.SGD.compareResults(SGD.java:241)
	at org.deaplearning.algo.SGD.start(SGD.java:204)
	at org.deaplearning.ChartingGUI$1.run(ChartingGUI.java:120)
	at java.lang.Thread.run(Thread.java:745)

When using the Nd4j.argMax method, exception shown as the above in rc3.9-SNAPSHOT, rc3.8 stable has not got this problem.

Thanks

**Comment by agibsonccc** [comment]
@AlexDBlack is this in the current unit test? I'm pretty sure argmax is fine when installing from source?

**Comment by agibsonccc** [comment]
This should be fixed? I'm closing this. Ensure you are using source not snapshot.
