### ISSUE TITLE
Exception in tranpose() function

### ISSUE THREAD

**Issue by c0der1337** [deeplearning4j/nd4j#86]
Java code:
    INDArray w = Nd4j.rand(new int[]{2,2});
    w.putScalar(0, 1);
    w.putScalar(1, 2);
    w.putScalar(2, 3);
    w.putScalar(3, 4);
    System.out.println(w);
    System.out.println(w.transpose());

Output:
[[1.0, 3.0]
[2.0, 4.0]]

thanks in advance for fixing

Exception in thread "main" java.lang.IllegalArgumentException: Invalid dimension: 1 : negative value
at org.nd4j.linalg.api.ndarray.BaseNDArray.checkArrangeArray(BaseNDArray.java:3742)
at org.nd4j.linalg.api.ndarray.BaseNDArray.permute(BaseNDArray.java:3699)
at org.nd4j.linalg.api.ndarray.BaseNDArray.transposei(BaseNDArray.java:2990)
at org.nd4j.linalg.api.ndarray.BaseNDArray.transpose(BaseNDArray.java:2976)

**Comment by agibsonccc** [comment]
Fixed.
