### ISSUE TITLE
Divide by zero exception on Nd4j.readNumpy() arrays 

### ISSUE THREAD

**Issue by edudar** [deeplearning4j/nd4j#883]
From #253 comment.

I do reads from `bumpy` output as `Nd4j.readNumpy(IOUtils.toInputStream(...), " ")` and see very similar exception occasionally. Stacktrace is different because of refactoring in the project I guess but it leads to the very same place after all:
```
Caused by: java.lang.ArithmeticException: / by zero
    at org.nd4j.linalg.api.ndarray.BaseNDArray.tensorssAlongDimension(BaseNDArray.java:725)
    at org.nd4j.linalg.api.ops.impl.accum.StandardDeviation.exec(StandardDeviation.java:91)
    at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.exec(DefaultOpExecutioner.java:245)
    at org.nd4j.linalg.api.ndarray.BaseNDArray.std(BaseNDArray.java:3357)
```
I was not able to reproduce it consistently. Same `numpy` output downloaded to dev machine was processed just fine.

P.S. Exception happens later in the code when I'm trying to use that value I got from `readNumpy` it's called `features` in the snippet below:
```
List<Double> distances = pairs.stream()
    .map(pair -> pair._1.features.sub(pair._2.features).norm2Number().doubleValue())
    .collect(toList());
INDArray ndDistances = Nd4j.create(Doubles.toArray(distances));
double mean = ndDistances.mean(1).getDouble(0);
double std = ndDistances.std(1).getDouble(0);
```

**Comment by edudar** [comment]
I was able to properly replicate this case and fixed the problem that led to broken input for nd4j. Closing this ticket.
