### ISSUE TITLE
NDArrayIndex.interval slices NDArray wrongly.

### ISSUE THREAD

**Issue by taisukeoe** [deeplearning4j/nd4j#981]
I found ND4S test cases are broken due to following bugs in 0.4-rc3.9.

```scala
//works fine
scala> Nd4j.linspace(1,5,5).get(NDArrayIndex.interval(0,2,2,false))
res3: org.nd4j.linalg.api.ndarray.INDArray = 1.00

//works fine
scala> Nd4j.linspace(1,5,5).get(NDArrayIndex.interval(0,2,2,true))
res4: org.nd4j.linalg.api.ndarray.INDArray = [1.00, 3.00]

//works fine
scala> Nd4j.linspace(1,5,5).get(NDArrayIndex.interval(1,2,3,false))
res11: org.nd4j.linalg.api.ndarray.INDArray = 2.00

//should be [2.00, 4.00]
scala> Nd4j.linspace(1,5,5).get(NDArrayIndex.interval(1,2,3,true))
res10: org.nd4j.linalg.api.ndarray.INDArray = [3.00, 5.00]

//should be [2.00, 4.00] 
scala> Nd4j.linspace(1,5,5).get(NDArrayIndex.interval(1,2,4,true))
res9: org.nd4j.linalg.api.ndarray.INDArray = [3.00, 5.00]

//should be [2.00, 4.00]
scala> Nd4j.linspace(1,5,5).get(NDArrayIndex.interval(1,2,4,false))
res8: org.nd4j.linalg.api.ndarray.INDArray = [3.00, 5.00]

//works fine
scala> Nd4j.linspace(1,5,5).get(NDArrayIndex.interval(2,2,4,false))
res1: org.nd4j.linalg.api.ndarray.INDArray = 3.00

//should return [3.00, 5.00] without exception
scala> Nd4j.linspace(1,5,5).get(NDArrayIndex.interval(2,2,4,true))
java.lang.IndexOutOfBoundsException: 6
  at org.bytedeco.javacpp.indexer.Indexer.checkIndex(Indexer.java:88)
  at org.bytedeco.javacpp.indexer.FloatRawIndexer.get(FloatRawIndexer.java:59)
  at org.nd4j.linalg.api.buffer.BaseDataBuffer.getDouble(BaseDataBuffer.java:1016)
  at org.nd4j.linalg.api.shape.Shape.getDouble(Shape.java:167)
  at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:1468)
  at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:3238)
```

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/pull/985
