### ISSUE TITLE
Data Type change error

### ISSUE THREAD

**Issue by thisIsNiceName** [deeplearning4j/nd4j#995]
So i changed the data type of my program like that : 

INDArray arr = Nd4j.create(1);
DataTypeUtil.setDTypeForContext(DataBuffer.Type.DOUBLE);

And as soon as I did that I got 2 errors : 

**org.bytedeco.javacpp.indexer.FloatRawIndexer cannot be cast to org.bytedeco.javacpp.indexer.DoubleIndexer
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.read(BaseDataBuffer.java:1456)
	at org.nd4j.linalg.factory.Nd4j.read(Nd4j.java:1964)
	at org.nd4j.linalg.dataset.DataSet.load(DataSet.java:346)
	at LENET.run(LENET.java:118)
Caused by: java.lang.ClassCastException: org.bytedeco.javacpp.indexer.FloatRawIndexer cannot be cast to org.bytedeco.javacpp.indexer.DoubleIndexer
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.put(BaseDataBuffer.java:1105)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.put(BaseDataBuffer.java:1088)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.read(BaseDataBuffer.java:1417)
	... 4 more**

And after that error in the console i got : 

**Invalid input: expect output columns must be equal to rows 200 x columns 200 but was instead [1, 1]**

==============================================================================

for the last error, i checked multiple time and I use the same size everytime, and I got that error after the data type change.

You can see the whole code here : 

Put the DataSet into file for memory reasons
http://puu.sh/pcB7C/516db30985.java and http://puu.sh/pcB8k/fddf3272cf.java and http://puu.sh/pcDhi/fc775701e2.java

for the pom.xml file, i used the one from github (with last version of dl4j) : http://puu.sh/pcEfy/1e3dd8dc7a.xml

I do not use the GPU for computing

Thank.

**Comment by agibsonccc** [comment]
@saudet Suggestions here? It's serialization related. Basically a different data type is loaded than is what is peristed.

**Comment by agibsonccc** [comment]
This SHOULD fix that: https://github.com/deeplearning4j/nd4j/pull/998
