### ISSUE TITLE
"Illegal combination of indexes for vector" when running GravesLSTMCharModellingExample

### ISSUE THREAD

**Issue by treo** [deeplearning4j/nd4j#997]
```
Exception in thread "main" java.lang.UnsupportedOperationException: Illegal combination of indexes for vector
	at org.nd4j.linalg.indexing.ShapeOffsetResolution.tryShortCircuit(ShapeOffsetResolution.java:113)
	at org.nd4j.linalg.indexing.ShapeOffsetResolution.exec(ShapeOffsetResolution.java:325)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.get(BaseNDArray.java:3671)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.put(BaseNDArray.java:1787)
	at org.deeplearning4j.nn.params.GravesLSTMParamInitializer.init(GravesLSTMParamInitializer.java:62)
	at org.deeplearning4j.nn.layers.factory.DefaultLayerFactory.getParams(DefaultLayerFactory.java:107)
	at org.deeplearning4j.nn.layers.factory.DefaultLayerFactory.create(DefaultLayerFactory.java:64)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:361)
	at org.deeplearning4j.examples.recurrent.character.GravesLSTMCharModellingExample.main(GravesLSTMCharModellingExample.java:90)
```

On current master.

**Comment by agibsonccc** [comment]
Mind seeing where this triggers? https://github.com/deeplearning4j/nd4j/blob/41f0a0befd321d98035cf9f636d3cc7048055167/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/indexing/ShapeOffsetResolution.java#L113-L113 A conditional breakpoint in intellij should be enough to catch that.

**Comment by treo** [comment]
Apparently new -SNAPSHOT Versions of DL4J aren't landing in sonatype at the moment. So I've been getting a version that has been using `new NDArrayIndex(0)` instead of `NDArrayIndex.point(0)`.
