### ISSUE TITLE
Master Broken

### ISSUE THREAD

**Issue by treo** [deeplearning4j/nd4j#999]
Commit 00890f5a734268079b2840fcb7b991a95c47eb91 breaks master such that running even just the following results in a null pointer exception:

```java
INDArray array = Nd4j.create(new float[]{1f,2f,3f,4f,5f});
float sum = array.sumNumber().floatValue();
```

```
Exception in thread "main" java.lang.NullPointerException
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.address(BaseDataBuffer.java:603)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:376)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:43)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.assign(BaseNDArray.java:2918)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.valueArrayOf(BaseNDArrayFactory.java:915)
	at org.nd4j.linalg.factory.Nd4j.valueArrayOf(Nd4j.java:4234)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:174)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.sum(BaseNDArray.java:3476)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.sumNumber(BaseNDArray.java:1069)
```

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/pull/1000
